version: 2
models:
- name: execution_blocks_clients_version_daily
  description: Daily aggregates of execution block counts, grouped by client and version.  Data is incrementally updated using `delete+insert` strategy.
  columns:
  - name: date
    description: Date of the execution block.
    data_type: DATE
  - name: client
    description: Client associated with the execution block.  Values are derived from the `extra_data` field.
    data_type: STRING
  - name: version
    description: Version associated with the execution block.  Values are derived from the `extra_data` field.
    data_type: STRING
  - name: value
    description: Sum of execution block counts for the given date, client, and version.
    data_type: INT
- name: execution_blocks_production
  description: Production model for execution blocks, containing block timestamps and extra data.  This model filters out the genesis block and applies a monthly incremental strategy for efficient updates.
  columns:
  - name: block_timestamp
    description: Timestamp of the block.
    data_type: TIMESTAMP
  - name: extra_data
    description: Extra data associated with the block.
    data_type: STRING
  tags:
  - production
  - execution
  - blocks
