version: 2
models:
- name: execution_blocks_clients_version_daily
  description: 'TODO: Add description for execution_blocks_clients_version_daily'
  meta:
    sector: execution
    refs:
    - execution_blocks_production
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - blocks
    - transformations
  columns:
  - name: cnt
    description: 'TODO: Add description for cnt'
    data_tests:
    - not_null
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: decoded_extra_data
    description: 'TODO: Add description for decoded_extra_data'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - cnt
      - date
- name: execution_blocks_production
  description: 'TODO: Add description for execution_blocks_production'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - blocks
    - transformations
  columns:
  - name: block_timestamp
    description: 'TODO: Add description for block_timestamp'
    data_tests:
    - not_null
  - name: extra_data
    description: 'TODO: Add description for extra_data'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - block_timestamp
      - extra_data
