version: 2
models:

- name: api_execution_blocks_clients_cnt_daily
  description: The api_execution_blocks_clients_cnt_daily model provides daily aggregated counts of API execution blocks per client, supporting operational monitoring and capacity planning.
  columns:

  - name: date
    description: The specific calendar date for the recorded data, formatted as YYYY-MM-DD.
    data_type: Date
    tests:
    - not_null

  - name: client
    description: The identifier for the client associated with the API execution blocks.
    data_type: String

  - name: value
    description: The count of API execution blocks for the given client on the specified date.
    data_type: UInt64
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.697942'
    _generated_fields:
    - columns.client.description
    - description
    - columns.client.data_type
    - columns.date.description
    - config.tags
    - config.materialized
    - columns.value.description
    - columns.value.data_type
    - columns.date.data_type

- name: api_execution_blocks_clients_pct_daily
  description: The api_execution_blocks_clients_pct_daily model provides daily percentage metrics of API execution blocks per client, facilitating monitoring of client-specific API usage patterns over time.
  columns:

  - name: date
    description: The specific calendar date for the recorded metrics.
    data_type: Date
    tests:
    - not_null

  - name: client
    description: Identifier for the client associated with the API execution data.
    data_type: String

  - name: value
    description: The percentage of execution blocks for the client on the given date, rounded to two decimal places.
    data_type: Float64
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.697996'
    _generated_fields:
    - columns.client.description
    - description
    - columns.client.data_type
    - columns.date.description
    - config.tags
    - config.materialized
    - columns.value.description
    - columns.value.data_type
    - columns.date.data_type

- name: fct_execution_blocks_clients_daily
  description: The fct_execution_blocks_clients_daily model aggregates daily execution block counts per client, providing insights into client activity levels over time for operational analysis.
  columns:

  - name: date
    description: The date of the recorded execution blocks, formatted as a date.
    data_type: Date
    tests:
    - not_null

  - name: client
    description: Identifier for the client associated with the execution blocks.
    data_type: String

  - name: cnt
    description: Total number of execution blocks for the client on the given date.
    data_type: UInt64

  - name: fraq
    description: Fraction of total blocks on that date attributed to the client.
    data_type: Float64
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.698108'
    _generated_fields:
    - columns.client.description
    - description
    - columns.client.data_type
    - columns.date.description
    - config.tags
    - config.materialized
    - columns.cnt.data_type
    - columns.cnt.description
    - columns.date.data_type

- name: api_execution_blocks_gas_usage_pct_daily
  description: The api_execution_blocks_gas_usage_pct_daily model provides daily insights into the percentage of gas used by API execution blocks, assisting in monitoring resource consumption trends over time.
  columns:

  - name: date
    description: The specific day for which the gas usage percentage is recorded.
    data_type: Date
    tests:
    - not_null

  - name: value
    description: The percentage of gas used by execution blocks on the given date, rounded to two decimal places.
    data_type: Float64
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.698032'
    _generated_fields:
    - description
    - columns.date.description
    - config.tags
    - config.materialized
    - columns.value.description
    - columns.value.data_type
    - columns.date.data_type

- name: api_execution_blocks_gas_usage_pct_monthly
  description: This model provides a monthly percentage of gas usage for execution blocks, enabling analysis of gas consumption trends over time.
  columns:

  - name: date
    description: The month for which the gas usage percentage is reported, formatted as a date.
    data_type: Date
    tests:
    - not_null

  - name: value
    description: The gas usage percentage for the month, rounded to two decimal places.
    data_type: Float64
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.698066'
    _generated_fields:
    - description
    - columns.date.description
    - config.tags
    - config.materialized
    - columns.value.description
    - columns.value.data_type
    - columns.date.data_type

- name: fct_execution_blocks_gas_usage_monthly
  description: The fct_execution_blocks_gas_usage_monthly model aggregates monthly gas usage and limits for execution blocks to support performance and resource utilization analysis.
  columns:

  - name: month
    description: The first day of the month representing the aggregation period.
    data_type: Date

  - name: gas_used_sum_monthly
    description: Total gas used in execution blocks during the month, measured in units consistent with gas consumption metrics.
    data_type: UInt64

  - name: gas_limit_sum_monthly
    description: Total gas limit allocated for execution blocks during the month, measured in units consistent with gas allocation metrics.
    data_type: UInt64

  - name: used
    description: Ratio of gas used to gas limit for the month.
    data_type: Float64
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.698149'
    _generated_fields:
    - description
    - columns.month.description
    - config.tags
    - config.materialized
    - columns.gas_used_sum_monthly.description
    - columns.gas_limit_sum_monthly.description
    - columns.month.data_type
    - columns.gas_used_sum_monthly.data_type
    - columns.gas_limit_sum_monthly.data_type

