version: 2
models:

- name: execution_blocks_clients_daily
  description: Aggregated daily data of execution blocks per client, including total value.
  columns:
  - name: date
    description: Date of the daily aggregation (UTC).
    data_type: DateTime
    tests:
    - not_null
  - name: client
    description: Client address involved in execution blocks.
    data_type: String
    tests:
    - not_null
  - name: value
    description: Sum of values (wei) for the client on the given date.
    data_type: UInt64
  config:
    access: public
- name: execution_blocks_clients_pct_daily
  description: Business-facing metric representing the percentage of client activity within execution blocks on a daily basis.
  columns:
  - name: date
    description: Date of the observation in YYYY-MM-DD format.
    data_type: Date
    tests:
    - not_null
  - name: client
    description: Client identifier (e.g., address or unique client ID).
    data_type: String
    tests:
    - not_null
  - name: value
    description: Total number of activity units associated with the client on the given date.
    data_type: UInt64
  - name: pct
    description: Percentage of client activity relative to total activity on that date, rounded to four decimal places.
    data_type: Float64
  config:
    access: public
- name: api_execution_blocks_clients_cnt_daily
  description: Daily count of clients with execution blocks, aggregated per date.
  columns:
  - name: date
    description: Calendar date of the aggregation (UTC).
    data_type: Date
  - name: client
    description: Client identifier, e.g., address or name.
    data_type: String
  - name: value
    description: Count of execution blocks for the client on the date.
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - blocks
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_blocks_clients_pct_daily
  description: Daily percentage of clients with execution blocks, calculated as the ratio of clients with execution blocks to total clients, expressed as a percentage.
  columns:
  - name: date
    description: Calendar date of the data point, in UTC.
    data_type: DateTime
  - name: client
    description: Unique identifier for the client.
    data_type: String
  - name: value
    description: Percentage of clients with execution blocks on the given date, rounded to two decimal places.
    data_type: Float64
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - blocks
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_execution_blocks_clients_daily
  description: Business-facing table aggregating client execution blocks per day, including counts and fractional shares.
  columns:
  - name: date
    description: Date of the aggregation (YYYY-MM-DD).
    data_type: Date
  - name: client
    description: Client identifier (e.g., address or client name).
    data_type: String
  - name: cnt
    description: Total count of execution blocks for the client on the date.
    data_type: UInt64
  - name: fraq
    description: Fraction of total blocks on that date attributed to the client.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - blocks
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_execution_blocks_gas_usage_pct_monthly
  description: Monthly gas usage statistics aggregated from daily gas usage data.
  columns:
  - name: month
    description: Month of the data aggregation.
    data_type: DateTime
  - name: gas_used_sum_monthly
    description: Total gas consumed in the month.
    data_type: UInt64
    tests:
    - not_null
  - name: gas_limit_sum_monthly
    description: Total gas limit for the month.
    data_type: UInt64
    tests:
    - not_null
  - name: used
    description: Ratio of gas used to gas limit.
    data_type: Float64
  config:
    materialized: view
    tags:
    - production
    - execution
    - transactions
    - gas
    access: public
  meta:
    owner: analytics_engineer
    authoritative: false
    generated_by: schema-writer
- name: api_execution_blocks_gas_usage_pct_daily
  description: Daily percentage of gas used in API execution blocks, derived from int_execution_blocks_gas_usage_daily, filtered to dates before today.
  columns:
  - name: date
    description: Date of the record (UTC), representing the day.
    data_type: DateTime
  - name: value
    description: Percentage of gas used in execution blocks, rounded to 2 decimal places.
    data_type: Float64
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - blocks
    - gas
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_blocks_gas_usage_monthly
  description: Monthly gas usage for API execution blocks, represented as a percentage.
  columns:
  - name: date
    description: Month of the data
    data_type: DateTime
    tests:
    - not_null
  - name: value
    description: Gas usage percentage
    data_type: Float64
    tests:
    - not_null
  config:
    materialized: view
    access: public
    tags:
    - production
    - execution
    - blocks
    - gas
  meta:
    owner: analytics_engineer
    authoritative: false
    generated_by: schema-writer
- name: api_execution_blocks_gas_usage_pct_monthly
  description: Business-facing view providing monthly gas usage percentage calculations based on execution blocks data, aggregated and formatted for reporting.
  columns:
  - name: date
    description: The month of the data aggregation, formatted as a date (e.g., 2023-10-01).
    data_type: Date
  - name: value
    description: Gas usage percentage for the month, rounded to two decimal places.
    data_type: Float64
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - blocks
    - gas
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_execution_blocks_gas_usage_monthly
  description: Aggregated gas usage metrics per month, including total gas used, total gas limit, and utilization ratio, derived from daily execution data.
  columns:
  - name: month
    description: The first day of the month for the aggregated data.
    data_type: DateTime
  - name: gas_used_sum_monthly
    description: Total gas used in wei during the month.
    data_type: UInt64
  - name: gas_limit_sum_monthly
    description: Total gas limit in wei during the month.
    data_type: UInt64
  - name: used
    description: Ratio of gas used to gas limit for the month.
    data_type: Float64
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - transactions
    - gas
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
