version: 2
models:

- name: execution_blocks_clients_daily
  description: Aggregated daily data of execution blocks per client, including total value.
  columns:
  - name: date
    description: Date of the daily aggregation (UTC).
    data_type: DateTime
    tests:
    - not_null
  - name: client
    description: Client address involved in execution blocks.
    data_type: String
    tests:
    - not_null
  - name: value
    description: Sum of values (wei) for the client on the given date.
    data_type: UInt64
  config:
    access: public
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: execution_blocks_clients_pct_daily
  description: Business-facing metric representing the percentage of client activity within execution blocks on a daily basis.
  columns:
  - name: date
    description: Date of the observation in YYYY-MM-DD format.
    data_type: Date
    tests:
    - not_null
  - name: client
    description: Client identifier (e.g., address or unique client ID).
    data_type: String
    tests:
    - not_null
  - name: value
    description: Total number of activity units associated with the client on the given date.
    data_type: UInt64
  - name: pct
    description: Percentage of client activity relative to total activity on that date, rounded to four decimal places.
    data_type: Float64
  config:
    access: public
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_blocks_clients_cnt_daily
  description: Daily count of clients with execution blocks, aggregated by date. Provides business insights into client activity over time.
  columns:
  - name: date
    description: Calendar date of the aggregation period.
    data_type: Date
  - name: client
    description: Unique identifier for the client.
    data_type: String
  - name: value
    description: Count of execution blocks for the client on the given date.
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - blocks
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_blocks_clients_pct_daily
  description: Business-facing metric representing the percentage of execution blocks associated with clients on a daily basis, derived from the raw execution data.
  columns:
  - name: date
    description: Date of the data aggregation (UTC), in 'YYYY-MM-DD' format.
    data_type: Date
  - name: client
    description: Client identifier (e.g., application or service name).
    data_type: String
  - name: value
    description: Percentage of execution blocks associated with clients, as a decimal between 0 and 100.
    data_type: Float64
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - blocks
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_execution_blocks_clients_daily
  description: This fact table aggregates daily client execution block data, including counts and percentages, for analysis of client activity over time.
  columns:
  - name: date
    description: Date of the record in YYYY-MM-DD format.
    data_type: Date
  - name: client
    description: Unique identifier for the client.
    data_type: String
  - name: cnt
    description: Total number of execution blocks for the client on the given date.
    data_type: UInt64
  - name: pct
    description: Percentage of total blocks across all clients on that date (range 0 to 1).
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - blocks
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
