version: 2
models:

- name: contracts_CowProtocol_GPv2Settlement_events
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2021-04-01"
      batch_months: 3

- name: contracts_CowProtocol_GPv2Settlement_calls
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2021-04-01"
      batch_months: 2
