version: 2
models:
- name: contracts_GBCDeposit_calls
  description: This model contains decoded call data for the GBCDeposit contract (0x0B98057eA310F4d31F2a452B414647007d1645d9) extracted from the `transactions` table.  It uses the `decode_calls` macro to parse the call data.
  columns:
  - name: block_number
    description: The block number where the transaction was included.
    data_type: INTEGER
  - name: block_hash
    description: The hash of the block where the transaction was included.
    data_type: STRING
  - name: block_timestamp
    description: The timestamp of the block where the transaction was included.
    data_type: TIMESTAMP
  - name: transaction_hash
    description: The hash of the transaction.
    data_type: STRING
  - name: transaction_index
    description: The index of the transaction within the block.
    data_type: INTEGER
  - name: from_address
    description: The address that initiated the transaction.
    data_type: STRING
  - name: to_address
    description: The address the transaction was sent to.
    data_type: STRING
  - name: gas_used
    description: The amount of gas used by the transaction.
    data_type: INTEGER
  - name: trace_address
    description: The trace address of the call.
    data_type: STRING
  - name: call_data
    description: The decoded call data.
    data_type: JSON
  - name: success
    description: Whether the call was successful.
    data_type: BOOLEAN
  tags:
  - contracts
  - calls
  - gbcdeposit
- name: contracts_GBCDeposit_events
  description: This model contains events emitted by the GBCDeposit contract (0x0B98057eA310F4d31F2a452B414647007d1645d9).  It's materialized incrementally using a delete+insert strategy for efficient updates.  The data is partitioned by month for improved query performance.
  columns:
  - name: block_number
    description: The block number where the event occurred.
    data_type: INTEGER
  - name: block_timestamp
    description: The timestamp of the block where the event occurred.
    data_type: TIMESTAMP
  - name: log_index
    description: The index of the log within the block.
    data_type: INTEGER
  - name: transaction_hash
    description: The hash of the transaction that emitted the event.
    data_type: STRING
  - name: contract_address
    description: The address of the contract that emitted the event.
    data_type: STRING
  - name: event_name
    description: The name of the event.
    data_type: STRING
  - name: event_data
    description: The data associated with the event.  This will be a JSON object containing the event parameters.
    data_type: JSON
  tags:
  - contracts
  - events
  - gbcdeposit
