version: 2
models:

- name: int_execution_transfers_whitelisted_daily
  description: Value (XDAI) transfers decoded from transactions, with daily aggregation.
  columns:
  - name: date
    description: Date of the transfer.
    data_type: DateTime
  - name: token_address
    description: Address of the token.
    data_type: String
  - name: symbol
    description: Symbol of the token.
    data_type: String
  - name: from
    description: Sender address.
    data_type: String
  - name: to
    description: Recipient address.
    data_type: String
  - name: amount
    description: Amount of the token transferred.
    data_type: Float64
  - name: amount_usd
    description: Amount in USD.
    data_type: Float64
  - name: transfer_count
    description: Number of transfers.
    data_type: String
  config:
    materialized: incremental
    unique_key: (date, token_address, "from", "to")
    partition_by: toStartOfMonth(date)
    tags:
    - production
    - execution
    - transfers
    - erc20
    - whitelisted
    - daily
    access: public
  meta:
    owner: analytics_engineer
    authoritative: false
    generated_by: schema-writer
- name: int_execution_transfers_whitelisted_raw
  description: Value (XDAI) transfers decoded from transactions. This model contains information about XDAI transfers decoded from transactions, including block number, block timestamp, transaction index, transfer index, transaction hash, sender address, recipient address, transfer value as binary, decimal string, and floating-point ether, EVM chain identifier, and monotonic ingestion version.
  columns:
  - name: block_number
    description: Height of the block.
    data_type: UInt32
  - name: block_timestamp
    description: UTC timestamp of the enclosing block.
    data_type: DateTime64(0, 'UTC')
  - name: transaction_index
    description: Index of the transaction within the block.
    data_type: UInt32
  - name: log_index
    description: Zero-based index of the log within the receipt.
    data_type: UInt32
  - name: transaction_hash
    description: Transaction hash.
    data_type: String
  - name: from
    description: Sender address.
    data_type: String
  - name: to
    description: Recipient address.
    data_type: String
  - name: token_address
    description: Token address.
    data_type: String
  - name: symbol
    description: Token symbol.
    data_type: String
  - name: decimals
    description: Decimals for the token.
    data_type: UInt32
  - name: amount
    description: Transfer amount as floating-point ether.
    data_type: Float64
  - name: price
    description: Price information.
    data_type: Float64
  - name: amount_usd
    description: Amount in USD.
    data_type: Float64
  - name: value_raw
    description: Raw value.
    data_type: String
  config:
    materialized: incremental
    incremental_strategy: append
    engine: ReplacingMergeTree()
    order_by: (block_timestamp, transaction_hash, log_index)
    unique_key: (block_number, transaction_index, log_index)
    partition_by: toStartOfMonth(block_timestamp)
    settings:
      allow_nullable_key: 1
    tags:
    - dev
    - execution
    - transfers
    - erc20
    - whitelisted
  meta:
    owner: analytics_engineer
    authoritative: false
    generated_by: schema-writer
