version: 2
models:
- name: yields_sdai_apy_daily
  description: Daily, 7-day moving average, and 30-day moving average of the annual percentage yield (APY) for sDAI.  Includes both mean and median calculations.
  columns:
  - name: date
    description: Date of the APY calculation.
    data_type: DATE
  - name: apy
    description: Daily APY for sDAI.
    data_type: FLOAT
  - name: label
    description: Type of APY (Daily, 7DMA, 30DMA, 7DMM, 30DMM).
    data_type: STRING
  - name: apy_7DMA
    description: 7-day moving average of the APY for sDAI.
    data_type: FLOAT
  - name: apy_30DMA
    description: 30-day moving average of the APY for sDAI.
    data_type: FLOAT
  - name: apy_7DMM
    description: 7-day moving median of the APY for sDAI.
    data_type: FLOAT
  - name: apy_30DMM
    description: 30-day moving median of the APY for sDAI.
    data_type: FLOAT
