version: 2
models:
- name: yields_sdai_apy_daily
  description: 'TODO: Add description for yields_sdai_apy_daily'
  meta:
    sector: execution
    refs:
    - yields_sdai_rate_daily
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - yields
    - metrics
  columns:
  - name: apy
    description: 'TODO: Add description for apy'
    data_tests:
    - not_null
  - name: apy_30DMA
    description: 'TODO: Add description for apy_30DMA'
    data_tests:
    - not_null
  - name: apy_30DMM
    description: 'TODO: Add description for apy_30DMM'
    data_tests:
    - not_null
  - name: apy_7DMA
    description: 'TODO: Add description for apy_7DMA'
    data_tests:
    - not_null
  - name: apy_7DMM
    description: 'TODO: Add description for apy_7DMM'
    data_tests:
    - not_null
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - apy
      - apy_30DMA
