version: 2
models:

- name: contracts_ConditionalTokens_calls
  description: Model representing Conditional Tokens call data, including transaction details, contract addresses, and output JSON types for analysis.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the call was made, in UTC.
    data_type: DateTime
  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String
  - name: contract_address
    description: Address of the contract involved in the call.
    data_type: String
  - name: output_json_type
    description: Boolean indicating if the output is in JSON format.
    data_type: UInt64
  - name: tx_table
    description: Name of the source table containing transaction data.
    data_type: String
  - name: contract_address_param
    description: Contract address parameter used in the call.
    data_type: String
  - name: output_json_type_param
    description: JSON type parameter used in the call.
    data_type: UInt64
  - name: incremental_column
    description: Column used for incremental processing, typically block timestamp.
    data_type: String
  - name: start_blocktime
    description: Starting block timestamp for data processing.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - conditionaltokens
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_ConditionalTokens_events
  description: This model captures conditional token events including block timestamp, log index, transaction hash, event type, and associated data for analysis.
  columns:
  - name: block_timestamp
    description: The timestamp of the block when the event was recorded.
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block, used to order events.
    data_type: UInt64
  - name: transaction_hash
    description: The hash of the transaction associated with the event.
    data_type: String
  - name: event_type
    description: The type of event emitted, e.g., 'Create', 'Resolve'.
    data_type: String
  - name: condition_id
    description: The identifier of the condition related to the event.
    data_type: String
  - name: collateral_token
    description: The address of the collateral token involved in the event.
    data_type: String
  - name: amount
    description: The amount involved in the event, in wei.
    data_type: String
  - name: outcome_index
    description: The index of the outcome associated with the event.
    data_type: UInt64
  - name: block_number
    description: The block number where the event was recorded.
    data_type: UInt64
  - name: event_data
    description: Additional event data in JSON format.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - conditionaltokens
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
