version: 2
models:

- name: contracts_ConditionalTokens_calls
  description: Model representing conditional token calls with relevant transaction details
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the transaction was included
    data_type: DateTime
  - name: transaction_hash
    description: Unique hash identifying the transaction
    data_type: String
  - name: contract_address
    description: Address of the contract involved in the call
    data_type: String
  - name: output_json_type
    description: Indicates if the output is in JSON format (boolean)
    data_type: String
  - name: tx_table
    description: Source table for transactions
    data_type: String
  - name: incremental_column
    description: Column used for incremental processing, typically block timestamp
    data_type: String
  - name: start_blocktime
    description: Starting block timestamp for data ingestion
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - contracts
    - conditional_tokens
    quote: true
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_ConditionalTokens_events
  description: Event data related to ConditionalTokens contracts, including block timestamps, log indices, and transaction details for tracking conditional token events.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted
    data_type: DateTime
  - name: log_index
    description: Log index within the block, indicating event order
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction that emitted the event
    data_type: String
  - name: event_type
    description: Type of the conditional token event (e.g., creation, resolution)
    data_type: String
  - name: contract_address
    description: Address of the ConditionalTokens contract emitting the event
    data_type: String
  - name: token_id
    description: Identifier of the token involved in the event
    data_type: String
  - name: amount
    description: Amount involved in the event, in wei
    data_type: String
  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - contracts
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
