version: 2
models:

- name: contracts_ConditionalTokens_calls
  description: This model captures conditional token call data, including transaction details, block timestamps, and contract-specific information relevant for analysis.
  columns:
  - name: transaction_hash
    description: Unique identifier for the transaction
    data_type: String
  - name: block_timestamp
    description: Timestamp of the block containing the transaction
    data_type: DateTime64(0, 'UTC')
  - name: block_number
    description: Number of the block containing the transaction
    data_type: UInt64
  - name: contract_address
    description: Address of the conditional token contract
    data_type: String
  - name: caller_address
    description: Address initiating the call
    data_type: String
  - name: call_data
    description: Encoded call data payload
    data_type: String
  - name: output_json_type
    description: Indicates if output is in JSON format (boolean)
    data_type: String
  - name: output_data
    description: Output data from the call, in JSON format
    data_type: String
  - name: gas_used
    description: Gas used for the transaction (wei)
    data_type: String
  - name: gas_price
    description: Gas price at the time of transaction (wei)
    data_type: String
  - name: status
    description: Transaction status (e.g., success, failure)
    data_type: String
  - name: error_message
    description: Error message if transaction failed
    data_type: String
  - name: created_at
    description: Record creation timestamp
    data_type: DateTime64(0, 'UTC')
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - conditionaltokens
    - calls
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_ConditionalTokens_events
  description: Events related to Conditional Tokens, including transaction details and timestamps.
  columns:
  - name: event_id
    description: Unique identifier for each event.
    data_type: String
  - name: block_timestamp
    description: Timestamp of the block when the event was recorded.
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction associated with the event.
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: event_type
    description: Type of the event emitted.
    data_type: String
  - name: condition_id
    description: Identifier for the specific condition involved.
    data_type: String
  - name: outcome_index
    description: Index of the outcome related to the event.
    data_type: UInt64
  - name: amount
    description: Amount involved in the event, in wei.
    data_type: String
  - name: sender
    description: Address of the sender initiating the event.
    data_type: String
  - name: recipient
    description: Address of the recipient involved in the event.
    data_type: String
  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - conditionaltokens
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
