version: 2
models:

- name: contracts_ConditionalTokens_calls
  description: This model captures data related to ConditionalTokens calls, including transaction details, contract addresses, and call-specific information. It is used for analysis and reporting of ConditionalTokens interactions.
  columns:
  - name: transaction_hash
    description: Unique hash identifying the transaction
    data_type: String
  - name: block_number
    description: Blockchain block number
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp of the block in UTC
    data_type: DateTime
  - name: contract_address
    description: Address of the ConditionalTokens contract
    data_type: String
  - name: caller_address
    description: Address initiating the call
    data_type: String
  - name: call_data
    description: Encoded call data payload
    data_type: String
  - name: output_json_type
    description: Indicates if the output is in JSON format (boolean)
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - conditionaltokens
    - calls
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_ConditionalTokens_events
  description: This model captures conditional token events related to contracts, including details about the event type, involved addresses, transaction info, and timestamps.
  columns:
  - name: event_id
    description: Unique identifier for each event, typically a hash or UUID.
    data_type: String
  - name: block_number
    description: Blockchain block number where the event was recorded.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp of the block when the event was included, in UTC.
    data_type: DateTime64(0, 'UTC')
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String
  - name: log_index
    description: Index of the log within the block, used to order events.
    data_type: UInt64
  - name: event_type
    description: Type of the conditional token event (e.g., creation, settlement).
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: condition_id
    description: Identifier for the condition associated with the event.
    data_type: String
  - name: condition_type
    description: Type of condition (e.g., binary, scalar).
    data_type: String
  - name: outcome_index
    description: Index of the outcome related to the event.
    data_type: UInt64
  - name: outcome_value
    description: Value or description of the outcome.
    data_type: String
  - name: amount
    description: Amount involved in the event, in wei.
    data_type: String
  - name: participant_address
    description: Address of the participant involved in the event.
    data_type: String
  - name: transaction_index
    description: Index of the transaction within the block.
    data_type: UInt64
  - name: created_at
    description: Timestamp when the record was created in the database, in UTC.
    data_type: DateTime64(0, 'UTC')
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - conditionaltokens
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
