version: 2
models:

- name: stg_execution__transactions
  description: Staging model for execution transactions, transforming raw chain data into a structured format for analysis.
  columns:
  - name: transaction_hash
    description: Unique identifier of the transaction (hash).
    data_type: String
  - name: transaction_index
    description: Zero-based index of the transaction within the block.
    data_type: UInt64
  - name: nonce
    description: Transaction nonce (number of transactions sent by sender).
    data_type: UInt64
  - name: block_number
    description: Height of the block containing this transaction.
    data_type: UInt32
  - name: from_address
    description: Address that initiated the transaction.
    data_type: String
  - name: to_address
    description: Recipient address; null if contract creation.
    data_type: String
  - name: value
    description: Transaction value in wei.
    data_type: UInt256
  - name: input
    description: Calldata or input data provided with the transaction.
    data_type: String
  - name: gas_limit
    description: Gas limit specified for the transaction.
    data_type: UInt64
  - name: gas_used
    description: Actual gas used by the transaction.
    data_type: UInt64
  - name: gas_price
    description: Gas price in wei (legacy, pre-EIP-1559).
    data_type: UInt64
  - name: transaction_type
    description: Transaction type (0=legacy, 1=access list, 2=EIP-1559).
    data_type: UInt32
  - name: max_priority_fee_per_gas
    description: Max tip per gas for EIP-1559 transactions.
    data_type: UInt64
  - name: max_fee_per_gas
    description: Max total fee per gas for EIP-1559 transactions.
    data_type: UInt64
  - name: success
    description: 1 if transaction succeeded, 0 if reverted.
    data_type: UInt8
  - name: r
    description: ECDSA signature component r.
    data_type: String
  - name: s
    description: ECDSA signature component s.
    data_type: String
  - name: v
    description: ECDSA recovery id / y-parity.
    data_type: UInt32
  - name: block_hash
    description: Hash of the block containing this transaction.
    data_type: String
  - name: chain_id
    description: Chain identifier (e.g., 100 for Gnosis).
    data_type: UInt64
  - name: block_timestamp
    description: UTC timestamp of the block containing this transaction.
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonically increasing version for ingestion tracking.
    data_type: UInt64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
