version: 2
models:

- name: stg_execution__transactions
  description: This model captures detailed information about blockchain transactions within execution blocks, facilitating analysis of transaction behaviors and outcomes.
  columns:

  - name: block_number
    description: The number of the block containing the transaction, indicating its position in the blockchain.
    data_type: UInt64

  - name: transaction_index
    description: The sequential index of the transaction within the block, starting from zero.
    data_type: UInt64
    tests:
    - not_null

  - name: transaction_hash
    description: Unique identifier (hash) of the transaction, used for referencing and verification.
    data_type: String
    tests:
    - unique
    - not_null

  - name: nonce
    description: A sequential number used to prevent transaction replay and ensure uniqueness for the sender's account.
    data_type: UInt64

  - name: from_address
    description: Address (EOA or contract) that signed the transaction.
    data_type: String

  - name: to_address
    description: Recipient address; null if contract creation.
    data_type: String

  - name: value
    description: Transaction value in wei as a decimal string.
    data_type: String

  - name: input
    description: Calldata or input data supplied with the transaction (hex).
    data_type: String

  - name: gas_limit
    description: Gas limit provided by the sender.
    data_type: UInt64

  - name: gas_used
    description: Actual gas used by the transaction.
    data_type: UInt64

  - name: gas_price
    description: Legacy gas price in wei (pre-EIP-1559).
    data_type: UInt64

  - name: transaction_type
    description: Envelope type (0 = legacy, 1 = access-list, 2 = EIP-1559).
    data_type: UInt32

  - name: max_priority_fee_per_gas
    description: Max miner tip per gas in wei for EIP-1559 transactions.
    data_type: UInt64

  - name: max_fee_per_gas
    description: Max total fee per gas in wei under EIP-1559.
    data_type: UInt64

  - name: success
    description: 1 if transaction succeeded; 0 if reverted.
    data_type: UInt8

  - name: r
    description: ECDSA signature component r.
    data_type: String

  - name: s
    description: ECDSA signature component s.
    data_type: String

  - name: v
    description: ECDSA recovery id or y-parity.
    data_type: UInt32

  - name: block_hash
    description: Hash of the enclosing block.
    data_type: String

  - name: chain_id
    description: EVM chain identifier.
    data_type: UInt64

  - name: block_timestamp
    description: UTC timestamp of the block (materialized from `block_timestamp`).
    data_type: DateTime64(0, 'UTC')

  - name: insert_version
    description: Monotonic ingestion version in nanoseconds.
    data_type: UInt64
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:59.122336'
    _generated_fields:
    - description
    - columns.transaction_hash.description
    - config.tags
    - config.materialized
    - columns.block_number.data_type
    - columns.nonce.description
    - columns.block_number.description
    - columns.transaction_index.description
    - columns.transaction_index.data_type
    - columns.nonce.data_type
    - columns.transaction_hash.data_type

