version: 2
models:

- name: stg_execution__transactions
  description: A staging model for execution transactions, transforming raw chain data into a structured format suitable for analysis.
  columns:
  - name: transaction_index
    description: Zero-based index of the transaction within the block.
    data_type: UInt64
    tests:
    - not_null
  - name: nonce
    description: Transaction nonce (sender's transaction count).
    data_type: UInt64
  - name: block_number
    description: Height of the block containing the transaction.
    data_type: UInt32
    tests:
    - not_null
  - name: transaction_hash
    description: Keccak-256 hash identifying the transaction.
    data_type: String
    tests:
    - not_null
    - unique
  - name: from_address
    description: Address (EOA or contract) that signed the transaction.
    data_type: String
    tests:
    - not_null
  - name: to_address
    description: Recipient address; null for contract creation.
    data_type: String
  - name: value
    description: Value transferred in wei.
    data_type: UInt256
  - name: input
    description: Calldata / input data supplied with the transaction (hex).
    data_type: String
  - name: gas_limit
    description: Gas limit provided by the sender.
    data_type: UInt64
  - name: gas_used
    description: Actual gas used by the transaction.
    data_type: UInt64
  - name: gas_price
    description: Legacy gas price in wei (pre-EIP-1559).
    data_type: UInt64
  - name: transaction_type
    description: Envelope type (0 = legacy, 1 = access-list, 2 = EIP-1559).
    data_type: UInt32
  - name: max_priority_fee_per_gas
    description: Max miner tip per gas (wei) for EIP-1559.
    data_type: UInt64
  - name: max_fee_per_gas
    description: Max total fee per gas (wei) under EIP-1559.
    data_type: UInt64
  - name: success
    description: 1 if the transaction succeeded; 0 if it reverted.
    data_type: UInt8
  - name: n_input_bytes
    description: Byte length of the input data.
    data_type: UInt32
  - name: n_input_zero_bytes
    description: Number of zero bytes in the input.
    data_type: UInt32
  - name: n_input_nonzero_bytes
    description: Number of non-zero bytes in the input.
    data_type: UInt32
  - name: n_rlp_bytes
    description: Total RLP-encoded payload size (bytes) if available.
    data_type: UInt32
  - name: timestamp
    description: Block timestamp (seconds since epoch).
    data_type: UInt32
  - name: r
    description: ECDSA signature r component.
    data_type: String
  - name: s
    description: ECDSA signature s component.
    data_type: String
  - name: v
    description: ECDSA recovery id / y-parity.
    data_type: UInt32
  - name: block_hash
    description: Hash of the enclosing block.
    data_type: String
  - name: chain_id
    description: EVM chain identifier.
    data_type: UInt64
  - name: block_timestamp
    description: UTC timestamp of the block (materialized from `timestamp`).
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonic ingestion version (nanoseconds).
    data_type: UInt64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
