version: 2
models:

- name: stg_execution__transactions
  description: Business-facing staging model for execution transactions, including transaction details, addresses, values, input data, and associated metadata.
  columns:
  - name: transaction_index
    description: Zero-based index of the transaction within the block.
    data_type: UInt64
  - name: nonce
    description: Transaction nonce (number of transactions sent by sender).
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String
  - name: block_number
    description: Height of the block containing the transaction.
    data_type: UInt32
  - name: from_address
    description: Address (EOA or contract) that signed the transaction.
    data_type: String
  - name: to_address
    description: Recipient address; null if contract creation.
    data_type: String
  - name: value_string
    description: Value transferred in decimal string format.
    data_type: String
  - name: input
    description: Calldata or input data supplied with the transaction (hex).
    data_type: String
  - name: gas_limit
    description: Gas limit provided by the sender.
    data_type: UInt64
  - name: gas_used
    description: Actual gas used by the transaction.
    data_type: UInt64
  - name: gas_price
    description: Legacy gas price in wei (for pre-EIP-1559 transactions).
    data_type: UInt64
  - name: transaction_type
    description: Envelope type (0 = legacy, 1 = access-list, 2 = EIP-1559).
    data_type: UInt32
  - name: max_priority_fee_per_gas
    description: Max miner tip per gas in wei (for EIP-1559).
    data_type: UInt64
  - name: max_fee_per_gas
    description: Max total fee per gas in wei (for EIP-1559).
    data_type: UInt64
  - name: success
    description: 1 if transaction succeeded; 0 if reverted.
    data_type: UInt8
  - name: n_input_bytes
    description: Byte length of input data.
    data_type: UInt32
  - name: n_input_zero_bytes
    description: Number of zero bytes in input.
    data_type: UInt32
  - name: n_input_nonzero_bytes
    description: Number of non-zero bytes in input.
    data_type: UInt32
  - name: n_rlp_bytes
    description: Total RLP-encoded payload size in bytes if available.
    data_type: UInt32
  - name: timestamp
    description: Block timestamp in seconds since epoch.
    data_type: UInt32
  - name: r
    description: ECDSA signature r component.
    data_type: String
  - name: s
    description: ECDSA signature s component.
    data_type: String
  - name: v
    description: ECDSA recovery id / y-parity.
    data_type: UInt32
  - name: block_hash
    description: Hash of the block containing the transaction.
    data_type: String
  - name: chain_id
    description: EVM chain identifier.
    data_type: UInt64
  - name: block_timestamp
    description: UTC timestamp of the block in DateTime64(0, 'UTC') format.
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonic ingestion version in nanoseconds.
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - transactions
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
