version: 2
models:
- name: transfers_erc20_bluechips
  description: 'ERC20 transfers of bluechip tokens.  This model filters logs from the `execution.logs` source to only include transfers of a specific bluechip token (address: ''e91d153e0b41518a2ce8dd3d7944fa863463a97d'').  Data is incrementally updated using `delete+insert` strategy.'
  columns:
  - name: block_number
    description: Number of the block where the transfer occurred.
    data_type: INTEGER
  - name: block_timestamp
    description: Timestamp of the block where the transfer occurred.
    data_type: TIMESTAMP
  - name: transaction_index
    description: Index of the transaction within the block.
    data_type: INTEGER
  - name: log_index
    description: Index of the log within the transaction.
    data_type: INTEGER
  - name: transaction_hash
    description: Hash of the transaction.
    data_type: STRING
  - name: token_address
    description: Address of the token transferred.
    data_type: STRING
  - name: from
    description: Address of the sender.
    data_type: STRING
  - name: to
    description: Address of the recipient.
    data_type: STRING
  - name: value
    description: Amount of tokens transferred.
    data_type: STRING
  tags:
  - erc20
  - bluechip
  - transfers
