version: 2
models:
- name: transfers_erc20_bluechips
  description: 'TODO: Add description for transfers_erc20_bluechips'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - transfers
    - transformations
  columns:
  - name: block_number
    description: 'TODO: Add description for block_number'
    data_tests:
    - not_null
  - name: block_timestamp
    description: 'TODO: Add description for block_timestamp'
    data_tests:
    - not_null
  - name: from
    description: 'TODO: Add description for from'
    data_tests:
    - not_null
  - name: log_index
    description: 'TODO: Add description for log_index'
    data_tests:
    - not_null
  - name: to
    description: 'TODO: Add description for to'
    data_tests:
    - not_null
  - name: token_address
    description: 'TODO: Add description for token_address'
    data_tests:
    - not_null
  - name: transaction_hash
    description: 'TODO: Add description for transaction_hash'
    data_tests:
    - not_null
  - name: transaction_index
    description: 'TODO: Add description for transaction_index'
    data_tests:
    - not_null
  - name: value
    description: 'TODO: Add description for value'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - block_number
      - block_timestamp
