version: 2
models:

- name: contracts_UniswapV3_Factory_events
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2022-04-22"
      batch_months: 6

- name: contracts_UniswapV3_Pool_events
  description: |
    Pool addresses are dynamically selected from contracts_whitelist seed
    based on whitelisted tokens (both token0 and token1 must be whitelisted).
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2022-04-22"
      batch_months: 6
