version: 2
models:

- name: contracts_UniswapV3_Factory_events
  meta:
    owner: analytics-team
    authoritative: false
    full_refresh:
      start_date: "2022-04-22"
      batch_months: 6

- name: contracts_UniswapV3_Pool_events
  meta:
    owner: analytics-team
    authoritative: false
    full_refresh:
      start_date: "2022-04-22"
      batch_months: 6