version: 2
models:
- name: rwa_backedfi_prices
  description: This model aggregates daily prices for various RWA-backed financial instruments from on-chain oracle events.  The data is sourced from individual contract-specific models, each tracking `AnswerUpdated` events.  The model uses a `delete+insert` incremental strategy for efficient updates.
  columns:
  - name: bticker
    description: The ticker symbol representing the RWA-backed financial instrument.
    data_type: string
  - name: date
    description: The date of the price observation (start of day).
    data_type: date
  - name: price
    description: The price of the instrument in USD, scaled down by a factor of 10^8.
    data_type: float
