version: 2
models:
- name: rwa_backedfi_prices
  description: 'TODO: Add description for rwa_backedfi_prices'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - rwa
    - transformations
  columns:
  - name: bticker
    description: 'TODO: Add description for bticker'
    data_tests:
    - not_null
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: price
    description: 'TODO: Add description for price'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - bticker
      - date
