version: 2
models:
- name: consensus_validators_queue
  meta:
    blockchain: consensus
    sector: validators
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - consensus
    - validators
  description: 'TODO: Add description for consensus_validators_queue'
  columns:
  - name: activation_eligibility_time
    description: 'TODO: Add description for activation_eligibility_time'
    data_tests:
    - not_null
    - unique
  - name: activation_time
    description: 'TODO: Add description for activation_time'
    data_tests:
    - not_null
    - unique
  - name: exit_request_time
    description: 'TODO: Add description for exit_request_time'
    data_tests:
    - not_null
    - unique
  - name: exit_time
    description: 'TODO: Add description for exit_time'
    data_tests:
    - not_null
    - unique
  - name: exit_voluntary_time
    description: 'TODO: Add description for exit_voluntary_time'
    data_tests:
    - not_null
    - unique
  - name: f_amount
    description: 'TODO: Add description for f_amount'
    data_tests:
    - not_null
    - unique
  - name: f_eth1_block_timestamp
    description: 'TODO: Add description for f_eth1_block_timestamp'
    data_tests:
    - not_null
    - unique
  - name: f_eth1_gas_price
    description: 'TODO: Add description for f_eth1_gas_price'
    data_tests:
    - not_null
    - unique
  - name: f_eth1_gas_used
    description: 'TODO: Add description for f_eth1_gas_used'
    data_tests:
    - not_null
    - unique
  - name: f_index
    description: 'TODO: Add description for f_index'
    data_tests:
    - not_null
    - unique
  - name: f_signature
    description: 'TODO: Add description for f_signature'
    data_tests:
    - not_null
    - unique
  - name: f_validator_pubkey
    description: 'TODO: Add description for f_validator_pubkey'
    data_tests:
    - not_null
    - unique
  - name: f_withdrawal_credentials
    description: 'TODO: Add description for f_withdrawal_credentials'
    data_tests:
    - not_null
    - unique
  - name: inclusion_time
    description: 'TODO: Add description for inclusion_time'
    data_tests:
    - not_null
    - unique
  - name: partition_month
    description: 'TODO: Add description for partition_month'
    data_tests:
    - not_null
    - unique
  - name: withdrawable_time
    description: 'TODO: Add description for withdrawable_time'
    data_tests:
    - not_null
    - unique
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - activation_eligibility_time
      - activation_time
