version: 2
models:

- name: stg_esg_consensus_power
  description: A staging model representing consensus power metrics with client, type, and mean values.
  columns:
  - name: type
    description: The type of consensus power, e.g., 4, 5, 6.
    data_type: String
  - name: client
    description: The client name, e.g., Lighthouse, Teku, Lodestar, Nimbus, Prysm.
    data_type: String
  - name: mean
    description: The mean value of consensus power in floating point.
    data_type: Float64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_execution_power
  description: A staging model representing execution power metrics, including client type, execution type, and mean execution power values.
  columns:
  - name: client
    description: Client name, e.g., 'Erigon', 'Nethermind'
    data_type: String
  - name: type
    description: Execution type, e.g., 4, 5, 6
    data_type: UInt64
  - name: mean
    description: Mean execution power value in floating point units
    data_type: Float64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_hardware_config
  description: A staging model representing hardware configuration details including type, CPU, cores and threads, architecture, RAM, storage, GPU, PSU, case, and OS.
  columns:
  - name: case
    description: Hardware case type (e.g., Integrated, Custom)
    data_type: String
  - name: cpu
    description: CPU model name (e.g., Intel i5-1135G7)
    data_type: String
  - name: storage
    description: Storage specification (e.g., 2 TB SSD)
    data_type: String
  - name: architecture
    description: CPU architecture (e.g., x86/x64)
    data_type: String
  - name: ram
    description: RAM size (e.g., 16 GB)
    data_type: String
  - name: os
    description: Operating system (e.g., Ubuntu 20.04)
    data_type: String
  - name: type
    description: Hardware type identifier (e.g., 4, 5, 6)
    data_type: UInt64
  - name: cores_threads
    description: Cores and threads configuration (e.g., 4/8)
    data_type: String
  - name: psu
    description: Power supply unit wattage (e.g., 65 Watt)
    data_type: String
  - name: gpu
    description: GPU model (e.g., Onboard, AM 6970)
    data_type: String
  config:
    access: public
    tags:
    - staging
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_idle_electric_power
  description: This model provides the idle electric power metrics with types and mean values for different categories.
  columns:
  - name: type
    description: Category type of idle electric power
    data_type: String
  - name: mean
    description: Average idle electric power values in units consistent with source
    data_type: Float64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_node_distribution
  description: A staging model representing the distribution of node types with associated distribution values used for ESG analysis.
  columns:
  - name: type
    description: Node type identifier (e.g., 4, 5, 6)
    data_type: UInt64
  - name: distribution
    description: Distribution value corresponding to each node type (e.g., 0.25, 0.50)
    data_type: Float64
  config:
    access: public
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__country_codes
  description: A staging model providing country code mappings, including region and sub-region classifications.
  columns:
  - name: name
    description: The country's name.
    data_type: String
  - name: alpha-2
    description: The ISO 3166-1 alpha-2 country code.
    data_type: String
  - name: alpha-3
    description: The ISO 3166-1 alpha-3 country code.
    data_type: String
  - name: country-code
    description: The numeric country code.
    data_type: String
  - name: iso_3166-2
    description: The ISO 3166-2 subdivision code.
    data_type: String
  - name: region
    description: The region classification.
    data_type: String
  - name: sub-region
    description: The sub-region classification.
    data_type: String
  - name: intermediate-region
    description: The intermediate region classification.
    data_type: String
  - name: region-code
    description: The code representing the region.
    data_type: String
  - name: sub-region-code
    description: The code representing the sub-region.
    data_type: String
  - name: intermediate-region-code
    description: The code representing the intermediate region.
    data_type: String
  config:
    access: public
    tags:
    - production
    - crawlers_data
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__ember_electricity_data
  description: A staging model for Ember Electricity Data, containing regional and category information, with temporal and value metrics used for analysis.
  columns:
  - name: Date
    description: The date of the data record, in UTC timestamp.
    data_type: DateTime
  - name: OECD
    description: OECD membership indicator (e.g., 'Yes' or 'No').
    data_type: String
  - name: code
    description: ISO 3 code representing the country or region.
    data_type: String
  - name: change
    description: YoY absolute change in electricity data.
    data_type: Float64
  - name: G7
    description: G7 membership indicator (e.g., 'Yes' or 'No').
    data_type: String
  - name: Area
    description: The geographical area name.
    data_type: String
  - name: EU
    description: European Union membership indicator (e.g., 'Yes' or 'No').
    data_type: String
  - name: region
    description: Ember region classification.
    data_type: String
  - name: ASEAN
    description: ASEAN membership indicator (e.g., 'Yes' or 'No').
    data_type: String
  - name: G20
    description: G20 membership indicator (e.g., 'Yes' or 'No').
    data_type: String
  - name: Subcategory
    description: Subcategory of the variable.
    data_type: String
  - name: Variable
    description: The variable name related to electricity data.
    data_type: String
  - name: Category
    description: The category classification.
    data_type: String
  - name: Value
    description: The measured value of the variable.
    data_type: Float64
  - name: Unit
    description: The measurement unit.
    data_type: String
  - name: type
    description: The type of data (e.g., 'actual', 'forecast').
    data_type: String
  - name: Continent
    description: Continent classification.
    data_type: String
  config:
    access: public
    materialized: view
    tags:
    - production
    - crawlers_data
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
