version: 2
models:

- name: stg_esg_consensus_power
  description: A staging model representing consensus power data, including client type, mean value, and type category.
  columns:
  - name: type
    description: Type category of consensus power (e.g., 4, 5, 6)
    data_type: String
    tests:
    - not_null
  - name: client
    description: Client name (e.g., Lighthouse, Teku, Lodestar, Nimbus, Prysm)
    data_type: String
    tests:
    - not_null
  - name: mean
    description: Mean value of consensus power (numeric, units unspecified)
    data_type: Float64
    tests:
    - not_null
  config:
    access: public
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_execution_power
  description: A staging model representing execution power data with client, type, and mean values
  columns:
  - name: type
    description: The execution type (numeric identifiers 4, 5, 6)
    data_type: UInt64
    tests:
    - not_null
  - name: client
    description: The client name (e.g., 'Erigon', 'Nethermind')
    data_type: String
    tests:
    - not_null
  - name: mean
    description: The average execution power in Gwei (floating point)
    data_type: Float64
    tests:
    - not_null
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_hardware_config
  description: A staging model representing hardware configuration details including type, CPU, cores/threads, architecture, RAM, storage, GPU, PSU, case, and OS.
  columns:
  - name: type
    description: Hardware type identifier (e.g., 4, 5, 6)
    data_type: UInt64
    tests:
    - not_null
  - name: cpu
    description: CPU model description (e.g., 'Intel i5-1135G7')
    data_type: String
    tests:
    - not_null
  - name: cores_threads
    description: Cores and threads count (e.g., '4/8', '6/12', '32/64')
    data_type: String
    tests:
    - not_null
  - name: architecture
    description: CPU architecture (e.g., 'x86/x64')
    data_type: String
    tests:
    - not_null
  - name: ram
    description: RAM size (e.g., '16 GB', '64 GB', '256 GB')
    data_type: String
    tests:
    - not_null
  - name: storage
    description: Storage capacity (e.g., '2 TB SSD', '2TB SSD')
    data_type: String
    tests:
    - not_null
  - name: gpu
    description: GPU model (e.g., 'Onboard', 'AM 6970')
    data_type: String
    tests:
    - not_null
  - name: psu
    description: Power supply unit wattage (e.g., '65 Watt', '650 Watt')
    data_type: String
    tests:
    - not_null
  - name: case
    description: Case type (e.g., 'Integrated', 'Custom')
    data_type: String
    tests:
    - not_null
  - name: os
    description: Operating system (e.g., 'Ubuntu 20.04')
    data_type: String
    tests:
    - not_null
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_idle_electric_power
  description: This model provides the average idle electric power values for different types, used for ESG analysis and reporting.
  columns:
  - name: type
    description: The category of electric power type (integer values 4, 5, 6)
    data_type: UInt64
    tests:
    - not_null
  - name: mean
    description: The average idle electric power in units consistent with source (float)
    data_type: Float64
    tests:
    - not_null
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_node_distribution
  description: A staging model providing node type and distribution data for ESG analysis.
  columns:
  - name: type
    description: Node type identifier (integer values 4, 5, 6)
    data_type: UInt64
    tests:
    - not_null
  - name: distribution
    description: Distribution value associated with each node type (percentages)
    data_type: Float64
    tests:
    - not_null
  config:
    access: public
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
