version: 2
models:

- name: stg_esg_consensus_power
  description: A staging model representing consensus power metrics with client, type, and mean values.
  columns:
  - name: type
    description: The type of consensus power, e.g., 4, 5, 6.
    data_type: String
  - name: client
    description: The client name, e.g., Lighthouse, Teku, Lodestar, Nimbus, Prysm.
    data_type: String
  - name: mean
    description: The mean value of consensus power in floating point.
    data_type: Float64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_execution_power
  description: A staging model representing execution power metrics, including client type, execution type, and mean execution power values.
  columns:
  - name: client
    description: Client name, e.g., 'Erigon', 'Nethermind'
    data_type: String
  - name: type
    description: Execution type, e.g., 4, 5, 6
    data_type: UInt64
  - name: mean
    description: Mean execution power value in floating point units
    data_type: Float64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_hardware_config
  description: A staging model representing hardware configuration details including type, CPU, cores and threads, architecture, RAM, storage, GPU, PSU, case, and OS.
  columns:
  - name: case
    description: Hardware case type (e.g., Integrated, Custom)
    data_type: String
  - name: cpu
    description: CPU model name (e.g., Intel i5-1135G7)
    data_type: String
  - name: storage
    description: Storage specification (e.g., 2 TB SSD)
    data_type: String
  - name: architecture
    description: CPU architecture (e.g., x86/x64)
    data_type: String
  - name: ram
    description: RAM size (e.g., 16 GB)
    data_type: String
  - name: os
    description: Operating system (e.g., Ubuntu 20.04)
    data_type: String
  - name: type
    description: Hardware type identifier (e.g., 4, 5, 6)
    data_type: UInt64
  - name: cores_threads
    description: Cores and threads configuration (e.g., 4/8)
    data_type: String
  - name: psu
    description: Power supply unit wattage (e.g., 65 Watt)
    data_type: String
  - name: gpu
    description: GPU model (e.g., Onboard, AM 6970)
    data_type: String
  config:
    access: public
    tags:
    - staging
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_idle_electric_power
  description: This model provides the idle electric power metrics with types and mean values for different categories.
  columns:
  - name: type
    description: Category type of idle electric power
    data_type: String
  - name: mean
    description: Average idle electric power values in units consistent with source
    data_type: Float64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_node_distribution
  description: A staging model representing the distribution of node types with associated distribution values used for ESG analysis.
  columns:
  - name: type
    description: Node type identifier (e.g., 4, 5, 6)
    data_type: UInt64
  - name: distribution
    description: Distribution value corresponding to each node type (e.g., 0.25, 0.50)
    data_type: Float64
  config:
    access: public
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
