version: 2
models:

- name: stg_crawlers_data__country_codes
  description: The stg_crawlers_data__country_codes model consolidates standardized country identifiers and regional classifications to support geographic analysis within the crawlers data pipeline.
  columns:

  - name: name
    description: The official country name.
    data_type: String

  - name: alpha-2
    description: The two-letter ISO 3166-1 alpha-2 country code.
    data_type: String

  - name: alpha-3
    description: The three-letter ISO 3166-1 alpha-3 country code.
    data_type: String

  - name: country-code
    description: The numeric ISO 3166-1 country code.
    data_type: String

  - name: iso_3166-2
    description: The ISO 3166-2 code representing the primary subdivision of the country.
    data_type: String

  - name: region
    description: The broad geographic region classification.
    data_type: String

  - name: sub-region
    description: The more specific geographic sub-region classification.
    data_type: String

  - name: intermediate-region
    description: An intermediate geographic classification between region and sub-region.
    data_type: String

  - name: region-code
    description: The code associated with the region classification.
    data_type: String

  - name: sub-region-code
    description: The code associated with the sub-region classification.
    data_type: String

  - name: intermediate-region-code
    description: The code associated with the intermediate-region classification.
    data_type: String
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:57.984843'
    _generated_fields:
    - columns.country-code.data_type
    - columns.intermediate-region.data_type
    - config.tags
    - columns.alpha-3.data_type
    - columns.name.description
    - columns.intermediate-region-code.description
    - columns.alpha-2.description
    - columns.region-code.description
    - description
    - columns.intermediate-region.description
    - columns.sub-region-code.data_type
    - columns.iso_3166-2.data_type
    - columns.alpha-2.data_type
    - columns.region.description
    - columns.country-code.description
    - columns.iso_3166-2.description
    - columns.alpha-3.description
    - columns.intermediate-region-code.data_type
    - columns.sub-region.description
    - columns.region-code.data_type
    - columns.sub-region.data_type
    - columns.sub-region-code.description
    - columns.region.data_type
    - columns.name.data_type
    - config.materialized

- name: stg_crawlers_data__ember_electricity_data
  description: This view aggregates and standardizes ember electricity data across various geographic and economic classifications to support analysis of electricity consumption and related trends.
  columns:

  - name: Area
    description: Name of the geographic area or country for which data is reported.
    data_type: String

  - name: code
    description: ''
    data_type: ''

  - name: Date
    description: Reporting date of the data point, typically in YYYY-MM-DD format.
    data_type: Date
    tests:
    - not_null

  - name: type
    description: ''
    data_type: String

  - name: Continent
    description: Continent where the Area is located.
    data_type: String

  - name: region
    description: Specific regional grouping within the continent, e.g., Ember region.
    data_type: ''

  - name: EU
    description: Boolean indicator (or equivalent) denoting EU membership.
    data_type: UInt8

  - name: OECD
    description: Boolean indicator denoting OECD membership.
    data_type: UInt8

  - name: G20
    description: Boolean indicator denoting G20 membership.
    data_type: UInt8

  - name: G7
    description: Boolean indicator denoting G7 membership.
    data_type: UInt8

  - name: ASEAN
    description: Boolean indicator denoting ASEAN membership.
    data_type: UInt8

  - name: Category
    description: Broad classification of the variable, e.g., consumption, production.
    data_type: String

  - name: Subcategory
    description: More specific classification within the Category, e.g., residential, industrial.
    data_type: String

  - name: Variable
    description: Specific metric or indicator being reported, such as total electricity consumption.
    data_type: String

  - name: Unit
    description: Measurement unit for the Value, e.g., GWh, MWh.
    data_type: String

  - name: Value
    description: Numerical value of the variable, representing the measurement in the specified Unit.
    data_type: Float64

  - name: change
    description: ''
    data_type: Int64

  - name: date
    description: The date of the data point in ISO format.
    data_type: DateTime

  - name: value
    description: The measured value of electricity data (numeric).
    data_type: Float64

  - name: category
    description: The category classification of the data.
    data_type: String

  - name: eu
    description: Indicator if the region is part of the EU.
    data_type: String

  - name: unit
    description: The unit of measurement for the value.
    data_type: String

  - name: asean
    description: Indicator if the region is part of ASEAN.
    data_type: String

  - name: oecd
    description: Indicator if the region is part of OECD.
    data_type: String

  - name: variable
    description: The variable name associated with the data.
    data_type: String

  - name: subcategory
    description: The subcategory classification.
    data_type: String

  - name: g20
    description: Indicator if the region is part of G20.
    data_type: String

  - name: g7
    description: Indicator if the region is part of G7.
    data_type: String

  - name: area
    description: The area name associated with the data.
    data_type: String

  - name: continent
    description: The continent where the region is located.
    data_type: String
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:57.985025'
    _generated_fields:
    - columns.Unit.description
    - columns.Category.data_type
    - columns.Continent.description
    - columns.code.data_type
    - config.tags
    - columns.G20.description
    - columns.ASEAN.description
    - columns.type.data_type
    - columns.ASEAN.data_type
    - columns.Area.description
    - description
    - columns.Variable.description
    - columns.OECD.data_type
    - columns.Date.description
    - columns.Subcategory.data_type
    - columns.OECD.description
    - columns.type.description
    - columns.EU.data_type
    - columns.Continent.data_type
    - columns.Subcategory.description
    - columns.region.description
    - columns.change.data_type
    - columns.Date.data_type
    - columns.Variable.data_type
    - columns.code.description
    - columns.change.description
    - columns.Area.data_type
    - columns.Value.data_type
    - columns.G7.description
    - columns.G20.data_type
    - columns.region.data_type
    - columns.G7.data_type
    - config.materialized
    - columns.Unit.data_type
    - columns.Value.description
    - columns.Category.description
    - columns.EU.description

