version: 2
models:

- name: stg_esg_consensus_power
  description: A staging model representing consensus power metrics with client, type, and mean values.
  columns:
  - name: type
    description: The type of consensus power, e.g., 4, 5, 6.
    data_type: String
  - name: client
    description: The client name, e.g., Lighthouse, Teku, Lodestar, Nimbus, Prysm.
    data_type: String
  - name: mean
    description: The mean value of consensus power in floating point.
    data_type: Float64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_execution_power
  description: A staging model representing execution power metrics, including client type, execution type, and mean execution power values.
  columns:
  - name: client
    description: Client name, e.g., 'Erigon', 'Nethermind'
    data_type: String
  - name: type
    description: Execution type, e.g., 4, 5, 6
    data_type: UInt64
  - name: mean
    description: Mean execution power value in floating point units
    data_type: Float64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_hardware_config
  description: A staging model representing hardware configuration details including type, CPU, cores and threads, architecture, RAM, storage, GPU, PSU, case, and OS.
  columns:
  - name: case
    description: Hardware case type (e.g., Integrated, Custom)
    data_type: String
  - name: cpu
    description: CPU model name (e.g., Intel i5-1135G7)
    data_type: String
  - name: storage
    description: Storage specification (e.g., 2 TB SSD)
    data_type: String
  - name: architecture
    description: CPU architecture (e.g., x86/x64)
    data_type: String
  - name: ram
    description: RAM size (e.g., 16 GB)
    data_type: String
  - name: os
    description: Operating system (e.g., Ubuntu 20.04)
    data_type: String
  - name: type
    description: Hardware type identifier (e.g., 4, 5, 6)
    data_type: UInt64
  - name: cores_threads
    description: Cores and threads configuration (e.g., 4/8)
    data_type: String
  - name: psu
    description: Power supply unit wattage (e.g., 65 Watt)
    data_type: String
  - name: gpu
    description: GPU model (e.g., Onboard, AM 6970)
    data_type: String
  config:
    access: public
    tags:
    - staging
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_idle_electric_power
  description: This model provides the idle electric power metrics with types and mean values for different categories.
  columns:
  - name: type
    description: Category type of idle electric power
    data_type: String
  - name: mean
    description: Average idle electric power values in units consistent with source
    data_type: Float64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_esg_node_distribution
  description: A staging model representing the distribution of node types with associated distribution values used for ESG analysis.
  columns:
  - name: type
    description: Node type identifier (e.g., 4, 5, 6)
    data_type: UInt64
  - name: distribution
    description: Distribution value corresponding to each node type (e.g., 0.25, 0.50)
    data_type: Float64
  config:
    access: public
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__country_codes
  description: A staging model that provides country code information including region, sub-region, and intermediate-region classifications for use in downstream analytics.
  columns:
  - name: region
    description: The geographical region of the country.
    data_type: String
  - name: sub-region-code
    description: Code representing the sub-region within the larger region.
    data_type: String
  - name: iso_3166-2
    description: ISO 3166-2 code for the country.
    data_type: String
  - name: alpha-3
    description: The three-letter country code (ISO 3166-1 alpha-3).
    data_type: String
  - name: sub-region
    description: The sub-region classification of the country.
    data_type: String
  - name: region-code
    description: Numeric code representing the region.
    data_type: String
  - name: country-code
    description: The country code.
    data_type: String
  - name: name
    description: The official country name.
    data_type: String
  - name: alpha-2
    description: The two-letter country code (ISO 3166-1 alpha-2).
    data_type: String
  - name: intermediate-region
    description: The intermediate region classification.
    data_type: String
  - name: intermediate-region-code
    description: Numeric code for the intermediate region.
    data_type: String
  config:
    access: public
    tags:
    - production
    - crawlers_data
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__ember_electricity_data
  description: A staging model containing ember electricity data with regional and categorical information.
  columns:
  - name: region
    description: The region name associated with the electricity data.
    data_type: String
  - name: date
    description: The date of the data point in ISO format.
    data_type: DateTime
  - name: value
    description: The measured value of electricity data (numeric).
    data_type: Float64
  - name: category
    description: The category classification of the data.
    data_type: String
  - name: eu
    description: Indicator if the region is part of the EU.
    data_type: String
  - name: unit
    description: The unit of measurement for the value.
    data_type: String
  - name: asean
    description: Indicator if the region is part of ASEAN.
    data_type: String
  - name: code
    description: The ISO 3 code representing the region.
    data_type: String
  - name: change
    description: The YoY absolute change in the value.
    data_type: Float64
  - name: oecd
    description: Indicator if the region is part of OECD.
    data_type: String
  - name: variable
    description: The variable name associated with the data.
    data_type: String
  - name: type
    description: The subcategory or type of the data.
    data_type: String
  - name: subcategory
    description: The subcategory classification.
    data_type: String
  - name: g20
    description: Indicator if the region is part of G20.
    data_type: String
  - name: g7
    description: Indicator if the region is part of G7.
    data_type: String
  - name: area
    description: The area name associated with the data.
    data_type: String
  - name: continent
    description: The continent where the region is located.
    data_type: String
  config:
    access: public
    materialized: view
    tags:
    - production
    - crawlers_data
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
