name: 'gnosis_dbt'
version: '1.0.0'
config-version: 2

profile: 'gnosis_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  gnosis_dbt: {}

seeds:
  gnosis_dbt:
    # optional: apply to all seeds in this package
    +quote_columns: false

    contracts_abi:
      engine: ReplacingMergeTree()
      order_by: [contract_address, implementation_address]
      +column_types:
        contract_address: "String"
        implementation_address: "String"
        abi_json: "String"
        contract_name: "String"
        source: "String"
        updated_at: "String"  

    event_signatures:
      engine: MergeTree()
      order_by: [contract_address, signature, event_name]
      +column_types:
        contract_address: "String"
        implementation_address: "String"
        contract_name: "String"
        event_name: "String"
        signature: "String"
        anonymous: "Int32"
        params: "String"
        indexed_params: "String"
        non_indexed_params: "String"

    function_signatures:
      engine: MergeTree()
      order_by: [contract_address, signature, function_name]
      +column_types:
        contract_address: "String"
        implementation_address: "String"
        contract_name: "String"
        function_name: "String"
        signature: "String"
        state_mutability: "String"
        input_params: "String"
        output_params: "String"
