name: 'gnosis_dbt'
version: '1.0.0'
config-version: 2

profile: 'gnosis_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  gnosis_dbt:

seeds:
  gnosis_dbt: 
    contracts_abi:
      engine: ReplacingMergeTree()
      order_by: [contract_address, implementation_address]
    event_signatures:
      engine: MergeTree()
      order_by: [contract_address, signature, event_name]
    function_signatures:
      engine: MergeTree()
      order_by: [contract_address, signature, function_name]