name: 'gnosis_dbt'
version: '1.0.0'
config-version: 2

profile: 'gnosis_dbt'  # This should match the profile name in profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  gnosis_dbt:

seeds:
  gnosis_dbt:
    ember_electricity_data:
    country_codes:
