services:
  dbt:
    container_name: dbt
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    restart: unless-stopped
    ports:
      - "8080:8000"
    command: > 
      /bin/bash -c "exec python -m http.server 8000 --directory logs & tail -f /dev/null"
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_URL: ${CLICKHOUSE_URL}
      CLICKHOUSE_PORT: ${CLICKHOUSE_PORT}
      CLICKHOUSE_SECURE: ${CLICKHOUSE_SECURE}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - type: bind
        source: ./
        target: /app
        consistency: cached
    working_dir: /app
    user: appuser
    networks:
      - dbt_net

networks:
  dbt_net: