services:
  dbt:
    container_name: dbt
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    restart: unless-stopped

    # Keep the existing mapping host 8080 → container 8000
    ports:
      - "8080:8000"

    env_file:
      - .env
    volumes:
      - type: bind
        source: ./
        target: /app
        consistency: cached
    working_dir: /app

    # Serve docs on port 8000 inside the container
    command: ["dbt", "docs", "serve", "--port", "8000", "--host", "0.0.0.0"]

    networks:
      - dbt_net

networks:
  dbt_net:
    driver: bridge
