services:
  dbt:
    container_name: dbt
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    restart: unless-stopped
    ports:
      - "8080:8000"
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./
        target: /app
        consistency: cached
    working_dir: /app
    networks:
      - dbt_net

networks:
  dbt_net:
    driver: bridge
