gnosis_dbt:
  target: ch-dbt
  outputs:
    ch-dbt:
      type: clickhouse
      schema: "dbt"
      verify: False
      host: "{{ env_var('CLICKHOUSE_URL') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | int }}"
      secure: "{{ (env_var('CLICKHOUSE_SECURE', 'False') | lower) == 'true' }}"
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      threads: 40
      connect_timeout: 60  # Increase the connect timeout (in seconds)
      read_timeout: 3000    # Increase the read timeout (in seconds)

    ch-valtrack: 
      type: clickhouse
      schema: "valtrack_preview"
      verify: False
      host: "{{ env_var('CLICKHOUSE_URL') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | int }}"
      secure: "{{ (env_var('CLICKHOUSE_SECURE', 'False') | lower) == 'true' }}"
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      threads: 40
      connect_timeout: 60
      read_timeout: 3000
    
    ch-goteth: 
      type: clickhouse
      schema: "goteth_preview"
      verify: False
      host: "{{ env_var('CLICKHOUSE_URL') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | int }}"
      secure: "{{ (env_var('CLICKHOUSE_SECURE', 'False') | lower) == 'true' }}"
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      threads: 40
      connect_timeout: 60
      read_timeout: 3000
