gnosis_dbt:
  target: clickhouse
  outputs:
    clickhouse:  # ClickHouse configuration for additional data sourcing
      type: clickhouse
      schema: "{{ env_var('CLICKHOUSE_SCHEMA') }}"
      verify: False
      host: "{{ env_var('CLICKHOUSE_URL') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | int }}"
      secure: "{{ (env_var('CLICKHOUSE_SECURE', 'False') | lower) == 'true' }}"
      cluster: '{cluster}'
      cluster_mode: True
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      threads: 40
      connect_timeout: 60  # Increase the connect timeout (in seconds)
      read_timeout: 3000    # Increase the read timeout (in seconds)
