gnosis_dbt:
  target: ch_dbt
  outputs:
    ch_dbt:
      type: clickhouse
      schema: "dbt"
      verify: False
      host: "{{ env_var('CLICKHOUSE_URL') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | int }}"
      secure: "{{ (env_var('CLICKHOUSE_SECURE', 'False') | lower) == 'true' }}"
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      threads: 40
      connect_timeout: 60
      read_timeout: 3000

    chaind:
      type: postgres
      dbname: "chaind"
      schema: "public"
      host: "{{ env_var('POSTGRES_HOST', 'postgres') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      threads: 80