gnosis_dbt:
  target: ch_dbt
  outputs:
    ch_dbt:
      type: clickhouse
      schema: "{{ env_var('CLICKHOUSE_DATABASE') }}"
      verify: False
      host: "{{ env_var('CLICKHOUSE_URL') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | int }}"
      secure: "{{ (env_var('CLICKHOUSE_SECURE', 'False') | lower) == 'true' }}"
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      threads: 40
      connect_timeout: 3000
      send_receive_timeout: 3000