version: 2
models:

- name: api_quarterly_data_gnosis_app_swaps
  description: Total swap transactions on Gnosis App per quarter.
  columns:
  - name: quarter
    description: Quarter start date.
    data_type: Date
  - name: swaps
    description: Total number of swap transactions in the quarter.
    data_type: UInt64

- name: api_quarterly_data_gnosis_app_swaps_filled
  description: Total filled swap transactions on Gnosis App per quarter.
  columns:
  - name: quarter
    description: Quarter start date.
    data_type: Date
  - name: swaps_filled
    description: Total number of filled swap transactions in the quarter.
    data_type: UInt64

- name: api_quarterly_data_gnosis_app_swap_volume
  description: Total swap volume in USD on Gnosis App per quarter.
  columns:
  - name: quarter
    description: Quarter start date.
    data_type: Date
  - name: volume_usd
    description: Sum of filled swap volume in USD during the quarter.
    data_type: Float64

- name: api_quarterly_data_gnosis_app_peak_swappers
  description: Peak daily unique swappers on Gnosis App within the quarter.
  columns:
  - name: quarter
    description: Quarter start date.
    data_type: Date
  - name: peak_daily_swappers
    description: Highest daily count of unique swap users in the quarter.
    data_type: UInt64
