version: 2
models:

- name: stg_crawlers_data__probelab_agent_semvers_avg_1d
  description: Daily aggregated data on agent semantic versions, including version types, time ranges, counts, and percentages, used for analysis of agent distribution.
  columns:
  - name: agent_version_type
    description: Type of agent version; nullable string.
    data_type: Nullable(String)
  - name: min_crawl_created_at
    description: Earliest crawl timestamp in the period; nullable datetime with microsecond precision.
    data_type: Nullable(DateTime64(6))
  - name: max_crawl_created_at
    description: Latest crawl timestamp in the period; nullable datetime with microsecond precision.
    data_type: Nullable(DateTime64(6))
  - name: agent_version_semver
    description: Array of semantic version components; nullable array of nullable integers.
    data_type: Array(Nullable(Int64))
  - name: agent_version_semver_str
    description: String representation of semantic version; nullable string.
    data_type: Nullable(String)
  - name: __count
    description: Count of records in the period; nullable float.
    data_type: Nullable(Float64)
  - name: __samples
    description: Number of samples used for aggregation; nullable unsigned integer.
    data_type: Nullable(UInt32)
  - name: __pct
    description: Percentage share of this version; nullable float.
    data_type: Nullable(Float64)
  - name: __total
    description: Total count for normalization; nullable float.
    data_type: Nullable(Float64)
  config:
    access: public
    tags:
    - production
    - crawlers_data
    - probelab_agent_semvers_avg_1d
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__probelab_cloud_provider_avg_1d
  description: Daily average share of cloud providers across crawls, aggregated for business insights.
  columns:
  - name: agent_version_type
    description: Type of agent version; nullable string.
    data_type: String
  - name: min_crawl_created_at
    description: Earliest crawl timestamp in the period; nullable DateTime64(0, 'UTC').
    data_type: DateTime64(0, 'UTC')
  - name: max_crawl_created_at
    description: Latest crawl timestamp in the period; nullable DateTime64(0, 'UTC').
    data_type: DateTime64(0, 'UTC')
  - name: cloud_provider
    description: Name of the cloud provider; nullable string.
    data_type: String
  - name: __count
    description: Count of records; nullable float.
    data_type: Float64
  - name: __samples
    description: Number of samples used; nullable unsigned int.
    data_type: UInt32
  - name: __pct
    description: Percentage share; nullable float.
    data_type: Float64
  - name: __total
    description: Total count for normalization; nullable float.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - crawlers_data
    - probelab_cloud_provider_avg_1d
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__probelab_countries_avg_1d
  description: Daily average share of peer countries, aggregated from crawls, for business analysis.
  columns:
  - name: agent_version_type
    description: Type of agent version, nullable string.
    data_type: String
  - name: min_crawl_created_at
    description: Earliest crawl timestamp in the period, nullable DateTime64(6).
    data_type: DateTime64(6)
  - name: max_crawl_created_at
    description: Latest crawl timestamp in the period, nullable DateTime64(6).
    data_type: DateTime64(6)
  - name: country_name
    description: Name of the country, nullable string.
    data_type: String
  - name: country
    description: Country code, nullable string.
    data_type: String
  - name: __count
    description: Count of records, nullable float.
    data_type: Float64
  - name: __samples
    description: Number of samples, nullable unsigned int.
    data_type: UInt32
  - name: __pct
    description: Percentage share, nullable float.
    data_type: Float64
  - name: __total
    description: Total count used for percentage calculation, nullable float.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - crawlers_data
    - probelab_countries_avg_1d
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__probelab_quic_support_over_7d
  description: 7‑day time series average share of QUIC support.
  columns:
  - name: agent_version_type
    description: Type of agent version, nullable string.
    data_type: Nullable(String)
  - name: min_crawl_created_at
    description: Earliest crawl timestamp in the 7-day window, nullable DateTime64.
    data_type: Nullable(DateTime64(6))
  - name: max_crawl_created_at
    description: Latest crawl timestamp in the 7-day window, nullable DateTime64.
    data_type: Nullable(DateTime64(6))
  - name: quic_support
    description: Support status for QUIC protocol, nullable string.
    data_type: Nullable(String)
  - name: __count
    description: Count of records in the window, nullable float.
    data_type: Nullable(Float64)
  - name: __samples
    description: Number of samples, nullable unsigned int.
    data_type: Nullable(UInt32)
  - name: __pct
    description: Percentage support, nullable float.
    data_type: Nullable(Float64)
  - name: __total
    description: Total count used for percentage calculation, nullable float.
    data_type: Nullable(Float64)
  config:
    access: public
    tags:
    - production
    - crawlers_data
    - probelab_quic_support_over_7d
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
