version: 2
models:

- name: stg_crawlers_data__probelab_agent_semvers_avg_1d
  description: Daily average distribution of agent semantic versions across crawls.
  columns:
  - name: agent_version_type
    description: Type of agent version, nullable string.
    data_type: Nullable(String)
  - name: min_crawl_created_at
    description: Earliest crawl timestamp in the period, nullable DateTime64(6).
    data_type: Nullable(DateTime64(6))
  - name: max_crawl_created_at
    description: Latest crawl timestamp in the period, nullable DateTime64(6).
    data_type: Nullable(DateTime64(6))
  - name: agent_version_semver
    description: Array of semantic version integers, nullable array of nullable Int64.
    data_type: Array(Nullable(Int64))
  - name: agent_version_semver_str
    description: Semantic version as string, nullable string.
    data_type: Nullable(String)
  - name: __count
    description: Count of records in the period, nullable float.
    data_type: Nullable(Float64)
  - name: __samples
    description: Number of samples, nullable unsigned int.
    data_type: Nullable(UInt32)
  - name: __pct
    description: Percentage share, nullable float.
    data_type: Nullable(Float64)
  - name: __total
    description: Total count, nullable float.
    data_type: Nullable(Float64)
  config:
    access: public
    tags:
    - production
    - crawlers_data
    - probelab_agent_semvers_avg_1d
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__probelab_cloud_provider_avg_1d
  description: Daily average share of cloud providers across crawls, representing the proportion of each cloud provider in the dataset for each day.
  columns:
  - name: agent_version_type
    description: Type of agent version; nullable if not available.
    data_type: Nullable(String)
  - name: min_crawl_created_at
    description: Earliest crawl timestamp for the period; nullable if not available.
    data_type: Nullable(DateTime64(6))
  - name: max_crawl_created_at
    description: Latest crawl timestamp for the period; nullable if not available.
    data_type: Nullable(DateTime64(6))
  - name: cloud_provider
    description: Name of the cloud provider; nullable if not specified.
    data_type: Nullable(String)
  - name: __count
    description: Count of records contributing to the average; nullable.
    data_type: Nullable(Float64)
  - name: __samples
    description: Number of samples used; nullable.
    data_type: Nullable(UInt32)
  - name: __pct
    description: Percentage share of the cloud provider; nullable.
    data_type: Nullable(Float64)
  - name: __total
    description: Total count used to compute percentage; nullable.
    data_type: Nullable(Float64)
  config:
    access: public
    tags:
    - production
    - crawlers_data
    - probelab_cloud_provider_avg_1d
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__probelab_countries_avg_1d
  description: Daily average share of peer countries with data aggregated from crawls.
  columns:
  - name: agent_version_type
    description: Type of agent version; nullable if unknown.
    data_type: String
  - name: min_crawl_created_at
    description: Earliest crawl timestamp in the period.
    data_type: DateTime64(0, 'UTC')
  - name: max_crawl_created_at
    description: Latest crawl timestamp in the period.
    data_type: DateTime64(0, 'UTC')
  - name: country_name
    description: Human-readable country name; nullable if unknown.
    data_type: String
  - name: country
    description: Country code or identifier; nullable if unknown.
    data_type: String
  - name: __count
    description: Count of records in the aggregation.
    data_type: Float64
  - name: __samples
    description: Number of samples used for averaging.
    data_type: UInt32
  - name: __pct
    description: Percentage share of the country relative to total.
    data_type: Float64
  - name: __total
    description: Total count or sum used for percentage calculation.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - crawlers_data
    - probelab_countries_avg_1d
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__probelab_quic_support_over_7d
  description: 7‑day time series average share of QUIC support.
  columns:
  - name: agent_version_type
    description: Type of agent version; nullable string.
    data_type: String
  - name: min_crawl_created_at
    description: Earliest crawl timestamp in the 7-day period; nullable datetime.
    data_type: DateTime64(6, 'UTC')
  - name: max_crawl_created_at
    description: Latest crawl timestamp in the 7-day period; nullable datetime.
    data_type: DateTime64(6, 'UTC')
  - name: quic_support
    description: Support status for QUIC protocol; nullable string.
    data_type: String
  - name: __count
    description: Count of records in the period; nullable float.
    data_type: Float64
  - name: __samples
    description: Number of samples used for calculations; nullable unsigned int.
    data_type: UInt32
  - name: __pct
    description: Percentage support; nullable float.
    data_type: Float64
  - name: __total
    description: Total count for reference; nullable float.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - crawlers_data
    - probelab_quic_support_over_7d
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
