version: 2
models:

- name: stg_crawlers_data__probelab_agent_semvers_avg_1d
  description: This view aggregates daily average semantic version data of agents, providing insights into version distribution and activity periods within the crawlers data pipeline.
  columns:

  - name: agent_version_type
    description: Categorizes the type of agent version, such as stable or beta.
    data_type: String

  - name: min_crawl_created_at
    description: Timestamp of the earliest crawl creation date within the dataset.
    data_type: DateTime64
    tests:
    - not_null

  - name: max_crawl_created_at
    description: Timestamp of the most recent crawl creation date within the dataset.
    data_type: DateTime64
    tests:
    - not_null

  - name: agent_version_semver
    description: Numerical representation of the semantic version, facilitating version comparisons.
    data_type: String

  - name: agent_version_semver_str
    description: String format of the semantic version, e.g., '1.2.3'.
    data_type: String

  - name: __count
    description: Number of records associated with the specific version type, agent version, and date range.
    data_type: UInt64

  - name: __samples
    description: Sample count or instances used to derive the averages or distributions.
    data_type: UInt64

  - name: __pct
    description: Percentage representation of the sample count relative to the total, expressed as a decimal.
    data_type: Float64

  - name: __total
    description: Total number of records considered in the dataset for the given grouping.
    data_type: UInt64
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:59.450954'
    _generated_fields:
    - columns.__pct.data_type
    - config.tags
    - columns.agent_version_type.data_type
    - columns.agent_version_semver_str.data_type
    - description
    - columns.__count.data_type
    - columns.agent_version_type.description
    - columns.max_crawl_created_at.data_type
    - columns.__samples.data_type
    - columns.__total.description
    - columns.agent_version_semver.data_type
    - columns.max_crawl_created_at.description
    - columns.__samples.description
    - columns.agent_version_semver.description
    - columns.agent_version_semver_str.description
    - config.materialized
    - columns.min_crawl_created_at.data_type
    - columns.min_crawl_created_at.description
    - columns.__pct.description
    - columns.__count.description
    - columns.__total.data_type

- name: stg_crawlers_data__probelab_cloud_provider_avg_1d
  description: This view aggregates daily average crawl data across different cloud providers, providing insights into crawler performance and distribution over time.
  columns:

  - name: agent_version_type
    description: Type of crawler agent version used during the crawl, indicating different software versions.
    data_type: String

  - name: min_crawl_created_at
    description: Timestamp of the earliest crawl creation date within the dataset.
    data_type: DateTime64
    tests:
    - not_null

  - name: max_crawl_created_at
    description: Timestamp of the most recent crawl creation date within the dataset.
    data_type: DateTime64
    tests:
    - not_null

  - name: cloud_provider
    description: Name of the cloud service provider hosting the crawler infrastructure.
    data_type: String

  - name: __count
    description: Number of crawl records included in the aggregation.
    data_type: UInt64

  - name: __samples
    description: Sample count of individual crawl instances used for statistical calculations.
    data_type: UInt64

  - name: __pct
    description: Percentage representation of the sample relative to total crawls, expressed as a decimal or percentage.
    data_type: Float64

  - name: __total
    description: Total number of crawl records considered in the dataset.
    data_type: Float64
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:59.451040'
    _generated_fields:
    - columns.__pct.data_type
    - config.tags
    - columns.agent_version_type.data_type
    - description
    - columns.__count.data_type
    - columns.agent_version_type.description
    - columns.cloud_provider.description
    - columns.max_crawl_created_at.data_type
    - columns.__samples.data_type
    - columns.__total.description
    - columns.max_crawl_created_at.description
    - columns.__samples.description
    - config.materialized
    - columns.min_crawl_created_at.data_type
    - columns.min_crawl_created_at.description
    - columns.__pct.description
    - columns.cloud_provider.data_type
    - columns.__count.description
    - columns.__total.data_type

- name: stg_crawlers_data__probelab_countries_avg_1d
  description: This view aggregates daily crawler data by country and agent version type, providing insights into crawling activity and coverage across different regions and versions.
  columns:

  - name: agent_version_type
    description: Categorizes crawler agents based on their version type.
    data_type: String

  - name: min_crawl_created_at
    description: Timestamp of the earliest crawl creation date within the dataset period.
    data_type: DateTime64
    tests:
    - not_null

  - name: max_crawl_created_at
    description: Timestamp of the most recent crawl creation date within the dataset period.
    data_type: DateTime64
    tests:
    - not_null

  - name: country_name
    description: Official name of the country associated with the crawling data.
    data_type: String

  - name: country
    description: Country code or identifier linked to the crawling activity.
    data_type: String

  - name: __count
    description: Total number of crawl records for the specified filters.
    data_type: UInt64

  - name: __samples
    description: Number of sample crawl records used for analysis.
    data_type: UInt64

  - name: __pct
    description: Percentage representation of the sample count relative to total records.
    data_type: Float64

  - name: __total
    description: Total number of crawl records across all samples and filters.
    data_type: UInt64
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:59.451121'
    _generated_fields:
    - columns.__pct.data_type
    - config.tags
    - columns.agent_version_type.data_type
    - columns.country_name.description
    - columns.country.data_type
    - description
    - columns.country.description
    - columns.__count.data_type
    - columns.agent_version_type.description
    - columns.max_crawl_created_at.data_type
    - columns.__samples.data_type
    - columns.__total.description
    - columns.country_name.data_type
    - columns.max_crawl_created_at.description
    - columns.__samples.description
    - config.materialized
    - columns.min_crawl_created_at.data_type
    - columns.min_crawl_created_at.description
    - columns.__pct.description
    - columns.__count.description
    - columns.__total.data_type

- name: stg_crawlers_data__probelab_quic_support_over_7d
  description: This view aggregates crawler data to analyze the support for QUIC protocol over a 7-day period, segmented by agent version type.
  columns:

  - name: agent_version_type
    description: Categorizes crawler agents based on their version type.
    data_type: String

  - name: min_crawl_created_at
    description: Earliest crawl creation timestamp within the data set.
    data_type: DateTime64
    tests:
    - not_null

  - name: max_crawl_created_at
    description: Latest crawl creation timestamp within the data set.
    data_type: DateTime64
    tests:
    - not_null

  - name: crawl_created_at
    description: Timestamp of the specific crawl event being analyzed.
    data_type: DateTime64
    tests:
    - not_null

  - name: quic_support
    description: Indicates whether QUIC support was present (e.g., boolean or categorical).
    data_type: String

  - name: __count
    description: Number of records matching the criteria.
    data_type: UInt64

  - name: __pct
    description: Percentage representation of the count relative to the total.
    data_type: Float64

  - name: __total
    description: Total number of records considered in the analysis.
    data_type: UInt64

  - name: __samples
    description: Number of samples, nullable unsigned int.
    data_type: Nullable(UInt32)
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:59.451199'
    _generated_fields:
    - columns.__pct.data_type
    - config.tags
    - columns.agent_version_type.data_type
    - description
    - columns.__count.data_type
    - columns.agent_version_type.description
    - columns.max_crawl_created_at.data_type
    - columns.quic_support.data_type
    - columns.quic_support.description
    - columns.__total.description
    - columns.max_crawl_created_at.description
    - config.materialized
    - columns.min_crawl_created_at.data_type
    - columns.min_crawl_created_at.description
    - columns.crawl_created_at.description
    - columns.__pct.description
    - columns.crawl_created_at.data_type
    - columns.__count.description
    - columns.__total.data_type

