version: 2
models:

- name: stg_crawlers_data__probelab_agent_semvers_avg_1d
  description: Daily aggregated data on agent semantic versions, including version distribution, counts, and percentages across crawl periods.
  columns:
  - name: agent_version_type
    description: Type of agent version, e.g., 'fullnode', 'lightnode'; nullable if unknown.
    data_type: Nullable(String)
    tests:
    - not_null
  - name: min_crawl_created_at
    description: Earliest crawl timestamp in the period, in UTC.
    data_type: Nullable(DateTime64(6))
  - name: max_crawl_created_at
    description: Latest crawl timestamp in the period, in UTC.
    data_type: Nullable(DateTime64(6))
  - name: agent_version_semver
    description: Array of semantic version components, e.g., [1, 2, 3]; nullable if not available.
    data_type: Array(Nullable(Int64))
  - name: agent_version_semver_str
    description: String representation of semantic version, e.g., '1.2.3'; nullable if not available.
    data_type: Nullable(String)
  - name: __count
    description: Count of records in the period, nullable.
    data_type: Nullable(Float64)
  - name: __samples
    description: Number of samples used for averaging, nullable.
    data_type: Nullable(UInt32)
  - name: __pct
    description: Percentage share of this version distribution, nullable.
    data_type: Nullable(Float64)
  - name: __total
    description: Total count across all versions, nullable.
    data_type: Nullable(Float64)
  config:
    access: public
    tags:
    - probelab
    - semver
    - daily
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__probelab_cloud_provider_avg_1d
  description: Daily average share of cloud providers, aggregated across crawls, providing insights into cloud provider distribution over time.
  columns:
  - name: agent_version_type
    description: Type of agent version; nullable string indicating agent semantic version category.
    data_type: String
    tests:
    - not_null
  - name: min_crawl_created_at
    description: Earliest crawl timestamp for the aggregation period.
    data_type: DateTime64(6, 'UTC')
  - name: max_crawl_created_at
    description: Latest crawl timestamp for the aggregation period.
    data_type: DateTime64(6, 'UTC')
  - name: cloud_provider
    description: Name of the cloud provider; nullable string.
    data_type: String
  - name: __count
    description: Count of records contributing to the average; nullable float.
    data_type: Float64
  - name: __samples
    description: Number of samples used in calculation; nullable unsigned integer.
    data_type: UInt32
  - name: __pct
    description: Percentage share of the cloud provider; nullable float.
    data_type: Float64
  - name: __total
    description: Total count used as denominator for percentage calculations; nullable float.
    data_type: Float64
  config:
    access: public
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__probelab_countries_avg_1d
  description: Daily average share of peer countries, aggregated over crawls, providing insights into country-level distribution.
  columns:
  - name: agent_version_type
    description: Type of agent version, nullable.
    data_type: String
    tests:
    - not_null
  - name: min_crawl_created_at
    description: Earliest crawl timestamp in the period.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: max_crawl_created_at
    description: Latest crawl timestamp in the period.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: country_name
    description: Name of the country, nullable.
    data_type: String
  - name: country
    description: Country code or identifier, nullable.
    data_type: String
  - name: __count
    description: Count of records in the aggregation.
    data_type: Float64
  - name: __samples
    description: Number of samples used for averaging.
    data_type: UInt32
  - name: __pct
    description: Percentage share of the country.
    data_type: Float64
  - name: __total
    description: Total count across all countries.
    data_type: Float64
  config:
    access: public
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__probelab_quic_support_over_7d
  description: 7‑day time series average share of QUIC support.
  columns:
  - name: agent_version_type
    description: Type of agent version; nullable string.
    data_type: String
    tests:
    - not_null
  - name: min_crawl_created_at
    description: Earliest crawl timestamp in the period; nullable datetime.
    data_type: DateTime64(6, 'UTC')
  - name: max_crawl_created_at
    description: Latest crawl timestamp in the period; nullable datetime.
    data_type: DateTime64(6, 'UTC')
  - name: quic_support
    description: Support status for QUIC protocol; nullable string.
    data_type: String
  - name: __count
    description: Count of records in the period; nullable float.
    data_type: Float64
  - name: __samples
    description: Number of samples; nullable unsigned int.
    data_type: UInt32
  - name: __pct
    description: Percentage support; nullable float.
    data_type: Float64
  - name: __total
    description: Total count for normalization; nullable float.
    data_type: Float64
  config:
    access: public
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
