version: 2
models:

- name: stg_crawlers_data__probelab_agent_semvers_avg_1d
  description: Daily average distribution of agent semantic versions across crawls.
  columns:
  - name: agent_version_type
    description: Type of agent version (e.g., browser, node).
    data_type: Nullable(String)
  - name: min_crawl_created_at
    description: Earliest crawl timestamp in the period.
    data_type: Nullable(DateTime64(6))
  - name: max_crawl_created_at
    description: Latest crawl timestamp in the period.
    data_type: Nullable(DateTime64(6))
  - name: agent_version_semver
    description: Array of semantic version components (nullable integers).
    data_type: Array(Nullable(Int64))
  - name: agent_version_semver_str
    description: Semantic version string representation.
    data_type: Nullable(String)
  - name: __count
    description: Count of occurrences in the period.
    data_type: Nullable(Float64)
  - name: __samples
    description: Number of samples.
    data_type: Nullable(UInt32)
  - name: __pct
    description: Percentage share of total.
    data_type: Nullable(Float64)
  - name: __total
    description: Total count for normalization.
    data_type: Nullable(Float64)
  config:
    access: public
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__probelab_cloud_provider_avg_1d
  description: Daily average share of cloud providers across crawls, representing the proportion of each cloud provider observed in the dataset on a given day.
  columns:
  - name: agent_version_type
    description: Type of agent version, nullable string.
    data_type: String
  - name: min_crawl_created_at
    description: Earliest crawl timestamp in the period, nullable datetime.
    data_type: DateTime64(6)
  - name: max_crawl_created_at
    description: Latest crawl timestamp in the period, nullable datetime.
    data_type: DateTime64(6)
  - name: cloud_provider
    description: Name of the cloud provider, nullable string.
    data_type: String
  - name: __count
    description: Count of observations for the cloud provider, nullable float.
    data_type: Float64
  - name: __samples
    description: Number of samples used to compute the average, nullable unsigned int.
    data_type: UInt32
  - name: __pct
    description: Percentage share of the cloud provider, nullable float.
    data_type: Float64
  - name: __total
    description: Total observations considered in the calculation, nullable float.
    data_type: Float64
  config:
    access: public
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__probelab_countries_avg_1d
  description: Daily average share of peer countries, aggregated over crawls, providing insights into country-level distribution patterns.
  columns:
  - name: __total
    description: Total count of observations for the day.
    data_type: Float64
  - name: country_name
    description: Name of the country.
    data_type: String
  - name: min_crawl_created_at
    description: Earliest crawl timestamp for the day.
    data_type: DateTime64(0, 'UTC')
  - name: __samples
    description: Number of samples used for aggregation.
    data_type: UInt32
  - name: country
    description: Country code or identifier.
    data_type: String
  - name: agent_version_type
    description: Type of agent version.
    data_type: String
  - name: max_crawl_created_at
    description: Latest crawl timestamp for the day.
    data_type: DateTime64(0, 'UTC')
  - name: __count
    description: Count of records for the country.
    data_type: Float64
  - name: __pct
    description: Percentage share of the country among total.
    data_type: Float64
  config:
    access: public
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__probelab_quic_support_over_7d
  description: 7‑day time series average share of QUIC support.
  columns:
  - name: agent_version_type
    description: Type of agent version; nullable string.
    data_type: String
  - name: min_crawl_created_at
    description: Earliest crawl timestamp in the period; nullable DateTime64(6).
    data_type: DateTime64(6, 'UTC')
  - name: max_crawl_created_at
    description: Latest crawl timestamp in the period; nullable DateTime64(6).
    data_type: DateTime64(6, 'UTC')
  - name: quic_support
    description: Support status for QUIC protocol; nullable string.
    data_type: String
  - name: __count
    description: Count of records contributing to the average; nullable float.
    data_type: Float64
  - name: __samples
    description: Number of samples used; nullable UInt32.
    data_type: UInt32
  - name: __pct
    description: Percentage support; nullable float.
    data_type: Float64
  - name: __total
    description: Total number of observations; nullable float.
    data_type: Float64
  config:
    access: public
    tags: []
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
