version: 2
models:

- name: int_execution_transactions_info_daily
  description: Daily aggregated information on execution transactions including gas usage, transaction type, and success status.
  columns:
  - name: date
    description: UTC date of the transaction.
    data_type: DateTime
  - name: transaction_type
    description: Type of the transaction.
    data_type: UInt32
  - name: success
    description: Indicator of transaction success (1 for success, 0 for failure).
    data_type: UInt8
  - name: n_txs
    description: Total number of transactions.
    data_type: UInt64
  - name: xdai_value
    description: Total value in native currency (XDAI).
    data_type: Float64
  - name: xdai_value_avg
    description: Average value in native currency (XDAI).
    data_type: Float64
  - name: xdai_value_median
    description: Median value in native currency (XDAI).
    data_type: Float64
  - name: gas_used
    description: Total gas used in transactions.
    data_type: UInt64
  - name: gas_price_avg
    description: Average gas price in Gwei.
    data_type: Int32
  - name: gas_price_median
    description: Median gas price in Gwei.
    data_type: Int32
  - name: fee_native_sum
    description: Total fee in native currency (XDAI).
    data_type: Float64
  - name: fee_usd_sum
    description: Total fee in USD.
    data_type: Float64
  config:
    materialized: incremental
    unique_key: (date, transaction_type, success)
    partition_by: toStartOfMonth(date)
    tags:
    - production
    - execution
    - transactions
    access: public
  meta:
    owner: analytics_engineer
    authoritative: false
    generated_by: schema-writer
- name: int_execution_transactions_by_project_daily
  description: Model representing daily execution transactions grouped by project.
  columns:
  - name: date
    description: Date of the transaction.
    data_type: DateTime
  - name: project
    description: Project name associated with the transaction.
    data_type: String
  - name: tx_count
    description: Total number of transactions.
    data_type: BigInt
  - name: active_accounts
    description: Number of active accounts.
    data_type: BigInt
  - name: ua_bitmap_state
    description: Bitmap state of user agents.
    data_type: String
  - name: gas_used_sum
    description: Total gas used.
    data_type: Float64
  - name: fee_native_sum
    description: Sum of native fees.
    data_type: Float64
  - name: fee_usd_sum
    description: Sum of fees in USD.
    data_type: Float64
  config:
    materialized: incremental
    unique_key:
    - date
    - project
    partition_by: toStartOfMonth(date)
    tags:
    - production
    - execution
    - transactions
    access: public
  meta:
    owner: analytics_engineer
    authoritative: false
    generated_by: schema-writer
- name: int_execution_transactions_by_project_hourly_recent
  description: '"Aggregated execution transactions by project and hour, including transaction count, active accounts, user-agent bitmap state, and fee sums."'
  columns:
  - name: hour
    description: Hour of the transaction (truncated to the nearest hour).
    data_type: DateTime
  - name: project
    description: Project associated with the transaction, defaulting to 'Unknown' if not found.
    data_type: String
  - name: tx_count
    description: Total number of transactions in the hour for the project.
    data_type: Int64
  - name: active_accounts
    description: Count of unique sender addresses in the transactions.
    data_type: Int64
  - name: ua_bitmap_state
    description: Bitmap state of user-agent hashes for the transactions.
    data_type: String
  - name: fee_native_sum
    description: Sum of transaction fees in native currency (GNO/XDAI).
    data_type: Float64
  - name: fee_usd_sum
    description: Sum of transaction fees converted to USD.
    data_type: Float64
  config:
    materialized: view
    access: public
    tags:
    - production
    - execution
    - transactions
    - hourly
  meta:
    owner: analytics_engineer
    authoritative: false
    generated_by: schema-writer
