version: 2
models:

- name: int_execution_transactions_info_daily
  description: Business-facing daily summary of execution transactions, including counts, values, and median metrics, aggregated by date, transaction type, and success status.
  columns:
  - name: date
    description: Date truncated from block_timestamp (UTC), representing the day of the transaction.
    data_type: DateTime
  - name: transaction_type
    description: Type of transaction, converted to string for categorization.
    data_type: String
  - name: success
    description: Indicator if the transaction succeeded (1) or reverted (0).
    data_type: UInt8
  - name: n_txs
    description: Total number of transactions for the given date, type, and success status.
    data_type: UInt64
  - name: xdai_value
    description: Sum of transaction values in xDai units (wei divided by 10^18).
    data_type: Float64
  - name: xdai_value_avg
    description: Average transaction value in xDai units.
    data_type: Float64
  - name: xdai_value_median
    description: Median transaction value in xDai units.
    data_type: Float64
  - name: gas_used
    description: Total gas used in transactions, in Gwei (gas_used / 10^9).
    data_type: Float64
  - name: gas_price_avg
    description: Average gas price in Gwei (gas_price / 10^9) for transactions.
    data_type: Int32
  - name: gas_price_median
    description: Median gas price in Gwei for transactions.
    data_type: Int32
  config:
    access: public
    tags:
    - production
    - execution
    - transactions
    materialized: table
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
