version: 2
models:

- name: int_execution_transactions_info_daily
  description: Daily aggregated execution transaction data including counts, values, and median metrics for transaction types and success status.
  columns:
  - name: date
    description: Date truncated from block timestamp (UTC).
    data_type: DateTime
  - name: transaction_type
    description: Type of transaction (e.g., transfer, contract call).
    data_type: String
  - name: success
    description: Transaction success status (1 = success, 0 = failure).
    data_type: UInt8
  - name: n_txs
    description: Total number of transactions for the given date, type, and success status.
    data_type: UInt64
  - name: xdai_value
    description: Sum of transaction values in xDai units.
    data_type: Float64
  - name: xdai_value_avg
    description: Average transaction value in xDai units.
    data_type: Float64
  - name: xdai_value_median
    description: Median transaction value in xDai units.
    data_type: Float64
  - name: gas_used
    description: Total gas used in Gwei units.
    data_type: Float64
  - name: gas_price_avg
    description: Average gas price in Gwei.
    data_type: Int32
  - name: gas_price_median
    description: Median gas price in Gwei.
    data_type: Int32
  config:
    access: public
    materialized: table
    tags:
    - aggregation
    - daily
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
