version: 2
models:

- name: int_execution_transactions_info_daily
  description: Business-facing summary of daily execution transactions, including counts, values, and median metrics for transaction types, success status, and gas usage.
  columns:
  - name: date
    description: Date representing the start of the day for the aggregated data.
    data_type: DateTime
    tests:
    - not_null
  - name: transaction_type
    description: Type of transaction (e.g., standard, contract creation), as string.
    data_type: String
    tests:
    - not_null
  - name: success
    description: Success status of transactions; 1 for success, 0 for failure.
    data_type: UInt8
    tests:
    - not_null
  - name: n_txs
    description: Total number of transactions of this type and success status for the day.
    data_type: UInt64
  - name: xdai_value
    description: Sum of transaction values in xDai units (wei divided by 10^18) for the group.
    data_type: Float64
  - name: xdai_value_avg
    description: Average transaction value in xDai units.
    data_type: Float64
  - name: xdai_value_median
    description: Median transaction value in xDai units.
    data_type: Float64
  - name: gas_used
    description: Total gas used in transactions (Gwei units, sum).
    data_type: Float64
  - name: gas_price_avg
    description: Average gas price in Gwei.
    data_type: Int32
  - name: gas_price_median
    description: Median gas price in Gwei.
    data_type: Int32
  config:
    access: public
    materialized: incremental
    tags:
    - execution
    - daily
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
