version: 2
models:
- name: p2p_peers_info
  description: 'TODO: Add description for p2p_peers_info'
  meta:
    sector: p2p
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - p2p
    - nebula
    - transformations
  columns:
  - name: cl_fork_name
    description: 'TODO: Add description for cl_fork_name'
    data_tests:
    - not_null
  - name: fork_digest
    description: 'TODO: Add description for fork_digest'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - cl_fork_name
      - fork_digest
