version: 2
models:
- name: p2p_peers_info
  description: This model aggregates information about P2P peers, joining data from the `visits` table with fork information.  It uses incremental strategy for efficient updates.
  columns:
  - name: visit_ended_at
    description: Timestamp indicating when the peer visit ended.
    data_type: timestamp
  - name: peer_id
    description: Unique identifier for the peer.
    data_type: string
  - name: agent_version
    description: Version of the peer's agent software.
    data_type: string
  - name: fork_digest
    description: Digest representing the current fork the peer is on.
    data_type: string
  - name: cl_fork_name
    description: Client fork name corresponding to the fork digest.
    data_type: string
  - name: cl_next_fork_name
    description: Client fork name the peer is expected to upgrade to.
    data_type: string
  - name: peer_properties
    description: JSON containing additional properties of the peer.
    data_type: json
  - name: crawl_error
    description: Information about any errors encountered during crawling.
    data_type: string
  - name: dial_errors
    description: Information about any dial errors encountered.
    data_type: string
  tags:
  - p2p
  - incremental
