version: 2
models:
- name: consensus_validators_waiting_times
  meta:
    blockchain: consensus
    sector: validators
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - consensus
    - validators
  description: 'TODO: Add description for consensus_validators_waiting_times'
  columns:
  - name: activation_delay
    description: 'TODO: Add description for activation_delay'
    data_tests:
    - not_null
    - unique
  - name: eligibility_delay
    description: 'TODO: Add description for eligibility_delay'
    data_tests:
    - not_null
    - unique
  - name: entry_delay
    description: 'TODO: Add description for entry_delay'
    data_tests:
    - not_null
    - unique
  - name: eth1_block_timestamp
    description: 'TODO: Add description for eth1_block_timestamp'
    data_tests:
    - not_null
    - unique
  - name: exit_activation_delay
    description: 'TODO: Add description for exit_activation_delay'
    data_tests:
    - not_null
    - unique
  - name: exit_delay
    description: 'TODO: Add description for exit_delay'
    data_tests:
    - not_null
    - unique
  - name: exit_withdrawable_delay
    description: 'TODO: Add description for exit_withdrawable_delay'
    data_tests:
    - not_null
    - unique
  - name: f_validator_pubkey
    description: 'TODO: Add description for f_validator_pubkey'
    data_tests:
    - not_null
    - unique
  - name: queue_exit_delay
    description: 'TODO: Add description for queue_exit_delay'
    data_tests:
    - not_null
    - unique
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - activation_delay
      - eligibility_delay
- name: consensus_validators_eff_balance_dist
  meta:
    blockchain: consensus
    sector: validators
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - consensus
    - validators
  description: 'TODO: Add description for consensus_validators_eff_balance_dist'
  columns:
  - name: FLOAT)/32000000000) as max_total
    description: 'TODO: Add description for FLOAT)/32000000000) as max_total'
    data_tests:
    - not_null
    - unique
  - name: FLOAT)/32000000000) as min_total
    description: 'TODO: Add description for FLOAT)/32000000000) as min_total'
    data_tests:
    - not_null
    - unique
  - name: FLOAT)/32000000000))/{{num_bins}} as bin_size
    description: 'TODO: Add description for FLOAT)/32000000000))/{{num_bins}} as bin_size'
    data_tests:
    - not_null
    - unique
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - FLOAT)/32000000000) as max_total
      - FLOAT)/32000000000) as min_total
- name: consensus_validators_participation_rate
  meta:
    blockchain: consensus
    sector: validators
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - consensus
    - validators
  description: 'TODO: Add description for consensus_validators_participation_rate'
  columns:
  - name: f_value
    description: 'TODO: Add description for f_value'
    data_tests:
    - not_null
    - unique
- name: consensus_validators_activations
  meta:
    blockchain: consensus
    sector: validators
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - consensus
    - validators
  description: 'TODO: Add description for consensus_validators_activations'
  columns:
  - name: cnt
    description: 'TODO: Add description for cnt'
    data_tests:
    - not_null
    - unique
  - name: day
    description: 'TODO: Add description for day'
    data_tests:
    - not_null
    - unique
  - name: label
    description: 'TODO: Add description for label'
    data_tests:
    - not_null
    - unique
  - name: month
    description: 'TODO: Add description for month'
    data_tests:
    - not_null
    - unique
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - cnt
      - day
- name: consensus_validators_entry_queue
  meta:
    blockchain: consensus
    sector: validators
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - consensus
    - validators
  description: 'TODO: Add description for consensus_validators_entry_queue'
  columns:
  - name: max(partition_month) as partition_month
    description: 'TODO: Add description for max(partition_month) as partition_month'
    data_tests:
    - not_null
    - unique
- name: consensus_validators_queue_cnt_d
  meta:
    blockchain: consensus
    sector: validators
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - consensus
    - validators
  description: 'TODO: Add description for consensus_validators_queue_cnt_d'
  columns:
  - name: activation_delay
    description: 'TODO: Add description for activation_delay'
    data_tests:
    - not_null
    - unique
  - name: eligibility_delay
    description: 'TODO: Add description for eligibility_delay'
    data_tests:
    - not_null
    - unique
  - name: entry_delay
    description: 'TODO: Add description for entry_delay'
    data_tests:
    - not_null
    - unique
  - name: eth1_block_timestamp
    description: 'TODO: Add description for eth1_block_timestamp'
    data_tests:
    - not_null
    - unique
  - name: exit_activation_delay
    description: 'TODO: Add description for exit_activation_delay'
    data_tests:
    - not_null
    - unique
  - name: exit_delay
    description: 'TODO: Add description for exit_delay'
    data_tests:
    - not_null
    - unique
  - name: exit_withdrawable_delay
    description: 'TODO: Add description for exit_withdrawable_delay'
    data_tests:
    - not_null
    - unique
  - name: f_validator_pubkey
    description: 'TODO: Add description for f_validator_pubkey'
    data_tests:
    - not_null
    - unique
  - name: queue_exit_delay
    description: 'TODO: Add description for queue_exit_delay'
    data_tests:
    - not_null
    - unique
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - activation_delay
      - eligibility_delay
