version: 2
models:

- name: contracts_sdai_events
  description: The `contracts_sdai_events` model captures and processes event logs related to the specified smart contract, enabling analysis of contract interactions and activities over time.
  columns:

  - name: block_timestamp
    description: The timestamp when the block was mined, in UTC.
    data_type: DateTime

  - name: log_index
    description: The index of the log within the block, used to order logs.
    data_type: UInt64

  - name: transaction_hash
    description: The hash of the transaction associated with the event.
    data_type: String

  - name: contract_address
    description: The address of the contract emitting the event.
    data_type: String

  - name: event_name
    description: The name of the event emitted.
    data_type: String

  - name: event_data
    description: The JSON payload containing event-specific data.
    data_type: JSON

  - name: sender_address
    description: The address initiating the transaction.
    data_type: String

  - name: recipient_address
    description: The address receiving tokens or assets, if applicable.
    data_type: String

  - name: amount
    description: The amount transferred, in wei or relevant units.
    data_type: String

  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64

  - name: transaction_index
    description: The index of the transaction within the block.
    data_type: UInt64

  - name: event_signature
    description: The signature of the event, used for identification.
    data_type: String
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2023-09-01"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.580141'
    _generated_fields:
    - description
    - config.tags
    - config.materialized

- name: contracts_wxdai_calls
  description: The `contracts_wxdai_calls` model captures and decodes call interactions with the specified wxDai contract, providing detailed insights into transaction activity over time.
  columns:

  - name: transaction_hash
    description: Unique hash identifying each transaction.
    data_type: String

  - name: block_number
    description: Number of the block containing the transaction.
    data_type: UInt64

  - name: block_timestamp
    description: Timestamp when the block was mined.
    data_type: DateTime64(0, 'UTC')

  - name: call_data
    description: Encoded call data for the transaction.
    data_type: String

  - name: caller_address
    description: Address of the caller initiating the call.
    data_type: String

  - name: contract_address
    description: Address of the wxdai contract involved.
    data_type: String

  - name: call_type
    description: Type of call made to the contract.
    data_type: String

  - name: call_value
    description: Value transferred during the call in wei.
    data_type: String

  - name: gas_used
    description: Amount of gas used for the call.
    data_type: UInt64

  - name: status
    description: Call execution status (e.g., success or failure).
    data_type: String

  - name: created_at
    description: Timestamp when the record was created.
    data_type: DateTime64(0, 'UTC')

  - name: updated_at
    description: Timestamp when the record was last updated.
    data_type: DateTime64(0, 'UTC')
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2020-07-01"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.580198'
    _generated_fields:
    - description
    - config.tags
    - config.materialized

- name: contracts_wxdai_events
  description: The `contracts_wxdai_events` model captures and processes event logs related to the specified contract address, enabling analysis of contract interactions on a monthly incremental basis.
  columns:

  - name: block_timestamp
    description: The timestamp of the block containing the event, in UTC.
    data_type: DateTime

  - name: log_index
    description: The index of the log within the block, used to order events.
    data_type: UInt64

  - name: transaction_hash
    description: The hash of the transaction that emitted the event.
    data_type: String

  - name: contract_address
    description: The address of the contract emitting the event.
    data_type: String

  - name: event_type
    description: The type of wxDai event (e.g., deposit, withdrawal).
    data_type: String

  - name: amount
    description: The amount involved in the event, in wei.
    data_type: String

  - name: sender
    description: The address initiating the transaction.
    data_type: String

  - name: recipient
    description: The address receiving the tokens, if applicable.
    data_type: String
  meta:
    owner: analytics-team
    authoritative: false
    full_refresh:
      start_date: "2020-07-01"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.580233'
    _generated_fields:
    - description
    - config.tags
    - config.materialized
