version: 2
models:

- name: contracts_sdai_events
  description: This model captures SDai contract events, including transaction details, block information, and event-specific data for analysis and reporting.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block (sequence number)
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction containing the event
    data_type: String
  - name: contract_address
    description: Address of the smart contract emitting the event
    data_type: String
  - name: event_name
    description: Name of the event emitted
    data_type: String
  - name: event_data
    description: JSON object containing event-specific data
    data_type: JSON
  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64
  - name: sender_address
    description: Address initiating the transaction
    data_type: String
  - name: recipient_address
    description: Address receiving tokens or assets (if applicable)
    data_type: String
  - name: amount
    description: Amount transferred in wei or relevant unit
    data_type: String
  - name: status
    description: Status of the transaction or event (e.g., success, failure)
    data_type: String
  - name: block_hash
    description: Hash of the block containing the event
    data_type: String
  - name: created_at
    description: Timestamp when the record was created in the database
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - contracts
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_wxdai_calls
  description: This model captures details of wxDai call transactions, including transaction hashes, block timestamps, sender and receiver addresses, call data, and associated metadata.
  columns:
  - name: transaction_hash
    description: Unique identifier for each transaction, represented as a hexadecimal string.
    data_type: String
  - name: block_timestamp
    description: Timestamp of the block containing the transaction, in UTC.
    data_type: DateTime
  - name: sender_address
    description: Address of the transaction sender, as a hexadecimal string.
    data_type: String
  - name: receiver_address
    description: Address of the transaction receiver, as a hexadecimal string.
    data_type: String
  - name: call_data
    description: Hex-encoded data payload of the call.
    data_type: String
  - name: call_type
    description: Type of call made, e.g., 'deposit', 'withdraw'.
    data_type: String
  - name: gas_used
    description: Amount of gas used for the transaction, in wei.
    data_type: UInt64
  - name: gas_price
    description: Gas price at the time of transaction, in wei.
    data_type: UInt64
  - name: status
    description: Transaction status, e.g., 'success' or 'failed'.
    data_type: String
  - name: block_number
    description: The number of the block containing the transaction.
    data_type: UInt64
  - name: created_at
    description: Timestamp when the record was created in the database.
    data_type: DateTime
  - name: updated_at
    description: Timestamp when the record was last updated.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - wxdai
    - calls
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_wxdai_events
  description: This model captures WXDai contract events, including transaction details, block info, and event-specific data, for business analysis and reporting.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted.
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: event_type
    description: Type of the event emitted.
    data_type: String
  - name: sender
    description: Address of the sender initiating the transaction.
    data_type: String
  - name: recipient
    description: Address of the recipient, if applicable.
    data_type: String
  - name: amount
    description: Amount involved in the event, in wei.
    data_type: String
  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  - name: event_data
    description: Raw JSON data of the event.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
