version: 2
models:

- name: contracts_sdai_events
  description: This model captures SDAI event data related to contracts, including transaction details, timestamps, and identifiers for analysis and reporting.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted.
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction associated with the event.
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: event_type
    description: Type of the event emitted.
    data_type: String
  - name: event_data
    description: JSON containing event-specific data.
    data_type: JSON
  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  - name: sender_address
    description: Address of the sender involved in the event.
    data_type: String
  - name: recipient_address
    description: Address of the recipient involved in the event.
    data_type: String
  - name: amount
    description: Amount transferred in wei.
    data_type: String
  - name: status
    description: Status of the event, e.g., 'success' or 'failure'.
    data_type: String
  - name: created_at
    description: Timestamp when the record was created.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - sdai
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_wxdai_calls
  description: This model contains data on WXDai calls related to contracts, including transaction details and call specifics.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the call occurred.
    data_type: DateTime
  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String
  - name: block_number
    description: Number of the block containing the transaction.
    data_type: UInt64
  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64
  - name: contract_address
    description: Address of the contract involved in the call.
    data_type: String
  - name: caller_address
    description: Address initiating the call.
    data_type: String
  - name: call_data
    description: Encoded call data payload.
    data_type: String
  - name: call_value
    description: Value transferred during the call in wei.
    data_type: String
  - name: output_json_type
    description: Indicates if output is in JSON format.
    data_type: UInt64
  - name: output_data
    description: Output data from the call.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - wxdai
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_wxdai_events
  description: This model captures WXDai event logs related to contracts, including transaction details, block information, and event-specific data for analysis and reporting.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted (UTC)
    data_type: DateTime
  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64
  - name: log_index
    description: Index of the log within the block
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction that emitted the event
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String
  - name: event_name
    description: Name of the emitted event
    data_type: String
  - name: amount
    description: Amount involved in the event, in wei
    data_type: String
  - name: sender
    description: Address of the sender involved in the event
    data_type: String
  - name: recipient
    description: Address of the recipient involved in the event
    data_type: String
  - name: data
    description: Raw event data payload in JSON format
    data_type: JSON
  - name: created_at
    description: Timestamp when the record was created in the database (UTC)
    data_type: DateTime
  - name: updated_at
    description: Timestamp when the record was last updated (UTC)
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - wxdai
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
