version: 2
models:
- name: rwa_backedfi_prices_1d
  description: Daily prices of RWA-backed financial instruments, forward-filled.  This model takes sparse daily price data and forward-fills missing values to create a complete daily time series for each instrument.
  columns:
  - name: bticker
    description: The ticker symbol of the RWA-backed financial instrument.
    data_type: STRING
  - name: date
    description: The date of the price observation.
    data_type: DATE
  - name: price
    description: The price of the RWA-backed financial instrument on the given date.
    data_type: FLOAT
