version: 2
models:

- name: int_bridges_flows_daily
  description: Daily flows of tokens between bridges on different chains.
  columns:
  - name: txs
    description: Number of transactions.
    data_type: Int
    tests:
    - not_null
  - name: volume_usd
    description: Total volume in USD.
    data_type: Float64
    tests:
    - not_null
  - name: bridge
    description: Identifier of the bridge.
    data_type: String
    tests:
    - not_null
  - name: dest_chain
    description: Destination chain.
    data_type: String
    tests:
    - not_null
  - name: net_usd
    description: Net volume in USD.
    data_type: Float64
  - name: date
    description: Date of the transaction.
    data_type: Date
    tests:
    - not_null
  - name: volume_token
    description: Total volume in tokens.
    data_type: Float64
    tests:
    - not_null
  - name: token
    description: Token identifier.
    data_type: String
    tests:
    - not_null
  - name: source_chain
    description: Source chain.
    data_type: String
    tests:
    - not_null
  tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date
            - bridge
            - source_chain
            - dest_chain
            - token
  config:
    access: public
  meta:
    owner: analytics
    authoritative: false
    generated_by: schema-writer
