version: 2
models:

- name: int_bridges_flows_daily
  description: The int_bridges_flows_daily model aggregates daily bridge transfer data, providing insights into token volumes, transaction counts, and net USD flows across different blockchain bridges and chains.
  columns:

  - name: date
    description: The date for which the bridge flow data is aggregated, in YYYY-MM-DD format.
    data_type: Date
    tests:
    - not_null

  - name: bridge
    description: The name or identifier of the blockchain bridge facilitating the transfer.
    data_type: String
    tests:
    - not_null

  - name: source_chain
    description: The originating blockchain network of the token transfer.
    data_type: String
    tests:
    - not_null

  - name: dest_chain
    description: The destination blockchain network of the token transfer.
    data_type: String
    tests:
    - not_null

  - name: token
    description: The symbol or identifier of the token being transferred.
    data_type: String
    tests:
    - not_null

  - name: direction
    description: The transfer direction, indicating whether the flow is inbound or outbound.
    data_type: String
    tests:
    - not_null

  - name: volume_token
    description: Total amount of tokens transferred on the given date, in token units.
    data_type: UInt64
    tests:
    - not_null

  - name: volume_usd
    description: Total USD value of tokens transferred on the given date.
    data_type: UInt64
    tests:
    - not_null

  - name: net_usd
    description: Net USD flow, representing the difference between inbound and outbound transfers on the given date.
    data_type: UInt64
    tests:
    - not_null

  - name: txs
    description: Number of transactions processed for the specified bridge flow on the given date.
    data_type: UInt64
    tests:
    - not_null
  meta:
    owner: analytics
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.002330'
    _generated_fields:
    - columns.direction.data_type
    - columns.date.description
    - columns.volume_usd.description
    - config.tags
    - columns.source_chain.description
    - columns.dest_chain.description
    - columns.dest_chain.data_type
    - columns.volume_usd.data_type
    - columns.bridge.data_type
    - columns.source_chain.data_type
    - description
    - columns.token.data_type
    - columns.net_usd.data_type
    - columns.date.data_type
    - columns.bridge.description
    - columns.txs.description
    - columns.token.description
    - columns.direction.description
    - columns.volume_token.data_type
    - config.materialized
    - columns.net_usd.description
    - columns.txs.data_type
    - columns.volume_token.description
  config:
    tags:
    - production
    - intermediate
    - bridges
    materialized: incremental
