version: 2
models:

- name: int_bridges_flows_daily
  description: The int_bridges_flows_daily model aggregates daily bridge transfer data, providing insights into token volumes, transaction counts, and net USD flows across different blockchain bridges and chains.
  columns:

  - name: date
    description: The date for which the bridge flow data is aggregated, in YYYY-MM-DD format.
    data_type: Date
    tests:
    - not_null

  - name: bridge
    description: The name or identifier of the blockchain bridge facilitating the transfer.
    data_type: String
    tests:
    - not_null

  - name: source_chain
    description: The originating blockchain network of the token transfer.
    data_type: String
    tests:
    - not_null

  - name: dest_chain
    description: The destination blockchain network of the token transfer.
    data_type: String
    tests:
    - not_null

  - name: token
    description: The symbol or identifier of the token being transferred.
    data_type: String
    tests:
    - not_null

  - name: direction
    description: The transfer direction, indicating whether the flow is inbound or outbound.
    data_type: String
    tests:
    - not_null

  - name: volume_token
    description: Total amount of tokens transferred on the given date, in token units.
    data_type: UInt64
    tests:
    - not_null

  - name: volume_usd
    description: Total USD value of tokens transferred on the given date.
    data_type: UInt64
    tests:
    - not_null

  - name: net_usd
    description: Net USD flow, representing the difference between inbound and outbound transfers on the given date.
    data_type: UInt64
    tests:
    - not_null

  - name: txs
    description: Number of transactions processed for the specified bridge flow on the given date.
    data_type: UInt64
    tests:
    - not_null
    - elementary.column_anomalies:
        column_anomalies:
        - null_count
        - min
        - max
        timestamp_column: date
        time_bucket:
          period: day
          count: 1
        severity: warn
        tags:
        - elementary
  meta:
    owner: analytics_team
    authoritative: false
  tests:
  - elementary.volume_anomalies:
      timestamp_column: date
      time_bucket:
        period: day
        count: 1
      training_period:
        period: day
        count: 56
      seasonality: day_of_week
      detection_period:
        period: day
        count: 2
      detection_delay:
        period: day
        count: 1
      anomaly_sensitivity: 3
      ignore_small_changes:
        spike_failure_percent_threshold: 10
        drop_failure_percent_threshold: 20
      severity: warn
      tags:
      - elementary
  - elementary.freshness_anomalies:
      timestamp_column: date
      time_bucket:
        period: day
        count: 1
      severity: warn
      tags:
      - elementary
  - elementary.schema_changes:
      severity: warn
      tags:
      - elementary
