version: 2
models:

- name: p2p_peers_info
  description: Aggregated information about peers from nebula_discv5 visits, including fork details and properties.
  columns:
  - name: visit_ended_at
    description: Timestamp when the visit ended (UTC).
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: peer_id
    description: Unique identifier for the peer.
    data_type: String
    tests:
    - not_null
    - unique
  - name: agent_version
    description: Version string of the peer's agent software.
    data_type: String
  - name: fork_digest
    description: String representation of the peer's fork digest.
    data_type: String
  - name: cl_fork_name
    description: Name of the fork corresponding to the fork digest.
    data_type: String
  - name: cl_next_fork_name
    description: Name of the next fork, either from peer properties or fallback.
    data_type: String
  - name: peer_properties
    description: JSON object containing various peer properties including fork info.
    data_type: JSON
  - name: crawl_error
    description: Error message if the crawl encountered issues.
    data_type: LowCardinality(Nullable(String))
  - name: dial_errors
    description: Array of dial error messages encountered during peer connection attempts.
    data_type: Array(LowCardinality(String))
  config:
    access: public
    materialized: view
    tags:
    - p2p
    - peers
    - information
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: p2p_discv4_peers_info
  description: Aggregated peer information derived from the discv4 crawl, including version, platform, runtime, and other metadata.
  columns:
  - name: visit_ended_at
    description: Timestamp when the peer visit ended.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: peer_id
    description: Unique identifier for the peer.
    data_type: String
    tests:
    - not_null
    - unique
  - name: agent_version
    description: Version string of the peer's agent software.
    data_type: String
  - name: peer_properties
    description: JSON object containing peer properties, including network ID.
    data_type: JSON
  - name: crawl_error
    description: Error message if the crawl encountered issues with this peer.
    data_type: LowCardinality(Nullable(String))
  - name: dial_errors
    description: Array of dial error messages encountered during connection attempts.
    data_type: Array(LowCardinality(String))
  - name: client
    description: Client type or platform extracted from the version string.
    data_type: String
  - name: variant
    description: Variant information parsed from the version string.
    data_type: String
  - name: version
    description: Peer software version, with build and channel suffixes removed.
    data_type: String
  - name: channel
    description: Release channel derived from version pre-build info, if available.
    data_type: String
  - name: build
    description: Build metadata or last dash-segment of the version string.
    data_type: String
  - name: platform
    description: Platform identifier extracted from version string.
    data_type: String
  - name: runtime
    description: Runtime environment extracted from version string.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - p2p
    - discv4
    - peer-info
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: p2p_discv4_peers_info2
  description: A model representing peer visit information from the Discv4 network crawl, including timestamps, peer identifiers, agent versions, properties, and error details.
  columns:
  - name: visit_ended_at
    description: Timestamp when the peer visit ended.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: peer_id
    description: Unique identifier for the peer.
    data_type: String
    tests:
    - not_null
    - unique
  - name: agent_version
    description: Version string of the peer's agent software.
    data_type: String
  - name: peer_properties
    description: JSON object containing properties of the peer.
    data_type: JSON
  - name: crawl_error
    description: Error message encountered during crawling, if any.
    data_type: LowCardinality(Nullable(String))
  - name: dial_errors
    description: List of dial errors encountered during the visit.
    data_type: Array(LowCardinality(String))
  config:
    access: public
    materialized: incremental
    tags:
    - p2p
    - discv4
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: p2p_discv5_peers_info
  description: Aggregated peer information from Discv5 network crawl data, including peer properties, protocol versions, fork details, and version parsing.
  columns:
  - name: visit_ended_at
    description: Timestamp when the peer visit ended.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: peer_id
    description: Unique identifier for the peer.
    data_type: String
    tests:
    - not_null
    - unique
  - name: fork_digest
    description: Fork digest as a string, representing the peer's fork.
    data_type: String
    tests:
    - not_null
  - name: cl_fork_name
    description: Human-readable name of the fork.
    data_type: String
  - name: cl_next_fork_name
    description: Human-readable name of the next fork.
    data_type: String
  - name: peer_properties
    description: JSON object containing peer properties including fork digests and versions.
    data_type: JSON
  - name: crawl_error
    description: Error message if the crawl encountered issues with this peer.
    data_type: LowCardinality(String)
  - name: dial_errors
    description: List of dial errors encountered during peer connection attempts.
    data_type: Array(LowCardinality(String))
  - name: client
    description: Client identifier extracted from agent version.
    data_type: String
  - name: variant
    description: Variant extracted from agent version.
    data_type: String
  - name: version
    description: Parsed version string from peer's version blob.
    data_type: String
  - name: channel
    description: Channel information parsed from version blob.
    data_type: String
  - name: build
    description: Build metadata extracted from version blob.
    data_type: String
  - name: platform
    description: Platform extracted from agent version slash parts.
    data_type: String
  - name: runtime
    description: Runtime environment extracted from agent version slash parts.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - discv5
    - peer-info
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_p2p_discv4_peers
  description: Aggregated peer visit data from Discv4 and Discv5 network crawls, including version, platform, runtime, and error details.
  columns:
  - name: visit_ended_at
    description: Timestamp when the peer visit ended.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: peer_id
    description: Unique identifier for the peer.
    data_type: String
    tests:
    - not_null
    - unique
  - name: agent_version
    description: Agent version string of the peer.
    data_type: String
  - name: peer_properties
    description: JSON object containing peer properties.
    data_type: JSON
  - name: crawl_error
    description: Error message if crawl failed; null if successful.
    data_type: LowCardinality(Nullable(String))
  - name: dial_errors
    description: Array of dial error messages encountered during visit.
    data_type: Array(LowCardinality(String))
  - name: client
    description: Client identifier extracted from peer's version string.
    data_type: String
  - name: variant
    description: Variant identifier from version string, if available.
    data_type: String
  - name: version
    description: Peer software version, derived from version string, with +build and channel suffixes removed.
    data_type: String
  - name: channel
    description: Release channel from version string, if specified.
    data_type: String
  - name: build
    description: Build metadata or last dash-segment from version string.
    data_type: String
  - name: platform
    description: Platform identifier extracted from agent version.
    data_type: String
  - name: runtime
    description: Runtime environment identifier, if available.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - p2p
    - discv4
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: int_p2p_discv5_clients_daily
  description: Aggregated daily counts of clients and platforms based on peer visit data, including counts per client label and platform.
  columns:
  - name: date
    description: The date of the peer visit, truncated to day.
    data_type: DateTime
    tests:
    - not_null
  - name: metric
    description: The metric type, either 'Clients' or 'Platform'.
    data_type: String
    tests:
    - not_null
  - name: label
    description: The label for the client or platform.
    data_type: String
    tests:
    - not_null
  - name: value
    description: Count of occurrences for the given label on the specified date.
    data_type: UInt64
    tests:
    - not_null
  config:
    access: public
    materialized: table
    tags:
    - p2p
    - discv5
    - daily
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_p2p_discv5_forks_daily
  description: Aggregated daily counts of current and next forks in the P2P network, based on peer visit data.
  columns:
  - name: date
    description: The day of the peer visit, truncated to day precision.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: label
    description: Label indicating whether the fork is current or next.
    data_type: String
    tests:
    - not_null
  - name: fork
    description: The fork name as a string.
    data_type: String
    tests:
    - not_null
  - name: cnt
    description: Count of visits associated with the specific fork and label.
    data_type: UInt64
    tests:
    - not_null
  config:
    access: public
    materialized: incremental
    tags:
    - p2p
    - discv5
    - forks
    - daily
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_p2p_discv5_geo_daily
  description: Aggregated daily geolocation data for P2P peers discovered via Discv5, including country, latitude, and longitude.
  columns:
  - name: date
    description: The day of the peer activity, truncated to day precision.
    data_type: DateTime
    tests:
    - not_null
  - name: lat
    description: Latitude of the peer's geolocation, or NULL if unavailable.
    data_type: String
  - name: long
    description: Longitude of the peer's geolocation, or NULL if unavailable.
    data_type: String
  - name: country
    description: Country code or name associated with the peer, or 'Unknown' if not available.
    data_type: String
  - name: peer_id
    description: Unique identifier of the peer.
    data_type: String
    tests:
    - not_null
    - unique
  - name: ip
    description: IP address of the peer.
    data_type: String
    tests:
    - not_null
  config:
    access: public
    materialized: table
    tags:
    - geo
    - daily
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_p2p_discv5_peers
  description: Contains detailed peer visit data including agent version, fork info, and parsed version components for analysis of network peers.
  columns:
  - name: visit_ended_at
    description: Timestamp when the peer visit ended.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: peer_id
    description: Unique identifier for the peer.
    data_type: String
    tests:
    - not_null
    - unique
  - name: agent_version
    description: Version string of the peer's agent software.
    data_type: String
  - name: fork_digest
    description: Fork digest as a string, indicating the fork version.
    data_type: String
  - name: cl_fork_name
    description: Human-readable name of the fork based on digest.
    data_type: String
  - name: cl_next_fork_name
    description: Human-readable name of the next fork version.
    data_type: String
  - name: next_fork_version
    description: Next fork version identifier as a string.
    data_type: String
  - name: peer_properties
    description: JSON object containing peer properties including fork info.
    data_type: JSON
  - name: crawl_error
    description: Error message if the crawl encountered issues.
    data_type: LowCardinality(Nullable(String))
  - name: dial_errors
    description: Array of dial error messages encountered during peer connection attempts.
    data_type: Array(LowCardinality(String))
  - name: client
    description: Client identifier parsed from agent version.
    data_type: String
  - name: variant
    description: Variant token extracted from agent version.
    data_type: String
  - name: version
    description: Main version component parsed from agent version.
    data_type: String
  - name: channel
    description: Channel identifier if present in agent version.
    data_type: String
  - name: build
    description: Build identifier or suffix from agent version.
    data_type: String
  - name: platform
    description: Platform token from agent version.
    data_type: String
  - name: runtime
    description: Runtime identifier from agent version.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - p2p
    - discv5
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: int_p2p_discv5_topology_latest
  description: Aggregated topology data from Discv5 network crawl, including peer and neighbor info with geolocation.
  columns:
  - name: date
    description: The day of the crawl, formatted as start of day timestamp.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: peer_ip
    description: IP address of the peer node.
    data_type: String
    tests:
    - not_null
  - name: peer_discovery_id_prefix
    description: Discovery ID prefix associated with the peer.
    data_type: UInt64
    tests:
    - not_null
  - name: peer_cl_fork_name
    description: Fork name of the peer client.
    data_type: String
  - name: peer_cl_next_fork_name
    description: Next fork name of the peer client.
    data_type: String
  - name: peer_client
    description: Client software name of the peer.
    data_type: String
  - name: peer_hostname
    description: Hostname geolocation info for peer IP.
    data_type: String
  - name: peer_city
    description: City geolocation info for peer IP.
    data_type: String
  - name: peer_country
    description: Country geolocation info for peer IP.
    data_type: String
  - name: peer_org
    description: Organization geolocation info for peer IP.
    data_type: String
  - name: peer_loc
    description: Location coordinates geolocation info for peer IP.
    data_type: String
  - name: neighbor_ip
    description: IP address of the neighbor node.
    data_type: String
  - name: neighbor_discovery_id_prefix
    description: Discovery ID prefix for neighbor.
    data_type: UInt64
  - name: neighbor_cl_fork_name
    description: Fork name of the neighbor client.
    data_type: String
  - name: neighbor_cl_next_fork_name
    description: Next fork name of the neighbor client.
    data_type: String
  - name: neighbor_client
    description: Client software name of the neighbor.
    data_type: String
  - name: neighbor_city
    description: City geolocation info for neighbor IP.
    data_type: String
  - name: neighbor_country
    description: Country geolocation info for neighbor IP.
    data_type: String
  - name: neighbor_org
    description: Organization geolocation info for neighbor IP.
    data_type: String
  - name: neighbor_loc
    description: Location coordinates geolocation info for neighbor IP.
    data_type: String
  - name: cnt
    description: Count of edges between peer and neighbor for the day.
    data_type: UInt64
    tests:
    - not_null
  config:
    access: public
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
