version: 2
models:

- name: p2p_peers_info
  description: Aggregated information about peers from nebula_discv5 visits, including fork details and properties.
  columns:
  - name: visit_ended_at
    description: Timestamp when the visit ended (UTC).
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: peer_id
    description: Unique identifier for the peer.
    data_type: String
    tests:
    - not_null
    - unique
  - name: agent_version
    description: Version string of the peer's agent software.
    data_type: String
  - name: fork_digest
    description: String representation of the peer's fork digest.
    data_type: String
  - name: cl_fork_name
    description: Name of the fork corresponding to the fork digest.
    data_type: String
  - name: cl_next_fork_name
    description: Name of the next fork, either from peer properties or fallback.
    data_type: String
  - name: peer_properties
    description: JSON object containing various peer properties including fork info.
    data_type: JSON
  - name: crawl_error
    description: Error message if the crawl encountered issues.
    data_type: LowCardinality(Nullable(String))
  - name: dial_errors
    description: Array of dial error messages encountered during peer connection attempts.
    data_type: Array(LowCardinality(String))
  config:
    access: public
    materialized: view
    tags:
    - p2p
    - peers
    - information
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: p2p_discv4_peers_info
  description: Aggregated peer information derived from the discv4 crawl, including version, platform, runtime, and other metadata.
  columns:
  - name: visit_ended_at
    description: Timestamp when the peer visit ended.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: peer_id
    description: Unique identifier for the peer.
    data_type: String
    tests:
    - not_null
    - unique
  - name: agent_version
    description: Version string of the peer's agent software.
    data_type: String
  - name: peer_properties
    description: JSON object containing peer properties, including network ID.
    data_type: JSON
  - name: crawl_error
    description: Error message if the crawl encountered issues with this peer.
    data_type: LowCardinality(Nullable(String))
  - name: dial_errors
    description: Array of dial error messages encountered during connection attempts.
    data_type: Array(LowCardinality(String))
  - name: client
    description: Client type or platform extracted from the version string.
    data_type: String
  - name: variant
    description: Variant information parsed from the version string.
    data_type: String
  - name: version
    description: Peer software version, with build and channel suffixes removed.
    data_type: String
  - name: channel
    description: Release channel derived from version pre-build info, if available.
    data_type: String
  - name: build
    description: Build metadata or last dash-segment of the version string.
    data_type: String
  - name: platform
    description: Platform identifier extracted from version string.
    data_type: String
  - name: runtime
    description: Runtime environment extracted from version string.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - p2p
    - discv4
    - peer-info
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: p2p_discv4_peers_info2
  description: A model representing peer visit information from the Discv4 network crawl, including timestamps, peer identifiers, agent versions, properties, and error details.
  columns:
  - name: visit_ended_at
    description: Timestamp when the peer visit ended.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: peer_id
    description: Unique identifier for the peer.
    data_type: String
    tests:
    - not_null
    - unique
  - name: agent_version
    description: Version string of the peer's agent software.
    data_type: String
  - name: peer_properties
    description: JSON object containing properties of the peer.
    data_type: JSON
  - name: crawl_error
    description: Error message encountered during crawling, if any.
    data_type: LowCardinality(Nullable(String))
  - name: dial_errors
    description: List of dial errors encountered during the visit.
    data_type: Array(LowCardinality(String))
  config:
    access: public
    materialized: incremental
    tags:
    - p2p
    - discv4
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: p2p_discv5_peers_info
  description: Aggregated peer information from Discv5 network crawl data, including peer properties, protocol versions, fork details, and version parsing.
  columns:
  - name: visit_ended_at
    description: Timestamp when the peer visit ended.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: peer_id
    description: Unique identifier for the peer.
    data_type: String
    tests:
    - not_null
    - unique
  - name: fork_digest
    description: Fork digest as a string, representing the peer's fork.
    data_type: String
    tests:
    - not_null
  - name: cl_fork_name
    description: Human-readable name of the fork.
    data_type: String
  - name: cl_next_fork_name
    description: Human-readable name of the next fork.
    data_type: String
  - name: peer_properties
    description: JSON object containing peer properties including fork digests and versions.
    data_type: JSON
  - name: crawl_error
    description: Error message if the crawl encountered issues with this peer.
    data_type: LowCardinality(String)
  - name: dial_errors
    description: List of dial errors encountered during peer connection attempts.
    data_type: Array(LowCardinality(String))
  - name: client
    description: Client identifier extracted from agent version.
    data_type: String
  - name: variant
    description: Variant extracted from agent version.
    data_type: String
  - name: version
    description: Parsed version string from peer's version blob.
    data_type: String
  - name: channel
    description: Channel information parsed from version blob.
    data_type: String
  - name: build
    description: Build metadata extracted from version blob.
    data_type: String
  - name: platform
    description: Platform extracted from agent version slash parts.
    data_type: String
  - name: runtime
    description: Runtime environment extracted from agent version slash parts.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - discv5
    - peer-info
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
