version: 2
models:

- name: stg_consensus__attestations
  description: Business-facing table containing processed attestation data from the consensus layer, including slot, indices, roots, signatures, and timestamp.
  columns:
  - name: slot
    description: Enclosing block slot.
    data_type: UInt64
  - name: attestation_index
    description: Index within the block.
    data_type: UInt64
  - name: aggregation_bits
    description: Aggregation bitfield.
    data_type: String
  - name: signature
    description: BLS signature.
    data_type: String
  - name: attestation_slot
    description: Attested slot.
    data_type: UInt64
  - name: committee_index
    description: Committee index.
    data_type: UInt64
  - name: beacon_block_root
    description: Beacon block root.
    data_type: String
  - name: source_epoch
    description: Source epoch.
    data_type: UInt64
  - name: source_root
    description: Source root.
    data_type: String
  - name: target_epoch
    description: Target epoch.
    data_type: UInt64
  - name: target_root
    description: Target root.
    data_type: String
  - name: slot_timestamp
    description: UTC timestamp derived from slot.
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonic ingestion version.
    data_type: UInt64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__blob_commitments
  description: Staging model for blob commitments, capturing per-slot KZG commitments with timestamp metadata.
  columns:
  - name: slot
    description: Slot number
    data_type: UInt64
  - name: commitment_index
    description: Index of the commitment within the slot
    data_type: UInt64
  - name: commitment
    description: KZG blob commitment as a hexadecimal string
    data_type: String
  - name: slot_timestamp
    description: UTC timestamp corresponding to the slot
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonic version for ingestion ordering
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - consensus
    - blob_commitments
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__blocks
  description: Staging model for consensus layer blocks, including core block data, attestations, slashing events, blob commitments, and related execution payloads. Used for further analysis and transformation.
  columns:
  - name: slot
    description: Slot number indicating the position in the chain.
    data_type: UInt64
  - name: proposer_index
    description: Index of the validator proposing the block.
    data_type: UInt64
  - name: parent_root
    description: Parent block root hash.
    data_type: String
  - name: state_root
    description: State root hash after the block.
    data_type: String
  - name: signature
    description: Block signature.
    data_type: String
  - name: version
    description: Fork version label for this block (e.g., bellatrix, capella).
    data_type: String
  - name: randao_reveal
    description: RANDAO reveal for randomness.
    data_type: String
  - name: graffiti
    description: Graffiti field.
    data_type: String
  - name: eth1_deposit_root
    description: Eth1 deposit root hash.
    data_type: String
  - name: eth1_deposit_count
    description: Count of Eth1 deposits included in the block.
    data_type: UInt64
  - name: eth1_block_hash
    description: Eth1 block hash.
    data_type: String
  - name: sync_aggregate_participation
    description: Number of sync committee participants.
    data_type: UInt64
  - name: withdrawals_count
    description: Number of withdrawals in the block.
    data_type: UInt32
  - name: blob_kzg_commitments_count
    description: Blob KZG commitments count (Deneb+).
    data_type: UInt32
  - name: execution_requests_count
    description: Count of execution requests.
    data_type: UInt32
  - name: slot_timestamp
    description: UTC timestamp derived from slot.
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonic ingestion version (nanoseconds).
    data_type: UInt64
  - name: attestations
    description: Attestation records included in blocks.
    data_type: JSON
  - name: attester_slashings
    description: Attester slashing events.
    data_type: JSON
  - name: blob_commitments
    description: KZG blob commitments per slot.
    data_type: JSON
  - name: blob_sidecars
    description: Blob sidecars accompanying Deneb blocks.
    data_type: JSON
  - name: bls_changes
    description: BLS-to-execution address change operations.
    data_type: JSON
  - name: deposits
    description: Eth1 deposits included in the beacon chain.
    data_type: JSON
  - name: execution_payloads
    description: Execution payloads embedded in beacon blocks.
    data_type: JSON
  - name: execution_requests
    description: Payload counts for deposits, withdrawals, and consolidations per slot.
    data_type: JSON
  - name: genesis
    description: Genesis information for the beacon chain.
    data_type: JSON
  - name: raw_blocks
    description: Raw JSON payloads of beacon blocks as retrieved.
    data_type: JSON
  - name: raw_genesis
    description: Raw JSON payload of beacon genesis endpoint.
    data_type: JSON
  - name: raw_rewards
    description: Raw rewards API snapshots.
    data_type: JSON
  - name: raw_specs
    description: Raw network spec parameters as JSON.
    data_type: JSON
  - name: raw_validators
    description: Raw validators API snapshots.
    data_type: JSON
  - name: rewards
    description: Per-slot proposer reward breakdowns.
    data_type: JSON
  - name: specs
    description: Flattened network spec parameters.
    data_type: JSON
  - name: sync_aggregates
    description: Sync committee aggregates per slot.
    data_type: JSON
  - name: time_helpers
    description: Helper table for converting slots to timestamps.
    data_type: JSON
  - name: transactions
    description: Execution transactions referenced from the beacon chain.
    data_type: JSON
  - name: transformer_progress
    description: Status of raw to modeled consensus transformations.
    data_type: JSON
  - name: validators
    description: Validator registry and dynamic balance/status data.
    data_type: JSON
  - name: voluntary_exits
    description: Voluntary exit messages.
    data_type: JSON
  - name: withdrawals
    description: Beacon-chain withdrawals list (Capella+).
    data_type: JSON
  config:
    access: public
    materialized: view
    tags:
    - production
    - consensus
    - blocks
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__deposits
  description: Deposits data captured from the beacon chain, including deposit details, proofs, and associated metadata for consensus analysis.
  columns:
  - name: proof
    description: Array of cryptographic proofs associated with the deposit.
    data_type: Array(String)
  - name: pubkey
    description: Validator's public key in hexadecimal format.
    data_type: String
  - name: slot_timestamp
    description: UTC timestamp when the deposit was recorded.
    data_type: DateTime64(0, 'UTC')
  - name: slot
    description: Slot number indicating the block height at deposit inclusion.
    data_type: UInt64
  - name: deposit_index
    description: Unique index of the deposit within the slot.
    data_type: UInt64
  - name: withdrawal_credentials
    description: Credentials for withdrawal, typically a hash of the withdrawal address.
    data_type: String
  - name: amount
    description: Deposit amount in wei.
    data_type: UInt64
  - name: signature
    description: BLS signature validating the deposit.
    data_type: String
  - name: insert_version
    description: Monotonically increasing version number for data ingestion.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - consensus
    - deposits
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__execution_requests
  description: This table contains counts of execution requests (deposits, withdrawals, consolidations) per slot, derived from consensus layer data sources.
  columns:
  - name: slot
    description: Slot number representing the position in the beacon chain.
    data_type: UInt64
  - name: payload
    description: Type of execution request, e.g., 'deposit', 'withdrawal', 'consolidation'.
    data_type: String
  - name: deposits_count
    description: Number of deposit requests within the slot.
    data_type: UInt32
  - name: withdrawals_count
    description: Number of withdrawal requests within the slot.
    data_type: UInt32
  - name: consolidations_count
    description: Number of consolidation requests within the slot.
    data_type: UInt32
  - name: slot_timestamp
    description: UTC timestamp corresponding to the slot.
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonically increasing version number for data ingestion.
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - consensus
    - execution_requests
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__rewards
  description: This table contains aggregated reward data per slot, including proposer rewards, attestations, sync committees, and slashings, for business analysis and reporting.
  columns:
  - name: slot
    description: Slot number.
    data_type: UInt64
  - name: proposer_index
    description: Validator index of the proposer.
    data_type: UInt64
  - name: total
    description: Total rewards for the slot.
    data_type: UInt64
  - name: attestations
    description: Reward component from attestations.
    data_type: UInt64
  - name: sync_aggregate
    description: Reward component from sync committee participation.
    data_type: UInt64
  - name: proposer_slashings
    description: Rewards slashed due to proposer misbehavior.
    data_type: UInt64
  - name: attester_slashings
    description: Rewards slashed due to attester misbehavior.
    data_type: UInt64
  - name: slot_timestamp
    description: UTC timestamp corresponding to the slot.
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Ingestion version for tracking updates.
    data_type: UInt64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__specs
  description: A staging model capturing consensus specifications parameters and related data for analysis and validation.
  columns:
  - name: parameter_value
    description: The value of the consensus parameter.
    data_type: String
  - name: parameter_name
    description: The name identifier of the consensus parameter.
    data_type: String
  config:
    access: public
    materialized: view
    tags:
    - production
    - consensus
    - specs
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__time_helpers
  description: Helper table for converting slots to timestamps, including genesis time, seconds per slot, and slots per epoch.
  columns:
  - name: genesis_time_unix
    description: Unix timestamp of the genesis block start time.
    data_type: UInt64
  - name: seconds_per_slot
    description: Number of seconds in each slot.
    data_type: UInt64
  - name: slots_per_epoch
    description: Number of slots in each epoch.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - consensus
    - time_helpers
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__validators
  description: A staging model capturing validator-related data from the consensus layer, including validator status, balances, and associated metadata for business analysis.
  columns:
  - name: slot
    description: Slot number at which validator data was recorded
    data_type: UInt64
  - name: validator_index
    description: Unique index identifying each validator
    data_type: UInt32
  - name: balance
    description: Validator's balance in Gwei
    data_type: UInt64
  - name: status
    description: Validator's current status (e.g., active, pending)
    data_type: String
  - name: pubkey
    description: Validator's public key
    data_type: String
  - name: withdrawal_credentials
    description: Withdrawal credentials associated with validator
    data_type: String
  - name: effective_balance
    description: Effective balance in Gwei
    data_type: UInt64
  - name: slashed
    description: Indicator if validator has been slashed (1) or not (0)
    data_type: UInt8
  - name: activation_eligibility_epoch
    description: Epoch when validator became eligible for activation
    data_type: UInt64
  - name: activation_epoch
    description: Epoch when validator was activated
    data_type: UInt64
  - name: exit_epoch
    description: Epoch when validator exited
    data_type: UInt64
  - name: withdrawable_epoch
    description: Epoch when validator's funds become withdrawable
    data_type: UInt64
  - name: slot_timestamp
    description: UTC timestamp corresponding to the slot
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonically increasing version for tracking data updates
    data_type: UInt64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__withdrawals
  description: This staging model consolidates withdrawal data from the consensus layer, providing a business-facing view of withdrawal events with key attributes.
  columns:
  - name: slot
    description: Slot number indicating the position in the chain.
    data_type: UInt64
  - name: block_number
    description: Block number containing the withdrawal.
    data_type: UInt64
  - name: block_hash
    description: Hash of the block containing the withdrawal.
    data_type: String
  - name: withdrawal_index
    description: Index of the withdrawal within the block.
    data_type: UInt64
  - name: validator_index
    description: Index of the validator associated with the withdrawal.
    data_type: UInt64
  - name: address
    description: Address receiving the withdrawal.
    data_type: String
  - name: amount
    description: Amount withdrawn in wei.
    data_type: UInt64
  - name: slot_timestamp
    description: UTC timestamp corresponding to the slot.
    data_type: DateTime64(0, 'UTC')
  config:
    access: public
    tags:
    - production
    - consensus
    - withdrawals
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
