version: 2
models:

- name: stg_consensus__attestations
  description: Business-facing table containing processed attestation data, including slot, index, committee, and cryptographic signatures, for consensus analysis.
  columns:
  - name: slot
    description: Enclosing block slot.
    data_type: UInt64
  - name: attestation_index
    description: Index within the block.
    data_type: UInt64
  - name: aggregation_bits
    description: Aggregation bitfield.
    data_type: String
  - name: signature
    description: BLS signature.
    data_type: String
  - name: attestation_slot
    description: Attested slot.
    data_type: UInt64
  - name: committee_index
    description: Committee index.
    data_type: UInt64
  - name: beacon_block_root
    description: Beacon block root.
    data_type: String
  - name: source_epoch
    description: Source epoch.
    data_type: UInt64
  - name: source_root
    description: Source root.
    data_type: String
  - name: target_epoch
    description: Target epoch.
    data_type: UInt64
  - name: target_root
    description: Target root.
    data_type: String
  - name: slot_timestamp
    description: UTC timestamp derived from slot.
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonic ingestion version.
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - consensus
    - attestations
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__blob_commitments
  description: A staging model capturing KZG blob commitments per slot, including commitment data and timestamps.
  columns:
  - name: slot
    description: Slot number in the beacon chain.
    data_type: UInt64
  - name: commitment_index
    description: Index of the commitment within the slot.
    data_type: UInt64
  - name: commitment
    description: KZG commitment string.
    data_type: String
  - name: slot_timestamp
    description: UTC timestamp corresponding to the slot.
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonically increasing version for data ingestion.
    data_type: UInt64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__blocks
  description: This staging model processes and consolidates beacon chain block data, including execution payloads, attestations, slashing events, and related metadata for analysis and reporting.
  columns:
  - name: slot
    description: Slot number indicating the position in the chain.
    data_type: UInt64
  - name: proposer_index
    description: Index of the validator proposing the block.
    data_type: UInt64
  - name: parent_root
    description: Parent block root hash.
    data_type: String
  - name: state_root
    description: State root hash after the block.
    data_type: String
  - name: signature
    description: Block signature for validation.
    data_type: String
  - name: version
    description: Fork version label for this block (e.g., bellatrix, capella).
    data_type: String
  - name: randao_reveal
    description: RANDAO reveal used for randomness.
    data_type: String
  - name: graffiti
    description: Graffiti field included in the block.
    data_type: String
  - name: eth1_deposit_root
    description: Root hash of Eth1 deposits.
    data_type: String
  - name: eth1_deposit_count
    description: Count of Eth1 deposits included.
    data_type: UInt64
  - name: eth1_block_hash
    description: Eth1 block hash associated with deposits.
    data_type: String
  - name: sync_aggregate_participation
    description: Number of participants in the sync committee.
    data_type: UInt64
  - name: withdrawals_count
    description: Number of withdrawals in the block.
    data_type: UInt32
  - name: blob_kzg_commitments_count
    description: Count of blob KZG commitments (Deneb+).
    data_type: UInt32
  - name: execution_requests_count
    description: Count of execution requests in the block.
    data_type: UInt32
  - name: slot_timestamp
    description: UTC timestamp derived from the slot.
    data_type: DateTime64(0, 'UTC')
  config:
    access: public
    materialized: view
    tags:
    - production
    - consensus
    - blocks
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__deposits
  description: This table contains processed deposit data from the consensus layer, including deposit pubkeys, withdrawal credentials, amounts, signatures, proofs, and associated slot timestamps, used for analysis of validator deposits and chain state.
  columns:
  - name: pubkey
    description: Validator public key in hexadecimal string format.
    data_type: String
  - name: withdrawal_credentials
    description: Withdrawal credentials hash, used to identify withdrawal address.
    data_type: String
  - name: deposit_index
    description: Sequential index of the deposit within the deposit tree.
    data_type: UInt64
  - name: slot
    description: Slot number when the deposit was processed.
    data_type: UInt64
  - name: amount
    description: Deposit amount in Gwei.
    data_type: UInt64
  - name: signature
    description: Deposit signature for validation.
    data_type: String
  - name: proof
    description: Array of Merkle proof elements for deposit inclusion.
    data_type: Array(String)
  - name: slot_timestamp
    description: UTC timestamp corresponding to the deposit slot.
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonically increasing version number for data ingestion.
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - consensus
    - deposits
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__execution_requests
  description: This table contains counts of execution requests (deposits, withdrawals, consolidations) per slot, serving as a staging layer for consensus-related execution request data.
  columns:
  - name: slot
    description: Slot number.
    data_type: UInt64
  - name: payload
    description: Type of execution request (e.g., deposit, withdrawal, consolidation).
    data_type: String
  - name: deposits_count
    description: Number of deposit requests in this slot.
    data_type: UInt32
  - name: withdrawals_count
    description: Number of withdrawal requests in this slot.
    data_type: UInt32
  - name: consolidations_count
    description: Number of consolidation requests in this slot.
    data_type: UInt32
  - name: slot_timestamp
    description: UTC timestamp corresponding to the slot.
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Ingestion version for tracking data updates.
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - consensus
    - execution_requests
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__rewards
  description: A staging model for consensus rewards data, capturing per-slot reward breakdowns and related metrics.
  columns:
  - name: slot
    description: Slot number indicating the epoch period.
    data_type: UInt64
  - name: proposer_index
    description: Index of the validator proposing in this slot.
    data_type: UInt64
  - name: total
    description: Total rewards accumulated in wei for the proposer in this slot.
    data_type: UInt64
  - name: attestations
    description: Number of attestations included in this slot.
    data_type: UInt64
  - name: sync_aggregate
    description: Rewards from sync committee attestations in wei.
    data_type: UInt64
  - name: proposer_slashings
    description: Count of proposer slashings in this slot.
    data_type: UInt64
  - name: attester_slashings
    description: Count of attester slashings in this slot.
    data_type: UInt64
  - name: slot_timestamp
    description: UTC timestamp corresponding to the slot.
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonically increasing version for data ingestion.
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - consensus
    - rewards
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__specs
  description: A staging model capturing consensus specifications parameters and related data for analysis and validation.
  columns:
  - name: parameter_value
    description: The value of the consensus parameter.
    data_type: String
  - name: parameter_name
    description: The name identifier of the consensus parameter.
    data_type: String
  config:
    access: public
    materialized: view
    tags:
    - production
    - consensus
    - specs
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__time_helpers
  description: Helper table for converting slots to timestamps, including genesis time, seconds per slot, and slots per epoch.
  columns:
  - name: genesis_time_unix
    description: Unix timestamp of the genesis block start time.
    data_type: UInt64
  - name: seconds_per_slot
    description: Number of seconds in each slot.
    data_type: UInt64
  - name: slots_per_epoch
    description: Number of slots in each epoch.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - consensus
    - time_helpers
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__validators
  description: A staging model containing validator data with status, balances, and key info for consensus operations.
  columns:
  - name: slot
    description: Slot number representing the consensus epoch.
    data_type: UInt64
  - name: validator_index
    description: Unique index of the validator within the validator registry.
    data_type: UInt32
  - name: balance
    description: Validator's balance in Gwei.
    data_type: UInt64
  - name: status
    description: Current status of the validator (e.g., active, pending, exited).
    data_type: String
  - name: pubkey
    description: Validator's public key.
    data_type: String
  - name: withdrawal_credentials
    description: Credentials used for withdrawal.
    data_type: String
  - name: effective_balance
    description: Effective balance in Gwei used for consensus weight.
    data_type: UInt64
  - name: slashed
    description: Indicator if the validator has been slashed (1) or not (0).
    data_type: UInt8
  - name: activation_eligibility_epoch
    description: Epoch when the validator became eligible for activation.
    data_type: UInt64
  - name: activation_epoch
    description: Epoch when the validator was activated.
    data_type: UInt64
  - name: exit_epoch
    description: Epoch when the validator exited.
    data_type: UInt64
  - name: withdrawable_epoch
    description: Epoch when the validator's funds become withdrawable.
    data_type: UInt64
  - name: slot_timestamp
    description: UTC timestamp corresponding to the slot.
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonically increasing version number for data freshness tracking.
    data_type: UInt64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_consensus__withdrawals
  description: This staging model consolidates withdrawal data from the consensus layer, providing a business-facing view of withdrawal events with key attributes.
  columns:
  - name: slot
    description: Slot number indicating the position in the chain.
    data_type: UInt64
  - name: block_number
    description: Block number containing the withdrawal.
    data_type: UInt64
  - name: block_hash
    description: Hash of the block containing the withdrawal.
    data_type: String
  - name: withdrawal_index
    description: Index of the withdrawal within the block.
    data_type: UInt64
  - name: validator_index
    description: Index of the validator associated with the withdrawal.
    data_type: UInt64
  - name: address
    description: Address receiving the withdrawal.
    data_type: String
  - name: amount
    description: Amount withdrawn in wei.
    data_type: UInt64
  - name: slot_timestamp
    description: UTC timestamp corresponding to the slot.
    data_type: DateTime64(0, 'UTC')
  config:
    access: public
    tags:
    - production
    - consensus
    - withdrawals
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
