version: 2
models:

- name: p2p_peers_cl_fork_daily
  description: Aggregated daily counts of peers by current and next forks, derived from peer visit data.
  columns:
  - name: date
    description: The day of the peer visit, truncated to day precision.
    data_type: DateTime
    tests:
    - not_null
  - name: label
    description: Label indicating whether the count is for 'Current Fork' or 'Next Fork'.
    data_type: String
  - name: fork
    description: The fork name associated with the peer visit.
    data_type: String
  - name: cnt
    description: Count of peers for the given date, label, and fork.
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - p2p
    - fork
    - daily
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: p2p_peers_clients_daily
  description: Daily aggregated count of unique peers per client, with date normalization.
  columns:
  - name: date
    description: The date representing the day of the peer activity, truncated to day level.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: client
    description: Client version or identifier, with 'Unknown' for missing values.
    data_type: String
    tests:
    - not_null
  - name: value
    description: Count of unique peers for the given date and client.
    data_type: UInt64
    tests:
    - not_null
  config:
    access: public
    materialized: table
    tags:
    - aggregation
    - daily
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: p2p_peers_geo_daily
  description: Daily aggregated data of P2P peers with geographic info, including counts and country.
  columns:
  - name: peer_id
    description: Unique identifier for each peer.
    data_type: String
    tests:
    - not_null
    - unique
  - name: date
    description: Date of the peer activity in UTC.
    data_type: DateTime
    tests:
    - not_null
  - name: country
    description: Country code or name associated with the peer's IP.
    data_type: String
  - name: cnt
    description: Count of peer occurrences on the given date and country.
    data_type: UInt64
    tests:
    - not_null
  config:
    access: public
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: p2p_peers_geo_hourly
  description: Aggregated geographical data of peers per hour, including location, country, and visit count.
  columns:
  - name: date
    description: Hourly timestamp of the data aggregation, truncated to hour.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: lat
    description: Latitude extracted from IP geolocation, in decimal degrees.
    data_type: String
  - name: long
    description: Longitude extracted from IP geolocation, in decimal degrees.
    data_type: String
  - name: country
    description: Country name; defaults to 'Unknown' if missing.
    data_type: String
  - name: peer_id
    description: Unique identifier of the peer.
    data_type: String
    tests:
    - not_null
    - unique
  - name: ip
    description: IP address of the peer.
    data_type: String
  - name: cnt
    description: Count of visits for the peer in the given hour.
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - p2p
    - geo
    - hourly
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: p2p_peers_geo_latest
  description: A view aggregating the latest geographical information of peers, including latitude, longitude, and country, based on IP data and peer activity.
  columns:
  - name: peer_id
    description: Unique identifier for each peer.
    data_type: String
    tests:
    - not_null
    - unique
  - name: date
    description: The day of the peer activity, in UTC.
    data_type: DateTime
    tests:
    - not_null
  - name: ip
    description: IP address associated with the peer.
    data_type: String
  - name: lat
    description: Latitude coordinate of the peer's IP location.
    data_type: String
  - name: long
    description: Longitude coordinate of the peer's IP location.
    data_type: String
  - name: country
    description: Country name derived from IP geolocation; 'Unknown' if not available.
    data_type: String
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: p2p_peers_geo_topology_latest
  description: A model representing the latest peer-to-peer network topology with geographical and connection details, including peer and neighbor info, timestamps, and counts.
  columns:
  - name: date
    description: The date of the crawl, truncated to day.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: peer_ip
    description: IP address of the peer.
    data_type: String
    tests:
    - not_null
  - name: peer_discovery_id_prefix
    description: Discovery ID prefix of the peer.
    data_type: UInt64
    tests:
    - not_null
  - name: peer_cl_fork_name
    description: Fork name of the peer client.
    data_type: String
  - name: peer_cl_next_fork_name
    description: Next fork name of the peer client.
    data_type: String
  - name: peer_client
    description: Client software of the peer.
    data_type: String
  - name: peer_hostname
    description: Hostname associated with the peer's IP.
    data_type: String
  - name: peer_city
    description: City location of the peer.
    data_type: String
  - name: peer_country
    description: Country location of the peer.
    data_type: String
  - name: peer_org
    description: Organization associated with the peer's IP.
    data_type: String
  - name: peer_loc
    description: Geographical coordinates of the peer.
    data_type: String
  - name: neighbor_ip
    description: IP address of the neighbor peer.
    data_type: String
  - name: neighbor_discovery_id_prefix
    description: Discovery ID prefix of the neighbor.
    data_type: UInt64
  - name: neighbor_cl_fork_name
    description: Fork name of the neighbor client.
    data_type: String
  - name: neighbor_cl_next_fork_name
    description: Next fork name of the neighbor client.
    data_type: String
  - name: neighbor_client
    description: Client software of the neighbor.
    data_type: String
  - name: neighbor_city
    description: City location of the neighbor.
    data_type: String
  - name: neighbor_country
    description: Country location of the neighbor.
    data_type: String
  - name: neighbor_org
    description: Organization associated with the neighbor's IP.
    data_type: String
  - name: neighbor_loc
    description: Geographical coordinates of the neighbor.
    data_type: String
  - name: cnt
    description: Count of edges between peer and neighbor for the given day.
    data_type: UInt64
    tests:
    - not_null
  config:
    access: public
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
