version: 2
models:
- name: p2p_peers_cl_fork_hourly
  description: 'TODO: Add description for p2p_peers_cl_fork_hourly'
  meta:
    sector: p2p
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - p2p
    - nebula
    - metrics
  columns:
  - name: el_fork_name
    description: 'TODO: Add description for el_fork_name'
    data_tests:
    - not_null
  - name: fork_digest
    description: 'TODO: Add description for fork_digest'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - el_fork_name
      - fork_digest
- name: p2p_peers_geo_hourly
  description: 'TODO: Add description for p2p_peers_geo_hourly'
  meta:
    sector: p2p
    refs:
    - p2p_peers_info
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - p2p
    - nebula
    - metrics
  columns:
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: ip
    description: 'TODO: Add description for ip'
    data_tests:
    - not_null
  - name: peer_id
    description: 'TODO: Add description for peer_id'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - date
      - ip
- name: p2p_peers_geo_latest
  description: 'TODO: Add description for p2p_peers_geo_latest'
  meta:
    sector: p2p
    refs:
    - p2p_peers_info
    - p2p_peers_info
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - p2p
    - nebula
    - metrics
  columns:
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: ip
    description: 'TODO: Add description for ip'
    data_tests:
    - not_null
  - name: peer_id
    description: 'TODO: Add description for peer_id'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - date
      - ip
- name: p2p_peers_cl_fork_daily
  description: 'TODO: Add description for p2p_peers_cl_fork_daily'
  meta:
    sector: p2p
    refs:
    - p2p_peers_info
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - p2p
    - nebula
    - metrics
  columns:
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: fork
    description: 'TODO: Add description for fork'
    data_tests:
    - not_null
  - name: peer_id
    description: 'TODO: Add description for peer_id'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - date
      - fork
- name: p2p_peers_geo_daily
  description: 'TODO: Add description for p2p_peers_geo_daily'
  meta:
    sector: p2p
    refs:
    - p2p_peers_info
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - p2p
    - nebula
    - metrics
  columns:
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: ip
    description: 'TODO: Add description for ip'
    data_tests:
    - not_null
  - name: peer_id
    description: 'TODO: Add description for peer_id'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - date
      - ip
- name: p2p_peers_el_fork_daily
  description: 'TODO: Add description for p2p_peers_el_fork_daily'
  meta:
    sector: p2p
    refs:
    - p2p_peers_info
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - p2p
    - nebula
    - metrics
  columns:
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: fork
    description: 'TODO: Add description for fork'
    data_tests:
    - not_null
  - name: peer_id
    description: 'TODO: Add description for peer_id'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - date
      - fork
- name: p2p_peers_clients_daily
  description: 'TODO: Add description for p2p_peers_clients_daily'
  meta:
    sector: p2p
    refs:
    - p2p_peers_info
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - p2p
    - nebula
    - metrics
  columns:
  - name: client
    description: 'TODO: Add description for client'
    data_tests:
    - not_null
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: peer_id
    description: 'TODO: Add description for peer_id'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - client
      - date
