version: 2
models:

- name: rwa_backedfi_prices
  description: Business-facing table containing backedfi price data with timestamp and ticker information.
  columns:
  - name: bticker
    description: Ticker symbol for the backedfi asset.
    data_type: String
    tests:
    - not_null
    - unique
  - name: date
    description: Date of the price record, truncated to day.
    data_type: DateTime
    tests:
    - not_null
  - name: price
    description: Price value in USD (or relevant currency) at the given date.
    data_type: Float64
  config:
    access: public
    materialized: incremental
    tags:
    - prices
    - backedfi
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_execution_rwa_backedfi_prices
  description: Business-facing table containing RWA-backedFi prices with associated metadata.
  columns:
  - name: date
    description: Date of the price record in UTC.
    data_type: DateTime
    tests:
    - not_null
  - name: price
    description: Price value in USD (or relevant currency); range depends on asset.
    data_type: Float64
  - name: bticker
    description: Business ticker symbol identifying the asset.
    data_type: String
    tests:
    - not_null
    - unique
  config:
    access: public
    materialized: table
    tags:
    - finance
    - prices
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
