version: 2
models:

- name: rwa_backedfi_prices
  description: Business-facing table containing backedfi price data with timestamp and ticker information.
  columns:
  - name: bticker
    description: Ticker symbol for the backedfi asset.
    data_type: String
    tests:
    - not_null
    - unique
  - name: date
    description: Date of the price record, truncated to day.
    data_type: DateTime
    tests:
    - not_null
  - name: price
    description: Price value in USD (or relevant currency) at the given date.
    data_type: Float64
  config:
    access: public
    materialized: incremental
    tags:
    - prices
    - backedfi
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_execution_rwa_backedfi_prices
  description: Business-facing table containing RWA-backedFi prices with associated metadata.
  columns:
  - name: bticker
    description: Ticker symbol identifying the backedFi (e.g., 'bC3M', 'TSLAx').
    data_type: String
  - name: price
    description: Price of the backedFi in wei (integer, 256-bit). Range depends on market data.
    data_type: UInt64
  - name: date
    description: Date of the price record in UTC (start of day).
    data_type: DateTime
  config:
    access: public
    tags:
    - production
    - execution
    - rwa
    - backedfi
    - prices
    materialized: incremental
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
