version: 2
models:

- name: rwa_backedfi_prices
  description: Business-facing table containing backedfi price data with timestamp and ticker information.
  columns:

  - name: bticker
    description: Ticker symbol for the backedfi asset.
    data_type: String
    tests:
    - not_null
    - unique

  - name: date
    description: Date of the price record, truncated to day.
    data_type: DateTime
    tests:
    - not_null

  - name: price
    description: Price value in USD (or relevant currency) at the given date.
    data_type: Float64
  config:
    access: public
    materialized: incremental
    tags:
    - prices
    - backedfi
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer

- name: int_execution_rwa_backedfi_prices
  description: The model aggregates daily closing prices for various backed financial instruments from Oracle event data, supporting RWA calculations and risk assessments.
  columns:

  - name: bticker
    description: Identifier for the specific backed financial instrument.
    data_type: String

  - name: date
    description: The date corresponding to the recorded price, truncated to the start of the day.
    data_type: DateTime64
    tests:
    - not_null

  - name: price
    description: The latest available price for the instrument on the given date, expressed as an unsigned integer with 8 decimal places precision.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - rwa
    - backedfi
    - prices
    materialized: incremental
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.750697'
    _generated_fields:
    - description
    - columns.price.description
    - columns.bticker.description
    - columns.date.description
    - config.tags
    - config.materialized
    - columns.bticker.data_type
    - columns.price.data_type
    - columns.date.data_type
