version: 2
models:

- name: contracts_GBCDeposit_calls
  description: This model captures GBC deposit call data, including transaction details, contract addresses, and deposit amounts, for analysis and reporting.
  columns:
  - name: transaction_hash
    description: Unique identifier for the transaction
    data_type: String
  - name: block_number
    description: Block number in which the transaction was included
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp of the block in UTC
    data_type: DateTime
  - name: contract_address
    description: Address of the contract involved in the deposit
    data_type: String
  - name: output_json_type
    description: Indicates if output is in JSON format (boolean)
    data_type: String
  - name: deposit_amount
    description: Amount deposited in wei
    data_type: String
  - name: deposit_id
    description: Unique identifier for the deposit
    data_type: String
  - name: deposit_timestamp
    description: Timestamp when the deposit was made
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - gbp_deposits
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_GBCDeposit_events
  description: Business-facing model representing GBC deposit events, including transaction details, deposit amounts, and related timestamps.
  columns:
  - name: transaction_hash
    description: Unique identifier of the transaction in hexadecimal format.
    data_type: String
  - name: block_number
    description: Block number in which the event was included.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp of the block in UTC.
    data_type: DateTime64(0, 'UTC')
  - name: log_index
    description: Index of the event log within the block.
    data_type: UInt64
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: depositor_address
    description: Address of the account making the deposit.
    data_type: String
  - name: deposit_amount_wei
    description: Deposit amount in wei.
    data_type: UInt64
  - name: deposit_id
    description: Unique identifier for the deposit event.
    data_type: String
  - name: deposit_timestamp
    description: Timestamp when the deposit was made.
    data_type: DateTime64(0, 'UTC')
  config:
    access: public
    materialized: incremental
    tags:
    - deposits
    - blockchain
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
