version: 2
models:

- name: contracts_GBCDeposit_calls
  description: This model captures GBC deposit call transactions with details on transaction hash, block number, block timestamp, sender, receiver, amount, and status.
  columns:
  - name: transaction_hash
    description: Unique identifier of the transaction.
    data_type: String
  - name: block_number
    description: Number of the block containing the transaction.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp when the block was mined.
    data_type: DateTime64(0, 'UTC')
  - name: sender
    description: Address of the sender initiating the call.
    data_type: String
  - name: receiver
    description: Address of the receiver of the deposit.
    data_type: String
  - name: amount
    description: Deposit amount in wei.
    data_type: UInt64
  - name: status
    description: Status of the call (e.g., success, failed).
    data_type: String
  config:
    access: public
    tags:
    - production
    - contracts
    - gbcdeposit
    - calls
    materialized: incremental
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_GBCDeposit_events
  description: Business-facing model representing GBC deposit events, including transaction details, deposit amounts, and related metadata.
  columns:
  - name: transaction_hash
    description: Unique identifier of the transaction in which the event occurred.
    data_type: String
  - name: block_number
    description: Blockchain block number where the event was recorded.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp of the block containing the event, in UTC.
    data_type: DateTime64(0, 'UTC')
  - name: log_index
    description: Index of the log within the block, used to order events.
    data_type: UInt64
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: depositor_address
    description: Address of the account making the deposit.
    data_type: String
  - name: deposit_amount
    description: Amount deposited, in wei.
    data_type: String
  - name: deposit_token
    description: Token type of the deposit.
    data_type: String
  - name: deposit_timestamp
    description: Timestamp when the deposit was made, in UTC.
    data_type: DateTime64(0, 'UTC')
  - name: event_type
    description: Type of event, e.g., 'Deposit'.
    data_type: String
  - name: transaction_fee
    description: Fee paid for the transaction, in wei.
    data_type: String
  - name: status
    description: Status of the deposit event, e.g., 'success' or 'failed'.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - gbcdeposit
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
