version: 2
models:

- name: contracts_GBCDeposit_calls
  description: This model captures GBC deposit call data, including transaction details, contract addresses, and deposit specifics for analysis.
  columns:
  - name: transaction_hash
    description: Unique identifier for the transaction
    data_type: String
    tests:
    - not_null
    - unique
  - name: block_timestamp
    description: Timestamp of the block in UTC
    data_type: DateTime
    tests:
    - not_null
  - name: block_number
    description: Number of the block containing the transaction
    data_type: UInt64
  - name: from_address
    description: Address initiating the transaction
    data_type: String
  - name: to_address
    description: Contract address receiving the transaction
    data_type: String
  - name: contract_address
    description: Address of the GBC deposit contract
    data_type: String
  - name: deposit_amount
    description: Amount deposited in wei
    data_type: String
  - name: deposit_token
    description: Token used for deposit (e.g., ETH, ERC20)
    data_type: String
  - name: deposit_timestamp
    description: Timestamp when the deposit was made in UTC
    data_type: DateTime
  - name: deposit_id
    description: Unique identifier for the deposit record
    data_type: String
    tests:
    - not_null
    - unique
  - name: deposit_event_index
    description: Index of the deposit event within the block
    data_type: UInt64
  - name: deposit_block_number
    description: Block number where the deposit event was recorded
    data_type: UInt64
  - name: deposit_transaction_index
    description: Transaction index within the block
    data_type: UInt64
  - name: deposit_log_index
    description: Log index within the transaction
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - deposits
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_GBCDeposit_events
  description: This model captures GBC deposit events with details such as block timestamp, log index, transaction hash, contract address, depositor address, deposit amount, and event timestamp.
  columns:
  - name: block_timestamp
    description: The timestamp of the block when the event occurred.
    data_type: DateTime
    tests:
    - not_null
  - name: log_index
    description: The index of the log within the block.
    data_type: UInt64
    tests:
    - not_null
  - name: transaction_hash
    description: The hash of the transaction associated with the event.
    data_type: String
    tests:
    - not_null
    - unique
  - name: contract_address
    description: The address of the contract emitting the event.
    data_type: String
    tests:
    - not_null
  - name: depositor_address
    description: The address of the depositor.
    data_type: String
    tests:
    - not_null
  - name: deposit_amount
    description: The amount deposited, in wei.
    data_type: UInt64
  - name: event_timestamp
    description: The timestamp when the event was recorded.
    data_type: DateTime
    tests:
    - not_null
  config:
    access: public
    materialized: incremental
    tags:
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
