version: 2
models:

- name: yields_sdai_rate_daily
  description: Daily yields SDai rate data including date, conversion rate, and calculated rate.
  columns:
  - name: date
    description: The day for which the rate data is recorded.
    data_type: DateTime
    tests:
    - not_null
  - name: sdai_conversion
    description: The minimum asset/share ratio (unitless) for the day.
    data_type: Float64
  - name: rate
    description: The difference in SDai conversion rate from the previous day, floored to 12 decimal places.
    data_type: Float64
  config:
    access: public
    materialized: incremental
    tags:
    - yield
    - sdai
    - daily
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_yields_sdai_rate_daily
  description: Daily calculated SDAI rate based on sparse daily data and calendar alignment, used for yield analysis.
  columns:
  - name: date
    description: The date representing the start of the day (UTC).
    data_type: DateTime
  - name: sdai_conversion
    description: The minimal SDAI conversion rate observed within the day (unitless ratio).
    data_type: Float64
  - name: rate
    description: The difference in SDAI conversion rates between consecutive days, floored to 12 decimal places.
    data_type: Float64
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - execution
    - yields
    - sdai_rate
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
