version: 2
models:

- name: int_yields_sdai_rate_daily
  description: The model calculates daily SDai exchange rates based on deposit events, providing a time series for yield analysis and rate tracking.
  columns:

  - name: date
    description: The specific day for which the SDai rate data is recorded, aligned to the start of the day.
    data_type: DateTime64

  - name: sdai_conversion
    description: The minimum SDai conversion value observed on the given day, representing the exchange rate at that time.
    data_type: Float64

  - name: rate
    description: The computed SDAI rate (scaled by 12) for the date; null if not available.
    data_type: UInt64
    quote: true
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - execution
    - yields
    - sdai_rate
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:59.145100'
    _generated_fields:
    - description
    - columns.date.description
    - config.tags
    - config.materialized
    - columns.sdai_conversion.description
    - columns.sdai_conversion.data_type
    - columns.date.data_type
- name: int_execution_yields_pools_fees_daily
  description: Daily accrued pool fees at pool×token grain for Uniswap V3 and Swapr V3 pools, computed from Swap + Flash events (gross fees; independent of Collect/claims). Swap amounts are treated as signed int256 (two's complement) and pool fee tiers are applied in ppm (1e6 denominator). Includes both token amount and USD for debugging.
  columns:
  - name: date
    data_type: Date
  - name: protocol
    data_type: String
  - name: pool_address
    data_type: String
  - name: token_address
    data_type: String
  - name: token
    data_type: String
  - name: fee_amount
    data_type: Float64
  - name: fees_usd
    data_type: Float64
  config:
    access: public
    materialized: incremental
    tags: [production, execution, yields, pools, fees, accrued]
