version: 2
models:

- name: yields_sdai_rate_daily
  description: Daily yields SDai rate data including date, conversion rate, and calculated rate.
  columns:
  - name: date
    description: The day for which the rate data is recorded.
    data_type: DateTime
    tests:
    - not_null
  - name: sdai_conversion
    description: The minimum asset/share ratio (unitless) for the day.
    data_type: Float64
  - name: rate
    description: The difference in SDai conversion rate from the previous day, floored to 12 decimal places.
    data_type: Float64
  config:
    access: public
    materialized: incremental
    tags:
    - yield
    - sdai
    - daily
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_yields_sdai_rate_daily
  description: Daily calculated rates of SDai based on on-chain events and historical data, used for analytics and reporting.
  columns:
  - name: date
    description: The day for which the rate is calculated, in UTC.
    data_type: DateTime
  - name: sdai_conversion
    description: The minimal observed conversion rate (asset/share) for the day.
    data_type: String
  - name: rate
    description: The calculated rate (asset/share) for the day, rounded to 12 decimal places.
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - execution
    - yields
    - sdai_rate
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
