version: 2
models:

- name: int_GBCDeposit_deposists_daily
  description: The `int_GBCDeposit_deposists_daily` view aggregates daily deposit amounts and withdrawal credentials from GBC deposit events to support financial analysis and reporting.
  columns:

  - name: date
    description: The date (at day granularity) of the deposit event, representing the start of the day for aggregation.
    data_type: DateTime64
    tests:
    - not_null

  - name: withdrawal_credentials
    description: The withdrawal credentials associated with each deposit, indicating the destination address or account.
    data_type: String

  - name: amount
    description: The total deposit amount in unsigned 64-bit integer units, summed for each date and withdrawal credential.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - execution
    - GBCDeposit
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.665498'
    _generated_fields:
    - description
    - columns.date.description
    - columns.withdrawal_credentials.description
    - config.tags
    - config.materialized
    - columns.amount.description
    - columns.withdrawal_credentials.data_type
    - columns.amount.data_type
    - columns.date.data_type
