version: 2
models:

- name: int_GBCDeposit_deposists_daily
  description: Daily aggregated data of GBC Deposit deposits, including total deposit amounts and withdrawal credentials, grouped by date for business analysis.
  columns:
  - name: date
    description: Date representing the start of the day for the deposit record.
    data_type: DateTime
  - name: withdrawal_credentials
    description: Withdrawal credentials associated with deposits (string).
    data_type: String
  - name: amount
    description: Total deposit amount in wei (unsigned 64-bit integer).
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - GBCDeposit
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
