version: 2
models:

- name: int_GBCDeposit_deposists_daily
  description: Daily aggregated data of GBC deposits, including withdrawal credentials and total amount deposited.
  columns:
  - name: date
    description: The start of the day for the deposit record, in UTC.
    data_type: DateTime
  - name: withdrawal_credentials
    description: Encoded withdrawal credentials from deposit parameters.
    data_type: String
  - name: amount
    description: Sum of deposit amounts in wei for the day.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - GBCDeposit
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
