version: 2
models:

- name: int_consensus_validators_balances_dist_daily
  description: Daily distribution of validator balances based on quantile calculations from the consensus layer data, aggregated per day.
  columns:
  - name: date
    description: The day for which the balance distribution is calculated, truncated from slot timestamp.
    data_type: DateTime
    tests:
    - not_null
  - name: q05
    description: 5th percentile of validator balances for the day.
    data_type: Float64
  - name: q10
    description: 10th percentile of validator balances for the day.
    data_type: Float64
  - name: q25
    description: 25th percentile of validator balances for the day.
    data_type: Float64
  - name: q50
    description: Median (50th percentile) of validator balances for the day.
    data_type: Float64
  - name: q75
    description: 75th percentile of validator balances for the day.
    data_type: Float64
  - name: q90
    description: 90th percentile of validator balances for the day.
    data_type: Float64
  - name: q95
    description: 95th percentile of validator balances for the day.
    data_type: Float64
  config:
    access: public
    materialized: incremental
    tags:
    - consensus
    - validators
    - balances
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_consensus_validators_status_daily
  description: Daily snapshot of validator statuses, counts, and related metrics for consensus validation.
  columns:
  - name: date
    description: Date representing the start of the day for the snapshot.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: status
    description: Validator status (e.g., active, slashed, pending).
    data_type: String
    tests:
    - not_null
  - name: cnt
    description: Count of validators in the specified status.
    data_type: UInt64
    tests:
    - not_null
  config:
    access: public
    materialized: table
    tags:
    - consensus
    - validators
    - daily
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
