version: 2
models:

- name: int_consensus_validators_balances_dist_daily
  description: Daily distribution of validator balances based on quantiles from the consensus layer, aggregated per day.
  columns:
  - name: date
    description: Date representing the start of the day (UTC) for the distribution.
    data_type: DateTime
  - name: q05
    description: 5th percentile of validator balances for the day.
    data_type: Float64
  - name: q10
    description: 10th percentile of validator balances for the day.
    data_type: Float64
  - name: q25
    description: 25th percentile of validator balances for the day.
    data_type: Float64
  - name: q50
    description: 50th percentile (median) of validator balances for the day.
    data_type: Float64
  - name: q75
    description: 75th percentile of validator balances for the day.
    data_type: Float64
  - name: q90
    description: 90th percentile of validator balances for the day.
    data_type: Float64
  - name: q95
    description: 95th percentile of validator balances for the day.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - consensus
    - validators_balances
    materialized: table
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_consensus_validators_status_daily
  description: Daily aggregated status of consensus validators, including counts and statuses, derived from raw beacon chain data.
  columns:
  - name: date
    description: Day-level date derived from slot_timestamp, representing the day of data aggregation.
    data_type: DateTime
  - name: status
    description: Validator status (e.g., 'active', 'pending', 'exited').
    data_type: String
  - name: cnt
    description: Count of validators with the given status on the date.
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - consensus
    - validators_status
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: int_consensus_attestations_daily
  description: Daily aggregated count of consensus attestations, grouped by date and inclusion delay.
  columns:
  - name: date
    description: Date representing the start of the day for which attestations are aggregated.
    data_type: DateTime
  - name: inclusion_delay
    description: Difference in slots between the attestation slot and the attestation inclusion slot.
    data_type: UInt64
  - name: cnt
    description: Count of attestations for the given date and inclusion delay.
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - consensus
    - attestations
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_consensus_blob_commitments_daily
  description: Daily aggregated data of consensus blob commitments, including commitment counts and timestamps.
  columns:
  - name: date
    description: Date representing the start of the day for the commitment data.
    data_type: DateTime64(0, 'UTC')
  - name: cnt
    description: Total number of blob commitments recorded on the date.
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - consensus
    - blob_commitments
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_consensus_blocks_daily
  description: Daily aggregation of consensus layer blocks with computed metrics such as blocks produced and missed.
  columns:
  - name: date
    description: The day for which the metrics are aggregated, in UTC.
    data_type: Date
  - name: blocks_produced
    description: Number of blocks produced on the given date.
    data_type: UInt64
  - name: blocks_missed
    description: Number of blocks missed on the given date.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - consensus
    - blocks
    materialized: table
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_consensus_credentials_daily
  description: Daily count of consensus credentials grouped by type, derived from validator data.
  columns:
  - name: date
    description: Date representing the start of the day (UTC) for the aggregated data.
    data_type: DateTime
  - name: credentials_type
    description: First four bytes of withdrawal credentials indicating credential type.
    data_type: String
  - name: cnt
    description: Count of validator credentials of the specified type for the day.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - consensus
    - credentials
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: int_consensus_deposits_daily
  description: Daily aggregated deposits data derived from the consensus layer, including total amount and count of deposits per day.
  columns:
  - name: date
    description: Date representing the start of the day (UTC) for deposit aggregation.
    data_type: DateTime
  - name: total_amount
    description: Sum of deposit amounts in Gwei for the day.
    data_type: Float64
  - name: cnt
    description: Count of deposit transactions for the day.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - consensus
    - deposits
    materialized: incremental
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_consensus_entry_queue_daily
  description: Daily aggregated data on validator activation days, quantiles, and mean activation days for consensus entry queue analysis.
  columns:
  - name: date
    description: Date representing the day of validator activation.
    data_type: DateTime64(0, 'UTC')
  - name: validator_count
    description: Total number of validators activated on the date.
    data_type: UInt64
  - name: q05
    description: 5th percentile of activation days.
    data_type: Float64
  - name: q10
    description: 10th percentile of activation days.
    data_type: Float64
  - name: q25
    description: 25th percentile of activation days.
    data_type: Float64
  - name: q50
    description: Median (50th percentile) of activation days.
    data_type: Float64
  - name: q75
    description: 75th percentile of activation days.
    data_type: Float64
  - name: q90
    description: 90th percentile of activation days.
    data_type: Float64
  - name: q95
    description: 95th percentile of activation days.
    data_type: Float64
  - name: mean
    description: Average activation days for validators activated on the date.
    data_type: Float64
  config:
    access: public
    materialized: table
    tags:
    - production
    - consensus
    - entry_queue
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_consensus_graffiti_daily
  description: Aggregated daily counts of graffiti labels with associated metadata, including detected brands, clients, and labels, for consensus layer analysis.
  columns:
  - name: date
    description: Date of the aggregated data, truncated to day.
    data_type: DateTime
  - name: graffiti
    description: Original graffiti string from the block, in hex format.
    data_type: String
  - name: label
    description: 'Final label assigned based on priority: brand, EL+CL combo, EL, CL, ''None'', or ''Other''.'
    data_type: String
  - name: cnt
    description: Count of occurrences for the given graffiti label on that date.
    data_type: UInt64
  - name: brands_found
    description: Array of detected brand keys present in graffiti.
    data_type: Array(String)
  - name: el_label
    description: Detected Ethereum client label if any.
    data_type: String
  - name: cl_label
    description: Detected consensus client label if any.
    data_type: String
  config:
    access: public
    materialized: table
    tags:
    - production
    - consensus
    - graffiti
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_consensus_validators_apy_daily
  description: Daily aggregated data on validator balances, deposits, withdrawals, and APY calculations for consensus validators.
  columns:
  - name: date
    description: The date representing the day of the record, truncated from slot timestamp.
    data_type: DateTime
  - name: balance
    description: Total validator balance in wei as of the date.
    data_type: UInt64
  - name: balance_diff
    description: Difference in total validator balance compared to previous day.
    data_type: Int64
  - name: deposited_amount
    description: Total amount deposited on the date in wei.
    data_type: UInt64
  - name: withdrawaled_amount
    description: Total amount withdrawn on the date in wei.
    data_type: UInt64
  - name: deposited_amount_request
    description: Sum of deposit request amounts in wei for the date.
    data_type: UInt64
  - name: withdrawaled_amount_request
    description: Sum of withdrawal request amounts in wei for the date.
    data_type: UInt64
  - name: eff_balance_diff
    description: Effective balance change considering deposits and withdrawals.
    data_type: Int64
  - name: rate
    description: Rate of change of balance relative to previous balance.
    data_type: Float64
  - name: apy
    description: Annual Percentage Yield calculated from rate, expressed as a percentage.
    data_type: Float64
  config:
    access: public
    materialized: table
    tags:
    - production
    - consensus
    - validators_apy
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_consensus_validators_apy_dist
  description: This model calculates the distribution of annual percentage yields (APY) for consensus validators, aggregated monthly, based on their rate of return derived from balance changes, deposits, withdrawals, and related metrics.
  columns:
  - name: date
    description: The start date of the month for which the APY distribution is calculated.
    data_type: DateTime64(0, 'UTC')
  - name: q05
    description: 5th percentile of the validator APY distribution for the month.
    data_type: Float64
  - name: q10
    description: 10th percentile of the validator APY distribution for the month.
    data_type: Float64
  - name: q25
    description: 25th percentile of the validator APY distribution for the month.
    data_type: Float64
  - name: q50
    description: Median (50th percentile) of the validator APY distribution for the month.
    data_type: Float64
  - name: q75
    description: 75th percentile of the validator APY distribution for the month.
    data_type: Float64
  - name: q90
    description: 90th percentile of the validator APY distribution for the month.
    data_type: Float64
  - name: q95
    description: 95th percentile of the validator APY distribution for the month.
    data_type: Float64
  config:
    access: public
    materialized: table
    tags:
    - production
    - consensus
    - validators_apy
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: int_consensus_validators_balances_daily
  description: Daily aggregated balances and effective balances of consensus validators, derived from slot-based data, for business insights.
  columns:
  - name: date
    description: Date representing the start of the day for the balance aggregation.
    data_type: DateTime
  - name: balance
    description: Sum of validator balances in Gwei (wei / 10^9).
    data_type: Float64
  - name: effective_balance
    description: Sum of validator effective balances in Gwei (wei / 10^9).
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - consensus
    - validators_balances
    materialized: table
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_consensus_withdrawls_dist_daily
  description: Daily aggregated statistics of consensus withdrawals including quantiles, total amount, and count, derived from the consensus withdrawals data.
  columns:
  - name: date
    description: Date representing the start of the day for the withdrawal statistics.
    data_type: DateTime64(0, 'UTC')
  - name: total_amount
    description: Sum of withdrawal amounts in wei for the day.
    data_type: UInt64
  - name: cnt
    description: Total number of withdrawal transactions for the day.
    data_type: UInt64
  - name: min
    description: Minimum withdrawal amount in wei within the day.
    data_type: UInt64
  - name: q05
    description: 5th percentile withdrawal amount in wei within the day.
    data_type: UInt64
  - name: q10
    description: 10th percentile withdrawal amount in wei within the day.
    data_type: UInt64
  - name: q25
    description: 25th percentile withdrawal amount in wei within the day.
    data_type: UInt64
  - name: q50
    description: Median withdrawal amount in wei within the day.
    data_type: UInt64
  - name: q75
    description: 75th percentile withdrawal amount in wei within the day.
    data_type: UInt64
  - name: q90
    description: 90th percentile withdrawal amount in wei within the day.
    data_type: UInt64
  - name: q95
    description: 95th percentile withdrawal amount in wei within the day.
    data_type: UInt64
  - name: max
    description: Maximum withdrawal amount in wei within the day.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - consensus
    - withdrawals
    materialized: incremental
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
