version: 2
models:

- name: api_bridges_cum_netflow_monthly_by_bridge
  description: Model showing cumulative netflow monthly data by bridge.
  columns:
  - name: date
    description: Date of the data entry.
    data_type: String
  - name: series
    description: Identifier for the bridge series.
    data_type: String
  - name: value
    description: Cumulative netflow in USD.
    data_type: Float64
  config:
    access: public
  meta:
    owner: null
    authoritative: false
    generated_by: schema-writer
- name: api_bridges_cum_netflow_monthly_total
  description: Monthly total cumulative netflow in USD.
  columns:
  - name: date
    description: Month of the data.
    data_type: String
    tests:
    - not_null
  - name: value
    description: Total netflow in USD for the month.
    data_type: Float64
    tests:
    - not_null
  config:
    access: public
  meta:
    owner: null
    authoritative: false
    generated_by: schema-writer
- name: api_bridges_cum_netflow_weekly_by_bridge
  description: Model showing cumulative netflow weekly by bridge.
  columns:
  - name: date
    description: Date of the week.
    data_type: String
  - name: series
    description: Identifier of the bridge.
    data_type: String
  - name: value
    description: Cumulative netflow in USD.
    data_type: Float64
  config:
    access: public
  meta:
    owner: null
    authoritative: false
    generated_by: schema-writer
- name: api_bridges_cum_netflow_weekly_total
  description: Cumulative total netflow in USD per week.
  columns:
  - name: date
    description: Date of the week.
    data_type: String
  - name: value
    description: Cumulative total netflow in USD per week.
    data_type: Float64
  config:
    materialized: view
    access: public
    tags:
    - production
    - bridges
    - api
  meta:
    owner: null
    authoritative: false
    generated_by: schema-writer
- name: api_bridges_inflow_outflow_monthly_by_bridge
  description: Monthly inflow and outflow values in USD by bridge.
  columns:
  - name: date
    description: Date of the data entry.
    data_type: String
    tests:
    - not_null
  - name: bridge
    description: Name of the bridge.
    data_type: String
    tests:
    - not_null
  - name: series
    description: Type of flow (inflow/outflow).
    data_type: String
    tests:
    - not_null
  - name: value
    description: Value in USD.
    data_type: Float64
    tests:
    - not_null
  config:
    access: public
  meta:
    owner: null
    authoritative: false
    generated_by: schema-writer
- name: api_bridges_inflow_outflow_weekly_by_bridge
  description: Weekly inflow and outflow data by bridge.
  columns:
  - name: date
    description: Date of the week.
    data_type: String
  - name: bridge
    description: Name of the bridge.
    data_type: String
  - name: series
    description: Type of flow (inflow/outflow).
    data_type: String
  - name: value
    description: Value in USD.
    data_type: Float64
  config:
    access: public
  meta:
    owner: null
    authoritative: false
    generated_by: schema-writer
- name: api_bridges_netflow_monthly_by_bridge
  description: Monthly netflow data by bridge, aggregated by date and bridge.
  columns:
  - name: date
    description: Date of the month
    data_type: Date
  - name: series
    description: Identifier of the bridge
    data_type: String
  - name: value
    description: Netflow value in USD
    data_type: Float64
  config:
    access: public
  meta:
    owner: null
    authoritative: false
    generated_by: schema-writer
- name: api_bridges_token_netflow_monthly_stacked
  description: Monthly netflow data for API bridges, stacked by token series.
  columns:
  - name: date
    description: Date of the month
    data_type: String
  - name: series
    description: Token series
    data_type: String
  - name: value
    description: Netflow value in USD
    data_type: Float64
    tests:
    - not_null
  config:
    materialized: view
    tags:
    - production
    - bridges
    - api
    access: public
  meta:
    owner: analytics
    authoritative: false
    generated_by: schema-writer
- name: api_bridges_token_netflow_weekly_stacked
  description: Weekly netflow USD values for tokens on bridges.
  columns:
  - name: date
    description: Date of the week.
    data_type: String
  - name: series
    description: Token series.
    data_type: String
  - name: value
    description: Netflow USD value.
    data_type: Float64
    tests:
    - not_null
  config:
    materialized: view
    access: public
    tags:
    - production
    - bridges
    - api
  meta:
    owner: analytics
    authoritative: false
    generated_by: schema-writer
