version: 2
models:
- name: contract_GBCDeposit_calls
  description: 'TODO: Add description for contract_GBCDeposit_calls'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - beacon
  columns: []
- name: contract_GBCDeposit_events
  description: 'TODO: Add description for contract_GBCDeposit_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - beacon
  columns: []
