version: 2
models:
- name: contracts_aaveV3_ PoolInstance_events
  description: 'TODO: Add description for contracts_aaveV3_ PoolInstance_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - aave
  columns: []
- name: contracts_aaveV3_PoolConfigurator_events
  description: 'TODO: Add description for contracts_aaveV3_PoolConfigurator_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - aave
  columns: []
