version: 2
models:

- name: contracts_aaveV3_PoolInstance_events
  description: This table captures all events emitted by the Aave V3 PoolInstance contract, including details about each event's parameters, transaction context, and block metadata.
  columns:
  - name: block_number
    description: The height of the block containing the event.
    data_type: UInt32
    tests:
    - not_null
  - name: block_hash
    description: Hash of the block containing the event.
    data_type: String
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String
    tests:
    - not_null
  - name: log_index
    description: Zero-based index of the log within the transaction.
    data_type: UInt32
    tests:
    - not_null
  - name: event_name
    description: Name of the emitted event (e.g., "Deposit", "Withdraw").
    data_type: String
  - name: event_signature
    description: Keccak-256 hash of the event signature.
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
    tests:
    - not_null
  - name: block_timestamp
    description: UTC timestamp when the block was mined.
    data_type: DateTime
    tests:
    - not_null
  - name: transaction_index
    description: Index of the transaction within the block.
    data_type: UInt32
  - name: pool_address
    description: Address of the specific PoolInstance contract related to the event.
    data_type: String
  - name: reserve_address
    description: Address of the reserve involved in the event, if applicable.
    data_type: String
  - name: amount
    description: Amount involved in the event, in wei.
    data_type: String
  - name: amount_f64
    description: Amount converted to floating-point GNO/XDAI (may lose precision).
    data_type: Float64
  - name: sender
    description: Address initiating the transaction or call.
    data_type: String
  - name: recipient
    description: Address receiving funds, if applicable.
    data_type: String
  - name: timestamp
    description: UTC timestamp of the event occurrence.
    data_type: DateTime
  - name: chain_id
    description: EVM chain identifier (e.g., 100 for Gnosis).
    data_type: UInt64
  - name: insert_version
    description: Monotonic ingestion version in nanoseconds.
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - aave
    - v3
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_aaveV3_PoolConfigurator_events
  description: Business-facing events related to the Aave V3 Pool Configurator, including logs emitted during configuration changes and contract interactions.
  columns:
  - name: block_number
    description: Height of the block containing the event.
    data_type: UInt32
    tests:
    - not_null
  - name: block_hash
    description: Hash of the block containing the event.
    data_type: String
  - name: transaction_index
    description: Index of the transaction within the block.
    data_type: UInt32
  - name: log_index
    description: Zero-based index of the log within the transaction.
    data_type: UInt32
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String
    tests:
    - not_null
  - name: address
    description: Contract address that emitted the event.
    data_type: String
    tests:
    - not_null
  - name: event_name
    description: Name of the event emitted (e.g., "ConfigurationChanged").
    data_type: String
    tests:
    - not_null
  - name: block_timestamp
    description: UTC timestamp of the block when the event was emitted.
    data_type: DateTime
    tests:
    - not_null
  - name: data
    description: Encoded event data payload (hex).
    data_type: String
  - name: topic0
    description: First indexed topic (event signature hash).
    data_type: String
  - name: topic1
    description: Second indexed topic (if applicable).
    data_type: String
  - name: topic2
    description: Third indexed topic (if applicable).
    data_type: String
  - name: topic3
    description: Fourth indexed topic (if applicable).
    data_type: String
  - name: chain_id
    description: EVM chain identifier.
    data_type: UInt64
  - name: insert_version
    description: Monotonic ingestion version (nanoseconds).
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - aave
    - contracts
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
