version: 2
models:
- name: contracts_aaveV3_PoolInstance_events
  description: Events emitted by the Aave V3 Pool Instance contract (0xb50201558B00496A145fE76f7424749556E326D8).  This model uses the `decode_logs` macro to parse event logs from the `execution.logs` table.
  columns:
  - name: block_number
    description: Number of the block where the event was emitted.
    data_type: INTEGER
  - name: block_timestamp
    description: Timestamp of the block where the event was emitted.
    data_type: TIMESTAMP
  - name: log_index
    description: Index of the log within the block.
    data_type: INTEGER
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: STRING
  - name: event_name
    description: Name of the event emitted.
    data_type: STRING
  - name: event_data
    description: Parsed JSON containing the event data.
    data_type: JSON
  - name: contract_address
    description: Address of the contract that emitted the event.
    data_type: STRING
  tags:
  - aave
  - v3
  - events
  - decoded_logs
- name: contracts_aaveV3_PoolConfigurator_events
  description: Events emitted by the Aave V3 Pool Configurator contract (0x7304979ec9E4EaA0273b6A037a31c4e9e5A75D16).  This model uses the `decode_logs` macro to parse event logs from the `execution.logs` table.
  columns:
  - name: block_number
    description: Number of the block where the event was emitted.
    data_type: INTEGER
  - name: block_timestamp
    description: Timestamp of the block where the event was emitted.
    data_type: TIMESTAMP
  - name: log_index
    description: Index of the log within the block.
    data_type: INTEGER
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: STRING
  - name: contract_address
    description: Address of the contract that emitted the event.
    data_type: STRING
  - name: event_name
    description: Name of the event emitted.
    data_type: STRING
  - name: event_data
    description: Parsed JSON containing event parameters.
    data_type: JSON
  tags:
  - aave
  - v3
  - events
  - pool_configurator
