version: 2
models:

- name: stg_execution__blocks
  description: Business-facing staging model for execution blocks, including core block metadata, transaction details, logs, and related chain data.
  columns:
  - name: block_number
    description: Height of the block containing the record.
    data_type: UInt32
  - name: block_hash
    description: Keccak-256 hash of the block header.
    data_type: String
  - name: parent_hash
    description: Hash of the parent block header.
    data_type: String
  - name: uncles_hash
    description: Keccak-256 hash of the ommers list.
    data_type: String
  - name: author
    description: Address (hex string) of the validator/miner proposing the block.
    data_type: String
  - name: state_root
    description: Root hash of the state trie.
    data_type: String
  - name: transactions_root
    description: Root hash of the transactions trie.
    data_type: String
  - name: receipts_root
    description: Root hash of the receipts trie.
    data_type: String
  - name: gas_used
    description: Total gas consumed by transactions in the block.
    data_type: UInt64
  - name: gas_limit
    description: Maximum gas allowed in the block.
    data_type: UInt64
  - name: extra_data
    description: Arbitrary extra-data bytes set by the block proposer (hex string).
    data_type: String
  - name: size
    description: Serialized block size in bytes.
    data_type: UInt64
  - name: mix_hash
    description: Mix hash (pre-merge PoW) or random field.
    data_type: String
  - name: nonce
    description: Block nonce (legacy field).
    data_type: String
  - name: base_fee_per_gas
    description: Base fee per gas (wei) introduced by EIP-1559.
    data_type: UInt64
  - name: withdrawals_root
    description: Root hash of withdrawals list (Shanghai+).
    data_type: String
  - name: block_timestamp
    description: UTC timestamp of the block.
    data_type: DateTime
  - name: chain_id
    description: EVM chain identifier (e.g., 100 for Gnosis).
    data_type: UInt64
  - name: insert_version
    description: Monotonic ingestion version (nanoseconds).
    data_type: UInt64
  - name: transaction_hash
    description: Keccak-256 hash of the transaction.
    data_type: String
  - name: transaction_index
    description: Zero-based index of the transaction within the block.
    data_type: UInt64
  - name: from_address
    description: Sender address (hex string) of the transaction.
    data_type: String
  - name: to_address
    description: Recipient address (hex string) or null for contract creation.
    data_type: String
  - name: value_binary
    description: Value transferred (native token) as 32-byte big-endian binary.
    data_type: String
  - name: value_string
    description: Value transferred as decimal string.
    data_type: String
  - name: value_f64
    description: Value transferred as floating-point ether (may lose precision).
    data_type: Float64
  - name: input
    description: Calldata or input data (hex string).
    data_type: String
  - name: gas_price
    description: Legacy gas price (wei).
    data_type: UInt64
  - name: transaction_type
    description: Envelope type (0=legacy,1=access-list,2=EIP-1559).
    data_type: UInt32
  - name: max_priority_fee_per_gas
    description: Max miner tip per gas (wei) for EIP-1559.
    data_type: UInt64
  - name: max_fee_per_gas
    description: Max total fee per gas (wei) under EIP-1559.
    data_type: UInt64
  - name: success
    description: 1 if transaction succeeded, 0 if reverted.
    data_type: UInt8
  - name: n_input_bytes
    description: Length of input data in bytes.
    data_type: UInt32
  - name: n_input_zero_bytes
    description: Number of zero bytes in input.
    data_type: UInt32
  - name: n_input_nonzero_bytes
    description: Number of non-zero bytes in input.
    data_type: UInt32
  - name: n_rlp_bytes
    description: Total RLP-encoded payload size in bytes.
    data_type: UInt32
  - name: timestamp
    description: Block timestamp (seconds since epoch).
    data_type: UInt32
  - name: r
    description: ECDSA signature r component.
    data_type: String
  - name: s
    description: ECDSA signature s component.
    data_type: String
  - name: v
    description: ECDSA recovery id / y-parity.
    data_type: UInt32
  - name: log_index
    description: Zero-based index of the log within the transaction.
    data_type: UInt32
  - name: address
    description: Contract address emitting the event.
    data_type: String
  - name: topic0
    description: First indexed topic (event signature hash).
    data_type: String
  - name: topic1
    description: Second indexed topic.
    data_type: String
  - name: topic2
    description: Third indexed topic.
    data_type: String
  - name: topic3
    description: Fourth indexed topic.
    data_type: String
  - name: data
    description: Non-indexed event data payload (hex string).
    data_type: String
  - name: n_data_bytes
    description: Length of data in bytes.
    data_type: UInt32
  - name: transfer_index
    description: Zero-based native transfer index within the transaction.
    data_type: UInt32
  - name: from_value_binary
    description: Balance before change (32-byte binary).
    data_type: String
  - name: from_value_string
    description: Balance before change (decimal string).
    data_type: String
  - name: to_value_binary
    description: Balance after change (32-byte binary).
    data_type: String
  - name: to_value_string
    description: Balance after change (decimal string).
    data_type: String
  - name: to_value_f64
    description: Balance after change as floating-point ether.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - blocks
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
