version: 2
models:

- name: stg_execution__blocks
  description: Business-facing staging model for execution layer blocks, including core block data, metadata, and related entities. Provides a cleaned and consolidated view for analysis.
  columns:
  - name: nonce
    description: Block nonce (legacy proof-of-work nonce) as a string.
    data_type: String
  - name: author
    description: Address (hex string) of the block proposer.
    data_type: String
  - name: block_timestamp
    description: UTC timestamp when the block was proposed.
    data_type: DateTime
  - name: parent_hash
    description: Hash of the parent block header.
    data_type: String
  - name: size
    description: Serialized size of the block in bytes.
    data_type: UInt64
  - name: block_number
    description: Height of the block in the chain.
    data_type: UInt64
  - name: block_hash
    description: Keccak-256 hash of the block header.
    data_type: String
  - name: mix_hash
    description: Mix hash (pre-merge PoW) or random field.
    data_type: String
  - name: gas_limit
    description: Maximum gas allowed in the block.
    data_type: UInt64
  - name: withdrawals_root
    description: Root hash of withdrawals list (Shanghai+).
    data_type: String
  - name: transactions_root
    description: Root hash of the transactions trie.
    data_type: String
  - name: receipts_root
    description: Root hash of the receipts trie.
    data_type: String
  - name: gas_used
    description: Total gas consumed by transactions in the block.
    data_type: UInt64
  - name: uncles_hash
    description: Keccak-256 hash of the ommers list.
    data_type: String
  - name: base_fee_per_gas
    description: Base fee per gas (wei) introduced by EIP-1559.
    data_type: UInt64
  - name: state_root
    description: Root hash of the state trie.
    data_type: String
  - name: chain_id
    description: Chain identifier (e.g., 100 for Gnosis).
    data_type: UInt64
  - name: insert_version
    description: Monotonic ingestion version timestamp.
    data_type: UInt64
  - name: extra_data
    description: Arbitrary extra data bytes set by proposer (hex).
    data_type: String
  config:
    access: public
    tags:
    - production
    - execution
    - blocks
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
