version: 2
models:

- name: stg_execution__blocks
  description: The stg_execution__blocks model consolidates blockchain block data relevant to execution, providing a structured view for analysis of block properties and transaction details.
  columns:

  - name: block_number
    description: The sequential number identifying the block within the blockchain.
    data_type: UInt64

  - name: block_hash
    description: Unique cryptographic hash representing the block.
    data_type: String
    tests:
    - unique
    - not_null

  - name: parent_hash
    description: Hash of the preceding block, establishing the chain linkage.
    data_type: String

  - name: uncles_hash
    description: Hash referencing uncle blocks included in this block.
    data_type: String

  - name: author
    description: Address of the miner or validator who produced the block, formatted as a hexadecimal string.
    data_type: String

  - name: state_root
    description: Root hash of the state trie after executing the block.
    data_type: String

  - name: transactions_root
    description: Root hash of the transaction trie within the block.
    data_type: String

  - name: receipts_root
    description: Root hash of the receipts trie for all transactions in the block.
    data_type: String

  - name: gas_used
    description: Total amount of gas consumed by all transactions in the block.
    data_type: UInt64

  - name: gas_limit
    description: Maximum amount of gas allowed for transactions in the block.
    data_type: UInt64

  - name: extra_data
    description: Additional arbitrary data included in the block, stored as raw bytes.
    data_type: String

  - name: size
    description: Size of the block in bytes.
    data_type: UInt64

  - name: mix_hash
    description: Hash used in the proof-of-work algorithm to validate the block.
    data_type: String

  - name: nonce
    description: Number used once in the proof-of-work process, aiding in block validation.
    data_type: String

  - name: base_fee_per_gas
    description: The base fee per gas unit, in wei, applicable after EIP-1559.
    data_type: Float64

  - name: withdrawals_root
    description: Root hash of the withdrawals trie, relevant for withdrawals included in the block.
    data_type: String

  - name: block_timestamp
    description: Unix timestamp indicating when the block was mined.
    data_type: DateTime64
    tests:
    - not_null

  - name: chain_id
    description: EVM chain identifier (e.g., 100 for Gnosis).
    data_type: UInt64

  - name: insert_version
    description: Monotonic ingestion version (nanoseconds).
    data_type: UInt64

  - name: transaction_hash
    description: Keccak-256 hash of the transaction.
    data_type: String

  - name: transaction_index
    description: Zero-based index of the transaction within the block.
    data_type: UInt64

  - name: from_address
    description: Sender address (hex string) of the transaction.
    data_type: String

  - name: to_address
    description: Recipient address (hex string) or null for contract creation.
    data_type: String

  - name: value_binary
    description: Value transferred (native token) as 32-byte big-endian binary.
    data_type: String

  - name: value_string
    description: Value transferred as decimal string.
    data_type: String

  - name: value_f64
    description: Value transferred as floating-point ether (may lose precision).
    data_type: Float64

  - name: input
    description: Calldata or input data (hex string).
    data_type: String

  - name: gas_price
    description: Legacy gas price (wei).
    data_type: UInt64

  - name: transaction_type
    description: Envelope type (0=legacy,1=access-list,2=EIP-1559).
    data_type: UInt32

  - name: max_priority_fee_per_gas
    description: Max miner tip per gas (wei) for EIP-1559.
    data_type: UInt64

  - name: max_fee_per_gas
    description: Max total fee per gas (wei) under EIP-1559.
    data_type: UInt64

  - name: success
    description: 1 if transaction succeeded, 0 if reverted.
    data_type: UInt8

  - name: n_input_bytes
    description: Length of input data in bytes.
    data_type: UInt32

  - name: n_input_zero_bytes
    description: Number of zero bytes in input.
    data_type: UInt32

  - name: n_input_nonzero_bytes
    description: Number of non-zero bytes in input.
    data_type: UInt32

  - name: n_rlp_bytes
    description: Total RLP-encoded payload size in bytes.
    data_type: UInt32

  - name: timestamp
    description: Block timestamp (seconds since epoch).
    data_type: UInt32

  - name: r
    description: ECDSA signature r component.
    data_type: String

  - name: s
    description: ECDSA signature s component.
    data_type: String

  - name: v
    description: ECDSA recovery id / y-parity.
    data_type: UInt32

  - name: log_index
    description: Zero-based index of the log within the transaction.
    data_type: UInt32

  - name: address
    description: Contract address emitting the event.
    data_type: String

  - name: topic0
    description: First indexed topic (event signature hash).
    data_type: String

  - name: topic1
    description: Second indexed topic.
    data_type: String

  - name: topic2
    description: Third indexed topic.
    data_type: String

  - name: topic3
    description: Fourth indexed topic.
    data_type: String

  - name: data
    description: Non-indexed event data payload (hex string).
    data_type: String

  - name: n_data_bytes
    description: Length of data in bytes.
    data_type: UInt32

  - name: transfer_index
    description: Zero-based native transfer index within the transaction.
    data_type: UInt32

  - name: from_value_binary
    description: Balance before change (32-byte binary).
    data_type: String

  - name: from_value_string
    description: Balance before change (decimal string).
    data_type: String

  - name: to_value_binary
    description: Balance after change (32-byte binary).
    data_type: String

  - name: to_value_string
    description: Balance after change (decimal string).
    data_type: String

  - name: to_value_f64
    description: Balance after change as floating-point ether.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - blocks
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.721547'
    _generated_fields:
    - columns.author.description
    - columns.gas_limit.data_type
    - columns.parent_hash.data_type
    - columns.receipts_root.description
    - config.tags
    - columns.uncles_hash.data_type
    - columns.size.description
    - columns.mix_hash.description
    - columns.block_hash.data_type
    - columns.uncles_hash.description
    - description
    - columns.block_hash.description
    - columns.withdrawals_root.data_type
    - columns.gas_used.description
    - columns.state_root.data_type
    - columns.parent_hash.description
    - columns.base_fee_per_gas.description
    - columns.mix_hash.data_type
    - columns.transactions_root.description
    - columns.withdrawals_root.description
    - columns.block_number.data_type
    - columns.block_number.description
    - columns.nonce.data_type
    - columns.author.data_type
    - columns.state_root.description
    - columns.base_fee_per_gas.data_type
    - config.materialized
    - columns.nonce.description
    - columns.extra_data.data_type
    - columns.size.data_type
    - columns.block_timestamp.data_type
    - columns.gas_limit.description
    - columns.transactions_root.data_type
    - columns.extra_data.description
    - columns.gas_used.data_type
    - columns.block_timestamp.description
    - columns.receipts_root.data_type
