version: 2
models:

- name: stg_execution__blocks
  description: Staging model for execution layer blocks, including block metadata, transaction data, logs, and associated state changes, sourced from the execution.blocks table with transformations applied.
  columns:
  - name: block_number
    description: Height of the block containing the record.
    data_type: UInt32
    tests:
    - not_null
  - name: block_hash
    description: Keccak-256 hash of the block header.
    data_type: String
    tests:
    - not_null
  - name: parent_hash
    description: Hash of the parent block header.
    data_type: String
  - name: uncles_hash
    description: Keccak-256 hash of the ommers list.
    data_type: String
  - name: author
    description: Address (hex string) of the validator/miner proposing the block.
    data_type: String
  - name: state_root
    description: Root hash of the state trie.
    data_type: String
  - name: transactions_root
    description: Root hash of the transactions trie.
    data_type: String
  - name: receipts_root
    description: Root hash of the receipts trie.
    data_type: String
  - name: gas_used
    description: Total gas consumed by transactions in the block.
    data_type: UInt64
    tests:
    - not_null
  - name: gas_limit
    description: Maximum gas allowed in the block.
    data_type: UInt64
    tests:
    - not_null
  - name: extra_data
    description: Arbitrary extra-data bytes set by the block proposer (hex).
    data_type: String
  - name: decoded_extra_data
    description: Decoded extra data from `extra_data` field.
    data_type: String
  - name: size
    description: Serialized block size in bytes.
    data_type: UInt64
    tests:
    - not_null
  - name: mix_hash
    description: Mix hash (pre-merge PoW) or random field.
    data_type: String
  - name: nonce
    description: Block nonce (legacy field).
    data_type: String
  - name: base_fee_per_gas
    description: Base fee per gas (wei) introduced by EIP-1559.
    data_type: UInt64
    tests:
    - not_null
  - name: withdrawals_root
    description: Root hash of withdrawals list (Shanghai+).
    data_type: String
  - name: chain_id
    description: EVM chain identifier (e.g., 100 for Gnosis).
    data_type: UInt64
    tests:
    - not_null
  - name: block_timestamp
    description: UTC timestamp for the block.
    data_type: DateTime
    tests:
    - not_null
  - name: insert_version
    description: Monotonic ingestion version (nanoseconds).
    data_type: UInt64
  - name: transactions
    description: Array of transaction hashes included in the block.
    data_type: String
  - name: logs_bloom
    description: Bloom filter for logs in this block.
    data_type: String
  - name: timestamp
    description: Unix epoch seconds when the block was proposed.
    data_type: UInt32
  - name: logs
    description: Event logs emitted by smart contracts within the block.
    data_type: JSON
  - name: transactions_data
    description: Detailed transaction data included in the block.
    data_type: JSON
  - name: native_transfers
    description: Decoded native token transfers within the block.
    data_type: JSON
  - name: contracts
    description: Contracts created in this block with deployment info.
    data_type: JSON
  - name: traces
    description: Execution traces for internal calls and contract creation.
    data_type: JSON
  - name: balance_diffs
    description: Balance changes caused by transactions in this block.
    data_type: JSON
  - name: storage_diffs
    description: Storage slot mutations within the block.
    data_type: JSON
  - name: code_diffs
    description: Changes to smart contract runtime code.
    data_type: JSON
  - name: nonce_diffs
    description: Nonce updates for accounts.
    data_type: JSON
  - name: withdrawals
    description: Beacon chain withdrawal data bridged into the block.
    data_type: JSON
  - name: indexing_state
    description: Worker-reported indexing state for this block.
    data_type: JSON
  - name: indexing_progress
    description: Aggregated progress metrics for indexing.
    data_type: JSON
  - name: continuous_ranges
    description: Summarized continuous block ranges and coverage.
    data_type: JSON
  - name: indexing_summary
    description: End-to-end indexing status and coverage.
    data_type: JSON
  - name: migrations
    description: Data migration records executed during ingestion.
    data_type: JSON
  config:
    access: public
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
