{{
  config(
    materialized='view',
    tags=['dev','execution','cow','tier1',
          'api:cow_solver_value_ts','granularity:daily']
  )
}}

-- Daily gross value generated by CoW solvers on Gnosis Chain, in USD.
-- Covers trades where a priceImprovement or surplus fee policy was applied
-- (Sep 2024+). Each value = CoW's protocol fee / fee_factor, i.e. the full
-- value found beyond the reference price before the protocol takes its cut.
-- volume-only fee policies are excluded as they carry no solver-quality signal.

SELECT
    toDate(block_timestamp)                                                      AS date,
    sum(solver_value_usd)                                                        AS value
FROM {{ ref('fct_execution_cow_trades') }}
WHERE toDate(block_timestamp) < today()
  AND fee_source = 'api'
  AND solver_value_usd > 0
GROUP BY date
ORDER BY date
