version: 2
models:

- name: api_probelab_clients_cloud_daily
  description: Daily aggregated data on probelab clients, including cloud provider, client version, and other metrics derived from crawlers.
  columns:
  - name: date
    description: Date representing the start of the day for the aggregated data.
    data_type: DateTime
  - name: client
    description: Client version type indicating the client software version.
    data_type: String
  - name: cloud
    description: Cloud provider name associated with the client.
    data_type: String
  - name: value
    description: Integer count of clients or instances for the given date, client, and cloud.
    data_type: Int32
  config:
    access: public
    materialized: view
    tags:
    - production
    - probelab
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_country_daily
  description: Daily aggregated data on client activity by country, including date, client type, country, and associated values, derived from crawlers data.
  columns:
  - name: date
    description: Date representing the start of the day for the aggregated data (UTC).
    data_type: DateTime64(0, 'UTC')
  - name: client
    description: Client version type or category.
    data_type: String
  - name: country
    description: Country code or name.
    data_type: String
  - name: value
    description: Integer value representing count or metric for the day.
    data_type: Int32
  config:
    access: public
    materialized: view
    tags:
    - production
    - probelab
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_daily
  description: Daily aggregated data on Probelab clients, including the maximum crawl creation timestamp, client version type, and the aggregated value of a specific metric.
  columns:
  - name: date
    description: The start of the day for the aggregated data, derived from max_crawl_created_at.
    data_type: DateTime
  - name: client
    description: The client version type associated with the data.
    data_type: String
  - name: value
    description: Aggregated metric value, represented as an integer after conversion.
    data_type: Int32
  config:
    access: public
    tags:
    - production
    - probelab
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_quic_daily
  description: Daily aggregated data on QUIC support, client versions, and related metrics derived from crawlers, used for business analysis and monitoring.
  columns:
  - name: date
    description: Date representing the start of the day for the aggregated data
    data_type: DateTime
  - name: client
    description: Client version type identifier
    data_type: String
  - name: quic
    description: Support status for QUIC protocol
    data_type: String
  - name: value
    description: Count of records for the given date, client, and QUIC support status
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - probelab
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_version_daily
  description: Daily aggregated data on API probelab clients, including version info and counts.
  columns:
  - name: date
    description: The start of the day for the aggregated data (UTC).
    data_type: DateTime64(0, 'UTC')
  - name: client
    description: Type of agent version client.
    data_type: String
  - name: version
    description: Semantic version string of the client.
    data_type: String
  - name: value
    description: Count of occurrences for the given day, client, and version.
    data_type: Int32
  config:
    access: public
    materialized: view
    tags:
    - production
    - probelab
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
