version: 2
models:

- name: api_probelab_clients_cloud_daily
  description: Daily aggregated data on clients, cloud providers, and related metrics for Probelab.
  columns:
  - name: date
    description: Date representing the start of the day for the aggregated data
    data_type: DateTime
    tests:
    - not_null
  - name: client
    description: Agent version type identifying the client
    data_type: String
    tests:
    - not_null
  - name: cloud
    description: Cloud provider name
    data_type: String
    tests:
    - not_null
  - name: value
    description: Integer value representing the count or metric for the day
    data_type: Int32
    tests:
    - not_null
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_country_daily
  description: Daily aggregated data on probelab clients by country, including counts and client types.
  columns:
  - name: date
    description: The start of the day for the data point, in UTC.
    data_type: DateTime
    tests:
    - not_null
  - name: client
    description: Client version type as a string.
    data_type: String
  - name: country
    description: Country code or name.
    data_type: String
  - name: value
    description: Count of clients for the given day, client, and country.
    data_type: UInt64
    tests:
    - not_null
  config:
    access: public
    tags:
    - daily
    - probelab
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_daily
  description: Daily aggregated data on Probelab clients, including client type and activity metrics.
  columns:
  - name: date
    description: The start of the day for the aggregated data (UTC).
    data_type: DateTime
    tests:
    - not_null
  - name: client
    description: Client type identifier, e.g., agent version or category.
    data_type: String
    tests:
    - not_null
  - name: value
    description: Numeric metric representing client activity or count.
    data_type: Float64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_quic_daily
  description: Daily aggregated data on QUIC support, client versions, and related metrics
  columns:
  - name: date
    description: Date representing the start of the day for the aggregated data
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: client
    description: Client version type
    data_type: String
    tests:
    - not_null
  - name: quic
    description: QUIC support status
    data_type: String
    tests:
    - not_null
  - name: value
    description: Count of records for the given date, client, and QUIC support status
    data_type: UInt64
    tests:
    - not_null
  config:
    access: public
    tags:
    - daily
    - quic
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_version_daily
  description: Daily aggregated data on API probelab clients, including version info, client type, and associated values for business analysis.
  columns:
  - name: date
    description: The start of the day for the aggregated record (UTC timestamp).
    data_type: DateTime
    tests:
    - not_null
  - name: client
    description: Type of agent client (e.g., browser, crawler).
    data_type: String
  - name: version
    description: Semantic version string of the client.
    data_type: String
  - name: value
    description: Count or metric value (integer, 32-bit).
    data_type: Int32
    tests:
    - not_null
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
