version: 2
models:

- name: api_probelab_clients_cloud_daily
  description: Daily aggregated data on cloud clients, including counts and provider info, derived from crawlers.
  columns:
  - name: date
    description: The start of the day for the aggregated data, in UTC.
    data_type: DateTime
  - name: client
    description: The client version type associated with the data.
    data_type: String
  - name: cloud
    description: The cloud provider name.
    data_type: String
  - name: value
    description: Count of clients for the given day, provider, and client type.
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - probelab
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_country_daily
  description: Daily aggregated data on Probelab clients by country, including client type and date.
  columns:
  - name: date
    description: The start of the day for the data point, in UTC.
    data_type: DateTime
  - name: client
    description: Client version type identifier.
    data_type: String
  - name: country
    description: Country code or name.
    data_type: String
  - name: value
    description: Count of clients for the given date, client, and country.
    data_type: UInt32
  config:
    access: public
    materialized: view
    tags:
    - production
    - probelab
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_daily
  description: Daily aggregated data on Probelab clients, including the maximum crawl creation date, client version type, and the aggregated value of a specific metric.
  columns:
  - name: date
    description: The start of the day for the crawl data, representing the date of aggregation.
    data_type: DateTime
  - name: client
    description: The client version type associated with the data.
    data_type: String
  - name: value
    description: Aggregated metric value (integer), representing the sum or count as per the query.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - probelab
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_quic_daily
  description: Daily aggregated data on QUIC support, client version types, and related metrics derived from crawlers data, used for monitoring and analysis.
  columns:
  - name: date
    description: Date representing the start of the day for the aggregated data (UTC).
    data_type: DateTime
  - name: client
    description: Client version type identifier.
    data_type: String
  - name: quic
    description: Support status for QUIC protocol (e.g., 'supported', 'not supported').
    data_type: String
  - name: value
    description: Count of records for the given date, client, and QUIC support status.
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - probelab
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_version_daily
  description: Daily aggregated data of API probelab clients, including version, client type, and count of occurrences, ordered by date.
  columns:
  - name: date
    description: Date representing the start of the day for the aggregated data.
    data_type: DateTime
  - name: client
    description: Type of client agent.
    data_type: String
  - name: version
    description: Semantic version string of the client.
    data_type: String
  - name: value
    description: Count of occurrences for the given date, client, and version.
    data_type: Int32
  config:
    access: public
    materialized: view
    tags:
    - production
    - probelab
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
