version: 2
models:

- name: api_probelab_clients_cloud_daily
  description: Daily aggregated data on client, cloud provider, and date, derived from crawlers.
  columns:
  - name: date
    description: Date representing the start of the day for the record
    data_type: DateTime64(0, 'UTC')
  - name: client
    description: Agent version type
    data_type: String
  - name: cloud
    description: Cloud provider name
    data_type: String
  - name: value
    description: Count of records for the given date, client, and cloud
    data_type: Int32
  config:
    access: public
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_country_daily
  description: Daily aggregated data on client activity per country, including counts and timestamps.
  columns:
  - name: date
    description: The day for which the data is aggregated, starting at midnight UTC.
    data_type: DateTime
  - name: client
    description: The client version type, representing different client categories.
    data_type: String
  - name: country
    description: The country code or name associated with the data.
    data_type: String
  - name: value
    description: The count of client occurrences for the given date, client, and country.
    data_type: UInt64
  config:
    access: public
    tags:
    - daily
    - client
    - country
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_daily
  description: Daily aggregated data on probelab clients including metrics like client version, and associated values, grouped by date and client.
  columns:
  - name: date
    description: The day for which the data is aggregated, in UTC.
    data_type: DateTime
  - name: client
    description: The client version type identifier.
    data_type: String
  - name: value
    description: The aggregated metric value, as an integer.
    data_type: Int32
  config:
    access: public
    materialized: table
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_quic_daily
  description: Daily aggregated data on QUIC support, client versions, and related metrics
  columns:
  - name: date
    description: Date representing the start of the day for the aggregated data
    data_type: DateTime
  - name: client
    description: Client version type
    data_type: String
  - name: quic
    description: QUIC support status
    data_type: String
  - name: value
    description: Count of records for the given date, client, and QUIC support status
    data_type: UInt64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_probelab_clients_version_daily
  description: Daily aggregated data on client versions, including counts and timestamps.
  columns:
  - name: date
    description: The start of day timestamp for the data point.
    data_type: DateTime64(0, 'UTC')
  - name: client
    description: Agent version type identifier.
    data_type: String
  - name: version
    description: Semantic version string of the agent.
    data_type: String
  - name: value
    description: Count of occurrences for the given client and version.
    data_type: UInt64
  config:
    access: public
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
