version: 2
models:

- name: int_execution_token_prices_daily
  description: The `int_execution_token_prices_daily` view consolidates daily price data for various tokens and stablecoins used in execution and trading activities, facilitating analysis of price trends and stability over time.
  columns:

  - name: date
    description: The date for which the price data is recorded, formatted as a date.
    data_type: Date

  - name: symbol
    description: The token or stablecoin symbol. When available, this uses the preferred presentation format from the `tokens_whitelist` seed (e.g. `USDC.e`, `EURe`, `xDAI`).
    data_type: String

  - name: price
    description: The recorded price of the token in USD, represented as a floating-point number.
    data_type: Float64
  meta:
    owner: analytics_team
    authoritative: false
  tests:
  - elementary.volume_anomalies:
      timestamp_column: date
      time_bucket:
        period: day
        count: 1
      training_period:
        period: day
        count: 56
      seasonality: day_of_week
      detection_period:
        period: day
        count: 2
      detection_delay:
        period: day
        count: 1
      anomaly_sensitivity: 3
      ignore_small_changes:
        spike_failure_percent_threshold: 10
        drop_failure_percent_threshold: 20
      severity: warn
      tags:
      - elementary
  - elementary.freshness_anomalies:
      timestamp_column: date
      time_bucket:
        period: day
        count: 1
      severity: warn
      tags:
      - elementary
  - elementary.schema_changes:
      severity: warn
      tags:
      - elementary
