version: 2
models:

- name: int_execution_token_prices_daily
  description: Value (XDAI) transfers decoded from transactions.
  columns:
  - name: date
    description: Date of the transaction.
    data_type: DateTime
  - name: symbol
    description: Symbol of the token.
    data_type: String
  - name: price
    description: Price of the token.
    data_type: Float64
  config:
    materialized: view
    access: public
  meta:
    owner: analytics_engineer
    authoritative: false
    generated_by: schema-writer
