version: 2
models:

- name: int_execution_token_prices_daily
  description: The `int_execution_token_prices_daily` view consolidates daily price data for various tokens and stablecoins used in execution and trading activities, facilitating analysis of price trends and stability over time.
  columns:

  - name: date
    description: The date for which the price data is recorded, formatted as a date.
    data_type: Date
    tests:
    - not_null

  - name: symbol
    description: The token or stablecoin symbol, standardized in uppercase.
    data_type: String

  - name: price
    description: The recorded price of the token in USD, represented as a floating-point number.
    data_type: UInt64
  config:
    materialized: view
    access: public
    tags:
    - production
    - execution
    - prices
    - daily
  meta:
    owner: analytics_engineer
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.744170'
    _generated_fields:
    - description
    - columns.price.description
    - columns.symbol.data_type
    - columns.date.description
    - config.tags
    - config.materialized
    - columns.symbol.description
    - columns.price.data_type
    - columns.date.data_type
