version: 2
models:

- name: contracts_AgentResultMapping_calls
  description: This model contains call data related to agent result mappings, including transaction details, contract addresses, and timestamps for analysis.
  columns:
  - name: transaction_hash
    description: Unique identifier of the transaction.
    data_type: String
  - name: block_number
    description: Block number in which the transaction was included.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp when the block was mined.
    data_type: DateTime64(0, 'UTC')
  - name: contract_address
    description: Address of the contract involved in the call.
    data_type: String
  - name: caller_address
    description: Address initiating the call.
    data_type: String
  - name: call_data
    description: Encoded data payload of the call.
    data_type: String
  - name: output_json_type
    description: Indicates if the output is in JSON format (true/false).
    data_type: UInt64
  - name: agent_result_mapping_id
    description: Unique identifier for the agent result mapping.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - agentresultmapping
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_AgentResultMapping_events
  description: This model processes agent result mapping events related to contracts, capturing event details, timestamps, and identifiers for analysis.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was recorded
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block, used to order logs
    data_type: UInt64
  - name: event_id
    description: Unique identifier for the event
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String
  - name: agent_result_id
    description: Identifier for the agent result associated with the event
    data_type: String
  - name: result_value
    description: Numeric value representing the result, in wei
    data_type: String
  - name: status_code
    description: Numeric status code indicating event status
    data_type: UInt64
  - name: event_type
    description: Type of the event, e.g., 'ResultMapped'
    data_type: String
  - name: created_at
    description: Timestamp when the record was created in the system
    data_type: DateTime
  - name: updated_at
    description: Timestamp when the record was last updated
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - agentresultmapping
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
