version: 2
models:

- name: contracts_AgentResultMapping_calls
  description: The `contracts_AgentResultMapping_calls` model captures and decodes call interactions related to a specific smart contract, facilitating analysis of transaction data and call behaviors for agent result mappings.
  columns:

  - name: transaction_hash
    description: Unique identifier of the transaction, used as primary key.
    data_type: String

  - name: block_number
    description: Block number in which the transaction was included.
    data_type: UInt64

  - name: block_timestamp
    description: Timestamp when the block was mined, in UTC.
    data_type: DateTime

  - name: contract_address
    description: Address of the contract involved in the call.
    data_type: String

  - name: caller_address
    description: Address of the caller initiating the transaction.
    data_type: String

  - name: output_json
    description: JSON output data from the call, containing detailed results.
    data_type: JSON

  - name: output_json_type
    description: Boolean indicating if output JSON is of a specific type.
    data_type: UInt64

  - name: start_blocktime
    description: Starting block timestamp for data extraction, in UTC.
    data_type: DateTime
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2025-06-30"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.367091'
    _generated_fields:
    - description
    - config.tags
    - config.materialized

- name: contracts_AgentResultMapping_events
  description: The contracts_AgentResultMapping_events model captures and processes blockchain event logs related to agent result mappings within smart contracts, enabling analysis of event occurrences and their associated data over time.
  columns:

  - name: block_timestamp
    description: The timestamp when the block was mined, in UTC.
    data_type: DateTime

  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64

  - name: log_index
    description: The index of the log within the block.
    data_type: UInt64

  - name: transaction_hash
    description: The hash of the transaction that generated the event.
    data_type: String

  - name: agent_result_mapping_id
    description: Unique identifier for the agent result mapping event.
    data_type: String

  - name: agent_address
    description: Address of the agent involved in the event.
    data_type: String

  - name: result_status
    description: Status of the result, e.g., 'success', 'failure'.
    data_type: String

  - name: result_value
    description: Numeric value associated with the result, in wei.
    data_type: String

  - name: event_data
    description: Additional event data in JSON format.
    data_type: JSON
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2025-06-10"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.367141'
    _generated_fields:
    - description
    - config.tags
    - config.materialized
