version: 2
models:

- name: contracts_AgentResultMapping_calls
  description: This model processes call data related to agent result mappings, including transaction details, contract addresses, timestamps, and output JSON data for analysis.
  columns:
  - name: transaction_hash
    description: Unique identifier for each transaction.
    data_type: String
  - name: block_timestamp
    description: Timestamp of the block containing the transaction, in UTC.
    data_type: DateTime
  - name: block_number
    description: Number of the block containing the transaction.
    data_type: UInt64
  - name: contract_address
    description: Address of the contract involved in the call.
    data_type: String
  - name: output_json
    description: JSON output data from the call, containing detailed results.
    data_type: JSON
  - name: output_json_type
    description: Indicator if the output JSON is of a specific type, boolean.
    data_type: String
  - name: agent_result_mapping_id
    description: Unique identifier for the agent result mapping, if applicable.
    data_type: String
  - name: call_data
    description: Raw call data captured during the transaction.
    data_type: String
  - name: output_data
    description: Processed output data from the call, in JSON format.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - agentresultmapping
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_AgentResultMapping_events
  description: This model captures event logs related to agent result mappings, including transaction details, block information, and event-specific data for analysis.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was logged, in UTC.
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block, used to order logs.
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String
  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: event_name
    description: Name of the event emitted.
    data_type: String
  - name: agent_result_id
    description: Unique identifier for the agent result, if applicable.
    data_type: String
  - name: result_status
    description: Status of the result, e.g., 'success', 'failure'.
    data_type: String
  - name: result_value
    description: Numeric value associated with the result, in wei.
    data_type: String
  - name: additional_data
    description: Additional event data in JSON format.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - agentresultmapping
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
