version: 2
models:

- name: contracts_AgentResultMapping_calls
  description: This model processes call data related to agent result mappings, capturing transaction details, contract addresses, timestamps, and output JSON data for analysis.
  columns:
  - name: transaction_hash
    description: Unique identifier for each transaction.
    data_type: String
  - name: block_number
    description: Block number in which the transaction was included.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp when the block was mined.
    data_type: DateTime64(0, 'UTC')
  - name: contract_address
    description: Address of the contract involved in the call.
    data_type: String
  - name: caller_address
    description: Address of the caller initiating the transaction.
    data_type: String
  - name: call_data
    description: Encoded call data payload.
    data_type: String
  - name: output_json
    description: JSON output of the call result.
    data_type: JSON
  - name: call_timestamp
    description: Timestamp when the call was executed.
    data_type: DateTime64(0, 'UTC')
  - name: output_json_type
    description: Indicator if output JSON is of a specific type.
    data_type: UInt64
  - name: incremental_column
    description: Column used for incremental processing, typically block timestamp.
    data_type: DateTime64(0, 'UTC')
  - name: start_blocktime
    description: Starting block timestamp for data processing.
    data_type: DateTime64(0, 'UTC')
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - agentresultmapping
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_AgentResultMapping_events
  description: This model processes agent result mapping events, capturing details about contract interactions, timestamps, and related identifiers for analysis of agent performance and event occurrences.
  columns:
  - name: block_timestamp
    description: Timestamp of the block in UTC when the event was recorded.
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block, used to order events.
    data_type: UInt64
  - name: contract_address
    description: Address of the contract involved in the event.
    data_type: String
  - name: agent_result_mapping_id
    description: Unique identifier for the agent result mapping event.
    data_type: String
  - name: agent_id
    description: Identifier of the agent associated with the event.
    data_type: String
  - name: result_code
    description: Numeric code representing the result status.
    data_type: UInt64
  - name: result_description
    description: Textual description of the result.
    data_type: String
  - name: event_timestamp
    description: Timestamp of when the event occurred, in UTC.
    data_type: DateTime
  - name: transaction_hash
    description: Hash of the transaction that triggered the event.
    data_type: String
  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  - name: event_data
    description: JSON object containing additional event details.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - agentresultmapping
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
