version: 2
models:
- name: execution_blocks_clients_daily
  description: Daily aggregates of execution block values by client.  Sums the `value` column from `execution_blocks_clients_version_daily` for each client on each day.
  columns:
  - name: date
    description: Date of the execution block.
    data_type: DATE
  - name: client
    description: Client associated with the execution block.
    data_type: VARCHAR
  - name: value
    description: Sum of values for the given client and date.
    data_type: FLOAT
- name: execution_blocks_clients_pct_daily
  description: Daily percentage of total execution block value for each client.  Calculated as the client's daily value divided by the total daily value across all clients.
  columns:
  - name: date
    description: Date of the execution block.
    data_type: DATE
  - name: client
    description: Address of the client.
    data_type: STRING
  - name: pct
    description: Percentage of total daily execution block value attributable to the client.
    data_type: FLOAT
