version: 2
models:
- name: execution_blocks_clients_pct_daily
  description: 'TODO: Add description for execution_blocks_clients_pct_daily'
  meta:
    sector: execution
    refs:
    - execution_blocks_clients_version_daily
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - blocks
    - metrics
  columns:
  - name: client
    description: 'TODO: Add description for client'
    data_tests:
    - not_null
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: value
    description: 'TODO: Add description for value'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - client
      - date
- name: execution_blocks_clients_daily
  description: 'TODO: Add description for execution_blocks_clients_daily'
  meta:
    sector: execution
    refs:
    - execution_blocks_clients_version_daily
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - blocks
    - metrics
  columns:
  - name: client
    description: 'TODO: Add description for client'
    data_tests:
    - not_null
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: value
    description: 'TODO: Add description for value'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - client
      - date
