version: 2
models:

- name: execution_blocks_clients_daily
  description: Aggregated daily data of execution blocks per client, including total value.
  columns:
  - name: date
    description: Date of the daily aggregation (UTC).
    data_type: DateTime
    tests:
    - not_null
  - name: client
    description: Client address involved in execution blocks.
    data_type: String
    tests:
    - not_null
  - name: value
    description: Sum of values (wei) for the client on the given date.
    data_type: UInt64
  config:
    access: public
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: execution_blocks_clients_pct_daily
  description: Business-facing metric representing the percentage of client activity within execution blocks on a daily basis.
  columns:
  - name: date
    description: Date of the observation in YYYY-MM-DD format.
    data_type: Date
    tests:
    - not_null
  - name: client
    description: Client identifier (e.g., address or unique client ID).
    data_type: String
    tests:
    - not_null
  - name: value
    description: Total number of activity units associated with the client on the given date.
    data_type: UInt64
  - name: pct
    description: Percentage of client activity relative to total activity on that date, rounded to four decimal places.
    data_type: Float64
  config:
    access: public
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
