#!/usr/bin/env python3
"""Generate the entity overlay from the entity dictionary.

Scans every project model's PHYSICAL columns (manifest + catalog merge)
against ``semantic/entity_dictionary.yml`` and writes two generated files:

* ``semantic/authoring/generated/entities_generated.yml`` — per-model entity
  annotations ``{model, entities: [{name, type, expr}]}``. Consumed by
  ``build_registry.load_generated_entities`` which merges them into the
  registry's ``entities`` field ONLY for models with no hand-authored
  semantic_model (hand-authored wins WHOLESALE — never a per-entity merge).
  Deliberately NOT named semantic_models.yml: the authoring loader is
  last-file-wins per model, which cannot express that precedence rule.
* ``semantic/relationships/entities_generated.yml`` — hub-and-spoke
  relationships (spoke -> hub, many_to_one, left join). Edges are
  ``quality_tier: approved`` only when BOTH endpoints are approved semantic
  models; everything else is ``candidate`` and listed in the report — approve
  the models, rerun, and the edges upgrade.

MULTI-BINDING: a model gets ONE annotation + ONE hub edge PER matching column
(not first-match-wins). A transfers model carrying ``from_address`` and
``to_address`` binds ``address`` twice, so the graph can join on either side.
Only the hub model's hub-key column is ``type: primary``; every other binding
is ``foreign``.

OVERRIDES: ``entity_dictionary.yml`` may carry a top-level ``overrides:`` list
of ``{model, column, entity}``. ``entity: <name>`` redirects that column to a
different entity on that model; ``entity: null`` suppresses it. A column lives
under exactly one entity globally; per-model exceptions live in overrides.

Skips (all listed in the review report):
* models whose hand-authored semantic_model declares ANY entity (hand wins
  wholesale for entities; an authored block WITHOUT entities still gets the
  generated overlay — the merge is entities-only, so nothing else is touched)
* internal-only / ``privacy:*``-tagged models and ``expose_to_mcp: false``
* raw sources (out of scope v1)

The generator is idempotent — it rewrites both files from scratch each run.
``--check`` re-generates in memory and exits 1 if the files on disk differ
(CI hook: catches hand-edits to generated files and stale overlays).
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.semantic.build_registry import (  # noqa: E402
    APPROVED_STATUSES,
    canonical_status,
    get_cerebro_meta,
    load_json,
    load_semantic_authoring,
    load_yaml_file,
    merge_column_info,
    semantic_authoring_roots,
)

GENERATED_HEADER = (
    "# generated by scripts/semantic/generate_entities.py — do not hand-edit\n"
)
ENTITIES_OUT = REPO_ROOT / "semantic" / "authoring" / "generated" / "entities_generated.yml"
RELATIONSHIPS_OUT = REPO_ROOT / "semantic" / "relationships" / "entities_generated.yml"
DICTIONARY_PATH = REPO_ROOT / "semantic" / "entity_dictionary.yml"

INTERNAL_TAGS = {"internal_only", "privacy:tier_internal"}


@dataclass
class Overrides:
    """Parsed per-(model, column) override directives.

    ``targets`` maps ``(model, column) -> entity|None`` (None = suppress) and
    is the exclusion lookup for a column's GLOBAL entity. ``forced`` maps
    ``(model, entity) -> [column, ...]`` in file order — the columns redirected
    or added TO that entity on that model. ``entries`` is the ordered raw list
    for the unmatched-override report.
    """

    targets: dict[tuple[str, str], Optional[str]] = field(default_factory=dict)
    forced: dict[tuple[str, str], list[str]] = field(default_factory=dict)
    entries: list[dict[str, Any]] = field(default_factory=list)


def parse_overrides(raw: list[dict[str, Any]], valid_entities: set[str]) -> Overrides:
    """Validate + index the raw ``overrides:`` list. Structural problems are
    fatal (SystemExit); model/column existence is checked later against the
    manifest (deferred to the report)."""
    ov = Overrides()
    for entry in raw or []:
        if not isinstance(entry, dict):
            raise SystemExit(f"entity_dictionary.yml overrides: entry is not a mapping: {entry!r}")
        model = entry.get("model")
        column = entry.get("column")
        if not model or not column:
            raise SystemExit(f"entity_dictionary.yml overrides: entry missing model/column: {entry!r}")
        if "entity" not in entry:
            raise SystemExit(
                f"entity_dictionary.yml overrides: {model}.{column} has no `entity` key "
                "(use `entity: null` to suppress)"
            )
        target = entry["entity"]
        if target is not None and target not in valid_entities:
            raise SystemExit(
                f"entity_dictionary.yml overrides: {model}.{column} -> unknown entity '{target}'"
            )
        key = (model, column)
        if key in ov.targets:
            raise SystemExit(f"entity_dictionary.yml overrides: duplicate (model, column) {key}")
        ov.targets[key] = target
        ov.entries.append({"model": model, "column": column, "entity": target})
        if target is not None:
            ov.forced.setdefault((model, target), []).append(column)
    return ov


def load_dictionary(path: Path = DICTIONARY_PATH) -> tuple[list[dict[str, Any]], Overrides]:
    """Load + validate the dictionary. Returns ``(entities, overrides)``."""
    payload = load_yaml_file(path)
    entries = payload.get("entities", []) or []
    seen: set[str] = set()
    for entry in entries:
        name = entry.get("entity", "")
        if not name:
            raise SystemExit("entity_dictionary.yml: entry without `entity` name")
        if name in seen:
            raise SystemExit(f"entity_dictionary.yml: duplicate entity '{name}'")
        seen.add(name)
        if entry.get("sensitivity") not in ("subject", "open"):
            raise SystemExit(
                f"entity_dictionary.yml: entity '{name}' needs sensitivity subject|open"
            )
        if not entry.get("columns"):
            raise SystemExit(f"entity_dictionary.yml: entity '{name}' has no columns")
    overrides = parse_overrides(payload.get("overrides", []) or [], seen)
    return entries, overrides


def _model_is_private(node: dict[str, Any]) -> tuple[bool, str]:
    tags = node.get("tags", []) or []
    meta = node.get("config", {}).get("meta") or node.get("meta") or {}
    if any(t in INTERNAL_TAGS for t in tags):
        return True, "internal_only tag"
    # Contract 0.7a: the generator never touches ANY privacy:*-tagged model —
    # broader than the registry's internal filter on purpose.
    privacy = [t for t in tags if str(t).startswith("privacy:")]
    if privacy:
        return True, f"privacy tag {privacy[0]}"
    if isinstance(meta, dict) and meta.get("expose_to_mcp") is False:
        return True, "expose_to_mcp: false"
    return False, ""


def _model_semantic_status(name: str, authored: dict[str, Any]) -> str:
    block = authored.get(name)
    if not block:
        return "docs_only"
    tier = canonical_status(get_cerebro_meta(block).get("quality_tier"))
    return "approved" if tier in APPROVED_STATUSES else "candidate"


def _effective_columns(
    model: str,
    entity: str,
    entry_columns: list[str],
    model_cols: set[str],
    overrides: Overrides,
) -> list[str]:
    """The columns that bind ``entity`` on ``model``: forced override columns
    (file order) first, then the entity's global columns present on the model
    that are NOT overridden away. Deduped, order-preserving; all must exist on
    the model."""
    out: list[str] = []
    forced = overrides.forced.get((model, entity), [])
    globals_ = [c for c in entry_columns if (model, c) not in overrides.targets]
    for col in list(forced) + globals_:
        if col in model_cols and col not in out:
            out.append(col)
    return out


def compute_overlay(
    manifest: dict[str, Any],
    catalog: dict[str, Any],
    dictionary: list[dict[str, Any]],
    overrides: Overrides,
    authored: dict[str, Any],
) -> dict[str, Any]:
    """Pure overlay core (no file I/O). Returns
    ``{annotations, relationships, report, dictionary, entity_models}``."""
    manifest_nodes = manifest.get("nodes", {})
    catalog_nodes = catalog.get("nodes", {})
    project_name = manifest.get("metadata", {}).get("project_name", "")

    report: dict[str, list] = defaultdict(list)
    # ── Pre-pass: per-model column sets + status (models only, non-private) ──
    model_cols: dict[str, set[str]] = {}
    model_status: dict[str, str] = {}
    for unique_id in sorted(manifest_nodes):
        node = manifest_nodes[unique_id]
        if node.get("resource_type") != "model":
            continue
        if project_name and node.get("package_name") not in ("", project_name):
            continue
        name = node["name"]
        private, why = _model_is_private(node)
        if private:
            report["skipped_private"].append((name, why))
            continue
        cols = merge_column_info(
            node.get("columns", {}) or {},
            catalog_nodes.get(unique_id, {}).get("columns", {}) or {},
        )
        model_cols[name] = set(cols)
        model_status[name] = _model_semantic_status(name, authored)

    def _has_hand_entities(model: str) -> bool:
        return bool((authored.get(model) or {}).get("entities"))

    # ── Pass A: hub keys (must resolve BEFORE annotations for primary-select) ──
    hub_col: dict[str, str] = {}
    for entry in dictionary:
        entity, hub = entry["entity"], entry.get("hub_model")
        if not hub:
            continue
        if hub not in model_cols:
            report["hub_missing"].append((entity, hub))
            continue
        eff = _effective_columns(hub, entity, entry["columns"], model_cols[hub], overrides)
        if not eff:
            report["hub_missing_key"].append((entity, hub, entry["columns"]))
            continue
        hub_col[entity] = eff[0]

    # ── Pass B: annotations (one binding per effective column) ──
    annotations: list[dict[str, Any]] = []
    entity_models: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for name in sorted(model_cols):
        cols = model_cols[name]
        hand = _has_hand_entities(name)
        declared = (
            {e.get("name") for e in (authored.get(name) or {}).get("entities") or []}
            if hand
            else set()
        )
        matched: list[dict[str, Any]] = []
        for entry in dictionary:
            entity = entry["entity"]
            eff = _effective_columns(name, entity, entry["columns"], cols, overrides)
            if not eff:
                continue
            if len(eff) > 1:
                report["multi_binding"].append((name, entity, eff))
            if hand:
                # Hand-authored entities win wholesale — no generated annotation.
                if entity not in declared:
                    report["suggest_hand_edit"].append((name, entity, eff))
                continue
            for col in eff:
                etype = (
                    "primary"
                    if entry.get("hub_model") == name and col == hub_col.get(entity)
                    else "foreign"
                )
                matched.append({"name": entity, "type": etype, "expr": col})
                entity_models[entity].append((name, col))
        if matched:
            annotations.append({"model": name, "entities": matched})

    # ── Pass C: edges (one per (spoke, column)) ──
    relationships: list[dict[str, Any]] = []
    edge_names: set[str] = set()
    for entry in dictionary:
        entity, hub = entry["entity"], entry.get("hub_model")
        if not hub or entity not in hub_col:
            continue
        key = hub_col[entity]
        hub_status = model_status.get(hub, "docs_only")
        for spoke, spoke_col in sorted(entity_models[entity]):
            if spoke == hub:
                continue
            both_approved = hub_status == "approved" and model_status.get(spoke) == "approved"
            tier = "approved" if both_approved else "candidate"
            if tier == "candidate":
                report["candidate_edges"].append((entity, spoke))
            edge_name = f"gen_{entity}__{spoke}__{spoke_col}__to__{hub}"
            if edge_name in edge_names:
                raise SystemExit(f"generate_entities: duplicate edge name {edge_name}")
            edge_names.add(edge_name)
            relationships.append(
                {
                    "name": edge_name,
                    "left_model": spoke,
                    "right_model": hub,
                    "left_keys": [spoke_col],
                    "right_keys": [key],
                    "cardinality": "many_to_one",
                    "join_semantics": "left",
                    "via_entity": entity,
                    "preferred_bridge": False,
                    "safe_for_dimension_enrichment": True,
                    "aggregate_then_join_only": False,
                    "allow_any_join": False,
                    "quality_tier": tier,
                }
            )

    # ── Override consumption / unmatched report ──
    for entry in overrides.entries:
        model, column = entry["model"], entry["column"]
        if model not in model_cols:
            report["override_unmatched"].append((model, column, "model missing/private"))
        elif column not in model_cols[model]:
            report["override_unmatched"].append((model, column, "column absent"))
        elif _has_hand_entities(model):
            report["override_on_hand_authored"].append((model, column))

    return {
        "annotations": annotations,
        "relationships": relationships,
        "report": report,
        "dictionary": dictionary,
        "entity_models": entity_models,
    }


def generate(target_dir: Path) -> dict[str, Any]:
    """Load artifacts + dictionary, then compute the overlay."""
    manifest, _ = load_json(target_dir / "manifest.json")
    catalog, _ = load_json(target_dir / "catalog.json")
    dictionary, overrides = load_dictionary()
    authored, _metrics = load_semantic_authoring(*semantic_authoring_roots(REPO_ROOT))
    return compute_overlay(manifest, catalog, dictionary, overrides, authored)


def render_entities_yaml(annotations: list[dict[str, Any]]) -> str:
    payload = {"version": 1, "generated_entities": annotations}
    return GENERATED_HEADER + yaml.safe_dump(payload, sort_keys=False, width=100)


def render_relationships_yaml(relationships: list[dict[str, Any]]) -> str:
    payload = {"version": 1, "relationships": relationships}
    return GENERATED_HEADER + yaml.safe_dump(payload, sort_keys=False, width=100)


def print_report(result: dict[str, Any]) -> None:
    report = result["report"]
    annotations = result["annotations"]
    relationships = result["relationships"]
    entity_models = result["entity_models"]

    print("── entity overlay review report ──")
    total_bindings = sum(len(a["entities"]) for a in annotations)
    print(f"models annotated: {len(annotations)}  bindings: {total_bindings}")
    for entry in result["dictionary"]:
        entity = entry["entity"]
        pairs = entity_models.get(entity, [])
        n_models = len({m for m, _ in pairs})
        hub = entry.get("hub_model") or "-"
        print(f"  {entity:20s} {n_models:4d} models / {len(pairs):4d} bindings  hub={hub}")
    approved_edges = sum(1 for r in relationships if r["quality_tier"] == "approved")
    candidate_edges = len(relationships) - approved_edges
    print(
        f"relationships: {len(relationships)} "
        f"({approved_edges} approved, {candidate_edges} candidate — "
        "candidate edges are runtime-invisible until both endpoint models are approved)"
    )
    for key, label in (
        ("skipped_private", "models skipped (privacy/internal)"),
        ("multi_binding", "models binding an entity on >1 column (multi-binding)"),
        ("suggest_hand_edit", "hand-authored models missing a dictionary entity (edit by hand)"),
        ("hub_missing", "dictionary hubs not found in manifest"),
        ("hub_missing_key", "hubs lacking the entity key column"),
        ("override_unmatched", "overrides whose model/column is missing"),
        ("override_on_hand_authored", "overrides on hand-authored models (ignored)"),
    ):
        rows = report.get(key, [])
        if rows:
            print(f"{label}: {len(rows)}")
            for row in rows[:12]:
                print(f"    {row}")
            if len(rows) > 12:
                print(f"    … +{len(rows) - 12} more")


def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target-dir", default=str(REPO_ROOT / "target"))
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and fail (exit 1) if files on disk differ",
    )
    return parser.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    args = parse_args(argv)
    result = generate(Path(args.target_dir))
    entities_text = render_entities_yaml(result["annotations"])
    relationships_text = render_relationships_yaml(result["relationships"])

    if args.check:
        stale = []
        for path, text in ((ENTITIES_OUT, entities_text), (RELATIONSHIPS_OUT, relationships_text)):
            on_disk = path.read_text(encoding="utf-8") if path.exists() else ""
            if not on_disk.startswith(GENERATED_HEADER):
                stale.append(f"{path}: missing generated header (hand-edited?)")
            elif on_disk != text:
                stale.append(f"{path}: differs from a fresh generation (stale or hand-edited)")
        if stale:
            for s in stale:
                print(f"generate-entities --check FAILED: {s}", file=sys.stderr)
            return 1
        print("generate-entities --check OK: generated files are fresh and unedited.")
        return 0

    ENTITIES_OUT.parent.mkdir(parents=True, exist_ok=True)
    ENTITIES_OUT.write_text(entities_text, encoding="utf-8")
    RELATIONSHIPS_OUT.write_text(relationships_text, encoding="utf-8")
    print(f"wrote {ENTITIES_OUT.relative_to(REPO_ROOT)}")
    print(f"wrote {RELATIONSHIPS_OUT.relative_to(REPO_ROOT)}")
    print_report(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
