version: 2
models:

- name: api_execution_circles_avatars
  description: View summarizing API execution circles and avatars data, including counts and totals for each date and avatar type.
  columns:
  - name: date
    description: Date of the data record (UTC).
    data_type: DateTime
  - name: avatar_type
    description: Type/category of avatar.
    data_type: String
  - name: cnt
    description: Count of occurrences for the avatar type on the given date.
    data_type: UInt64
  - name: total
    description: Total number of executions or relevant metric for the date.
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - circles
    - avatars
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_circles_backers_cnt_latest
  description: Business-facing metric representing the latest count of backers in execution circles, along with the percentage change compared to seven days prior.
  columns:
  - name: total
    description: Total number of backers in the latest execution circles.
    data_type: UInt64
  - name: change_pct
    description: Percentage change in backers compared to seven days ago, rounded to one decimal.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - backers
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_circles_groups_cnt_latest
  description: Business metric representing the latest count of execution circles for groups, along with the percentage change compared to the data from 7 days prior.
  columns:
  - name: total
    description: Total number of execution circles for groups in the latest data snapshot.
    data_type: UInt64
  - name: change_pct
    description: Percentage change in execution circles compared to 7 days ago, rounded to 1 decimal.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - groups
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_circles_humans_cnt_latest
  description: Business-facing metric representing the latest count of humans in execution circles, along with the percentage change compared to seven days prior.
  columns:
  - name: total
    description: Total number of humans in execution circles at the latest timestamp.
    data_type: UInt64
  - name: change_pct
    description: Percentage change in human count compared to seven days ago, rounded to one decimal.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - humans
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_circles_orgs_cnt_latest
  description: Business-facing metric representing the latest count of organizations involved in execution circles, along with the percentage change compared to data from 7 days prior.
  columns:
  - name: total
    description: Total count of organizations involved in execution circles at the latest timestamp.
    data_type: UInt64
  - name: change_pct
    description: Percentage change in organization count compared to data from 7 days ago, rounded to one decimal place.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - orgs
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_execution_circles_avatars
  description: A fact table aggregating execution data related to circles and avatars, including daily counts, totals, and related metrics for analysis.
  columns:
  - name: date
    description: The date of the record, representing the day for which metrics are aggregated.
    data_type: DateTime
  - name: avatar_type
    description: The type/category of avatar involved in the execution.
    data_type: String
  - name: cnt
    description: Count of executions for the given date and avatar type.
    data_type: UInt64
  - name: total
    description: Cumulative sum of counts over time per avatar type.
    data_type: UInt64
  - name: max_date
    description: The maximum date present in the dataset, used for reference.
    data_type: DateTime
  - name: min_date
    description: The minimum date present in the dataset, used for reference.
    data_type: DateTime
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - avatars
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_execution_circles_backing
  description: Aggregated data on execution circles backing, including date series, total counts, and cumulative sums for analysis.
  columns:
  - name: max_date
    description: Maximum date in the dataset, representing the latest date processed.
    data_type: DateTime
  - name: min_date
    description: Minimum date in the dataset, representing the earliest date processed.
    data_type: DateTime
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - circles
    - backing
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
