version: 2
models:

- name: api_execution_circles_avatars
  description: Provides aggregated data on avatar types and counts per date for execution circles, used for business analytics and reporting.
  columns:
  - name: date
    description: The date for which the data is aggregated, in UTC.
    data_type: DateTime
  - name: avatar_type
    description: Type/category of the avatar used in execution circles.
    data_type: String
  - name: cnt
    description: Count of avatars of the specified type on the given date.
    data_type: UInt64
  - name: total
    description: Total number of execution circle entries for the given date.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - avatars
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_circles_backers_cnt_latest
  description: Business-facing metric representing the latest count of backers in execution circles, along with the percentage change compared to the data from 7 days prior.
  columns:
  - name: total
    description: Total number of backers in the latest execution circles.
    data_type: UInt64
  - name: change_pct
    description: Percentage change in backers count compared to 7 days ago, rounded to 1 decimal.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - backers
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_circles_groups_cnt_latest
  description: Business-facing view summarizing the latest total count of execution circles and their change percentage over the past 7 days.
  columns:
  - name: total
    description: Total number of execution circles for the latest date.
    data_type: UInt64
  - name: change_pct
    description: Percentage change in total circles compared to 7 days prior, rounded to 1 decimal.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - groups
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_circles_humans_cnt_latest
  description: Business-facing model providing the latest count of humans and the percentage change compared to the data from 7 days prior, derived from execution data.
  columns:
  - name: total
    description: Total number of humans in the latest data snapshot.
    data_type: UInt64
  - name: change_pct
    description: Percentage change in human count compared to data from 7 days ago.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - humans
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_circles_orgs_cnt_latest
  description: Business-facing model providing the latest count of organizations involved in API executions, along with the percentage change over the previous 7 days.
  columns:
  - name: total
    description: Total number of organizations involved in API executions at the latest date.
    data_type: UInt64
  - name: change_pct
    description: Percentage change in organization count compared to 7 days prior, rounded to one decimal place.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - orgs
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: fct_execution_circles_avatars
  description: Aggregated data representing execution circles and avatars, including temporal series, counts, totals, and related metadata for business analysis.
  columns:
  - name: min_date
    description: Earliest date in the dataset.
    data_type: DateTime
  - name: max_date
    description: Latest date in the dataset.
    data_type: DateTime
  - name: date
    description: Date in 'YYYY-MM-DD' format.
    data_type: Date
  - name: avatar_type
    description: Type/category of avatar.
    data_type: String
  - name: cnt
    description: Count of avatars for given date and type.
    data_type: UInt64
  - name: total
    description: Cumulative sum of counts over time per avatar type.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - avatars
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_execution_circles_backing
  description: Aggregated data on execution circles backing, including date series, totals, and related metrics for analysis and reporting.
  columns:
  - name: min_date
    description: Earliest date in the dataset.
    data_type: DateTime
  - name: max_date
    description: Latest date in the dataset.
    data_type: DateTime
  - name: date
    description: Date in the series generated from min_date to max_date.
    data_type: DateTime
  - name: cnt
    description: Count of execution circles for the specific date.
    data_type: UInt64
  - name: total
    description: Cumulative total of execution circles up to the current date.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - backing
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
