version: 2
models:

- name: api_execution_circles_avatars
  description: The api_execution_circles_avatars view aggregates daily counts of avatar types used in API executions within circles, providing insights into avatar usage trends over time.
  columns:

  - name: date
    description: The specific date of the recorded avatar usage data.
    data_type: Date
    tests:
    - not_null

  - name: avatar_type
    description: The category or type of avatar used in API executions.
    data_type: String

  - name: cnt
    description: The number of occurrences for a specific avatar type on the given date.
    data_type: UInt64

  - name: total
    description: The total number of avatar usage events recorded on the given date.
    data_type: UInt64
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.652862'
    _generated_fields:
    - description
    - columns.date.description
    - columns.total.description
    - config.tags
    - config.materialized
    - columns.cnt.data_type
    - columns.total.data_type
    - columns.avatar_type.data_type
    - columns.avatar_type.description
    - columns.cnt.description
    - columns.date.data_type

- name: api_execution_circles_backers_cnt_latest
  description: This view provides the latest count of backers for API executions and the percentage change compared to the count from seven days prior, enabling trend analysis of backer engagement.
  columns:

  - name: total
    description: The total number of backers for API executions as of the most recent date or seven days prior, depending on the context.
    data_type: UInt64

  - name: change_pct
    description: Percentage change in backers count compared to 7 days ago, rounded to 1 decimal.
    data_type: Float64
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.652930'
    _generated_fields:
    - description
    - columns.total.description
    - config.tags
    - config.materialized
    - columns.total.data_type

- name: api_execution_circles_groups_cnt_latest
  description: This view provides the latest total count of group avatars and the percentage change compared to the count from seven days prior, enabling trend analysis of group activity.
  columns:

  - name: total
    description: The total number of group avatars at the latest date and seven days prior, representing counts in the respective periods.
    data_type: UInt64

  - name: change_pct
    description: Percentage change in total circles compared to 7 days prior, rounded to 1 decimal.
    data_type: Float64
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.652963'
    _generated_fields:
    - description
    - columns.total.description
    - config.tags
    - config.materialized
    - columns.total.data_type

- name: api_execution_circles_humans_cnt_latest
  description: This view provides the latest count of human avatars and the percentage change compared to the count from seven days prior, facilitating trend analysis of human avatar activity.
  columns:

  - name: total
    description: The total number of human avatars recorded at the specified date.
    data_type: UInt64

  - name: change_pct
    description: Percentage change in human count compared to data from 7 days ago.
    data_type: Float64
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.653005'
    _generated_fields:
    - description
    - columns.total.description
    - config.tags
    - config.materialized
    - columns.total.data_type

- name: api_execution_circles_orgs_cnt_latest
  description: This view provides the latest count of organization avatars and the percentage change compared to the count from seven days prior, supporting trend analysis of organizational activity.
  columns:

  - name: total
    description: The total number of organization avatars at the specified date, representing the count of organizations in the system.
    data_type: UInt64

  - name: change_pct
    description: Percentage change in organization count compared to 7 days prior, rounded to one decimal place.
    data_type: Float64
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.653039'
    _generated_fields:
    - description
    - columns.total.description
    - config.tags
    - config.materialized
    - columns.total.data_type

- name: fct_execution_circles_avatars
  description: The fct_execution_circles_avatars model provides a daily time series of avatar type counts within execution circles, enabling trend analysis and data completeness checks over a specified date range.
  columns:

  - name: min_date
    description: The earliest date present in the source data, indicating the start of the data range.
    data_type: Date

  - name: max_date
    description: The latest date present in the source data, indicating the end of the data range.
    data_type: Date

  - name: date
    description: Date in 'YYYY-MM-DD' format.
    data_type: Date

  - name: avatar_type
    description: Type/category of avatar.
    data_type: String

  - name: cnt
    description: Count of avatars for given date and type.
    data_type: UInt64

  - name: total
    description: Cumulative sum of counts over time per avatar type.
    data_type: UInt64
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.653084'
    _generated_fields:
    - description
    - columns.min_date.description
    - config.tags
    - config.materialized
    - columns.min_date.data_type
    - columns.max_date.description
    - columns.max_date.data_type

- name: fct_execution_circles_backing
  description: The fct_execution_circles_backing model provides a daily cumulative count of execution circle backing events, facilitating trend analysis over time.
  columns:

  - name: min_date
    description: The earliest date present in the backing events dataset.
    data_type: Date

  - name: max_date
    description: The latest date present in the backing events dataset.
    data_type: Date

  - name: date
    description: Date in the series generated from min_date to max_date.
    data_type: DateTime

  - name: cnt
    description: Count of execution circles for the specific date.
    data_type: UInt64

  - name: total
    description: Cumulative total of execution circles up to the current date.
    data_type: UInt64
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.653124'
    _generated_fields:
    - description
    - columns.min_date.description
    - config.tags
    - config.materialized
    - columns.min_date.data_type
    - columns.max_date.description
    - columns.max_date.data_type

