version: 2
models:

- name: api_execution_circles_avatars
  description: View summarizing API execution circles and avatars data, including counts and totals for each date and avatar type.
  columns:
  - name: date
    description: Date of the data record (UTC).
    data_type: DateTime
  - name: avatar_type
    description: Type/category of avatar.
    data_type: String
  - name: cnt
    description: Count of occurrences for the avatar type on the given date.
    data_type: UInt64
  - name: total
    description: Total number of executions or relevant metric for the date.
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - circles
    - avatars
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_circles_backers_cnt_latest
  description: Business-facing metric representing the latest count of backers in execution circles, along with the percentage change compared to 7 days prior.
  columns:
  - name: total
    description: Total number of backers in the latest execution circles.
    data_type: UInt64
  - name: change_pct
    description: Percentage change in backers compared to 7 days ago, rounded to one decimal place.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - backers
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_circles_groups_cnt_latest
  description: A model providing the latest count of execution circles and groups, along with the percentage change compared to data from 7 days prior.
  columns:
  - name: total
    description: Total number of execution circles/groups in the latest data snapshot.
    data_type: UInt64
  - name: change_pct
    description: Percentage change between latest total and total from 7 days prior, rounded to one decimal place.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - groups
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_circles_humans_cnt_latest
  description: Business-facing metric representing the latest count of humans in execution circles, along with the change percentage compared to 7 days prior.
  columns:
  - name: total
    description: Total number of humans in execution circles at the latest timestamp.
    data_type: UInt64
  - name: change_pct
    description: Percentage change in human count compared to 7 days ago, rounded to 1 decimal.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - humans
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_circles_orgs_cnt_latest
  description: Business-facing model providing the latest count of organizations involved in API executions and the percentage change compared to the data from 7 days prior.
  columns:
  - name: total
    description: Total number of organizations involved in API executions as of the latest date.
    data_type: UInt64
  - name: change_pct
    description: Percentage change in organization count compared to 7 days prior, rounded to 1 decimal.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - orgs
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_execution_circles_avatars
  description: Aggregated data for execution circles and avatars, including date series, avatar types, counts, totals, and related metrics for business analysis.
  columns:
  - name: min_date
    description: Earliest date in the dataset.
    data_type: DateTime
  - name: max_date
    description: Latest date in the dataset.
    data_type: DateTime
  - name: date
    description: Specific date in the series.
    data_type: DateTime
  - name: avatar_type
    description: Type/category of avatar.
    data_type: String
  - name: cnt
    description: Count of avatars for the given date and type.
    data_type: UInt64
  - name: total
    description: Cumulative sum of counts over time per avatar type.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - execution
    - circles
    - avatars
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_execution_circles_backing
  description: Aggregated data for execution circles backing, including date series, totals, and related metrics.
  columns:
  - name: min_date
    description: Earliest date in the dataset.
    data_type: DateTime
  - name: max_date
    description: Latest date in the dataset.
    data_type: DateTime
  - name: date
    description: Sequential date generated within the date range.
    data_type: DateTime
  - name: cnt
    description: Count of records for the specific date.
    data_type: UInt64
  - name: total
    description: Cumulative sum of `cnt` over ordered dates.
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - circles
    - backing
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
