version: 2
models:
- name: execution_txs_info_daily
  description: 'TODO: Add description for execution_txs_info_daily'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - transactions
    - metrics
  columns:
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: gas_price_avg
    description: 'TODO: Add description for gas_price_avg'
    data_tests:
    - not_null
  - name: gas_price_median
    description: 'TODO: Add description for gas_price_median'
    data_tests:
    - not_null
  - name: gas_used
    description: 'TODO: Add description for gas_used'
    data_tests:
    - not_null
  - name: n_txs
    description: 'TODO: Add description for n_txs'
    data_tests:
    - not_null
  - name: success
    description: 'TODO: Add description for success'
    data_tests:
    - not_null
  - name: transaction_type
    description: 'TODO: Add description for transaction_type'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - date
      - gas_price_avg
