version: 2
models:

- name: execution_txs_info_daily
  description: Business-facing summary of daily execution transactions, including counts, gas usage, and average/median gas prices, aggregated by date, transaction type, and success status.
  columns:
  - name: date
    description: Date representing the start of the day (UTC).
    data_type: DateTime
    tests:
    - not_null
  - name: transaction_type
    description: Type of transaction (e.g., legacy, EIP-1559).
    data_type: String
    tests:
    - not_null
  - name: success
    description: Transaction success status (1 = success, 0 = failure).
    data_type: UInt8
    tests:
    - not_null
  - name: n_txs
    description: Total number of transactions for the given grouping.
    data_type: UInt64
  - name: gas_used
    description: Total gas used by transactions (sum over group).
    data_type: UInt64
  - name: gas_price_avg
    description: Average gas price (wei) across transactions in the group.
    data_type: Int32
  - name: gas_price_median
    description: Median gas price (wei) across transactions in the group.
    data_type: Int32
  config:
    access: public
    materialized: table
    tags:
    - daily
    - execution
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
