version: 2
models:
- name: execution_txs_info_daily
  description: Daily aggregates of execution layer transaction information.  Provides counts, gas usage, and gas price statistics categorized by transaction type and success status.
  columns:
  - name: date
    description: Date of the transaction (start of day).
    data_type: DATE
  - name: transaction_type
    description: Type of transaction.
    data_type: STRING
  - name: success
    description: Boolean indicating transaction success.
    data_type: BOOLEAN
  - name: n_txs
    description: Number of transactions.
    data_type: INT
  - name: gas_used
    description: Total gas used.
    data_type: INT
  - name: gas_price_avg
    description: Average gas price.
    data_type: INT
  - name: gas_price_median
    description: Median gas price.
    data_type: INT
  tags:
  - execution
  - daily
  - aggregates
