version: 2
models:
- name: contracts_wxdai_events
  description: 'TODO: Add description for contracts_wxdai_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - tokens
  columns: []
- name: contracts_wxdai_calls
  description: 'TODO: Add description for contracts_wxdai_calls'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - tokens
  columns: []
