version: 2
models:
- name: wxdai_events
  description: 'TODO: Add description for wxdai_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - tokens
  columns: []
