version: 2
models:
- name: execution_state_size_diff
  description: This model calculates the difference in storage size for each address over time.  It sums the difference in storage values, considering a change to a zero value as a reduction in size.
  columns:
  - name: block_timestamp
    description: Timestamp of the block.
    data_type: timestamp
  - name: address
    description: Address involved in the storage change.
    data_type: string
  - name: bytes_diff
    description: Difference in storage size in bytes (positive for increase, negative for decrease).
    data_type: int
  tags:
  - execution
  - size
  - state
