version: 2
models:
- name: execution_state_size_diff
  description: 'TODO: Add description for execution_state_size_diff'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - state
    - transformations
  columns:
  - name: address
    description: 'TODO: Add description for address'
    data_tests:
    - not_null
  - name: block_timestamp
    description: 'TODO: Add description for block_timestamp'
    data_tests:
    - not_null
  - name: bytes_diff
    description: 'TODO: Add description for bytes_diff'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - address
      - block_timestamp
