version: 2
models:

- name: esg_consensus_power
  description: Provides consensus power data with client types and mean values for analysis.
  columns:
  - name: type
    description: The type of power consensus, e.g., 4, 5, 6.
    data_type: UInt64
    tests:
    - not_null
  - name: client
    description: The client name, e.g., Lighthouse, Teku, Lodestar, Nimbus, Prysm.
    data_type: String
    tests:
    - not_null
  - name: mean
    description: The mean value of power consensus in floating point units.
    data_type: Float64
    tests:
    - not_null
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: esg_country_power_consumption
  description: Aggregated power consumption data by country, combining consensus and execution power metrics along with client-specific estimates.
  columns:
  - name: date
    description: Date of the power consumption record
    data_type: DateTime
    tests:
    - not_null
  - name: country
    description: Country code or name
    data_type: String
    tests:
    - not_null
  - name: power
    description: Estimated power consumption in units consistent with source data
    data_type: Float64
  - name: mean
    description: Calculated mean power value based on client and configuration data
    data_type: Float64
  - name: client
    description: Client identifier associated with power metrics
    data_type: String
  - name: type
    description: Power type category (e.g., consensus, execution, idle)
    data_type: String
  config:
    materialized: table
    access: public
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: esg_execution_power
  description: A model representing execution power metrics categorized by type and client, with mean values.
  columns:
  - name: type
    description: The type of execution, represented as an integer.
    data_type: UInt64
    tests:
    - not_null
  - name: client
    description: The client name, such as 'Erigon' or 'Nethermind'.
    data_type: String
    tests:
    - not_null
  - name: mean
    description: The average execution power value, in floating point units.
    data_type: Float64
    tests:
    - not_null
  config:
    access: public
    materialized: view
    tags:
    - metrics
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: esg_hardware_config
  description: Hardware configuration details including type, CPU, cores/threads, architecture, RAM, storage, GPU, PSU, case, and OS.
  columns:
  - name: architecture
    description: CPU architecture type, e.g., x86/x64.
    data_type: String
    tests:
    - not_null
  - name: os
    description: Operating system installed, e.g., Ubuntu 20.04.
    data_type: String
    tests:
    - not_null
  - name: ram
    description: RAM size in GB, e.g., 16 GB, 64 GB, 256 GB.
    data_type: String
    tests:
    - not_null
  - name: storage
    description: Storage capacity, e.g., 2 TB SSD.
    data_type: String
    tests:
    - not_null
  - name: type
    description: Hardware type identifier, e.g., 4, 5, 6.
    data_type: UInt64
    tests:
    - not_null
    - unique
  - name: cpu
    description: CPU model, e.g., Intel i5-1135G7.
    data_type: String
    tests:
    - not_null
  - name: cores_threads
    description: Cores and threads, e.g., 4/8, 6/12, 32/64.
    data_type: String
    tests:
    - not_null
  - name: psu
    description: Power supply wattage, e.g., 65 Watt, 650 Watt.
    data_type: String
    tests:
    - not_null
  - name: case
    description: Case type, e.g., Integrated, Custom.
    data_type: String
    tests:
    - not_null
  - name: gpu
    description: GPU model, e.g., Onboard, AM 6970.
    data_type: String
    tests:
    - not_null
  config:
    access: public
    materialized: view
    tags:
    - hardware
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: esg_idle_electric_power
  description: Model representing average idle electric power metrics categorized by type.
  columns:
  - name: type
    description: Power type categories (e.g., 4, 5, 6)
    data_type: UInt64
    tests:
    - not_null
  - name: mean
    description: Average idle electric power in units consistent with source (e.g., kWh)
    data_type: Float64
    tests:
    - not_null
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: esg_node_distribution
  description: Provides the distribution of node types with their associated proportions.
  columns:
  - name: type
    description: Node type identifier (e.g., 4, 5, 6)
    data_type: UInt64
    tests:
    - not_null
    - unique
  - name: distribution
    description: Proportion of nodes for each type (values between 0 and 1)
    data_type: Float64
    tests:
    - not_null
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: int_esg_country_power_consumption
  description: Business-facing model aggregating power consumption data by country and client, based on multiple source tables and calculations.
  columns:
  - name: date
    description: The date of the power consumption record.
    data_type: DateTime
  - name: country
    description: The country code or name associated with the record.
    data_type: String
  - name: client
    description: The client identifier, e.g., consensus or execution client.
    data_type: String
  - name: type
    description: The type of power measurement or power source.
    data_type: String
  - name: mean
    description: The average power consumption value in wei.
    data_type: UInt64
  config:
    access: public
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
