version: 2
models:

- name: stg_crawlers_data__dune_labels
  description: (helpful, business-facing; use a folded block scalar `>`; no blank lines)
  columns:
  - name: label
    description: concise
    data_type: String
  - name: address
    description: concise
    data_type: String
  - name: introduced_at
    description: concise
    data_type: String
  config:
    access: public
  meta:
    owner: null
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__dune_prices
  description: Raw data from the Dune crawler including prices for XDAI and DAI tokens.
  columns:
  - name: symbol
    description: Symbol of the token.
    data_type: String
  - name: price_date
    description: Date for the price data.
    data_type: DateTime
    tests:
    - not_null
  - name: price_xdai
    description: Price of the token in XDAI.
    data_type: Float64
    tests:
    - not_null
  - name: price_dai
    description: Price of the token in DAI.
    data_type: Float64
    tests:
    - not_null
  - name: price_usd
    description: Price of the token in USD.
    data_type: Float64
    tests:
    - not_null
  config:
    access: public
  meta:
    owner: analytics
    authoritative: false
    generated_by: schema-writer
