version: 2
models:

- name: stg_crawlers_data__dune_labels
  description: (helpful, business-facing; use a folded block scalar `>`; no blank lines)
  columns:
  - name: label
    description: concise
    data_type: String
  - name: address
    description: concise
    data_type: String
  - name: introduced_at
    description: concise
    data_type: String
  - name: label_raw
    description: concise
    data_type: String
  config:
    access: public
  meta:
    owner: null
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__dune_prices
  description: Daily token prices per symbol from the Dune crawler (generic per-token table).
  columns:
    - name: date
      description: Date (UTC) for the price snapshot.
      data_type: Date
      tests:
        - not_null
    - name: symbol
      description: Uppercased token symbol.
      data_type: String
      tests:
        - not_null
    - name: price
      description: Latest observed price for the token on that day.
      data_type: Float64
      tests:
        - not_null
  tests:
    - dbt_utils.unique_combination_of_columns:
        combination_of_columns: [date, symbol]
  config:
    access: public
  meta:
    owner: analytics
    authoritative: false
    generated_by: schema-writer
