version: 2
models:

- name: stg_crawlers_data__dune_labels
  description: Staging model for Dune labels, processing raw label data, normalizing, and categorizing labels into known projects or generic ERC20 tokens.
  columns:
  - name: address
    description: Ethereum address in lowercase, used as primary key for labels.
    data_type: String
  - name: label_raw
    description: Original label string extracted from source, before normalization.
    data_type: String
  - name: introduced_at
    description: Timestamp when the label was introduced, in UTC.
    data_type: DateTime
  - name: s1
    description: Label after removing whitespace around delimiters.
    data_type: String
  - name: s2
    description: Label after removing token tail patterns.
    data_type: String
  - name: s3
    description: Label trimmed to the main part before suffixes.
    data_type: String
  - name: s4
    description: Label after removing version indicators and suffixes.
    data_type: String
  - name: s4_l
    description: Lowercase version of s4 for pattern matching.
    data_type: String
  - name: looks_like_token_tail
    description: Boolean indicating if label resembles a token tail pattern.
    data_type: UInt64
  - name: wl_symbol
    description: Whitelisted symbol associated with the address, if available.
    data_type: String
  - name: s5
    description: Label after categorizing into known project types based on s4_l.
    data_type: String
  - name: s7
    description: Label after cleaning and removing known suffixes or patterns.
    data_type: String
  - name: project_canon
    description: Canonical project name after mapping various label patterns to known categories.
    data_type: String
  - name: project
    description: Final project classification, defaulting to 'ERC20' if label resembles a token.
    data_type: String
  - name: project_raw
    description: Raw project label before final classification.
    data_type: String
  - name: label
    description: Final label used for referencing the project, same as project_raw.
    data_type: String
  config:
    materialized: view
    access: public
    tags:
    - staging
    - crawlers_data
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__dune_prices
  description: Staging model for Dune prices data, providing daily aggregated prices with symbol normalization.
  columns:
  - name: date
    description: The date of the price, truncated to day in UTC.
    data_type: DateTime
  - name: symbol
    description: The uppercase symbol of the asset.
    data_type: String
  - name: price
    description: The last known price in float64.
    data_type: Float64
  config:
    materialized: view
    access: public
    tags:
    - staging
    - crawlers_data
  meta:
    owner: data-team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__dune_gno_supply
  description: Staging model for GNO supply data from Dune crawlers; includes label, block date, and supply figures.
  columns:
  - name: label
    description: Identifier label for the supply data
    data_type: String
  - name: block_date
    description: Date of the block in ISO format (UTC)
    data_type: DateTime
  - name: supply
    description: Supply amount in GNO
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - staging
    - crawlers_data
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__dune_bridge_flows
  description: >
    Ledger of bridge transfers (from Dune MV) loaded into ClickHouse and exposed
    as a staging view. One row ≈ one flow between source_chain and dest_chain via a bridge.
  columns:
    - name: timestamp
      description: UTC timestamp of the flow.
      data_type: DateTime
      tests:
        - not_null
    - name: bridge
      description: Bridge name/identifier.
      data_type: String
      tests:
        - not_null
    - name: source_chain
      description: Origin chain name.
      data_type: String
      tests:
        - not_null
    - name: dest_chain
      description: Destination chain name.
      data_type: String
      tests:
        - not_null
    - name: token
      description: Token symbol involved in the transfer.
      data_type: String
      tests:
        - not_null
    - name: amount_token
      description: Amount of tokens transferred (native token units).
      data_type: Float64
    - name: amount_usd
      description: USD value of the transfer at the time recorded.
      data_type: Float64
    - name: direction
      description: >
        Flow direction relative to Gnosis:
        'in'  if dest_chain = 'Gnosis',
        'out' if source_chain = 'Gnosis',
        else 'xchain'.
      data_type: String
    - name: net_usd
      description: Signed USD flow relative to Gnosis (in = +amount_usd, out = -amount_usd, xchain = 0).
      data_type: Float64
  config:
    access: public
  meta:
    owner: analytics
    authoritative: false
    generated_by: schema-writer
