version: 2
models:
  - name: stg_crawlers_data__dune_labels
    description: Latest label per address from playground_max.dune_labels (normalized lowercase 0x-prefixed).
    columns:
      - name: address
        description: Lowercased 0x-prefixed address.
        data_type: String
      - name: project
        description: Latest label for the address.
        data_type: String
      - name: introduced_at
        description: Timestamp of the latest label seen for the address.
        data_type: DateTime
    config:
      access: public
      materialized: view
      tags: [staging, crawlers_data]

  - name: stg_crawlers_data__dune_prices
    description: Daily xDAI/DAI prices with a convenience price_usd column (prefers XDAI, falls back to DAI≈1.0).
    columns:
      - name: price_date
        description: Price day (UTC).
        data_type: Date
      - name: price_xdai
        description: USD price for XDAI if available.
        data_type: Float64
      - name: price_dai
        description: USD price for DAI if available.
        data_type: Float64
      - name: price_usd
        description: Preferred daily USD price used for fee conversion.
        data_type: Float64
    config:
      access: public
      materialized: view
      tags: [staging, crawlers_data]