version: 2
models:

- name: stg_crawlers_data__dune_labels
  description: Staging model that processes and cleans Dune labels data, extracting labels, timestamps, and categorizing projects based on label patterns.
  columns:
  - name: address
    description: Lowercased blockchain address associated with the label.
    data_type: String
  - name: label_raw
    description: Raw label string extracted from the source data.
    data_type: String
  - name: introduced_at
    description: Timestamp indicating when the label was introduced.
    data_type: DateTime
  - name: s1
    description: Label after trimming and replacing specific characters.
    data_type: String
  - name: s2
    description: Label after removing address hashes and suffixes.
    data_type: String
  - name: s3
    description: Label truncated to the main part before versioning or suffixes.
    data_type: String
  - name: s4
    description: Label after removing version indicators and suffixes.
    data_type: String
  - name: s4_l
    description: Lowercase version of s4 for pattern matching.
    data_type: String
  - name: looks_like_token_tail
    description: Boolean indicating if label resembles a token address tail.
    data_type: UInt64
  - name: symbol
    description: Token symbol from whitelist, if available.
    data_type: String
  - name: wl_symbol
    description: Whitelisted symbol associated with the address.
    data_type: String
  - name: s5
    description: Label after categorization into project types.
    data_type: String
  - name: s7
    description: Label after cleaning and removing known suffixes or patterns.
    data_type: String
  - name: project_canon
    description: Canonical project name based on label patterns and known mappings.
    data_type: String
  - name: project
    description: Final project categorization, defaulting to 'ERC20' if label resembles an address.
    data_type: String
  - name: project_raw
    description: Raw project label before final categorization.
    data_type: String
  config:
    access: public
    materialized: view
    tags:
    - staging
    - crawlers_data
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__dune_prices
  description: Staging model for Dune prices data, providing daily aggregated prices with symbol normalization.
  columns:
  - name: date
    description: The date of the price, truncated to day in UTC.
    data_type: DateTime
  - name: symbol
    description: The uppercase symbol of the asset.
    data_type: String
  - name: price
    description: The last known price in float64.
    data_type: Float64
  config:
    materialized: view
    access: public
    tags:
    - staging
    - crawlers_data
  meta:
    owner: data-team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__dune_bridge_flows
  description: >
    Ledger of bridge transfers (from Dune MV) loaded into ClickHouse and exposed
    as a staging view. One row ≈ one flow between source_chain and dest_chain via a bridge.
  columns:
    - name: timestamp
      description: UTC timestamp of the flow.
      data_type: DateTime
      tests:
        - not_null
    - name: bridge
      description: Bridge name/identifier.
      data_type: String
      tests:
        - not_null
    - name: source_chain
      description: Origin chain name.
      data_type: String
      tests:
        - not_null
    - name: dest_chain
      description: Destination chain name.
      data_type: String
      tests:
        - not_null
    - name: token
      description: Token symbol involved in the transfer.
      data_type: String
      tests:
        - not_null
    - name: amount_token
      description: Amount of tokens transferred (native token units).
      data_type: Float64
    - name: amount_usd
      description: USD value of the transfer at the time recorded.
      data_type: Float64
    - name: direction
      description: >
        Flow direction relative to Gnosis:
        'in'  if dest_chain = 'Gnosis',
        'out' if source_chain = 'Gnosis',
        else 'xchain'.
      data_type: String
    - name: net_usd
      description: Signed USD flow relative to Gnosis (in = +amount_usd, out = -amount_usd, xchain = 0).
      data_type: Float64
  config:
    access: public
  meta:
    owner: analytics
    authoritative: false
    generated_by: schema-writer
