version: 2
models:
- name: probelab_peers_clients_daily
  description: 'TODO: Add description for probelab_peers_clients_daily'
  meta:
    sector: probelab
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - probelab
  columns:
  - name: client
    description: 'TODO: Add description for client'
    data_tests:
    - not_null
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: value
    description: 'TODO: Add description for value'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - client
      - date
- name: probelab_peers_clients_country_daily
  description: 'TODO: Add description for probelab_peers_clients_country_daily'
  meta:
    sector: probelab
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - probelab
  columns:
  - name: client
    description: 'TODO: Add description for client'
    data_tests:
    - not_null
  - name: country
    description: 'TODO: Add description for country'
    data_tests:
    - not_null
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: value
    description: 'TODO: Add description for value'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - client
      - country
- name: probelab_peers_clients_version_daily
  description: 'TODO: Add description for probelab_peers_clients_version_daily'
  meta:
    sector: probelab
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - probelab
  columns:
  - name: client
    description: 'TODO: Add description for client'
    data_tests:
    - not_null
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: value
    description: 'TODO: Add description for value'
    data_tests:
    - not_null
  - name: version
    description: 'TODO: Add description for version'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - client
      - date
- name: probelab_peers_clients_cloud_daily
  description: 'TODO: Add description for probelab_peers_clients_cloud_daily'
  meta:
    sector: probelab
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - probelab
  columns:
  - name: client
    description: 'TODO: Add description for client'
    data_tests:
    - not_null
  - name: cloud
    description: 'TODO: Add description for cloud'
    data_tests:
    - not_null
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: value
    description: 'TODO: Add description for value'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - client
      - cloud
- name: probelab_peers_clients_quic_daily
  description: 'TODO: Add description for probelab_peers_clients_quic_daily'
  meta:
    sector: probelab
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - probelab
  columns:
  - name: client
    description: 'TODO: Add description for client'
    data_tests:
    - not_null
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: quic
    description: 'TODO: Add description for quic'
    data_tests:
    - not_null
  - name: value
    description: 'TODO: Add description for value'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - client
      - date
