version: 2
models:
- name: contracts_circles_v1_Hub_events
  description: 'TODO: Add description for contracts_circles_v1_Hub_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - Circles
  columns: []
- name: contracts_circles_v2_NameRegistry_events
  description: 'TODO: Add description for contracts_circles_v2_NameRegistry_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - Circles
  columns: []
- name: contracts_circles_v2_Hub_events
  description: 'TODO: Add description for contracts_circles_v2_Hub_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - Circles
  columns: []
