version: 2
models:

- name: contracts_circles_v1_Hub_events
  description: This model aggregates hub event data related to contracts, including timestamps, addresses, and event details for analysis and reporting.
  columns:
  - name: block_timestamp
    description: The timestamp when the block containing the event was mined (UTC).
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block (sequential, starting at 0).
    data_type: UInt64
  - name: transaction_hash
    description: The hash identifying the transaction that emitted the event.
    data_type: String
  - name: contract_address
    description: The address of the contract emitting the event.
    data_type: String
  - name: event_name
    description: The name of the event emitted.
    data_type: String
  - name: event_data
    description: The JSON payload containing event-specific data.
    data_type: JSON
  - name: sender_address
    description: The address initiating the transaction or event sender.
    data_type: String
  - name: recipient_address
    description: The address receiving tokens or assets, if applicable.
    data_type: String
  - name: amount
    description: The amount transferred, in wei or relevant units.
    data_type: String
  - name: block_number
    description: The block number in which the event was included.
    data_type: UInt64
  - name: created_at
    description: Timestamp when the record was created in the database.
    data_type: DateTime
  - name: updated_at
    description: Timestamp when the record was last updated.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - hub_events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_circles_v2_Hub_events
  description: This model captures hub events related to contracts, including transaction details, event types, and associated metadata for analysis and reporting.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was recorded
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block (sequence number)
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction associated with the event
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String
  - name: event_type
    description: Type of the event emitted
    data_type: String
  - name: event_data
    description: JSON payload containing event-specific data
    data_type: JSON
  - name: sender_address
    description: Address of the sender initiating the transaction
    data_type: String
  - name: recipient_address
    description: Address of the recipient, if applicable
    data_type: String
  - name: amount_wei
    description: Amount transferred in wei; may overflow 64-bit, stored as String if necessary
    data_type: String
  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64
  - name: created_at
    description: Timestamp when the record was created in the database
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - hub_events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_circles_v2_NameRegistry_events
  description: Events emitted by the NameRegistry contract, capturing registration, renewal, and transfer activities related to domain names and addresses.
  columns:
  - name: block_timestamp
    description: Timestamp of the event block in UTC
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction that emitted the event
    data_type: String
  - name: event_type
    description: Type of the event (e.g., Registration, Renewal, Transfer)
    data_type: String
  - name: name
    description: Domain name involved in the event
    data_type: String
  - name: owner_address
    description: Address of the current owner in hexadecimal format
    data_type: String
  - name: registrant_address
    description: Address of the registrant in hexadecimal format
    data_type: String
  - name: registration_expiry
    description: Expiry timestamp of the registration in UTC
    data_type: DateTime
  - name: transfer_from
    description: Previous owner address in transfer events
    data_type: String
  - name: transfer_to
    description: New owner address in transfer events
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - contracts
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
