version: 2
models:

- name: contracts_circles_v1_Hub_events
  description: This model captures event data related to contracts and circles, including timestamps, identifiers, and transaction details for analysis and reporting.
  columns:
  - name: block_timestamp
    description: Timestamp of the block in UTC.
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash of the transaction.
    data_type: String
  - name: contract_address
    description: Address of the contract involved, in hexadecimal.
    data_type: String
  - name: circle_id
    description: Identifier for the circle, if applicable.
    data_type: String
  - name: event_type
    description: Type of event emitted.
    data_type: String
  - name: event_data
    description: JSON object containing event-specific data.
    data_type: JSON
  - name: created_at
    description: Record creation timestamp in UTC.
    data_type: DateTime
  - name: updated_at
    description: Record last update timestamp in UTC.
    data_type: DateTime
  config:
    access: public
    tags:
    - production
    - contracts
    - circles
    - events
    materialized: incremental
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_circles_v2_Hub_events
  description: This model captures event data related to contract circles, including timestamps, identifiers, and event-specific details for analysis and reporting.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was recorded.
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block, used to order events.
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction associated with the event.
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: circle_id
    description: Unique identifier for the circle related to the event.
    data_type: String
  - name: event_type
    description: Type of the event (e.g., 'created', 'updated', 'deleted').
    data_type: String
  - name: event_payload
    description: JSON object containing event-specific data.
    data_type: JSON
  - name: created_at
    description: Timestamp when the record was created in the system.
    data_type: DateTime
  - name: updated_at
    description: Timestamp when the record was last updated.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - circles
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_circles_v2_NameRegistry_events
  description: This model captures NameRegistry events related to contracts and circles, including event details, addresses, and timestamps for analysis.
  columns:
  - name: event_id
    description: Unique identifier for each event record.
    data_type: String
  - name: contract_address
    description: Address of the contract involved in the event.
    data_type: String
  - name: circle_id
    description: Identifier for the circle associated with the event.
    data_type: String
  - name: event_type
    description: Type of the event (e.g., registration, update).
    data_type: String
  - name: event_timestamp
    description: Timestamp when the event occurred, in UTC.
    data_type: DateTime
  - name: block_number
    description: Blockchain block number at which the event was recorded.
    data_type: UInt64
  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String
  - name: sender_address
    description: Address of the sender involved in the event.
    data_type: String
  - name: recipient_address
    description: Address of the recipient involved in the event.
    data_type: String
  - name: event_data
    description: Raw JSON data associated with the event.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - circles
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_circles_v2_CirclesBackingFactory_events
  description: This model captures events emitted by the CirclesBackingFactory contract, including transaction details and event-specific data relevant for analysis.
  columns:
  - name: block_timestamp
    description: The timestamp when the block containing the event was mined.
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block, used to order events.
    data_type: UInt64
  - name: transaction_hash
    description: The hash of the transaction that emitted the event.
    data_type: String
  - name: event_type
    description: The type of event emitted by the CirclesBackingFactory.
    data_type: String
  - name: circle_id
    description: Identifier of the circle associated with the event.
    data_type: String
  - name: backing_amount
    description: The amount backing the circle, in wei.
    data_type: String
  - name: backing_token
    description: The token used for backing, typically an address.
    data_type: String
  - name: sender
    description: Address of the entity that initiated the event.
    data_type: String
  - name: recipient
    description: Address of the recipient involved in the event.
    data_type: String
  - name: event_timestamp
    description: The timestamp when the event was emitted.
    data_type: DateTime
  config:
    access: public
    tags:
    - production
    - contracts
    - circles
    - events
    materialized: incremental
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
