version: 2
models:

- name: contracts_circles_v1_Hub_events
  description: This model captures hub events related to contracts, including timestamps, addresses, and event-specific data for analytics and reporting purposes.
  columns:
  - name: block_timestamp
    description: The timestamp when the block containing the event was mined.
    data_type: DateTime
    tests:
    - not_null
  - name: log_index
    description: The index of the log within the block, indicating order.
    data_type: UInt64
    tests:
    - not_null
  - name: contract_address
    description: The address of the contract emitting the event.
    data_type: String
    tests:
    - not_null
  - name: event_name
    description: The name of the event emitted.
    data_type: String
  - name: event_data
    description: The JSON payload containing event-specific data.
    data_type: JSON
  - name: transaction_hash
    description: The hash of the transaction that included the event.
    data_type: String
  - name: sender_address
    description: The address initiating the transaction.
    data_type: String
  - name: recipient_address
    description: The address receiving tokens or assets, if applicable.
    data_type: String
  - name: amount
    description: The amount transferred, in wei or relevant units.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - contracts
    - hub_events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_circles_v2_Hub_events
  description: This model captures hub events related to contracts, including transaction details, event types, and associated metadata for analysis and reporting.
  columns:
  - name: block_timestamp
    description: The timestamp when the block containing the event was mined, in UTC.
    data_type: DateTime
    tests:
    - not_null
  - name: log_index
    description: The index of the log within the block, used to order events.
    data_type: UInt64
    tests:
    - not_null
  - name: transaction_hash
    description: The hash of the transaction that emitted the event.
    data_type: String
    tests:
    - not_null
    - unique
  - name: contract_address
    description: The address of the contract emitting the event.
    data_type: String
    tests:
    - not_null
  - name: event_type
    description: The type of the event emitted, indicating its purpose or category.
    data_type: String
  - name: circle_id
    description: Unique identifier for the circle associated with the event.
    data_type: String
  - name: circle_name
    description: Human-readable name of the circle.
    data_type: String
  - name: event_data
    description: JSON object containing additional event-specific data.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - hub_events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_circles_v2_NameRegistry_events
  description: Events emitted by the NameRegistry contract, capturing registration and update activities.
  columns:
  - name: block_timestamp
    description: The timestamp when the event was recorded on the blockchain.
    data_type: DateTime
    tests:
    - not_null
  - name: log_index
    description: The index of the log within the block, used to order events.
    data_type: UInt64
    tests:
    - not_null
  - name: transaction_hash
    description: The hash of the transaction that emitted the event.
    data_type: String
    tests:
    - not_null
    - unique
  - name: event_type
    description: Type of event, e.g., 'Registered', 'Updated'.
    data_type: String
  - name: name
    description: The registered name associated with the event.
    data_type: String
  - name: owner_address
    description: Blockchain address of the owner involved in the event.
    data_type: String
  - name: registration_date
    description: Date when the name was registered or last updated.
    data_type: DateTime
  - name: expires_at
    description: Expiration date of the registration, if applicable.
    data_type: DateTime
  - name: block_number
    description: The block number in which the event was included.
    data_type: UInt64
  - name: event_data
    description: Raw JSON data of the event payload.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - contracts
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
