version: 2
models:

- name: contracts_circles_v1_Hub_events
  description: This model captures event data related to contracts circles, including timestamps, identifiers, and related metadata for analysis and reporting.
  columns:
  - name: block_timestamp
    description: The timestamp when the block was mined, in UTC.
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block, used to order logs.
    data_type: UInt64
  - name: transaction_hash
    description: The hash of the transaction that generated the event.
    data_type: String
  - name: contract_address
    description: The address of the contract emitting the event.
    data_type: String
  - name: event_name
    description: The name of the event emitted.
    data_type: String
  - name: event_data
    description: The JSON payload of the event data.
    data_type: JSON
  - name: sender_address
    description: The address of the sender involved in the event.
    data_type: String
  - name: recipient_address
    description: The address of the recipient involved in the event.
    data_type: String
  - name: value
    description: The amount transferred in wei.
    data_type: UInt64
  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64
  - name: event_timestamp
    description: The timestamp when the event was emitted, in UTC.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - circles
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_circles_v2_Hub_events
  description: This model captures event data related to contract circles, including timestamps, identifiers, and event-specific details for analysis and reporting.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was recorded
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction associated with the event
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String
  - name: circle_id
    description: Unique identifier for the circle
    data_type: String
  - name: event_type
    description: Type of the event emitted
    data_type: String
  - name: event_data
    description: JSON containing event-specific data
    data_type: JSON
  - name: created_at
    description: Timestamp when the record was created in the system
    data_type: DateTime
  - name: updated_at
    description: Timestamp when the record was last updated
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - circles
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_circles_v2_NameRegistry_events
  description: Events emitted by the NameRegistry contract, including details such as transaction hash, block number, and event-specific data.
  columns:
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String
  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp when the block was mined.
    data_type: DateTime64(0, 'UTC')
  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64
  - name: event_name
    description: Name of the emitted event.
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: name
    description: Name associated with the event.
    data_type: String
  - name: owner
    description: Address of the owner involved in the event.
    data_type: String
  - name: registration_time
    description: Time when the registration occurred.
    data_type: DateTime64(0, 'UTC')
  config:
    access: public
    tags:
    - production
    - contracts
    - circles
    - events
    materialized: incremental
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_circles_v2_CirclesBackingFactory_events
  description: Events emitted by the CirclesBackingFactory contract, including transaction details, block info, and event-specific data.
  columns:
  - name: transaction_hash
    description: Unique hash identifying the transaction that emitted the event.
    data_type: String
  - name: block_number
    description: Block number in which the event was included.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp of the block containing the event.
    data_type: DateTime64(0, 'UTC')
  - name: log_index
    description: Index of the log within the block, used to order events.
    data_type: UInt64
  - name: event_type
    description: Type of the event emitted, e.g., 'BackingAdded', 'BackingRemoved'.
    data_type: String
  - name: backing_id
    description: Identifier for the backing entity involved in the event.
    data_type: String
  - name: amount_wei
    description: Amount associated with the event, in wei.
    data_type: UInt64
  - name: sender_address
    description: Address of the sender who triggered the event.
    data_type: String
  - name: recipient_address
    description: Address of the recipient involved in the event, if applicable.
    data_type: String
  - name: event_data
    description: Raw JSON data of the event, if available.
    data_type: JSON
  config:
    access: public
    tags:
    - production
    - contracts
    - circles
    - events
    materialized: incremental
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
