version: 2
models:
  - name: contracts_circles_registry
    meta: {owner: analytics_team, authoritative: false}
    tests: [{elementary.schema_changes: {severity: warn, tags: [elementary]}}]
    columns:
      - name: address
        tests: [not_null]
      - name: contract_type
        tests: [not_null]
  - name: contracts_circles_v1_Hub_events
    meta: {owner: analytics_team, authoritative: false}
    tests: [{elementary.schema_changes: {severity: warn, tags: [elementary]}}]
  - name: contracts_circles_v2_Hub_events
    meta: {owner: analytics_team, authoritative: false}
    tests: [{elementary.schema_changes: {severity: warn, tags: [elementary]}}]
  - name: contracts_circles_v2_NameRegistry_events
    meta: {owner: analytics_team, authoritative: false}
    tests: [{elementary.schema_changes: {severity: warn, tags: [elementary]}}]
  - name: contracts_circles_v2_CirclesBackingFactory_events
    meta: {owner: analytics_team, authoritative: false}
    tests: [{elementary.schema_changes: {severity: warn, tags: [elementary]}}]
  - name: contracts_circles_v2_StandardTreasury_events
    meta: {owner: analytics_team, authoritative: false}
    tests: [{elementary.schema_changes: {severity: warn, tags: [elementary]}}]
  - name: contracts_circles_v2_BaseGroupFactory_events
    meta: {owner: analytics_team, authoritative: false}
    tests: [{elementary.schema_changes: {severity: warn, tags: [elementary]}}]
  - name: contracts_circles_v2_CMGroupDeployer_events
    meta: {owner: analytics_team, authoritative: false}
    tests: [{elementary.schema_changes: {severity: warn, tags: [elementary]}}]
  - name: contracts_circles_v2_BaseGroup_events
    meta: {owner: analytics_team, authoritative: false}
    tests: [{elementary.schema_changes: {severity: warn, tags: [elementary]}}]
  - name: contracts_circles_v2_ERC20Lift_events
    meta: {owner: analytics_team, authoritative: false}
    tests: [{elementary.schema_changes: {severity: warn, tags: [elementary]}}]
  - name: contracts_circles_v2_ReferralsModule_events
    meta: {owner: analytics_team, authoritative: false}
    tests: [{elementary.schema_changes: {severity: warn, tags: [elementary]}}]
  - name: contracts_circles_v2_InvitationModule_events
    meta: {owner: analytics_team, authoritative: false}
    tests: [{elementary.schema_changes: {severity: warn, tags: [elementary]}}]
  - name: contracts_circles_v2_InvitationFarm_events
    meta: {owner: analytics_team, authoritative: false}
    tests: [{elementary.schema_changes: {severity: warn, tags: [elementary]}}]
  - name: contracts_circles_v2_PaymentGatewayFactory_events
    meta: {owner: analytics_team, authoritative: false}
    tests: [{elementary.schema_changes: {severity: warn, tags: [elementary]}}]
  - name: contracts_circles_v2_ERC20TokenOfferCycle_events
    meta: {owner: analytics_team, authoritative: false}
    tests: [{elementary.schema_changes: {severity: warn, tags: [elementary]}}]
