version: 2
models:

- name: contracts_Swapr_v3_AlgebraFactory_calls
  description: This model captures swapr algebra factory call events, including transaction details and call parameters.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event occurred.
    data_type: DateTime
  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String
  - name: contract_address
    description: Address of the contract involved in the call.
    data_type: String
  - name: caller
    description: Address of the caller initiating the call.
    data_type: String
  - name: call_data
    description: Encoded call data payload.
    data_type: String
  - name: output_json_type
    description: Indicates if the output is in JSON format.
    data_type: UInt64
  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  - name: transaction_index
    description: Index of the transaction within the block.
    data_type: UInt64
  - name: call_type
    description: Type of the call made.
    data_type: String
  - name: call_value
    description: Value transferred during the call in wei.
    data_type: String
  - name: call_gas
    description: Gas limit for the call.
    data_type: String
  - name: call_gas_price
    description: Gas price for the call in wei.
    data_type: String
  - name: call_nonce
    description: Nonce of the call.
    data_type: UInt64
  - name: call_success
    description: Indicates if the call was successful.
    data_type: UInt64
  - name: call_error
    description: Error message if the call failed.
    data_type: String
  - name: call_input
    description: Input data for the call.
    data_type: String
  - name: call_output
    description: Output data from the call.
    data_type: String
  - name: call_block_number
    description: Block number at which the call was made.
    data_type: UInt64
  - name: call_timestamp
    description: Timestamp of the call.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - swapr
    - calls
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_Swapr_v3_AlgebraFactory_events
  description: This model captures swapr algebra factory events including transaction details, block information, and event-specific data for analysis and reporting.
  columns:
  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64
  - name: block_timestamp
    description: The timestamp when the block was mined.
    data_type: DateTime
  - name: transaction_hash
    description: Hash of the transaction associated with the event.
    data_type: String
  - name: log_index
    description: The index of the log within the block.
    data_type: UInt64
  - name: event_type
    description: The type of the event emitted by the factory.
    data_type: String
  - name: factory_address
    description: The address of the factory contract emitting the event.
    data_type: String
  - name: token0
    description: Address of the first token involved in the swap.
    data_type: String
  - name: token1
    description: Address of the second token involved in the swap.
    data_type: String
  - name: amount0
    description: Amount of token0 involved in the swap (in wei).
    data_type: String
  - name: amount1
    description: Amount of token1 involved in the swap (in wei).
    data_type: String
  - name: recipient
    description: Address receiving the tokens.
    data_type: String
  - name: event_id
    description: Unique identifier for the event.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - swapr
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_Swapr_v3_AlgebraPool_calls
  description: This model captures call data for the Swapr v3 Algebra Pool, including transaction details, block info, and call-specific data, used for analytics and reporting.
  columns:
  - name: block_number
    description: The number of the block in which the call was included.
    data_type: UInt64
  - name: block_timestamp
    description: The timestamp when the block was mined, in UTC.
    data_type: DateTime
  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String
  - name: log_index
    description: The index of the log within the transaction.
    data_type: UInt64
  - name: caller
    description: Address of the caller initiating the call.
    data_type: String
  - name: contract_address
    description: Address of the contract being called.
    data_type: String
  - name: call_data
    description: Encoded call data payload.
    data_type: String
  - name: value
    description: Amount transferred in wei during the call.
    data_type: String
  - name: gas_used
    description: Gas used for the call execution.
    data_type: UInt64
  - name: success
    description: Whether the call was successful.
    data_type: UInt64
  - name: error_message
    description: Error message if the call failed.
    data_type: String
  - name: block_start
    description: Start of the block range for the call.
    data_type: DateTime
  - name: block_end
    description: End of the block range for the call.
    data_type: DateTime
  config:
    access: public
    tags:
    - production
    - contracts
    - swapr
    - calls
    materialized: incremental
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_Swapr_v3_AlgebraPool_events
  description: This model captures swap events from the Swapr v3 Algebra Pool, including transaction details, pool state, and event-specific data for analysis and reporting.
  columns:
  - name: block_number
    description: The block number at which the event was recorded.
    data_type: UInt64
  - name: block_timestamp
    description: The timestamp of the block in UTC.
    data_type: DateTime
  - name: transaction_hash
    description: The hash of the transaction containing the event.
    data_type: String
  - name: log_index
    description: The index of the log within the block.
    data_type: UInt64
  - name: pool_address
    description: The address of the Algebra Pool contract.
    data_type: String
  - name: sender
    description: The address initiating the swap.
    data_type: String
  - name: recipient
    description: The address receiving the output tokens.
    data_type: String
  - name: amount0_delta
    description: Change in token0 amount during the swap (in wei).
    data_type: String
  - name: amount1_delta
    description: Change in token1 amount during the swap (in wei).
    data_type: String
  - name: sqrt_price_x96
    description: The square root of the price at the time of the event, scaled by 2^96.
    data_type: String
  - name: liquidity
    description: The current liquidity in the pool.
    data_type: String
  - name: tick
    description: The current tick of the pool.
    data_type: Int64
  - name: event_type
    description: The type of event, e.g., 'Swap'.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - swapr
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
