version: 2
models:

- name: contracts_Swapr_v3_AlgebraFactory_calls
  description: This model captures swapr algebra factory call events, including transaction details, contract addresses, and call-specific data for analysis and reporting.
  columns:
  - name: transaction_hash
    description: Unique identifier of the transaction; used as primary key.
    data_type: String
  - name: block_number
    description: The block number in which the transaction was included.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp when the block was mined; in UTC.
    data_type: DateTime
  - name: contract_address
    description: Address of the contract involved in the call.
    data_type: String
  - name: caller_address
    description: Address initiating the call.
    data_type: String
  - name: call_data
    description: Encoded call data payload.
    data_type: String
  - name: output_json_type
    description: Indicates if the output is in JSON format; boolean.
    data_type: String
  - name: output_type
    description: Type of output returned by the call.
    data_type: String
  - name: output_value
    description: Result of the call, in JSON or string format.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - swapr
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_Swapr_v3_AlgebraFactory_events
  description: Events emitted by the Swapr v3 AlgebraFactory contract, including transaction details, block information, and event-specific data.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted.
    data_type: DateTime
  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String
  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: event_name
    description: Name of the emitted event.
    data_type: String
  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  - name: args
    description: JSON object containing event-specific arguments.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - swapr
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_Swapr_v3_AlgebraPool_calls
  description: This model captures call data related to Swapr v3 Algebra Pools, including transaction details, block info, and call specifics for analysis.
  columns:
  - name: block_number
    description: The number of the block containing the call, indicating its position in the blockchain.
    data_type: UInt64
  - name: block_timestamp
    description: The timestamp when the block was mined, in UTC.
    data_type: DateTime
  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String
  - name: log_index
    description: Index of the log within the transaction, indicating call order.
    data_type: UInt64
  - name: caller_address
    description: Address initiating the call, in hexadecimal format.
    data_type: String
  - name: contract_address
    description: Address of the contract being called, in hexadecimal format.
    data_type: String
  - name: call_data
    description: Encoded call data payload, in hexadecimal.
    data_type: String
  - name: call_type
    description: Type of call made, e.g., 'swap', 'addLiquidity'.
    data_type: String
  - name: gas_used
    description: Amount of gas used for the call, in wei.
    data_type: String
  - name: status
    description: Call execution status, e.g., 'success' or 'failure'.
    data_type: String
  - name: block_start_time
    description: Start time of the block, in UTC.
    data_type: DateTime
  - name: block_end_time
    description: End time of the block, in UTC.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - swapr
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_Swapr_v3_AlgebraPool_events
  description: This model captures Swapr v3 Algebra Pool events, including transaction details, pool states, and event-specific data for analysis and reporting.
  columns:
  - name: block_number
    description: Ethereum block number in which the event was included.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp of the block containing the event, in UTC.
    data_type: DateTime64(0, 'UTC')
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String
  - name: log_index
    description: Index of the event log within the block.
    data_type: UInt64
  - name: pool_address
    description: Address of the Algebra Pool contract involved in the event.
    data_type: String
  - name: event_type
    description: Type of the event emitted, e.g., 'Swap', 'Mint', 'Burn'.
    data_type: String
  - name: amount0
    description: Amount of token0 involved in the event, in wei.
    data_type: String
  - name: amount1
    description: Amount of token1 involved in the event, in wei.
    data_type: String
  - name: sqrt_price_x96
    description: Square root price at the time of the event, scaled by 2^96.
    data_type: String
  - name: liquidity
    description: Total liquidity in the pool at the time of the event.
    data_type: String
  - name: sender
    description: Address initiating the transaction.
    data_type: String
  - name: recipient
    description: Address receiving tokens or involved in the event.
    data_type: String
  - name: amount0_scaled
    description: Scaled amount of token0 (e.g., in decimal form).
    data_type: String
  - name: amount1_scaled
    description: Scaled amount of token1 (e.g., in decimal form).
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - swapr
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
