version: 2
models:

- name: contracts_Swapr_v3_AlgebraFactory_calls
  description: The `contracts_Swapr_v3_AlgebraFactory_calls` model captures and decodes call data related to the Swapr v3 AlgebraFactory contract, enabling analysis of contract interactions over time.
  columns:

  - name: transaction_hash
    description: Unique identifier for each transaction
    data_type: String

  - name: block_number
    description: Block number in which the transaction was included
    data_type: UInt64

  - name: block_timestamp
    description: Timestamp of the block in UTC
    data_type: DateTime64(0, 'UTC')

  - name: contract_address
    description: Address of the Swapr v3 AlgebraFactory contract
    data_type: String

  - name: call_data
    description: Encoded call data for the contract call
    data_type: String

  - name: output_json_type
    description: Indicates if output is in JSON format (true/false)
    data_type: UInt64

  - name: output_data
    description: Output data from the contract call, in JSON if applicable
    data_type: JSON

  - name: call_type
    description: Type of call made to the contract (e.g., 'call', 'delegatecall')
    data_type: String

  - name: gas_used
    description: Gas used for the call in wei
    data_type: String

  - name: caller_address
    description: Address initiating the call
    data_type: String

  - name: caller_balance
    description: Balance of the caller at the time of call, in wei
    data_type: String

  - name: call_value
    description: Ether value transferred in the call, in wei
    data_type: String

  - name: call_success
    description: Whether the call was successful (1 for success, 0 for failure)
    data_type: UInt64
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.493510'
    _generated_fields:
    - description
    - config.tags
    - config.materialized
  config:
    tags:
    - production
    - contracts
    - swapr
    - calls
    materialized: incremental

- name: contracts_Swapr_v3_AlgebraFactory_events
  description: The `contracts_Swapr_v3_AlgebraFactory_events` model captures and processes event logs related to the Swapr v3 AlgebraFactory contract, enabling analysis of contract interactions and event occurrences over time.
  columns:

  - name: block_timestamp
    description: Timestamp of the block when the event was emitted.
    data_type: DateTime

  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String

  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64

  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String

  - name: event_name
    description: Name of the event emitted.
    data_type: String

  - name: sender
    description: Address of the sender initiating the transaction.
    data_type: String

  - name: recipient
    description: Address of the recipient involved in the event.
    data_type: String

  - name: amount_in
    description: Input amount in wei.
    data_type: String

  - name: amount_out
    description: Output amount in wei.
    data_type: String

  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64

  - name: event_data
    description: Raw JSON data of the event.
    data_type: JSON
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.493570'
    _generated_fields:
    - description
    - config.tags
    - config.materialized
  config:
    tags:
    - production
    - contracts
    - swapr
    - events
    materialized: incremental

- name: contracts_Swapr_v3_AlgebraPool_calls
  description: The `contracts_Swapr_v3_AlgebraPool_calls` model captures and processes call interactions related to the Swapr v3 Algebra Pool contract, enabling analysis of contract activity over time.
  columns:

  - name: transaction_hash
    description: Unique identifier for the transaction
    data_type: String

  - name: block_number
    description: Block number in which the transaction was included
    data_type: UInt64

  - name: block_timestamp
    description: Timestamp when the block was mined
    data_type: DateTime64(0, 'UTC')

  - name: pool_address
    description: Address of the swap pool contract
    data_type: String

  - name: caller_address
    description: Address initiating the call
    data_type: String

  - name: call_data
    description: Encoded call data payload
    data_type: String

  - name: call_type
    description: Type of call made (e.g., swap, addLiquidity)
    data_type: String

  - name: gas_used
    description: Gas used for the transaction (in wei)
    data_type: String

  - name: gas_price
    description: Gas price at the time of transaction (in wei)
    data_type: String

  - name: value
    description: ETH value transferred in the call (wei)
    data_type: String

  - name: status
    description: Transaction success status (true/false)
    data_type: String
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.493662'
    _generated_fields:
    - description
    - config.tags
    - config.materialized
  config:
    tags:
    - production
    - contracts
    - swapr
    - calls
    materialized: incremental

- name: contracts_Swapr_v3_AlgebraPool_events
  description: The `contracts_Swapr_v3_AlgebraPool_events` model captures and processes event logs related to Swapr's Algebra Pool smart contract, enabling analysis of pool activities and events over time.
  columns:

  - name: block_number
    description: The block number at which the event was recorded.
    data_type: UInt64

  - name: block_timestamp
    description: The timestamp when the block was mined, in UTC.
    data_type: DateTime

  - name: transaction_hash
    description: The hash of the transaction that triggered the event.
    data_type: String

  - name: log_index
    description: The index of the log within the block.
    data_type: UInt64

  - name: pool_address
    description: Address of the Algebra Pool contract involved in the event.
    data_type: String

  - name: event_type
    description: Type of the event (e.g., Swap, Mint, Burn).
    data_type: String

  - name: sender
    description: Address initiating the transaction or event.
    data_type: String

  - name: recipient
    description: Address receiving tokens or assets, if applicable.
    data_type: String

  - name: amount0
    description: Amount of token0 involved in the event, in wei.
    data_type: String

  - name: amount1
    description: Amount of token1 involved in the event, in wei.
    data_type: String

  - name: sqrt_price_x96
    description: Square root of the price, scaled by 2^96.
    data_type: String

  - name: liquidity
    description: Liquidity of the pool at the time of the event.
    data_type: String

  - name: tick
    description: Current tick of the pool.
    data_type: Int32

  - name: amount0_delta
    description: Change in token0 amount during the event, in wei.
    data_type: String

  - name: amount1_delta
    description: Change in token1 amount during the event, in wei.
    data_type: String
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.493728'
    _generated_fields:
    - description
    - config.tags
    - config.materialized
  config:
    tags:
    - production
    - contracts
    - swapr
    - events
    materialized: incremental
