version: 2
models:

- name: contracts_OmenAgentResultMapping_calls
  description: This model processes call data related to Omen Agent Result Mapping, including transaction details, contract addresses, and timing information for analysis and reporting.
  columns:
  - name: transaction_hash
    description: Unique identifier for each transaction.
    data_type: String
  - name: block_number
    description: Block number in which the transaction was included.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp when the block was mined.
    data_type: DateTime64(0, 'UTC')
  - name: contract_address
    description: Address of the contract involved in the call.
    data_type: String
  - name: output_json_type
    description: Indicates if the output is in JSON format (true/false).
    data_type: UInt64
  - name: transaction_index
    description: Index of the transaction within the block.
    data_type: UInt64
  - name: call_data
    description: Encoded call data for the transaction.
    data_type: String
  - name: block_time
    description: Alias for block_timestamp, representing the time of the block.
    data_type: DateTime64(0, 'UTC')
  - name: incremental_column
    description: Column used for incremental processing, typically block timestamp.
    data_type: DateTime64(0, 'UTC')
  - name: start_blocktime
    description: Starting block timestamp for data processing window.
    data_type: DateTime64(0, 'UTC')
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - omenagentresultmapping
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_OmenAgentResultMapping_events
  description: This model processes event logs related to Omen Agent Result Mapping, capturing details of contract events for analysis.
  columns:
  - name: block_timestamp
    description: Timestamp of the block containing the event, in UTC.
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block, used to order logs.
    data_type: UInt64
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: event_id
    description: Unique identifier for the event, possibly a hash.
    data_type: String
  - name: result_mapping_id
    description: Identifier for the result mapping, linking to related records.
    data_type: String
  - name: status
    description: Status of the event, e.g., 'success', 'failure'.
    data_type: String
  - name: details
    description: Additional event details in JSON format.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - omenagentresultmapping
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
