version: 2
models:

- name: contracts_OmenAgentResultMapping_calls
  description: This model captures call results from the Omen Agent Result Mapping, including transaction details, block info, and output data, used for analysis of contract interactions.
  columns:
  - name: transaction_hash
    description: Unique identifier for the transaction
    data_type: String
  - name: block_number
    description: The block number in which the transaction was included
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp when the block was mined
    data_type: DateTime64(0, 'UTC')
  - name: contract_address
    description: Address of the contract involved in the call
    data_type: String
  - name: output_json
    description: JSON output data from the call result
    data_type: JSON
  - name: output_json_type
    description: Indicates if output JSON is of a specific type
    data_type: UInt64
  - name: block_start_time
    description: Start time of the block
    data_type: DateTime64(0, 'UTC')
  - name: block_end_time
    description: End time of the block
    data_type: DateTime64(0, 'UTC')
  - name: output_data
    description: Extracted output data from the call result
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - contracts
    - agent_results
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_OmenAgentResultMapping_events
  description: This model captures event mappings related to Omen Agent Results, including details of the event, associated contract, and timestamp information.
  columns:
  - name: block_timestamp
    description: The timestamp of the block when the event was recorded.
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block.
    data_type: UInt64
  - name: contract_address
    description: The address of the contract emitting the event.
    data_type: String
  - name: event_type
    description: The type of event emitted, e.g., 'ResultMapped'.
    data_type: String
  - name: result_id
    description: Unique identifier for the result, typically a hash or ID.
    data_type: String
  - name: mapping_details
    description: JSON object containing detailed mapping information.
    data_type: JSON
  - name: created_at
    description: Timestamp when the record was created.
    data_type: DateTime
  - name: updated_at
    description: Timestamp when the record was last updated.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
