version: 2
models:

- name: contracts_OmenAgentResultMapping_calls
  description: The `contracts_OmenAgentResultMapping_calls` model captures and processes call data related to the Omen Agent contract, enabling analysis of contract interactions over time with incremental updates.
  columns:

  - name: transaction_hash
    description: Unique identifier for each transaction.
    data_type: String

  - name: block_number
    description: Block number in which the transaction was included.
    data_type: UInt64

  - name: block_timestamp
    description: Timestamp when the block was mined, in UTC.
    data_type: DateTime

  - name: contract_address
    description: Address of the contract involved in the call.
    data_type: String

  - name: output_json_type
    description: Indicates if the output is in JSON format; boolean flag.
    data_type: String

  - name: transaction_index
    description: Index of the transaction within the block.
    data_type: UInt64

  - name: call_data
    description: Encoded call data for the transaction.
    data_type: String

  - name: caller_address
    description: Address initiating the call.
    data_type: String

  - name: call_value
    description: Value transferred in the call, in wei.
    data_type: String

  - name: gas_used
    description: Gas used for the transaction.
    data_type: UInt64

  - name: gas_price
    description: Gas price at the time of the transaction, in wei.
    data_type: String
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2024-09-30"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.435047'
    _generated_fields:
    - description
    - config.tags
    - config.materialized

- name: contracts_OmenAgentResultMapping_events
  description: The `contracts_OmenAgentResultMapping_events` model captures and processes event logs related to Omen Agent Result Mapping contracts, enabling analysis of contract interactions and event occurrences over time.
  columns:

  - name: block_timestamp
    description: Timestamp of the block when the event occurred.
    data_type: DateTime

  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64

  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64

  - name: transaction_hash
    description: Hash of the transaction associated with the event.
    data_type: String

  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String

  - name: event_name
    description: Name of the event.
    data_type: String

  - name: result_id
    description: Unique identifier for the result.
    data_type: String

  - name: result_value
    description: Value associated with the result.
    data_type: String

  - name: result_timestamp
    description: Timestamp when the result was recorded.
    data_type: DateTime

  - name: additional_data
    description: Additional event-related data in JSON format.
    data_type: JSON
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2024-09-30"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.435099'
    _generated_fields:
    - description
    - config.tags
    - config.materialized
