version: 2
models:

- name: contracts_OmenAgentResultMapping_calls
  description: This model contains call data from the Omen Agent Result Mapping, including transaction details, contract address, and timing information.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the call occurred.
    data_type: DateTime
  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String
  - name: contract_address
    description: Address of the contract involved in the call.
    data_type: String
  - name: output_json_type
    description: Indicates if the output is in JSON format; boolean flag.
    data_type: UInt64
  - name: start_blocktime
    description: Block timestamp marking the start of the data range.
    data_type: DateTime
  - name: incremental_column
    description: Column used for incremental processing, typically block timestamp.
    data_type: String
  - name: tx_table
    description: Reference to the source transactions table.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - omenagentresultmapping
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_OmenAgentResultMapping_events
  description: This model processes event logs related to Omen Agent Result Mapping, capturing details of contract events, timestamps, and associated identifiers.
  columns:
  - name: block_timestamp
    description: The timestamp of the block when the event was logged.
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block.
    data_type: UInt64
  - name: contract_address
    description: The address of the contract emitting the event.
    data_type: String
  - name: event_type
    description: The type of event emitted, e.g., 'ResultMapped'.
    data_type: String
  - name: result_id
    description: Unique identifier for the result, typically a hash or UUID.
    data_type: String
  - name: agent_id
    description: Identifier of the agent involved in the event.
    data_type: String
  - name: mapping_status
    description: Status of the mapping process, e.g., 'pending', 'confirmed'.
    data_type: String
  - name: additional_data
    description: Additional event data in JSON format.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - omenagentresultmapping
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
