version: 2
models:
- name: execution_state_address_current
  description: Current execution state by address, summarizing total byte differences.
  columns:
  - name: address
    description: Address of the contract or account.
    data_type: STRING
  - name: bytes
    description: Sum of byte differences for the address.
    data_type: INT
  tags:
  - execution
  - summary
- name: execution_state_size_daily
  description: Daily aggregated execution state size, calculated as a cumulative sum of daily differences.  Uses an incremental strategy for efficient updates.
  columns:
  - name: date
    description: Date of the daily aggregation.
    data_type: DATE
  - name: bytes
    description: Cumulative sum of execution state size in bytes.
    data_type: INT
  tags:
  - execution
  - daily_agg
  - incremental
