version: 2
models:
- name: execution_state_address_current
  description: 'TODO: Add description for execution_state_address_current'
  meta:
    sector: execution
    refs:
    - execution_state_size_diff
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - state
    - metrics
  columns:
  - name: address
    description: 'TODO: Add description for address'
    data_tests:
    - not_null
  - name: bytes
    description: 'TODO: Add description for bytes'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - address
      - bytes
- name: execution_state_size_daily
  description: 'TODO: Add description for execution_state_size_daily'
  meta:
    sector: execution
    refs:
    - execution_state_size_diff
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - state
    - metrics
  columns:
  - name: bytes_diff
    description: 'TODO: Add description for bytes_diff'
    data_tests:
    - not_null
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - bytes_diff
      - date
