version: 2
models:

- name: rwa_backedfi_prices_1d
  description: Daily price data for backedfi tokens, aggregated and forward-filled to provide continuous time series.
  columns:
  - name: bticker
    description: Token ticker symbol (e.g., bC3M, bCOIN).
    data_type: String
    tests:
    - not_null
    - unique
  - name: date
    description: Date of the price record (UTC, YYYY-MM-DD).
    data_type: DateTime
    tests:
    - not_null
  - name: price
    description: Token price in USD (floating-point, may contain nulls if data missing).
    data_type: Float64
  config:
    access: public
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_rwa_backedfi_prices_daily
  description: Daily prices for RWA-backed financial instruments, sourced from execution layer data, aggregated and stored for business analysis and reporting.
  columns:
  - name: date
    description: Date of the price record (UTC), in 'YYYY-MM-DD' format.
    data_type: Date
    tests:
    - not_null
  - name: price
    description: Price value in USD, with up to 8 decimal places.
    data_type: Float64
  - name: bticker
    description: Business ticker symbol identifying the instrument.
    data_type: String
    tests:
    - not_null
    - unique
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_execution_rwa_backedfi_prices_daily
  description: Business-facing table containing daily prices for RWA-backed financial instruments, aggregated and forward-filled from raw execution data.
  columns:
  - name: date
    description: Date of the price record in YYYY-MM-DD format.
    data_type: DateTime
    tests:
    - not_null
  - name: bticker
    description: Ticker symbol identifier for the financial instrument.
    data_type: String
    tests:
    - not_null
  - name: price
    description: Price of the instrument in USD units; may include decimal values.
    data_type: Float64
    tests:
    - not_null
  config:
    access: public
    tags:
    - financial
    - daily
    - prices
    materialized: table
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
