version: 2
models:

- name: rwa_backedfi_prices_1d
  description: Daily price data for backedfi tokens, aggregated and forward-filled to provide continuous time series.
  columns:
  - name: bticker
    description: Token ticker symbol (e.g., bC3M, bCOIN).
    data_type: String
    tests:
    - not_null
    - unique
  - name: date
    description: Date of the price record (UTC, YYYY-MM-DD).
    data_type: DateTime
    tests:
    - not_null
  - name: price
    description: Token price in USD (floating-point, may contain nulls if data missing).
    data_type: Float64
  config:
    access: public
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_rwa_backedfi_prices_daily
  description: Daily prices of RWA-backed financial instruments used for analytics and reporting.
  columns:
  - name: date
    description: Date of the price record in UTC.
    data_type: DateTime
  - name: bticker
    description: Business ticker symbol identifying the instrument.
    data_type: String
  - name: price
    description: Price value in USD.
    data_type: Float64
  config:
    access: public
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_execution_rwa_backedfi_prices_daily
  description: Daily aggregated prices for RWA-backed financial instruments, sourced from raw execution data. Contains forward-filled prices per ticker and date.
  columns:
  - name: date
    description: Date of the price record in UTC.
    data_type: DateTime
  - name: bticker
    description: Ticker symbol identifier for the financial instrument.
    data_type: String
  - name: price
    description: Price value in USD, forward-filled per date and ticker.
    data_type: Float64
  config:
    access: public
    tags:
    - financial
    - daily
    - prices
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
