version: 2
models:

- name: api_execution_rwa_backedfi_prices_daily
  description: The api_execution_rwa_backedfi_prices_daily model provides daily pricing data for RWA-backed financial instruments to support analytics and reporting.
  columns:

  - name: bticker
    description: Unique identifier for the financial instrument, typically a ticker symbol.
    data_type: String

  - name: date
    description: The date of the recorded price, formatted as YYYY-MM-DD.
    data_type: Date
    tests:
    - not_null

  - name: price
    description: The daily price of the instrument, expressed in its respective currency units.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - execution
    - tier1
    - api:rwa_backedfi_prices
    - granularity:daily
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.759702'
    _generated_fields:
    - description
    - columns.price.description
    - columns.bticker.description
    - columns.date.description
    - config.tags
    - config.materialized
    - columns.bticker.data_type
    - columns.price.data_type
    - columns.date.data_type

- name: fct_execution_rwa_backedfi_prices_daily
  description: The fct_execution_rwa_backedfi_prices_daily view consolidates daily price data for various backed finance instruments, providing a continuous and filled time series for analysis and reporting purposes.
  columns:

  - name: bticker
    description: Unique identifier for each backed finance instrument or token.
    data_type: String

  - name: date
    description: The specific calendar date for the recorded price, in YYYY-MM-DD format.
    data_type: Date
    tests:
    - not_null

  - name: price
    description: The daily price of the instrument, represented as a numeric value; may be null if data is unavailable.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - rwa
    - backedfi
    - prices
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.759756'
    _generated_fields:
    - description
    - columns.price.description
    - columns.bticker.description
    - columns.date.description
    - config.tags
    - config.materialized
    - columns.bticker.data_type
    - columns.price.data_type
    - columns.date.data_type
