version: 2
models:

- name: rwa_backedfi_prices_1d
  description: Daily price data for backedfi tokens, aggregated and forward-filled to provide continuous time series.
  columns:
  - name: bticker
    description: Token ticker symbol (e.g., bC3M, bCOIN).
    data_type: String
    tests:
    - not_null
    - unique
  - name: date
    description: Date of the price record (UTC, YYYY-MM-DD).
    data_type: DateTime
    tests:
    - not_null
  - name: price
    description: Token price in USD (floating-point, may contain nulls if data missing).
    data_type: Float64
  config:
    access: public
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_rwa_backedfi_prices_daily
  description: Daily prices for RWA-backed FI assets used in execution analysis.
  columns:
  - name: bticker
    description: Asset ticker symbol.
    data_type: String
  - name: date
    description: Date of the price record (YYYY-MM-DD).
    data_type: DateTime
  - name: price
    description: Asset price in USD.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - rwa
    - backedfi
    - prices
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_execution_rwa_backedfi_prices_daily
  description: Daily prices for RWA-backed financial instruments, aggregated by ticker and date.
  columns:
  - name: bticker
    description: Ticker symbol identifying the financial instrument.
    data_type: String
  - name: date
    description: Calendar date for the price record (UTC).
    data_type: Date
  - name: price
    description: Price value in USD units.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - execution
    - rwa
    - backedfi
    - prices
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
