version: 2
models:

- name: contracts_aaveV3_PoolInstance_events
  description: Events emitted by the Aave V3 PoolInstance contract, capturing logs related to pool activity, including event types, timestamps, and transaction details.
  columns:
  - name: block_timestamp
    description: The timestamp of the block when the event was emitted, in UTC.
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block, used to order events.
    data_type: UInt64
  - name: transaction_hash
    description: The hash of the transaction that emitted the event.
    data_type: String
  - name: event_type
    description: The type of event emitted, e.g., 'Deposit', 'Withdraw'.
    data_type: String
  - name: pool_address
    description: The address of the Aave V3 Pool contract involved in the event.
    data_type: String
  - name: user_address
    description: The address of the user involved in the event.
    data_type: String
  - name: reserve_asset
    description: The asset involved in the event, e.g., token address or symbol.
    data_type: String
  - name: amount
    description: The amount transferred or involved in the event, in wei or smallest units.
    data_type: String
  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64
  - name: transaction_index
    description: The index of the transaction within the block.
    data_type: UInt64
  - name: event_data
    description: Raw JSON data of the event for additional context.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - aaveV3
    - pool_events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_aaveV3_PoolConfigurator_events
  description: Events emitted by the Aave V3 PoolConfigurator contract, capturing configuration changes and administrative actions.
  columns:
  - name: event_id
    description: Unique identifier for each event record.
    data_type: String
  - name: block_number
    description: Blockchain block number where the event was emitted.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp of the block containing the event.
    data_type: DateTime64(0, 'UTC')
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String
  - name: log_index
    description: Index of the event log within the block.
    data_type: UInt64
  - name: event_name
    description: Name of the emitted event (e.g., "ConfigurationChanged").
    data_type: String
  - name: sender
    description: Address of the account that initiated the event.
    data_type: String
  - name: new_setting_value
    description: The new configuration value set by the event, if applicable.
    data_type: String
  - name: old_setting_value
    description: The previous configuration value before the change, if applicable.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - aaveV3
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
