version: 2
models:

- name: contracts_aaveV3_PoolInstance_events
  description: The `contracts_aaveV3_PoolInstance_events` model captures and processes event logs related to Aave V3 pool instances, enabling analysis of protocol interactions and state changes over time.
  columns:

  - name: block_timestamp
    description: Timestamp of the block when the event was emitted, in UTC.
    data_type: DateTime

  - name: transaction_hash
    description: Unique hash identifying the transaction that emitted the event.
    data_type: String

  - name: log_index
    description: Index of the log within the block, used to order events.
    data_type: UInt64

  - name: event_type
    description: Type of the event emitted, e.g., 'Deposit', 'Withdraw'.
    data_type: String

  - name: pool_address
    description: Address of the Aave V3 Pool contract instance.
    data_type: String

  - name: reserve_asset
    description: Address of the reserve asset involved in the event.
    data_type: String

  - name: amount
    description: Amount involved in the event, denominated in wei.
    data_type: String

  - name: user_address
    description: Address of the user involved in the event.
    data_type: String

  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.508146'
    _generated_fields:
    - description
    - config.tags
    - config.materialized
  config:
    tags:
    - production
    - aave
    - v3
    - contracts
    - events
    materialized: incremental

- name: contracts_aaveV3_PoolConfigurator_events
  description: The `contracts_aaveV3_PoolConfigurator_events` model captures and processes event logs related to the Aave V3 Pool Configurator, enabling analysis of configuration changes and events within the protocol.
  columns:

  - name: block_number
    description: The block number at which the event was emitted.
    data_type: UInt64

  - name: log_index
    description: The index of the log within the block.
    data_type: UInt64

  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String

  - name: block_timestamp
    description: Timestamp of the block when the event was emitted.
    data_type: DateTime

  - name: event_name
    description: Name of the event emitted, e.g., 'PoolConfigChanged'.
    data_type: String

  - name: sender
    description: Address of the sender who triggered the event.
    data_type: String

  - name: new_config_value
    description: The new configuration value set by the event, in wei or relevant units.
    data_type: String

  - name: old_config_value
    description: The previous configuration value before the event, in wei or relevant units.
    data_type: String

  - name: event_data
    description: Raw JSON data of the event for additional context.
    data_type: JSON
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.508097'
    _generated_fields:
    - description
    - config.tags
    - config.materialized
  config:
    tags:
    - production
    - aave
    - v3
    - contracts
    - events
    materialized: incremental
