version: 2
models:

- name: contracts_aaveV3_PoolInstance_events
  description: This model captures the PoolInstance events from Aave V3, including block timestamp, log index, transaction hash, event name, and related data for analysis of contract interactions.
  columns:
  - name: block_timestamp
    description: The timestamp of the block containing the event, in UTC.
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block, indicating order of events.
    data_type: UInt64
  - name: transaction_hash
    description: The hash of the transaction that emitted the event.
    data_type: String
  - name: event_name
    description: The name of the event emitted by the contract.
    data_type: String
  - name: pool_address
    description: The address of the Aave V3 pool contract involved in the event.
    data_type: String
  - name: reserve_address
    description: The address of the reserve token involved in the event.
    data_type: String
  - name: amount
    description: The amount involved in the event, in wei.
    data_type: String
  - name: from_address
    description: The address initiating the transaction or event.
    data_type: String
  - name: to_address
    description: The recipient address involved in the event.
    data_type: String
  - name: event_data
    description: Additional event data in JSON format.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - aave
    - v3
    - contracts
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_aaveV3_PoolConfigurator_events
  description: Events emitted by the Aave V3 PoolConfigurator contract, including details about configuration changes, with timestamps and transaction info.
  columns:
  - name: block_timestamp
    description: Block timestamp when the event was emitted
    data_type: DateTime
  - name: log_index
    description: Log index within the block
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction that emitted the event
    data_type: String
  - name: event_name
    description: Name of the event emitted
    data_type: String
  - name: pool_address
    description: Address of the PoolConfigurator contract
    data_type: String
  - name: new_configuration
    description: JSON object containing the new configuration parameters
    data_type: JSON
  - name: block_number
    description: Block number at which the event was emitted
    data_type: UInt64
  - name: transaction_index
    description: Index of the transaction within the block
    data_type: UInt64
  - name: event_data
    description: Raw event data payload
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - aave
    - v3
    - contracts
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
