version: 2
models:

- name: contracts_aaveV3_PoolInstance_events
  description: Events emitted by the Aave V3 PoolInstance contract, including details about event type, associated addresses, transaction info, and event-specific data.
  columns:
  - name: event_id
    description: Unique identifier for each event record.
    data_type: String
    tests:
    - not_null
    - unique
  - name: block_number
    description: Blockchain block number where the event was emitted.
    data_type: UInt64
    tests:
    - not_null
  - name: block_timestamp
    description: Timestamp when the block was mined, in UTC.
    data_type: DateTime
    tests:
    - not_null
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String
    tests:
    - not_null
  - name: log_index
    description: Index of the event log within the block.
    data_type: UInt64
    tests:
    - not_null
  - name: event_type
    description: Type of the event emitted, e.g., 'Deposit', 'Withdraw'.
    data_type: String
    tests:
    - not_null
  - name: contract_address
    description: Address of the Aave V3 PoolInstance contract emitting the event.
    data_type: String
    tests:
    - not_null
  - name: user_address
    description: Address of the user involved in the event.
    data_type: String
  - name: reserve_address
    description: Address of the reserve token related to the event.
    data_type: String
  - name: amount
    description: Amount involved in the event, in wei.
    data_type: String
  - name: transaction_index
    description: Index of the transaction within the block.
    data_type: UInt64
  - name: event_data
    description: Additional event-specific data in JSON format.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - aaveV3
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_aaveV3_PoolConfigurator_events
  description: Events emitted by the Aave V3 PoolConfigurator contract, capturing configuration changes and related activities.
  columns:
  - name: block_timestamp
    description: The timestamp when the event was emitted, in UTC.
    data_type: DateTime
    tests:
    - not_null
  - name: log_index
    description: The index of the log within the block, used to order events.
    data_type: UInt64
    tests:
    - not_null
  - name: transaction_hash
    description: The hash of the transaction that emitted the event.
    data_type: String
    tests:
    - not_null
    - unique
  - name: event_name
    description: The name of the event emitted by the contract.
    data_type: String
    tests:
    - not_null
  - name: pool_address
    description: The address of the Aave V3 pool contract associated with the event.
    data_type: String
    tests:
    - not_null
  - name: reserve_asset
    description: The address of the reserve asset involved in the configuration change.
    data_type: String
  - name: configuration_data
    description: JSON object containing configuration parameters and their new values.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - aave
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
