version: 2
models:

- name: contracts_aaveV3_PoolInstance_events
  description: Events emitted by the Aave V3 PoolInstance contract, capturing transaction details, event types, and associated metadata for analytics and monitoring purposes.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted, in UTC.
    data_type: DateTime
  - name: transaction_hash
    description: Unique hash identifying the transaction that emitted the event.
    data_type: String
  - name: log_index
    description: Index of the log within the block, used to order events.
    data_type: UInt64
  - name: event_type
    description: Type of the event emitted, e.g., 'Deposit', 'Withdraw'.
    data_type: String
  - name: pool_address
    description: Address of the Aave V3 Pool contract instance.
    data_type: String
  - name: reserve_asset
    description: Address of the reserve asset involved in the event.
    data_type: String
  - name: amount
    description: Amount involved in the event, denominated in wei.
    data_type: String
  - name: user_address
    description: Address of the user involved in the event.
    data_type: String
  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - aave
    - v3
    - contracts
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_aaveV3_PoolConfigurator_events
  description: Events emitted by the Aave V3 PoolConfigurator contract, capturing configuration changes, with timestamps and transaction details.
  columns:
  - name: block_number
    description: The block number at which the event was emitted.
    data_type: UInt64
  - name: log_index
    description: The index of the log within the block.
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted.
    data_type: DateTime
  - name: event_name
    description: Name of the event emitted, e.g., 'PoolConfigChanged'.
    data_type: String
  - name: sender
    description: Address of the sender who triggered the event.
    data_type: String
  - name: new_config_value
    description: The new configuration value set by the event, in wei or relevant units.
    data_type: String
  - name: old_config_value
    description: The previous configuration value before the event, in wei or relevant units.
    data_type: String
  - name: event_data
    description: Raw JSON data of the event for additional context.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - aave
    - v3
    - contracts
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
