version: 2
models:

- name: contracts_aaveV3_PoolInstance_events
  description: This model captures event logs related to Aave V3 pool instances, including transaction details, block information, and event-specific data for analysis and reporting.
  columns:
  - name: block_timestamp
    description: The timestamp when the block was mined, in UTC.
    data_type: DateTime
  - name: transaction_hash
    description: The hash identifying the transaction, unique per transaction.
    data_type: String
  - name: log_index
    description: The index of the log within the block, used to order logs.
    data_type: UInt64
  - name: pool_address
    description: The address of the Aave V3 pool contract involved in the event.
    data_type: String
  - name: event_name
    description: The name of the event emitted, e.g., 'Deposit', 'Withdraw'.
    data_type: String
  - name: reserve_asset
    description: The asset involved in the event, represented as an address.
    data_type: String
  - name: amount
    description: The amount involved in the event, in wei.
    data_type: String
  - name: user_address
    description: The address of the user involved in the event.
    data_type: String
  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64
  - name: event_data
    description: Raw JSON data of the event for detailed analysis.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - aave
    - v3
    - contracts
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_aaveV3_PoolConfigurator_events
  description: Events emitted by the Aave V3 PoolConfigurator contract, capturing configuration changes and related activities.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted.
    data_type: DateTime
  - name: log_index
    description: Log index within the block, used to order events.
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String
  - name: event_name
    description: Name of the event emitted by the contract.
    data_type: String
  - name: pool_address
    description: Address of the pool associated with the event.
    data_type: String
  - name: new_config_value
    description: New configuration value set by the event, in wei or relevant units.
    data_type: String
  - name: old_config_value
    description: Previous configuration value before the event, in wei or relevant units.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - aave
    - v3
    - contracts
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
