version: 2
models:

- name: contracts_aaveV3_PoolInstance_events
  description: Event logs related to Aave V3 pool instances, capturing transaction details, event types, and associated metadata for analysis.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block, used to order events
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction that emitted the event
    data_type: String
  - name: event_type
    description: Type of the event emitted, e.g., Deposit, Withdraw
    data_type: String
  - name: pool_address
    description: Address of the Aave pool contract involved in the event
    data_type: String
  - name: reserve_address
    description: Address of the reserve token involved in the event
    data_type: String
  - name: amount
    description: Amount involved in the event, in wei
    data_type: String
  - name: user_address
    description: Address of the user involved in the event
    data_type: String
  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64
  - name: event_data
    description: Raw JSON data of the event for debugging or detailed analysis
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - aave
    - v3
    - contracts
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_aaveV3_PoolConfigurator_events
  description: Events emitted by the Aave V3 PoolConfigurator contract, including details about configuration changes, with timestamps and transaction info.
  columns:
  - name: block_timestamp
    description: The timestamp of the block when the event was emitted.
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block, used to order events.
    data_type: UInt64
  - name: transaction_hash
    description: The hash of the transaction that emitted the event.
    data_type: String
  - name: event_name
    description: The name of the event emitted by the PoolConfigurator.
    data_type: String
  - name: pool_address
    description: The address of the pool associated with the event.
    data_type: String
  - name: new_configuration
    description: JSON object containing the new configuration parameters set by the event.
    data_type: JSON
  - name: old_configuration
    description: JSON object containing the previous configuration parameters before the event.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - aave
    - v3
    - contracts
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
