version: 2
models:

- name: int_execution_state_size_full_diff_daily
  description: This model calculates the daily net change in storage size for execution states by aggregating storage diffs, supporting incremental updates for performance analysis.
  columns:

  - name: date
    description: The specific day for which the storage size difference is calculated, truncated to the start of the day.
    data_type: DateTime64
    tests:
    - not_null

  - name: bytes_diff
    description: The net change in storage size in bytes for the day, where positive indicates an increase and negative indicates a decrease.
    data_type: UInt64
  meta:
    owner: analytics_team
    authoritative: false
  tests:
  - elementary.volume_anomalies:
      timestamp_column: date
      time_bucket:
        period: day
        count: 1
      training_period:
        period: day
        count: 56
      seasonality: day_of_week
      detection_period:
        period: day
        count: 2
      detection_delay:
        period: day
        count: 1
      anomaly_sensitivity: 3
      ignore_small_changes:
        spike_failure_percent_threshold: 10
        drop_failure_percent_threshold: 20
      severity: warn
      tags:
      - elementary
  - elementary.freshness_anomalies:
      timestamp_column: date
      time_bucket:
        period: day
        count: 1
      severity: warn
      tags:
      - elementary
  - elementary.schema_changes:
      severity: warn
      tags:
      - elementary
