version: 2
models:

- name: execution_state_size_diff_daily
  description: Daily summary of execution state size differences, including bytes diff per address and date.
  columns:
  - name: address
    description: Ethereum address (20-byte hex string) involved in the size diff.
    data_type: String
    tests:
    - not_null
    - unique
  - name: date
    description: Date for which the size difference is calculated, in UTC.
    data_type: DateTime
    tests:
    - not_null
  - name: bytes_diff
    description: Sum of size difference in bytes for the address on the given date.
    data_type: Int64
  config:
    access: public
    materialized: table
    tags:
    - daily
    - execution
    - state
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: int_execution_state_size_full_diff_daily
  description: Daily aggregated differences in execution state sizes, including bytes difference per day, derived from storage diffs and related data.
  columns:
  - name: date
    description: The day for which the size difference is calculated (UTC, YYYY-MM-DD).
    data_type: DateTime
    tests:
    - not_null
  - name: bytes_diff
    description: Sum of byte size differences for storage diffs on the given day (signed integer).
    data_type: Int64
  config:
    access: public
    materialized: incremental
    tags:
    - execution
    - diffs
    - daily
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
