version: 2
models:

- name: contracts_FPMMDeterministicFactory_calls
  description: This model processes deterministic factory call data, aggregating call details for analysis and reporting.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the call was made
    data_type: DateTime
  - name: transaction_hash
    description: Unique hash identifying the transaction
    data_type: String
  - name: contract_address
    description: Address of the contract involved in the call
    data_type: String
  - name: caller_address
    description: Address initiating the call
    data_type: String
  - name: method_id
    description: Identifier of the method called
    data_type: String
  - name: call_data
    description: Encoded call data payload
    data_type: String
  - name: return_value
    description: Value returned from the call
    data_type: String
  - name: block_number
    description: Block number in which the call was included
    data_type: UInt64
  - name: gas_used
    description: Gas used for the call
    data_type: UInt64
  - name: status
    description: Call execution status (e.g., success or failure)
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - fpmm
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_FPMMDeterministicFactory_events
  description: This model processes deterministic factory event logs related to FPMM contracts, capturing event details, timestamps, and identifiers for analysis.
  columns:
  - name: block_timestamp
    description: Timestamp of the block containing the event, in UTC.
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block, used to order logs.
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash identifying the transaction that emitted the event.
    data_type: String
  - name: event_type
    description: Type of the event emitted by the factory contract.
    data_type: String
  - name: factory_address
    description: Address of the factory contract emitting the event.
    data_type: String
  - name: event_data
    description: JSON object containing event-specific data.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - fpmm
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
