version: 2
models:

- name: contracts_FPMMDeterministicFactory_calls
  description: This model captures call data for the FPMM Deterministic Factory contracts, including transaction details, block information, and call specifics, used for analysis of contract interactions.
  columns:
  - name: block_number
    description: The number of the block containing the transaction.
    data_type: UInt64
  - name: block_timestamp
    description: The timestamp when the block was mined.
    data_type: DateTime64(0, 'UTC')
  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String
  - name: log_index
    description: The index of the log within the transaction.
    data_type: UInt64
  - name: contract_address
    description: The address of the contract involved in the call.
    data_type: String
  - name: caller_address
    description: The address initiating the call.
    data_type: String
  - name: call_data
    description: Encoded data payload of the call.
    data_type: String
  - name: call_type
    description: The type of call (e.g., 'call', 'delegatecall').
    data_type: String
  - name: output_json_type
    description: Indicates if the output is in JSON format (boolean).
    data_type: String
  - name: output_data
    description: The output data from the call, in JSON format.
    data_type: String
  - name: block_hash
    description: Hash of the block containing the transaction.
    data_type: String
  - name: status
    description: Transaction execution status (e.g., 'success', 'failure').
    data_type: String
  - name: gas_used
    description: Gas used for the transaction.
    data_type: UInt64
  - name: gas_price
    description: Gas price in wei.
    data_type: String
  - name: value
    description: Value transferred in wei.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - fpmm
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_FPMMDeterministicFactory_events
  description: This model processes deterministic factory event logs related to FPMM contracts, capturing event details for analysis and reporting.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash of the transaction
    data_type: String
  - name: event_type
    description: Type of the event emitted
    data_type: String
  - name: factory_address
    description: Address of the factory contract emitting the event
    data_type: String
  - name: token_address
    description: Address of the token involved in the event
    data_type: String
  - name: amount
    description: Amount involved in the event, in wei
    data_type: UInt64
  - name: sender_address
    description: Address of the sender initiating the event
    data_type: String
  - name: recipient_address
    description: Address of the recipient involved in the event
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - fpmm
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
