version: 2
models:

- name: contracts_FPMMDeterministicFactory_calls
  description: This model processes deterministic factory call data related to FPMM contracts, capturing call details, timestamps, and related transaction info for business analysis.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the call occurred, in UTC.
    data_type: DateTime
  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String
  - name: contract_address
    description: Address of the contract involved in the call.
    data_type: String
  - name: call_data
    description: Encoded data of the call, in hexadecimal format.
    data_type: String
  - name: block_number
    description: The block number in which the call was included.
    data_type: UInt64
  - name: caller_address
    description: Address of the caller initiating the call.
    data_type: String
  - name: output_json_type
    description: Indicates if the output is in JSON format; boolean.
    data_type: String
  - name: output_data
    description: Output data from the call, in JSON or hex.
    data_type: String
  - name: gas_used
    description: Gas used for the call, in wei.
    data_type: String
  - name: status
    description: Call execution status; e.g., success or failure.
    data_type: String
  - name: created_at
    description: Record creation timestamp in UTC.
    data_type: DateTime
  - name: updated_at
    description: Record last update timestamp in UTC.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - fpmm
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_FPMMDeterministicFactory_events
  description: This model captures deterministic factory event logs related to FPMM contracts, including transaction details, block info, and event-specific data.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction that emitted the event
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String
  - name: event_type
    description: Type of the event emitted
    data_type: String
  - name: event_data
    description: JSON object containing event-specific data
    data_type: JSON
  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - fpmm
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
