version: 2
models:

- name: contracts_FPMMDeterministicFactory_calls
  description: This model processes deterministic factory call data related to FPMM contracts, capturing call details, timestamps, and associated transaction info for analysis.
  columns:
  - name: block_timestamp
    description: The timestamp when the block was mined, in UTC
    data_type: DateTime
  - name: transaction_hash
    description: Unique hash identifying the transaction
    data_type: String
  - name: contract_address
    description: Address of the contract involved in the call
    data_type: String
  - name: call_data
    description: Encoded call data for the contract function
    data_type: String
  - name: call_type
    description: Type of the call (e.g., 'call', 'delegatecall')
    data_type: String
  - name: block_number
    description: The block number in which the transaction was included
    data_type: UInt64
  - name: log_index
    description: Index of the log within the block
    data_type: UInt64
  - name: output_json_type
    description: Indicates if the output is in JSON format (boolean)
    data_type: String
  - name: start_blocktime
    description: The start block timestamp for data processing window
    data_type: DateTime
  - name: output_data
    description: The output data from the call, in JSON or string format
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - fpmm
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_FPMMDeterministicFactory_events
  description: This model processes deterministic factory events related to FPMM contracts, capturing key event data for analysis.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted
    data_type: DateTime
  - name: log_index
    description: Log index within the block (sequence number)
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction containing the event
    data_type: String
  - name: event_type
    description: Type of the event emitted by the factory
    data_type: String
  - name: factory_address
    description: Address of the factory contract emitting the event
    data_type: String
  - name: owner_address
    description: Address of the owner involved in the event
    data_type: String
  - name: token_id
    description: Unique identifier for the token involved in the event
    data_type: String
  - name: amount
    description: Amount associated with the event, in wei
    data_type: String
  - name: additional_data
    description: Additional event data in JSON format
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - fpmm
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
