version: 2
models:

- name: contracts_agave_LendingPool_events
  description: The `contracts_agave_LendingPool_events` model captures and processes event logs from Agave Protocol's LendingPool contract, enabling analysis of protocol interactions, reserve data updates, and yield rate changes over time. This model is used to extract ReserveDataUpdated events containing liquidityRate for stablecoin yield calculations.
  columns:

  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64

  - name: block_timestamp
    description: Timestamp of the block when the event was emitted, in UTC.
    data_type: DateTime64

  - name: transaction_hash
    description: Unique hash identifying the transaction that emitted the event.
    data_type: Nullable(String)

  - name: transaction_index
    description: Index of the transaction within the block.
    data_type: UInt64

  - name: log_index
    description: Index of the log within the block, used to order events.
    data_type: UInt64

  - name: contract_address
    description: Address of the Agave LendingPool contract emitting the event.
    data_type: Nullable(String)

  - name: event_name
    description: Name of the event emitted, e.g., 'ReserveDataUpdated', 'Deposit', 'Withdraw'.
    data_type: String

  - name: decoded_params
    description: Map of decoded event parameters. For ReserveDataUpdated events, contains 'reserve', 'liquidityRate' (or 'liqudityRate' in Aave V2), 'stableBorrowRate', 'variableBorrowRate', 'liquidityIndex', and 'variableBorrowIndex'.
    data_type: Map(String, Nullable(String))
  meta:
    owner: analytics-team
    authoritative: false
  config:
    tags:
    - production
    - agave
    - contracts
    - events
    materialized: incremental

