version: 2
models:

- name: contracts_Seer_MarketFactory_calls
  description: This model captures call data related to the Seer MarketFactory contracts, including transaction details, block information, and call specifics for analysis and reporting.
  columns:
  - name: block_timestamp
    description: The timestamp of the block containing the call, in UTC.
    data_type: DateTime
  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String
  - name: block_number
    description: The number of the block containing the call.
    data_type: UInt64
  - name: call_id
    description: Unique identifier for the call within the transaction.
    data_type: String
  - name: caller_address
    description: Address of the caller initiating the call.
    data_type: String
  - name: contract_address
    description: Address of the contract being called.
    data_type: String
  - name: function_name
    description: Name of the function invoked in the contract.
    data_type: String
  - name: call_data
    description: Encoded data payload of the call.
    data_type: String
  - name: output_json_type
    description: Indicates if the output is in JSON format; boolean.
    data_type: String
  - name: output_data
    description: The output data from the call, in JSON or raw format.
    data_type: String
  - name: block_hash
    description: Hash of the block containing the call.
    data_type: String
  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64
  - name: gas_used
    description: Amount of gas used for the call, in wei.
    data_type: String
  - name: status
    description: Call execution status; e.g., success or failure.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - seermarketfactory
    - calls
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_Seer_MarketFactory_events
  description: This model captures event logs from the Seer MarketFactory contract, including transaction details, block info, and event-specific data for analysis.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted, in UTC.
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block, used to order events.
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash identifying the transaction that emitted the event.
    data_type: String
  - name: event_name
    description: Name of the event emitted, indicating the type of event.
    data_type: String
  - name: contract_address
    description: Address of the Seer MarketFactory contract emitting the event.
    data_type: String
  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  - name: sender
    description: Address of the sender initiating the transaction.
    data_type: String
  - name: recipient
    description: Address of the recipient involved in the event.
    data_type: String
  - name: amount
    description: Amount transferred or involved in the event, in wei.
    data_type: String
  - name: additional_data
    description: JSON object containing extra event-specific data.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - seermarketfactory
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_Seer_Wrapped1155Factory_calls
  description: This model captures call events from the Seer Wrapped1155Factory contract, including transaction details, block info, and call-specific data for analysis and reporting.
  columns:
  - name: transaction_hash
    description: Unique identifier of the transaction containing the call.
    data_type: String
  - name: block_number
    description: Block number in which the transaction was included.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp when the block was mined.
    data_type: DateTime64(0, 'UTC')
  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64
  - name: call_type
    description: Type of the call (e.g., transfer, approval).
    data_type: String
  - name: caller_address
    description: Address initiating the call.
    data_type: String
  - name: contract_address
    description: Address of the Wrapped1155Factory contract.
    data_type: String
  - name: token_id
    description: Identifier of the token involved in the call.
    data_type: String
  - name: amount
    description: Amount involved in the call, in wei.
    data_type: String
  - name: data
    description: Additional call data payload.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - seerpm
    - wrapped1155factory
    - calls
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_Seer_Wrapped1155Factory_events
  description: This model captures events emitted by the Seer Wrapped 1155 Factory contract, including details such as transaction hash, block number, event type, and timestamp.
  columns:
  - name: transaction_hash
    description: Unique identifier of the transaction emitting the event.
    data_type: String
  - name: block_number
    description: The block number in which the event was included.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp when the block was mined, in UTC.
    data_type: DateTime
  - name: event_type
    description: Type of the event emitted by the contract.
    data_type: String
  - name: contract_address
    description: Address of the Seer Wrapped 1155 Factory contract emitting the event.
    data_type: String
  - name: event_data
    description: JSON object containing event-specific data payload.
    data_type: JSON
  - name: log_index
    description: Log index within the block, indicating the event's position.
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - seerpm
    - wrapped1155factory
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
