version: 2
models:

- name: contracts_Seer_MarketFactory_calls
  description: The 'contracts_Seer_MarketFactory_calls' model captures and processes call data related to the Seer MarketFactory contract, enabling analysis of contract interactions over time.
  columns:

  - name: transaction_hash
    description: Unique identifier for the transaction
    data_type: String

  - name: block_number
    description: Block number in which the transaction was included
    data_type: UInt64

  - name: block_timestamp
    description: Timestamp of the block in UTC
    data_type: DateTime

  - name: caller_address
    description: Address of the caller initiating the call
    data_type: String

  - name: contract_address
    description: Address of the contract being called
    data_type: String

  - name: call_data
    description: Encoded call data payload
    data_type: String

  - name: call_type
    description: Type of call (e.g., 'function', 'fallback')
    data_type: String

  - name: call_value
    description: Value transferred with the call in wei
    data_type: String

  - name: call_gas
    description: Gas limit for the call
    data_type: String

  - name: call_gas_price
    description: Gas price in wei
    data_type: String

  - name: output_json_type
    description: Indicates if output is in JSON format (boolean)
    data_type: String

  - name: incremental_column
    description: Column used for incremental processing, typically block timestamp
    data_type: String

  - name: start_blocktime
    description: Starting block timestamp for data processing
    data_type: String
  meta:
    owner: analytics-team
    authoritative: false
    full_refresh:
      start_date: "2024-10-08"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.469468'
    _generated_fields:
    - description
    - config.tags
    - config.materialized

- name: contracts_Seer_MarketFactory_events
  description: The `contracts_Seer_MarketFactory_events` model captures and stores event logs related to the Seer MarketFactory contract, enabling analysis of contract interactions and event occurrences over time.
  columns:

  - name: transaction_hash
    description: Unique hash identifying the transaction; used as primary key.
    data_type: String

  - name: block_number
    description: Block number containing the event.
    data_type: UInt64

  - name: block_timestamp
    description: Timestamp of the block in UTC.
    data_type: DateTime64(0, 'UTC')

  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64

  - name: event_type
    description: Type of the event emitted by the contract.
    data_type: String

  - name: contract_address
    description: Address of the Seer MarketFactory contract emitting the event.
    data_type: String

  - name: sender
    description: Address initiating the transaction.
    data_type: String

  - name: recipient
    description: Address receiving tokens or assets, if applicable.
    data_type: String

  - name: amount
    description: Amount involved in the event, in wei or relevant units.
    data_type: String

  - name: additional_data
    description: JSON object containing event-specific details.
    data_type: JSON
  meta:
    owner: analytics-team
    authoritative: false
    full_refresh:
      start_date: "2024-10-08"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.469538'
    _generated_fields:
    - description
    - config.tags
    - config.materialized

- name: contracts_Seer_Wrapped1155Factory_calls
  description: The `contracts_Seer_Wrapped1155Factory_calls` model captures and decodes call data related to the Wrapped1155Factory contract, enabling analysis of contract interactions and events over time.
  columns:

  - name: transaction_hash
    description: Unique identifier of the transaction.
    data_type: String

  - name: block_number
    description: The block number in which the transaction was included.
    data_type: UInt64

  - name: block_timestamp
    description: Timestamp when the block was mined.
    data_type: DateTime64(0, 'UTC')

  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64

  - name: caller
    description: Address initiating the call.
    data_type: String

  - name: contract_address
    description: Address of the contract being called.
    data_type: String

  - name: call_data
    description: Encoded call data payload.
    data_type: String

  - name: call_type
    description: Type of call (e.g., 'mint', 'transfer').
    data_type: String

  - name: gas_used
    description: Gas used for the call.
    data_type: UInt64

  - name: success
    description: Indicates if the call was successful.
    data_type: UInt64

  - name: block_start
    description: Start of the block range for the call.
    data_type: DateTime64(0, 'UTC')

  - name: block_end
    description: End of the block range for the call.
    data_type: DateTime64(0, 'UTC')
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2024-02-07"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.469585'
    _generated_fields:
    - description
    - config.tags
    - config.materialized

- name: contracts_Seer_Wrapped1155Factory_events
  description: The `contracts_Seer_Wrapped1155Factory_events` model captures and processes event logs related to the Wrapped1155Factory contract, enabling analysis of contract interactions and event occurrences over time.
  columns:

  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64

  - name: block_timestamp
    description: Timestamp when the block was mined.
    data_type: DateTime

  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String

  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64

  - name: event_type
    description: Type of the event emitted (e.g., Transfer, Approval).
    data_type: String

  - name: creator_address
    description: Address of the creator contract emitting the event.
    data_type: String

  - name: token_id
    description: The ID of the token involved in the event.
    data_type: String

  - name: from_address
    description: Address from which tokens are transferred or approved.
    data_type: String

  - name: to_address
    description: Address to which tokens are transferred or approved.
    data_type: String

  - name: amount
    description: Quantity of tokens transferred or approved.
    data_type: String

  - name: event_data
    description: Additional event data in JSON format.
    data_type: JSON
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2024-02-07"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.469626'
    _generated_fields:
    - description
    - config.tags
    - config.materialized
