{
 "title": "Gnosis P2P Network Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; padding: 0; margin: 00; width: 100%; height: 100%; overflow: hidden;\">\n    <img src=\"https://raw.githubusercontent.com/gnosischain/media-kit/refs/heads/main/Logos/02%20Gnosis%20Chain/Transparent/PNG/GnosisChain-Horizontal-01-Moss.png\" alt=\"Sample Image\" style=\"max-width: 100%; height: 100%;\">\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 0 },
   "options": {
    "content": "<div style=\"background-color: #3e6957 ; height: 100%; display: flex; justify-content: center; overflow: hidden;\">\n    <h1 style=\"color: #f5f0e4; font-weight: bold; font-size: 45px;font-family: sans-serif;\">P2P Network</h1>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 2 },
   "options": {
    "content": "<div style=\"background-color: #fffcf8; height: 100%;  justify-content: center; overflow: hidden;\">\n  \n  <h1 style=\"color: #3e6957; font-weight: bold; font-size: 25px;font-family: sans-serif;\">Dashboard Overview</h1>\n  \n  <p>This dashboard provides a comprehensive view of Peer-to-Peer (P2P) network data. Key metrics include the number of active peers, geo location, client diversity and more.</p> \n</div>\n"
   }
  },
  {
   "title": "Active Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM dbt.p2p_valtrack_nodes_cnt_1d\nWHERE \n  active_nodes>0\nORDER BY date DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Countries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM dbt.p2p_valtrack_nodes_cnt_country_1d\nWHERE \n  active_nodes>0\nGROUP BY date\nORDER BY date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n  latitude\n  ,longitude\n  ,COUNT(*) as cnt\nFROM \n  dbt.p2p_valtrack_nodes_geo_last_day \nGROUP BY 1,2"
    }
   ]
  },
  {
   "title": "Last  day seen nodes",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT * FROM dbt.p2p_valtrack_nodes_cnt_1h\nWHERE\n  DATE_TRUNC('day',date) = DATE_TRUNC('day',now() - INTERVAL 15 DAY)"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 13, "w": 21, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT \ndate as datetime\n,CAST(date AS text) AS datetime_label\n,country AS item\n,active_nodes AS cnt\n FROM dbt.p2p_valtrack_nodes_cnt_country_1d\n ORDER BY date, cnt DESC"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT * FROM dbt.p2p_valtrack_nodes_cnt_1d"
    }
   ]
  }
 ]
}