{
 "title": "Consensus Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; padding: 0; margin: 00; width: 100%; height: 100%; overflow: hidden;\">\n    <img src=\"https://raw.githubusercontent.com/gnosischain/media-kit/refs/heads/main/Logos/02%20Gnosis%20Chain/Transparent/PNG/GnosisChain-Horizontal-01-Moss.png\" alt=\"Sample Image\" style=\"max-width: 100%; height: 100%;\">\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 0 },
   "options": {
    "content": "<div style=\"background-color: #3e6957 ; height: 100%; display: flex; justify-content: center; overflow: hidden;\">\n    <h1 style=\"color: #f5f0e4; font-weight: bold; font-size: 45px;font-family: sans-serif;\">Consensus Overview</h1>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 2 },
   "options": {
    "content": "<div style=\"background-color: #fffcfc; height: 100%;  justify-content: center; overflow: hidden;\">\n  \n  <h1 style=\"color: #3e6957; font-weight: bold; font-size: 25px;font-family: sans-serif; padding: 1rem;\">Blocks Production</h1>\n  \n  <p style=\"padding: 1rem;\">This dashboard provides a comprehensive view of Peer-to-Peer (P2P) network data. Key metrics include the number of active peers, geo location, client diversity and more.</p> \n</div>\n"
   }
  },
  {
   "title": "Last Day Active Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nactive\nFROM dbt.consensus_validators_participation_rate\nORDER BY day DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Last Day Active Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nactive\nFROM dbt.consensus_validators_participation_rate\nORDER BY day DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Last Day Active Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nactive\nFROM dbt.consensus_validators_participation_rate\nORDER BY day DESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n*\n,CAST(day AS text) AS datetime_label\n,SUM(cnt) OVER(ORDER BY day) AS total\nFROM dbt.consensus_validators_activations\nORDER BY day ASC"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 20, "x": 2, "y": 17 },
   "options": {
    "content": "<div style=\"background-color:  #3e6957; height: 100%; display: flex; justify-content: center; overflow: hidden;\">\n</div>"
   }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT \n* \n,CAST(day AS text) AS datetime_label\nFROM dbt.consensus_blocks_production\nORDER BY day ASC, label DESC"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 18 },
   "options": {
    "content": "<div style=\"background-color: #fffcfc; height: 100%;  justify-content: center; overflow: hidden;\">\n  \n  <h1 style=\"color: #3e6957; font-weight: bold; font-size: 25px;font-family: sans-serif; padding: 1rem;\">Blocks Production</h1>\n  \n  <p style=\"padding: 1rem;\">This dashboard provides a comprehensive view of Peer-to-Peer (P2P) network data. Key metrics include the number of active peers, geo location, client diversity and more.</p> \n</div>\n"
   }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\nday\n,participation_rate * 100 AS pct\n,CAST(day AS text) AS datetime_label\nFROM dbt.consensus_validators_participation_rate\nORDER BY day ASC"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 20, "x": 2, "y": 30 },
   "options": {
    "content": "<div style=\"background-color:  #3e6957; height: 100%; display: flex; justify-content: center; overflow: hidden;\">\n</div>"
   }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT \n* \n,CAST(day AS text) AS datetime_label\nFROM dbt.consensus_atts_inclusion_distance_d\nORDER BY day ASC"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 31 },
   "options": {
    "content": "<div style=\"background-color: #fffcfc; height: 100%;  justify-content: center; overflow: hidden;\">\n  \n  <h1 style=\"color: #3e6957; font-weight: bold; font-size: 25px;font-family: sans-serif; padding: 1rem;\">Network Attestations</h1>\n  \n  <p style=\"padding: 1rem;\">This dashboard provides a comprehensive view of Peer-to-Peer (P2P) network data. Key metrics include the number of active peers, geo location, client diversity and more.</p> \n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 20, "x": 2, "y": 43 },
   "options": {
    "content": "<div style=\"background-color:  #3e6957; height: 100%; display: flex; justify-content: center; overflow: hidden;\">\n</div>"
   }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT \n* \n,CAST(day AS text) AS datetime_label\nFROM dbt.consensus_validators_waiting_times\nWHERE label = 'Median Entry'\nORDER BY day ASC"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 44 },
   "options": {
    "content": "<div style=\"background-color: #fffcfc; height: 100%;  justify-content: center; overflow: hidden;\">\n  \n  <h1 style=\"color: #3e6957; font-weight: bold; font-size: 25px;font-family: sans-serif; padding: 1rem;\">Waiting Times</h1>\n  \n  <p style=\"padding: 1rem;\">This dashboard provides a comprehensive view of Peer-to-Peer (P2P) network data. Key metrics include the number of active peers, geo location, client diversity and more.</p> \n</div>\n"
   }
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT \n* \n,CAST(day AS text) AS datetime_label\nFROM dbt.consensus_validators_waiting_times\nWHERE label = 'Median Exit'\nORDER BY day ASC"
    }
   ]
  },
  {
   "title": "Last 7 Days Median Entry Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \navg(value) AS value\nFROM dbt.consensus_validators_waiting_times\nWHERE label = 'Median Entry'\nAND day >= (SELECT MAX(day) FROM dbt.consensus_validators_waiting_times) - INTERVAL 7 DAYS\n"
    }
   ]
  },
  {
   "title": "Last 14 Days Median Exit Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \navg(value) AS value\nFROM dbt.consensus_validators_waiting_times\nWHERE label = 'Median Exit'\nAND day >= ((SELECT MAX(day) FROM dbt.consensus_validators_waiting_times) - INTERVAL 14 DAYS)"
    }
   ]
  }
 ]
}