
SELECT
    date,
    peer_ip,
    peer_discovery_id_prefix,
    peer_cl_fork_name,
    peer_cl_next_fork_name,
    peer_client,
    peer_hostname,
    peer_city,
    peer_country,
    peer_org,
    splitByChar(',', peer_loc)[1] AS peer_lat,
    splitByChar(',', peer_loc)[2] AS peer_lon,
    neighbor_ip,
    neighbor_discovery_id_prefix,
    neighbor_cl_fork_name,
    neighbor_cl_next_fork_name,
    neighbor_client,
    neighbor_city,
    neighbor_country,
    neighbor_org,
    splitByChar(',', neighbor_loc)[1] AS neighbor_lat,
    splitByChar(',', neighbor_loc)[2] AS neighbor_lon,
    cnt
FROM  {{ ref('int_p2p_discv5_topology_latest') }}