# models/execution/abi/schema.yml
version: 2

models:

  - name: contract_abis # Define the upstream model too if not already done
    description: "Stores contract ABIs, likely fetched from an external source."
    columns:
      - name: contract_address
        description: "Contract address."
        tests:
          - unique
          - not_null
      - name: abi_json
        description: "The contract ABI in JSON format."
        # Add tests if needed, e.g., ensuring it's valid JSON if possible via tests