version: 2
models:
- name: contracts_abi
  description: This model contains the ABIs for all contracts, sourced from various sources.  It includes the contract address, implementation address (for proxies), ABI JSON, contract name, and source.
  columns:
  - name: contract_address
    description: The contract address (proxy or regular).
    data_type: STRING
  - name: implementation_address
    description: For proxy contracts, the implementation address; NULL for regular/implementation contracts.
    data_type: STRING
  - name: abi_json
    description: The ABI JSON.
    data_type: JSON
  - name: contract_name
    description: Contract name from blockscout.
    data_type: STRING
  - name: source
    description: ABI source (e.g., 'blockscout').
    data_type: STRING
  - name: updated_at
    description: Last updated timestamp.
    data_type: TIMESTAMP
