version: 2
models:
- name: contracts_abi
  description: 'TODO: Add description for contracts_abi'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - abi
  columns:
  - name: abi_json
    description: 'TODO: Add description for abi_json'
    data_tests:
    - not_null
  - name: contract_address
    description: 'TODO: Add description for contract_address'
    data_tests:
    - not_null
  - name: contract_name
    description: 'TODO: Add description for contract_name'
    data_tests:
    - not_null
  - name: contracts
    description: 'TODO: Add description for contracts'
    data_tests:
    - not_null
  - name: implementation_address
    description: 'TODO: Add description for implementation_address'
    data_tests:
    - not_null
  - name: name
    description: 'TODO: Add description for name'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - abi_json
      - contract_address
