version: 2
models:

- name: contracts_backedfi_TSLAx_Oracle_events
  description: Business-facing data model capturing TSLAx Oracle events and related contract data.
  columns:
  - name: block_number
    description: Block height in which the event was included.
    data_type: UInt32
    tests:
    - not_null
  - name: block_hash
    description: Hash of the block containing the event.
    data_type: String
  - name: log_index
    description: Index of the event log within the block.
    data_type: UInt32
    tests:
    - not_null
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String
    tests:
    - not_null
  - name: address
    description: Contract address that emitted the event.
    data_type: String
    tests:
    - not_null
  - name: topic0
    description: First indexed topic, typically the event signature hash.
    data_type: String
  - name: topic1
    description: Second indexed topic, if applicable.
    data_type: String
  - name: topic2
    description: Third indexed topic, if applicable.
    data_type: String
  - name: topic3
    description: Fourth indexed topic, if applicable.
    data_type: String
  - name: data
    description: Non-indexed event data payload (hex-encoded).
    data_type: String
  - name: n_data_bytes
    description: Length of the `data` field in bytes.
    data_type: UInt32
  - name: chain_id
    description: EVM chain identifier.
    data_type: UInt64
  - name: block_timestamp
    description: UTC timestamp of the block containing the event.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: insert_version
    description: Monotonically increasing version for data ingestion.
    data_type: UInt64
  config:
    access: public
    tags:
    - backedfi_oracle_events
    materialized: incremental
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bC3M_Oracle_events
  description: Business-facing model capturing Oracle events related to backedfi contracts, including transaction details, logs, contract creation, and associated metadata.
  columns:
  - name: block_number
    description: Height of the block containing the event.
    data_type: UInt32
    tests:
    - not_null
  - name: block_hash
    description: Hash of the block containing the event.
    data_type: String
  - name: transaction_index
    description: Zero-based index of the transaction within the block.
    data_type: UInt32
  - name: log_index
    description: Zero-based index of the log within the transaction.
    data_type: UInt32
  - name: transaction_hash
    description: Hash identifying the transaction that emitted the event.
    data_type: String
    tests:
    - not_null
  - name: address
    description: Contract address that emitted the event.
    data_type: String
  - name: topic0
    description: First indexed topic (event signature hash).
    data_type: String
  - name: topic1
    description: Second indexed topic.
    data_type: String
  - name: topic2
    description: Third indexed topic.
    data_type: String
  - name: topic3
    description: Fourth indexed topic.
    data_type: String
  - name: data
    description: Non-indexed event data payload (hex).
    data_type: String
  - name: n_data_bytes
    description: Length of `data` in bytes.
    data_type: UInt32
  - name: chain_id
    description: EVM chain identifier.
    data_type: UInt64
  - name: block_timestamp
    description: UTC timestamp of the block containing the event.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: insert_version
    description: Monotonic ingestion version (nanoseconds).
    data_type: UInt64
  config:
    access: public
    tags:
    - backedfi_oracle_events
    materialized: incremental
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bCOIN_Oracle_events
  description: Business-facing data model capturing Oracle events related to backedfi bCOIN contracts, including logs, contract creation, and associated transaction data.
  columns:
  - name: block_number
    description: Block height containing the event or transaction.
    data_type: UInt32
    tests:
    - not_null
  - name: block_hash
    description: Hash of the block containing the event.
    data_type: String
  - name: transaction_index
    description: Zero-based index of the transaction within the block.
    data_type: UInt32
  - name: log_index
    description: Zero-based index of the log within the transaction.
    data_type: UInt32
  - name: transaction_hash
    description: Hash identifying the transaction.
    data_type: String
    tests:
    - not_null
  - name: address
    description: Contract address emitting the event.
    data_type: String
    tests:
    - not_null
  - name: topic0
    description: First indexed topic, typically the event signature hash.
    data_type: String
  - name: topic1
    description: Second indexed topic.
    data_type: String
  - name: topic2
    description: Third indexed topic.
    data_type: String
  - name: topic3
    description: Fourth indexed topic.
    data_type: String
  - name: data
    description: Non-indexed event data payload in hex.
    data_type: String
  - name: n_data_bytes
    description: Length of `data` in bytes.
    data_type: UInt32
  - name: chain_id
    description: EVM chain identifier.
    data_type: UInt64
  - name: block_timestamp
    description: UTC timestamp of the block containing the event.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: insert_version
    description: Monotonic ingestion version in nanoseconds.
    data_type: UInt64
  config:
    access: public
    tags:
    - backedfi_oracle_events
    materialized: incremental
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bCSPX_Oracle_events
  description: Business-facing dataset capturing Oracle events related to backedfi B-CSPX on Gnosis Chain, including logs, contract creations, and associated metadata.
  columns:
  - name: block_number
    description: Height of the block containing the event.
    data_type: UInt32
    tests:
    - not_null
  - name: block_hash
    description: Hash of the block containing the event.
    data_type: String
  - name: transaction_index
    description: Index of the transaction within the block.
    data_type: UInt32
  - name: log_index
    description: Zero-based index of the log within the transaction.
    data_type: UInt32
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String
  - name: address
    description: Contract address that emitted the event.
    data_type: String
  - name: topic0
    description: First indexed topic (event signature hash).
    data_type: String
  - name: topic1
    description: Second indexed topic.
    data_type: String
  - name: topic2
    description: Third indexed topic.
    data_type: String
  - name: topic3
    description: Fourth indexed topic.
    data_type: String
  - name: data
    description: Non-indexed event data payload in hex.
    data_type: String
  - name: n_data_bytes
    description: Length of `data` in bytes.
    data_type: UInt32
  - name: chain_id
    description: EVM chain identifier.
    data_type: UInt64
  - name: block_timestamp
    description: UTC timestamp of the block containing the event.
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonic ingestion version (nanoseconds).
    data_type: UInt64
  config:
    access: public
    tags:
    - backedfi_oracle_events
    materialized: incremental
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bHIGH_Oracle_events
  description: Business-facing data model capturing Oracle events related to backedfi_bHIGH contracts, including deployment, transfer, and event logs.
  columns:
  - name: block_number
    description: Block height containing the event.
    data_type: UInt32
    tests:
    - not_null
  - name: block_hash
    description: Hash of the block containing the event.
    data_type: String
  - name: transaction_index
    description: Index of the transaction within the block.
    data_type: UInt32
  - name: log_index
    description: Index of the log within the transaction.
    data_type: UInt32
  - name: transaction_hash
    description: Hash identifying the transaction.
    data_type: String
    tests:
    - not_null
  - name: address
    description: Contract address emitting the event.
    data_type: String
  - name: event_type
    description: Type of Oracle event (e.g., deployment, transfer, log).
    data_type: String
  - name: event_data
    description: Raw event data payload (hex).
    data_type: String
  - name: timestamp
    description: UTC timestamp of the event occurrence.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: chain_id
    description: EVM chain identifier.
    data_type: UInt64
  - name: insert_version
    description: Monotonic ingestion version (nanoseconds).
    data_type: UInt64
  config:
    access: public
    tags:
    - backedfi_oracle_events
    materialized: incremental
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bIB01_Oracle_events
  description: Business-facing table capturing Oracle event logs and related data from the BackedFi system, including transaction details, logs, contract creations, and associated metadata.
  columns:
  - name: block_number
    description: Height of the block containing the event.
    data_type: UInt32
    tests:
    - not_null
  - name: block_hash
    description: Hash of the block containing the event.
    data_type: String
  - name: transaction_index
    description: Zero-based index of the transaction within the block.
    data_type: UInt32
    tests:
    - not_null
  - name: log_index
    description: Zero-based index of the log within the transaction.
    data_type: UInt32
  - name: transaction_hash
    description: Hash identifying the transaction.
    data_type: String
    tests:
    - not_null
  - name: address
    description: Contract address that emitted the event.
    data_type: String
    tests:
    - not_null
  - name: topic0
    description: First indexed topic (event signature hash).
    data_type: String
  - name: topic1
    description: Second indexed topic.
    data_type: String
  - name: topic2
    description: Third indexed topic.
    data_type: String
  - name: topic3
    description: Fourth indexed topic.
    data_type: String
  - name: data
    description: Non-indexed event data payload (hex).
    data_type: String
  - name: n_data_bytes
    description: Length of `data` in bytes.
    data_type: UInt32
  - name: chain_id
    description: EVM chain identifier.
    data_type: UInt64
  - name: block_timestamp
    description: UTC timestamp of the block containing the event.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: insert_version
    description: Monotonic ingestion version (nanoseconds).
    data_type: UInt64
  config:
    access: public
    tags:
    - backedfi_oracle_events
    materialized: incremental
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bIBTA_Oracle_events
  description: Business-facing data model capturing Oracle events related to BackedFi BIBTA contracts, including logs, transactions, contract deployments, and associated metadata for comprehensive analysis.
  columns:
  - name: block_number
    description: Height of the block containing the event or transaction.
    data_type: UInt32
    tests:
    - not_null
  - name: block_hash
    description: Hash of the block containing the event or transaction.
    data_type: String
  - name: transaction_index
    description: Zero-based index of the transaction within the block.
    data_type: UInt32
    tests:
    - not_null
  - name: transaction_hash
    description: Hash identifying the transaction.
    data_type: String
    tests:
    - not_null
    - unique
  - name: log_index
    description: Zero-based index of the log within the transaction.
    data_type: UInt32
  - name: event_name
    description: Name of the Oracle event emitted.
    data_type: String
  - name: event_signature
    description: Hash of the event signature.
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
    tests:
    - not_null
  - name: data
    description: Hex-encoded event data payload.
    data_type: String
  - name: chain_id
    description: EVM chain identifier.
    data_type: UInt64
  - name: block_timestamp
    description: UTC timestamp of the block containing the event.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: event_params
    description: JSON object containing parsed event parameters.
    data_type: JSON
  - name: success
    description: Indicator if the event was successfully processed.
    data_type: UInt8
  - name: insert_version
    description: Monotonic ingestion version (nanoseconds).
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - backedfi_oracle_events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bMSTR_Oracle_events
  description: Business-facing model capturing Oracle event data related to backedfi contracts, including logs, contract creation, and associated transaction details.
  columns:
  - name: block_number
    description: Block height at which the event or transaction was included.
    data_type: UInt32
    tests:
    - not_null
  - name: block_hash
    description: Hash of the block containing the event or transaction.
    data_type: String
  - name: transaction_index
    description: Zero-based index of the transaction within the block.
    data_type: UInt32
    tests:
    - not_null
  - name: log_index
    description: Zero-based index of the log within the transaction.
    data_type: UInt32
  - name: transaction_hash
    description: Hash identifying the transaction.
    data_type: String
    tests:
    - not_null
  - name: address
    description: Contract address emitting the event.
    data_type: String
    tests:
    - not_null
  - name: topic0
    description: First indexed topic, typically the event signature hash.
    data_type: String
  - name: topic1
    description: Second indexed topic.
    data_type: String
  - name: topic2
    description: Third indexed topic.
    data_type: String
  - name: topic3
    description: Fourth indexed topic.
    data_type: String
  - name: data
    description: Non-indexed event data payload in hex format.
    data_type: String
  - name: n_data_bytes
    description: Length of the `data` field in bytes.
    data_type: UInt32
  - name: chain_id
    description: EVM chain identifier.
    data_type: UInt64
  - name: block_timestamp
    description: UTC timestamp of the block containing the event.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: insert_version
    description: Monotonic ingestion version in nanoseconds.
    data_type: UInt64
  config:
    access: public
    tags:
    - backedfi_oracle_events
    materialized: incremental
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bNVDA_Oracle_events
  description: This model captures Oracle event logs related to backedfi and bNVDA contracts, including transaction details, logs, contract creation, and associated metadata.
  columns:
  - name: block_number
    description: Height of the block containing the event log.
    data_type: UInt32
    tests:
    - not_null
  - name: block_hash
    description: Hash of the block containing the event.
    data_type: String
  - name: transaction_index
    description: Zero-based index of the transaction within the block.
    data_type: UInt32
    tests:
    - not_null
  - name: log_index
    description: Zero-based index of the log within the transaction.
    data_type: UInt32
  - name: transaction_hash
    description: Hash identifying the transaction that emitted the event.
    data_type: String
    tests:
    - not_null
  - name: address
    description: Contract address that emitted the event.
    data_type: String
    tests:
    - not_null
  - name: topic0
    description: First indexed topic, typically the event signature hash.
    data_type: String
  - name: topic1
    description: Second indexed topic.
    data_type: String
  - name: topic2
    description: Third indexed topic.
    data_type: String
  - name: topic3
    description: Fourth indexed topic.
    data_type: String
  - name: data
    description: Non-indexed event data payload in hex.
    data_type: String
  - name: n_data_bytes
    description: Length of `data` in bytes.
    data_type: UInt32
  - name: chain_id
    description: EVM chain identifier.
    data_type: UInt64
  - name: block_timestamp
    description: UTC timestamp of the block containing the event.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: insert_version
    description: Monotonic ingestion version in nanoseconds.
    data_type: UInt64
  config:
    access: public
    tags:
    - backedfi_oracle_events
    materialized: incremental
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
