version: 2
models:
- name: contracts_backedfi_bCSPX_Oracle_events
  description: 'TODO: Add description for contracts_backedfi_bCSPX_Oracle_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - backedfi
  columns: []
- name: contracts_backedfi_bMSTR_Oracle_events
  description: 'TODO: Add description for contracts_backedfi_bMSTR_Oracle_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - backedfi
  columns: []
- name: contracts_backedfi_bHIGH_Oracle_events
  description: 'TODO: Add description for contracts_backedfi_bHIGH_Oracle_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - backedfi
  columns: []
- name: contracts_backedfi_TSLAx_Oracle_events
  description: 'TODO: Add description for contracts_backedfi_TSLAx_Oracle_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - backedfi
  columns: []
- name: contracts_backedfi_bIB01_Oracle_events
  description: 'TODO: Add description for contracts_backedfi_bIB01_Oracle_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - backedfi
  columns: []
- name: contracts_backedfi_bCOIN_Oracle_events
  description: 'TODO: Add description for contracts_backedfi_bCOIN_Oracle_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - backedfi
  columns: []
- name: contracts_backedfi_bC3M_Oracle_events
  description: 'TODO: Add description for contracts_backedfi_bC3M_Oracle_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - backedfi
  columns: []
- name: contracts_backedfi_bIBTA_Oracle_events
  description: 'TODO: Add description for contracts_backedfi_bIBTA_Oracle_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - backedfi
  columns: []
- name: contracts_backedfi_bNVDA_Oracle_events
  description: 'TODO: Add description for contracts_backedfi_bNVDA_Oracle_events'
  meta:
    sector: execution
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - contracts
    - backedfi
  columns: []
