version: 2
models:
- name: contracts_backedfi_TSLAx_Oracle_events
  description: This model contains events from the TSLAx Oracle contract (0x19972d1750F959dD14Cf436Da6360185BD54Cea0) on the Backed Finance platform.  The data is sourced from the `execution.logs` table and uses the `decode_logs` macro to parse event logs.
  columns:
  - name: block_number
    description: The block number where the event occurred.
    data_type: INTEGER
  - name: block_hash
    description: The hash of the block where the event occurred.
    data_type: STRING
  - name: block_timestamp
    description: The timestamp of the block where the event occurred.
    data_type: TIMESTAMP
  - name: transaction_hash
    description: The hash of the transaction that emitted the event.
    data_type: STRING
  - name: log_index
    description: The index of the log within the transaction.
    data_type: INTEGER
  - name: contract_address
    description: The address of the contract that emitted the event.
    data_type: STRING
  - name: event_name
    description: The name of the event emitted.
    data_type: STRING
  - name: event_data
    description: The data associated with the event, parsed as JSON.
    data_type: JSON
  tags:
  - backedfi_oracle_events
- name: contracts_backedfi_bC3M_Oracle_events
  description: Events emitted by the BackedFi Oracle contract (0x83Ec02059F686E747392A22ddfED7833bA0d7cE3).  This model uses the `decode_logs` macro to parse event logs from the `execution.logs` table.
  columns:
  - name: block_number
    description: Number of the block where the event was emitted.
    data_type: INTEGER
  - name: block_timestamp
    description: Timestamp of the block where the event was emitted.
    data_type: TIMESTAMP
  - name: log_index
    description: Index of the log within the block.
    data_type: INTEGER
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: STRING
  - name: contract_address
    description: Address of the contract that emitted the event.
    data_type: STRING
  - name: event_name
    description: Name of the event emitted.
    data_type: STRING
  - name: event_data
    description: Parsed JSON data from the event logs.
    data_type: JSON
  tags:
  - backedfi_oracle_events
  refs:
  - source('execution', 'logs')
- name: contracts_backedfi_bCOIN_Oracle_events
  description: Events emitted by the bCOIN Oracle contract (0x69B2D456e8830847f488afDde2a636BFB26218c6).  This model uses the `decode_logs` macro to parse event logs from the `execution.logs` table.
  columns:
  - name: block_number
    description: Number of the block where the event was emitted.
    data_type: INTEGER
  - name: block_hash
    description: Hash of the block where the event was emitted.
    data_type: STRING
  - name: block_timestamp
    description: Timestamp of the block where the event was emitted.
    data_type: TIMESTAMP
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: STRING
  - name: log_index
    description: Index of the log within the block.
    data_type: INTEGER
  - name: contract_address
    description: Address of the contract that emitted the event.
    data_type: STRING
  - name: event_name
    description: Name of the event emitted.
    data_type: STRING
  - name: event_data
    description: Parsed JSON data from the event.
    data_type: JSON
  tags:
  - backedfi_oracle_events
- name: contracts_backedfi_bCSPX_Oracle_events
  description: Events emitted by the bCSPX Oracle contract (0x1332D2b4dc83238B621b7F7D0F72fEc58Bb81A9b).  This model uses the `decode_logs` macro to parse event logs from the `execution.logs` table.
  columns:
  - name: block_number
    description: Number of the block where the event was emitted.
    data_type: INTEGER
  - name: block_timestamp
    description: Timestamp of the block where the event was emitted.
    data_type: TIMESTAMP
  - name: log_index
    description: Index of the log within the block.
    data_type: INTEGER
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: STRING
  - name: contract_address
    description: Address of the contract that emitted the event.
    data_type: STRING
  - name: event_name
    description: Name of the event emitted.
    data_type: STRING
  - name: event_data
    description: Parsed JSON data from the event logs.
    data_type: JSON
  tags:
  - backedfi_oracle_events
- name: contracts_backedfi_bHIGH_Oracle_events
  description: This model contains events from the bHIGH Oracle contract (0x9e8e794ad6ecdb6d5c7eabe059d30e907f58859b) decoded from the `execution.logs` table.  Data is incrementally updated using `delete+insert` strategy.
  columns:
  - name: block_number
    description: The block number where the event occurred.
    data_type: INTEGER
  - name: block_timestamp
    description: The timestamp of the block where the event occurred.
    data_type: TIMESTAMP
  - name: log_index
    description: The index of the log within the block.
    data_type: INTEGER
  - name: transaction_hash
    description: The hash of the transaction that emitted the event.
    data_type: STRING
  - name: contract_address
    description: The address of the contract that emitted the event.
    data_type: STRING
  - name: event_name
    description: The name of the event.
    data_type: STRING
  - name: event_data
    description: The decoded data of the event.
    data_type: JSON
  tags:
  - backedfi_oracle_events
- name: contracts_backedfi_bIB01_Oracle_events
  description: Events emitted by the BackedFi bIB01 Oracle contract (0x788d911ae7c95121a89a0f0306db65d87422e1de).  This model uses the `decode_logs` macro to parse event logs from the `execution.logs` table.
  columns:
  - name: block_number
    description: Number of the block where the event was emitted.
    data_type: INTEGER
  - name: block_timestamp
    description: Timestamp of the block where the event was emitted.
    data_type: TIMESTAMP
  - name: log_index
    description: Index of the log within the block.
    data_type: INTEGER
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: STRING
  - name: contract_address
    description: Address of the contract that emitted the event.
    data_type: STRING
  - name: event_name
    description: Name of the event emitted.
    data_type: STRING
  - name: event_data
    description: Parsed JSON data from the event logs.
    data_type: JSON
  tags:
  - backedfi_oracle_events
- name: contracts_backedfi_bIBTA_Oracle_events
  description: Events emitted by the bIBTA Oracle contract (0x9f9953d8a2c5366f098754d48f2d69b144ce03da).  Decoded using the `decode_logs` macro.
  columns:
  - name: block_number
    description: Number of the block where the event was emitted.
    data_type: INTEGER
  - name: block_timestamp
    description: Timestamp of the block where the event was emitted.
    data_type: TIMESTAMP
  - name: log_index
    description: Index of the log within the block.
    data_type: INTEGER
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: STRING
  - name: contract_address
    description: Address of the contract that emitted the event.
    data_type: STRING
  - name: event_name
    description: Name of the event emitted.
    data_type: STRING
  - name: event_data
    description: Parsed JSON data from the event logs.
    data_type: JSON
  tags:
  - backedfi_oracle_events
- name: contracts_backedfi_bMSTR_Oracle_events
  description: Events emitted by the BackedFi bMSTR Oracle contract (0xC8429803DCdA7DF86822aB173ea285C10BF1EB66).  This model decodes event logs from the `execution.logs` table.
  columns:
  - name: block_number
    description: Number of the block where the event was emitted.
    data_type: INTEGER
  - name: block_timestamp
    description: Timestamp of the block where the event was emitted.
    data_type: TIMESTAMP
  - name: log_index
    description: Index of the log within the block.
    data_type: INTEGER
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: STRING
  - name: contract_address
    description: Address of the contract that emitted the event.
    data_type: STRING
  - name: event_name
    description: Name of the event emitted.
    data_type: STRING
  - name: event_data
    description: Parsed JSON data from the event.
    data_type: JSON
  tags:
  - backedfi_oracle_events
  materialized: incremental
  incremental_strategy: delete+insert
- name: contracts_backedfi_bNVDA_Oracle_events
  description: Events emitted by the BackedFi bNVDA Oracle contract (0x1D3be4d05Eba2aA6c4eEdE85a74f491C31766E64).  This model uses the `decode_logs` macro to parse event logs from the `execution.logs` table.
  columns:
  - name: block_number
    description: Number of the block where the event was emitted.
    data_type: INTEGER
  - name: block_timestamp
    description: Timestamp of the block where the event was emitted.
    data_type: TIMESTAMP
  - name: log_index
    description: Index of the log within the block.
    data_type: INTEGER
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: STRING
  - name: contract_address
    description: Address of the contract that emitted the event.
    data_type: STRING
  - name: event_name
    description: Name of the event emitted.
    data_type: STRING
  - name: event_data
    description: Parsed JSON data from the event logs.
    data_type: JSON
  tags:
  - backedfi_oracle_events
