version: 2
models:
- name: yields_sdai_rate_daily
  description: 'TODO: Add description for yields_sdai_rate_daily'
  meta:
    sector: execution
    refs:
    - contracts_sdai_events
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - execution
    - yields
    - transformations
  columns:
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: sdai_conversion
    description: 'TODO: Add description for sdai_conversion'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - date
      - sdai_conversion
