version: 2
models:
- name: yields_sdai_rate_daily
  description: This model calculates the daily rate of change in the SDai conversion rate.  It uses a calendar table to ensure daily granularity, even when no events occur on a given day. The rate is calculated as the difference between consecutive days' median conversion rates, floored to 12.  Incremental strategy is used for efficiency.
  columns:
  - name: date
    description: The date of the conversion rate.
    data_type: DATE
  - name: sdai_conversion
    description: The median SDai conversion rate for the day.
    data_type: FLOAT
  - name: rate
    description: The daily change in the SDai conversion rate, floored to 12.
    data_type: INT64
