version: 2
models:

- name: execution_state_address_current
  description: Current execution state of addresses, aggregating relevant data from execution layer tables.
  columns:
  - name: address
    description: Ethereum address (20-byte hex string) representing the account or contract.
    data_type: String
    tests:
    - not_null
    - unique
  - name: bytes
    description: Sum of bytes_diff values (total bytes changed) for the address.
    data_type: UInt64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: execution_state_size_daily
  description: Daily snapshot of execution state size metrics, including bytes difference and cumulative size.
  columns:
  - name: date
    description: Date of the snapshot in 'YYYY-MM-DD' format.
    data_type: Date
    tests:
    - not_null
  - name: bytes_diff
    description: Difference in execution state size bytes compared to previous day.
    data_type: UInt64
  config:
    access: public
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_state_full_size_daily
  description: Daily snapshot of the full size of API execution state in bytes, aggregated from the raw data sources for business analysis.
  columns:
  - name: date
    description: Date of the snapshot in YYYY-MM-DD format.
    data_type: Date
  - name: value
    description: Size of the API execution state in gigabytes.
    data_type: Float64
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - state
    - size
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: fct_execution_state_full_size_daily
  description: Business-facing table summarizing daily total bytes of execution state size.
  columns:
  - name: date
    description: Date of the record (YYYY-MM-DD).
    data_type: Date
  - name: bytes
    description: Cumulative sum of bytes_diff over time (bytes).
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - execution
    - state
    - size
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
