version: 2
models:

- name: execution_state_address_current
  description: Current execution state of addresses, aggregating relevant data from execution layer tables.
  columns:
  - name: address
    description: Ethereum address (20-byte hex string) representing the account or contract.
    data_type: String
    tests:
    - not_null
    - unique
  - name: bytes
    description: Sum of bytes_diff values (total bytes changed) for the address.
    data_type: UInt64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: execution_state_size_daily
  description: Daily snapshot of execution state size metrics, including bytes difference and cumulative size.
  columns:
  - name: date
    description: Date of the snapshot in 'YYYY-MM-DD' format.
    data_type: Date
    tests:
    - not_null
  - name: bytes_diff
    description: Difference in execution state size bytes compared to previous day.
    data_type: UInt64
  config:
    access: public
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: api_execution_state_full_size_daily
  description: Daily aggregated data showing the size of API execution states, derived from raw execution data. Includes date and value in gigabytes.
  columns:
  - name: date
    description: Calendar date of the aggregation (UTC).
    data_type: Date
    tests:
    - not_null
  - name: value
    description: Size of the execution state in gigabytes (GB).
    data_type: Float64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: fct_execution_state_full_size_daily
  description: Aggregated daily size of execution states, including cumulative bytes.
  columns:
  - name: date
    description: Calendar date for the record, in YYYY-MM-DD format.
    data_type: Date
    tests:
    - not_null
  - name: bytes
    description: Cumulative size in bytes of execution state data up to the date.
    data_type: UInt64
  config:
    access: public
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
