version: 2
models:

- name: api_execution_state_full_size_daily
  description: The api_execution_state_full_size_daily model provides daily aggregated data on the size of API execution states, facilitating trend analysis and capacity planning.
  columns:

  - name: date
    description: The specific calendar date for the recorded data point.
    data_type: Date
    tests:
    - not_null

  - name: value
    description: The size of the execution state in gigabytes, calculated by dividing bytes by 10^9.
    data_type: Float64
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.777030'
    _generated_fields:
    - description
    - columns.date.description
    - config.tags
    - config.materialized
    - columns.value.description
    - columns.value.data_type
    - columns.date.data_type

- name: fct_execution_state_full_size_daily
  description: The fct_execution_state_full_size_daily model aggregates daily cumulative bytes of execution state data, providing insights into storage size trends over time for operational monitoring.
  columns:

  - name: date
    description: The date for which the size data is recorded, representing a daily timestamp.
    data_type: Date
    tests:
    - not_null

  - name: bytes
    description: The total cumulative size in bytes of execution state data up to the specified date.
    data_type: UInt64
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.777076'
    _generated_fields:
    - description
    - columns.date.description
    - columns.bytes.data_type
    - config.tags
    - config.materialized
    - columns.bytes.description
    - columns.date.data_type

