version: 2
models:

- name: execution_state_address_current
  description: Current execution state of addresses, aggregating relevant data from execution layer tables.
  columns:

  - name: address
    description: Ethereum address (20-byte hex string) representing the account or contract.
    data_type: String
    tests:
    - not_null
    - unique

  - name: bytes
    description: Sum of bytes_diff values (total bytes changed) for the address.
    data_type: UInt64
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer

- name: execution_state_size_daily
  description: Daily snapshot of execution state size metrics, including bytes difference and cumulative size.
  columns:

  - name: date
    description: Date of the snapshot in 'YYYY-MM-DD' format.
    data_type: Date
    tests:
    - not_null

  - name: bytes_diff
    description: Difference in execution state size bytes compared to previous day.
    data_type: UInt64
  config:
    access: public
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer

- name: api_execution_state_full_size_daily
  description: The api_execution_state_full_size_daily model provides daily aggregated data on the size of API execution states, facilitating trend analysis and capacity planning.
  columns:

  - name: date
    description: The specific calendar date for the recorded data point.
    data_type: Date
    tests:
    - not_null

  - name: value
    description: The size of the execution state in gigabytes, calculated by dividing bytes by 10^9.
    data_type: Float64
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - tier1
    - api:state_size
    - granularity:daily
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.777030'
    _generated_fields:
    - description
    - columns.date.description
    - config.tags
    - config.materialized
    - columns.value.description
    - columns.value.data_type
    - columns.date.data_type

- name: fct_execution_state_full_size_daily
  description: The fct_execution_state_full_size_daily model aggregates daily cumulative bytes of execution state data, providing insights into storage size trends over time for operational monitoring.
  columns:

  - name: date
    description: The date for which the size data is recorded, representing a daily timestamp.
    data_type: Date
    tests:
    - not_null

  - name: bytes
    description: The total cumulative size in bytes of execution state data up to the specified date.
    data_type: UInt64
  config:
    access: public
    tags:
    - production
    - execution
    - state
    - size
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.777076'
    _generated_fields:
    - description
    - columns.date.description
    - columns.bytes.data_type
    - config.tags
    - config.materialized
    - columns.bytes.description
    - columns.date.data_type
