version: 2
models:

- name: contracts_Realitio_v2_1_calls
  description: A record of calls made to the Realitio v2.1 contract, including transaction details, block information, and call-specific data for analysis and auditing purposes.
  columns:
  - name: transaction_hash
    description: Unique identifier of the transaction in which the call was made.
    data_type: String
  - name: block_number
    description: The block height at which the transaction was included.
    data_type: UInt64
  - name: block_timestamp
    description: The timestamp when the block was mined, in UTC.
    data_type: DateTime64(0, 'UTC')
  - name: caller_address
    description: Ethereum address of the caller initiating the call.
    data_type: String
  - name: contract_address
    description: Ethereum address of the contract being called.
    data_type: String
  - name: call_data
    description: Encoded call data payload sent in the transaction.
    data_type: String
  - name: call_value
    description: Amount of wei transferred with the call.
    data_type: String
  - name: call_gas
    description: Gas limit for the call.
    data_type: UInt64
  - name: call_gas_price
    description: Gas price in wei for the call.
    data_type: String
  - name: call_nonce
    description: Transaction nonce for the caller.
    data_type: UInt64
  - name: call_success
    description: Indicates if the call was successful.
    data_type: String
  - name: call_return_data
    description: Return data from the call, if any.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - realitio
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_Realitio_v2_1_events
  description: Events emitted by the Realitio v2.1 contract, capturing transaction details, block information, and event-specific data for analytics and monitoring.
  columns:
  - name: transaction_hash
    description: Unique hash identifying the transaction (hex string).
    data_type: String
  - name: block_number
    description: Block number in which the event was included.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp when the block was mined (UTC).
    data_type: DateTime
  - name: log_index
    description: Index of the event log within the block.
    data_type: UInt64
  - name: event_type
    description: Type of the event emitted (e.g., 'AnswerRevealed', 'QuestionCreated').
    data_type: String
  - name: question_id
    description: Identifier for the question associated with the event.
    data_type: String
  - name: answer
    description: The answer submitted or revealed, if applicable.
    data_type: String
  - name: question_content
    description: Content/details of the question.
    data_type: String
  - name: reward
    description: Reward amount in wei associated with the question.
    data_type: String
  - name: final_answer
    description: Final answer revealed for the question.
    data_type: String
  - name: final_answer_timestamp
    description: Timestamp when the final answer was revealed (UTC).
    data_type: DateTime
  - name: is_finalized
    description: Indicates if the question has been finalized (true/false).
    data_type: String
  - name: created_at
    description: Record creation timestamp in UTC.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - realitio
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
