version: 2
models:

- name: contracts_Realitio_v2_1_calls
  description: This model captures call data related to Realitio v2.1 contracts, including transaction details, contract addresses, and call-specific information for analysis and reporting.
  columns:
  - name: transaction_hash
    description: Unique hash identifier for each transaction
    data_type: String
  - name: block_number
    description: Block number at which the transaction was included
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp when the block was mined
    data_type: DateTime64(0, 'UTC')
  - name: contract_address
    description: Address of the contract involved in the call
    data_type: String
  - name: caller_address
    description: Address initiating the call
    data_type: String
  - name: call_data
    description: Encoded data payload of the call
    data_type: String
  - name: call_value
    description: Amount transferred in wei during the call
    data_type: String
  - name: call_gas
    description: Gas used for the call
    data_type: UInt64
  - name: call_gas_price
    description: Gas price in wei
    data_type: String
  - name: call_nonce
    description: Transaction nonce for the caller
    data_type: UInt64
  - name: output_json_type
    description: Indicates if the output is in JSON format
    data_type: UInt64
  - name: output_data
    description: Output data from the call, stored as JSON
    data_type: JSON
  config:
    materialized: incremental
    access: public
    tags:
    - production
    - contracts
    - realitio
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_Realitio_v2_1_events
  description: This table captures event data related to Realitio v2.1 contracts, including transaction details, block information, and event-specific data points.
  columns:
  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64
  - name: block_timestamp
    description: The timestamp when the block was mined (UTC).
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block.
    data_type: UInt64
  - name: transaction_hash
    description: The hash of the transaction that emitted the event.
    data_type: String
  - name: event_name
    description: The name of the event emitted.
    data_type: String
  - name: question_id
    description: Identifier for the question associated with the event.
    data_type: String
  - name: answer
    description: The answer provided in the event, if applicable.
    data_type: String
  - name: answerer
    description: Address of the account that provided the answer.
    data_type: String
  - name: bond_amount
    description: The bond amount in wei associated with the event.
    data_type: String
  - name: question_content
    description: The content of the question asked.
    data_type: String
  - name: question_timestamp
    description: The timestamp when the question was created (UTC).
    data_type: DateTime
  - name: event_data
    description: Additional event-specific data in JSON format.
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - realitio
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
