version: 2
models:

- name: contracts_Realitio_v2_1_calls
  description: The contracts_Realitio_v2_1_calls model captures and processes call interactions from the Realitio v2.1 smart contract, enabling analysis of user queries and responses over time.
  columns:

  - name: transaction_hash
    description: Unique identifier for each transaction in the Ethereum network.
    data_type: String

  - name: block_number
    description: The block number containing the transaction.
    data_type: UInt64

  - name: block_timestamp
    description: The timestamp when the block was mined, in UTC.
    data_type: DateTime

  - name: log_index
    description: The index of the log within the block.
    data_type: UInt64

  - name: caller
    description: Address of the entity initiating the call.
    data_type: String

  - name: contract_address
    description: Address of the contract being called.
    data_type: String

  - name: call_data
    description: Encoded data payload of the call.
    data_type: String

  - name: response_data
    description: Response data returned from the call.
    data_type: String

  - name: call_type
    description: Type of call made, e.g., 'call', 'delegatecall'.
    data_type: String

  - name: gas_used
    description: Amount of gas used for the call, in wei.
    data_type: UInt64

  - name: success
    description: Whether the call was successful (true/false).
    data_type: String

  - name: created_at
    description: Timestamp when the record was created in the database.
    data_type: DateTime
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.450972'
    _generated_fields:
    - description
    - config.tags
    - config.materialized
  config:
    tags:
    - production
    - contracts
    - realitio
    - calls
    materialized: incremental

- name: contracts_Realitio_v2_1_events
  description: The `contracts_Realitio_v2_1_events` model captures and processes event logs related to Realitio V2.1 contract interactions, enabling analysis of contract activity over time.
  columns:

  - name: block_timestamp
    description: Timestamp of the block when the event was recorded.
    data_type: DateTime

  - name: log_index
    description: Index of the log within the block (order of logs).
    data_type: UInt64

  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String

  - name: event_name
    description: Name of the event emitted.
    data_type: String

  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String

  - name: question_id
    description: Unique identifier for the question associated with the event.
    data_type: String

  - name: answer
    description: The answer provided in the event, if applicable.
    data_type: String

  - name: answerer
    description: Address of the account that provided the answer.
    data_type: String

  - name: answer_timestamp
    description: Timestamp when the answer was submitted.
    data_type: DateTime

  - name: question_content
    description: Content of the question posed.
    data_type: String

  - name: question_timestamp
    description: Timestamp when the question was created.
    data_type: DateTime

  - name: status
    description: Current status of the question (e.g., open, answered, canceled).
    data_type: String

  - name: created_at
    description: Record creation timestamp.
    data_type: DateTime

  - name: updated_at
    description: Record last update timestamp.
    data_type: DateTime
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.451032'
    _generated_fields:
    - description
    - config.tags
    - config.materialized
  config:
    tags:
    - production
    - contracts
    - realitio
    - events
    materialized: incremental
