version: 2
models:

- name: contracts_Realitio_v2_1_calls
  description: This model captures call data related to Realitio v2.1 contracts, including transaction details, block information, and call-specific attributes for analysis and reporting purposes.
  columns:
  - name: transaction_hash
    description: Unique identifier of the transaction in which the call occurred.
    data_type: String
  - name: block_number
    description: Number of the block containing the transaction.
    data_type: UInt64
  - name: block_timestamp
    description: Timestamp when the block was mined, in UTC.
    data_type: DateTime64(0, 'UTC')
  - name: caller_address
    description: Address of the caller initiating the call.
    data_type: String
  - name: contract_address
    description: Address of the contract being called.
    data_type: String
  - name: call_data
    description: Encoded data payload of the call.
    data_type: String
  - name: output_json_type
    description: Indicates if the output is in JSON format; true or false.
    data_type: String
  - name: output_data
    description: The output data returned from the call.
    data_type: String
  - name: call_success
    description: Boolean indicating if the call was successful.
    data_type: String
  - name: gas_used
    description: Amount of gas used for the call, in wei.
    data_type: String
  - name: call_type
    description: Type of the call, e.g., 'call', 'delegatecall'.
    data_type: String
  - name: created_at
    description: Timestamp when the record was created in the database.
    data_type: DateTime64(0, 'UTC')
  - name: updated_at
    description: Timestamp when the record was last updated.
    data_type: DateTime64(0, 'UTC')
  config:
    materialized: incremental
    access: public
    tags:
    - production
    - contracts
    - realitio
    - calls
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_Realitio_v2_1_events
  description: This model captures Realitio V2.1 event logs related to contract interactions, including timestamps, addresses, and event-specific data.
  columns:
  - name: block_timestamp
    description: The timestamp when the block was mined (UTC)
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block (sequence number)
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction associated with the event
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String
  - name: event_type
    description: Type of the event emitted (e.g., 'AnswerSubmitted', 'QuestionCreated')
    data_type: String
  - name: question_id
    description: Unique identifier for the question related to the event
    data_type: String
  - name: answer
    description: The answer submitted or relevant to the event
    data_type: String
  - name: answerer
    description: Address of the entity submitting the answer
    data_type: String
  - name: question_content
    description: Content of the question posed in the event
    data_type: String
  - name: question_created_at
    description: Timestamp when the question was created (UTC)
    data_type: DateTime
  - name: answer_submitted_at
    description: Timestamp when the answer was submitted (UTC)
    data_type: DateTime
  - name: block_number
    description: The number of the block containing the event
    data_type: UInt64
  - name: gas_price
    description: Gas price at the time of the transaction (wei)
    data_type: String
  - name: gas_used
    description: Gas used by the transaction
    data_type: UInt64
  - name: event_data
    description: Raw event data in JSON format
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - realitio
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
