version: 2

sources:
  - name: crawlers_data
    schema: crawlers_data
    tables:
      - name: dune_labels
      - name: dune_prices
  - name: playground_max
    schema: playground_max
    tables:
      - name: dune_bridge_flows