version: 2
models:

- name: fct_yields_sdai_apy_daily
  description: This view aggregates daily SDAI yield data to compute annual percentage yields (APY) and their moving averages and medians over specified windows, facilitating trend analysis of yield performance.
  columns:

  - name: date
    description: The date of the yield observation, formatted as a date string.
    data_type: Date
    tests:
    - not_null

  - name: apy
    description: The calculated annual percentage yield (APY) for the given date, expressed as a percentage (0-100%).
    data_type: Float64

  - name: apy_7DMA
    description: The 7-day moving average of the APY, providing a smoothed yield trend over the past week, expressed as a percentage.
    data_type: Float64

  - name: apy_30DMA
    description: The 30-day moving average of the APY, indicating longer-term yield trends, expressed as a percentage.
    data_type: Float64

  - name: apy_7DMM
    description: The 7-day moving median of the APY, offering a robust central tendency measure over the past week, expressed as a percentage.
    data_type: Float64

  - name: apy_30DMM
    description: The 30-day moving median of the APY, reflecting longer-term median yield performance, expressed as a percentage.
    data_type: Float64

  - name: label
    description: Label indicating the type of APY value ('Daily', '7DMA', '30DMA', '7DMM', '30DMM').
    data_type: String
  config:
    access: public
    tags:
    - production
    - execution
    - yields
    - sdai_apy
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:59.153348'
    _generated_fields:
    - description
    - columns.apy_30DMM.data_type
    - columns.apy_7DMM.data_type
    - columns.apy.description
    - columns.date.description
    - columns.apy_30DMA.data_type
    - config.tags
    - config.materialized
    - columns.apy_7DMM.description
    - columns.apy_7DMA.data_type
    - columns.apy.data_type
    - columns.apy_30DMA.description
    - columns.apy_30DMM.description
    - columns.apy_7DMA.description
    - columns.date.data_type
