version: 2
models:

- name: yields_sdai_apy_daily
  description: Business-facing table providing daily and aggregated annual percentage yield (APY) metrics derived from the yields_sdai_rate_daily source, including 7-day and 30-day moving averages and medians, with labels indicating the type of metric.
  columns:
  - name: date
    description: Date of the yield data in YYYY-MM-DD format.
    data_type: DateTime
    tests:
    - not_null
  - name: apy
    description: Daily APY percentage (annualized), in percent units.
    data_type: Float64
  - name: label
    description: 'Label indicating the metric type: ''Daily'', ''7DMA'', ''30DMA'', ''7DMM'', or ''30DMM''.'
    data_type: String
    tests:
    - not_null
  - name: apy_7DMA
    description: 7-day moving average of APY, in percent units.
    data_type: Float64
  - name: apy_30DMA
    description: 30-day moving average of APY, in percent units.
    data_type: Float64
  - name: apy_7DMM
    description: 7-day median of APY, in percent units.
    data_type: Float64
  - name: apy_30DMM
    description: 30-day median of APY, in percent units.
    data_type: Float64
  config:
    access: public
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_yields_sdai_apy_daily
  description: Daily calculated yields and moving averages for SDai APY, including 7-day and 30-day DMA and DMM metrics.
  columns:
  - name: date
    description: Date of the yield record (UTC).
    data_type: DateTime
  - name: apy
    description: Annual Percentage Yield (APY) in percent, calculated as floor of compounded rate over 365 days, scaled by 100.
    data_type: Float64
  - name: apy_7DMM
    description: 7-day median of APY, smoothed over 7 days, scaled by 100.
    data_type: Float64
  - name: apy_30DMM
    description: 30-day median of APY, smoothed over 30 days, scaled by 100.
    data_type: Float64
  - name: apy_7DMA
    description: 7-day moving average of APY, scaled by 100.
    data_type: Float64
  - name: apy_30DMA
    description: 30-day moving average of APY, scaled by 100.
    data_type: Float64
  - name: label
    description: Label indicating the type of APY value ('Daily', '7DMA', '30DMA', '7DMM', '30DMM').
    data_type: String
  config:
    access: public
    tags:
    - production
    - execution
    - yields
    - sdai_apy
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
