version: 2
models:

- name: contracts_backedfi_TSLAx_Oracle_events
  description: This model captures Oracle events related to TSLA on the BackedFi platform, including transaction details, timestamps, and related metadata.
  columns:
  - name: block_timestamp
    description: The timestamp when the block was mined, in UTC.
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block, used to order logs.
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash identifying the transaction associated with the event.
    data_type: String
  - name: contract_address
    description: The address of the contract emitting the event.
    data_type: String
  - name: event_type
    description: The type of Oracle event (e.g., 'PriceUpdate', 'Settlement').
    data_type: String
  - name: event_value
    description: The value associated with the event, such as price or amount.
    data_type: String
  - name: event_timestamp
    description: The timestamp when the event was emitted, in UTC.
    data_type: DateTime
  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64
  - name: transaction_index
    description: The index of the transaction within the block.
    data_type: UInt64
  - name: sender_address
    description: Address of the sender initiating the transaction.
    data_type: String
  - name: receiver_address
    description: Address of the receiver, if applicable.
    data_type: String
  - name: gas_price
    description: Gas price paid for the transaction, in wei.
    data_type: String
  - name: gas_used
    description: Amount of gas used by the transaction.
    data_type: String
  - name: status
    description: Status of the transaction ('success', 'failed', etc.).
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bC3M_Oracle_events
  description: This model captures Oracle event logs related to BackedFi, including transaction details, block information, and event-specific data for analysis and reporting purposes.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was logged, in UTC.
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block, used to order logs.
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash identifying the transaction associated with the event.
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  - name: event_name
    description: Name of the event emitted.
    data_type: String
  - name: event_data
    description: JSON object containing event-specific data payload.
    data_type: JSON
  - name: sender_address
    description: Address of the sender involved in the event.
    data_type: String
  - name: recipient_address
    description: Address of the recipient involved in the event.
    data_type: String
  - name: amount
    description: Amount transferred or involved in the event, in wei.
    data_type: String
  - name: token_symbol
    description: Symbol of the token involved.
    data_type: String
  - name: block_hash
    description: Hash of the block containing the event.
    data_type: String
  - name: created_at
    description: Timestamp when the record was created in the database.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bCOIN_Oracle_events
  description: This model captures Oracle event logs related to backedfi bCOIN, including transaction details, block information, and event-specific data for analytics and reporting purposes.
  columns:
  - name: block_timestamp
    description: Timestamp of the block containing the event, in UTC.
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block, used to order events.
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: event_name
    description: Name of the Oracle event.
    data_type: String
  - name: event_data
    description: JSON object containing event-specific data.
    data_type: JSON
  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  - name: sender_address
    description: Address of the sender initiating the transaction.
    data_type: String
  - name: amount_wei
    description: Amount involved in the event, denominated in wei.
    data_type: String
  - name: status
    description: Status of the event, e.g., 'success' or 'failure'.
    data_type: String
  - name: created_at
    description: Timestamp when the record was created in the system.
    data_type: DateTime
  - name: updated_at
    description: Timestamp when the record was last updated.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bCSPX_Oracle_events
  description: This model captures Oracle events related to backedfi's bCSPX contract, including timestamped logs and transaction details.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was logged
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash identifying the transaction
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String
  - name: event_name
    description: Name of the emitted event
    data_type: String
  - name: event_data
    description: JSON object containing event-specific data
    data_type: JSON
  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64
  - name: sender_address
    description: Address initiating the transaction
    data_type: String
  - name: gas_used
    description: Amount of gas used in the transaction (wei)
    data_type: String
  - name: status
    description: Status of the transaction (e.g., success or failure)
    data_type: String
  - name: created_at
    description: Timestamp when the record was created in the database
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bHIGH_Oracle_events
  description: This model captures Oracle events related to the backedfi protocol, including transaction details, block information, and event-specific data.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block (order of logs)
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction associated with the event
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String
  - name: event_name
    description: Name of the Oracle event
    data_type: String
  - name: event_data
    description: JSON containing event-specific data
    data_type: JSON
  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64
  - name: sender_address
    description: Address initiating the transaction
    data_type: String
  - name: amount_in_wei
    description: Amount associated with the event in wei
    data_type: String
  - name: status
    description: Status of the event (e.g., success, failed)
    data_type: String
  - name: gas_used
    description: Gas used for the transaction
    data_type: UInt64
  - name: gas_price
    description: Gas price in wei
    data_type: String
  - name: block_hash
    description: Hash of the block containing the event
    data_type: String
  - name: timestamp
    description: Alias for block_timestamp for convenience
    data_type: DateTime
  - name: log_data
    description: Raw log data in JSON format
    data_type: JSON
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bIB01_Oracle_events
  description: This model captures Oracle event logs related to BackedFi, including transaction details, block information, and event-specific data for analysis and reporting.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was recorded
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block, used to order logs
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash identifying the transaction
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String
  - name: event_name
    description: Name of the Oracle event emitted
    data_type: String
  - name: event_data
    description: JSON object containing event-specific data
    data_type: JSON
  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64
  - name: sender_address
    description: Address of the transaction sender
    data_type: String
  - name: receiver_address
    description: Address of the transaction receiver, if applicable
    data_type: String
  - name: amount_wei
    description: Amount transferred in wei, may overflow 64-bit, stored as String
    data_type: String
  - name: token_id
    description: Identifier of the token involved, if applicable
    data_type: String
  - name: block_hash
    description: Hash of the block containing the event
    data_type: String
  - name: gas_used
    description: Gas used for the transaction, in wei
    data_type: String
  - name: status
    description: Status of the transaction (e.g., success, failure)
    data_type: String
  - name: timestamp
    description: Alias for block_timestamp for convenience
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bIBTA_Oracle_events
  description: This model captures Oracle event logs related to BackedFi, including transaction details, block information, and event-specific data for analysis and reporting.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was recorded
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block, used to order logs
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash identifying the transaction
    data_type: String
  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64
  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String
  - name: event_name
    description: Name of the Oracle event
    data_type: String
  - name: oracle_id
    description: Identifier for the Oracle instance
    data_type: String
  - name: data
    description: Event-specific data payload in JSON format
    data_type: JSON
  - name: sender
    description: Address of the sender initiating the transaction
    data_type: String
  - name: gas_price
    description: Gas price in wei at the time of transaction
    data_type: String
  - name: gas_used
    description: Gas used for the transaction
    data_type: UInt64
  - name: status
    description: Transaction status (e.g., success, failure)
    data_type: String
  - name: block_hash
    description: Hash of the block containing the event
    data_type: String
  - name: created_at
    description: Timestamp when the record was created in the database
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bMSTR_Oracle_events
  description: This model captures Oracle events related to BackedFi's bMSTR token, including transaction details, block info, and event-specific data for analysis.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted, in UTC.
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block, used to order events.
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash of the transaction associated with the event.
    data_type: String
  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: event_name
    description: Name of the Oracle event.
    data_type: String
  - name: oracle_id
    description: Identifier for the Oracle involved in the event.
    data_type: String
  - name: data
    description: Event-specific data payload, formatted as JSON.
    data_type: JSON
  - name: amount
    description: Amount involved in the event, in wei.
    data_type: String
  - name: sender
    description: Address of the sender initiating the event.
    data_type: String
  - name: recipient
    description: Address of the recipient involved in the event.
    data_type: String
  - name: block_hash
    description: Hash of the block containing the event.
    data_type: String
  - name: created_at
    description: Timestamp when the record was created in the database.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bNVDA_Oracle_events
  description: This model captures Oracle events related to backedfi's bNVDA contract, including timestamped logs and transaction details.
  columns:
  - name: block_timestamp
    description: The timestamp when the block was mined, in UTC.
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block, used to order logs.
    data_type: UInt64
  - name: transaction_hash
    description: The hash of the transaction associated with the event.
    data_type: String
  - name: contract_address
    description: The address of the Oracle contract emitting the event.
    data_type: String
  - name: event_type
    description: The type of Oracle event (e.g., 'Update', 'Response').
    data_type: String
  - name: event_data
    description: The JSON payload containing event-specific data.
    data_type: JSON
  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64
  - name: log_data
    description: Raw log data in hexadecimal format.
    data_type: String
  - name: sender_address
    description: Address of the sender initiating the transaction.
    data_type: String
  - name: status
    description: The status of the transaction or event (e.g., 'success', 'failed').
    data_type: String
  - name: block_time
    description: The timestamp of the block in UTC.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
