version: 2
models:

- name: contracts_backedfi_TSLAx_Oracle_events
  description: The `contracts_backedfi_TSLAx_Oracle_events` model captures and processes blockchain event logs related to the TSLAx contract on BackedFi, enabling analysis of on-chain activities and oracle interactions over time.
  columns:

  - name: block_timestamp
    description: The timestamp when the block was mined, in UTC.
    data_type: DateTime

  - name: log_index
    description: The index of the log within the block, indicating order.
    data_type: UInt64

  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String

  - name: event_type
    description: The type of the Oracle event (e.g., 'PriceUpdate', 'Settlement').
    data_type: String

  - name: event_data
    description: JSON object containing event-specific data.
    data_type: JSON

  - name: contract_address
    description: The address of the contract emitting the event.
    data_type: String

  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64

  - name: transaction_index
    description: The index of the transaction within the block.
    data_type: UInt64

  - name: sender_address
    description: Address of the transaction sender.
    data_type: String

  - name: receiver_address
    description: Address of the transaction receiver.
    data_type: String
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2025-01-01"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.552078'
    _generated_fields:
    - description
    - config.tags
    - config.materialized

- name: contracts_backedfi_bC3M_Oracle_events
  description: This model captures and processes blockchain event logs related to the BackedFi contracts from the Oracle source, enabling analysis of contract interactions over time.
  columns:

  - name: block_timestamp
    description: Timestamp of the block when the event was recorded
    data_type: DateTime

  - name: log_index
    description: Log index within the block, used to order events
    data_type: UInt64

  - name: transaction_hash
    description: Hash of the transaction that emitted the event
    data_type: String

  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String

  - name: event_name
    description: Name of the Oracle event
    data_type: String

  - name: oracle_id
    description: Identifier for the Oracle instance
    data_type: String

  - name: round_id
    description: Identifier for the specific round of the Oracle
    data_type: String

  - name: answer
    description: The answer provided by the Oracle, in wei or relevant units
    data_type: String

  - name: answered_in_round
    description: Round number in which the answer was provided
    data_type: String

  - name: created_at
    description: Timestamp when the event record was created in the system
    data_type: DateTime

  - name: updated_at
    description: Timestamp when the event record was last updated
    data_type: DateTime
  meta:
    owner: analytics-team
    authoritative: false
    full_refresh:
      start_date: "2023-07-01"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.552136'
    _generated_fields:
    - description
    - config.tags
    - config.materialized

- name: contracts_backedfi_bCOIN_Oracle_events
  description: This model captures and stores Oracle event logs related to the BackedFi platform, enabling analysis of contract interactions and event occurrences over time.
  columns:

  - name: block_timestamp
    description: Timestamp of the block when the event was emitted (UTC)
    data_type: DateTime

  - name: log_index
    description: Index of the log within the block (sequence number)
    data_type: UInt64

  - name: transaction_hash
    description: Unique hash of the transaction associated with the event
    data_type: String

  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String

  - name: event_name
    description: Name of the Oracle event
    data_type: String

  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64

  - name: amount_wei
    description: Amount involved in the event, in wei
    data_type: String

  - name: token_address
    description: Address of the token involved in the event
    data_type: String

  - name: sender_address
    description: Address initiating the transaction
    data_type: String

  - name: receiver_address
    description: Address receiving tokens or assets
    data_type: String

  - name: additional_data
    description: JSON containing extra event details
    data_type: JSON
  meta:
    owner: analytics-team
    authoritative: false
    full_refresh:
      start_date: "2025-01-01"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.552178'
    _generated_fields:
    - description
    - config.tags
    - config.materialized

- name: contracts_backedfi_bCSPX_Oracle_events
  description: The `contracts_backedfi_bCSPX_Oracle_events` model captures and processes blockchain event logs related to the BackedFi bCSPX Oracle contract, enabling analysis of oracle interactions and event occurrences over time.
  columns:

  - name: block_timestamp
    description: The timestamp of the block when the event was emitted.
    data_type: DateTime

  - name: log_index
    description: The index of the log within the block (sequence number).
    data_type: UInt64

  - name: transaction_hash
    description: Unique hash of the transaction that emitted the event.
    data_type: String

  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String

  - name: event_name
    description: Name identifier of the event type.
    data_type: String

  - name: event_data
    description: JSON object containing event-specific data.
    data_type: JSON

  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64

  - name: sender_address
    description: Address of the sender involved in the event.
    data_type: String

  - name: recipient_address
    description: Address of the recipient involved in the event.
    data_type: String

  - name: amount
    description: Amount transferred or involved, in wei.
    data_type: String

  - name: gas_used
    description: Gas used for the transaction.
    data_type: UInt64

  - name: gas_price
    description: Gas price at the time of transaction, in wei.
    data_type: String

  - name: block_hash
    description: Hash of the block containing the event.
    data_type: String

  - name: log_topics
    description: List of topics associated with the log.
    data_type: JSON
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2024-11-01"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.552226'
    _generated_fields:
    - description
    - config.tags
    - config.materialized

- name: contracts_backedfi_bHIGH_Oracle_events
  description: The `contracts_backedfi_bHIGH_Oracle_events` model captures and processes blockchain event logs related to the BackedFi protocol, enabling analysis of contract interactions and event occurrences over time.
  columns:

  - name: block_timestamp
    description: Timestamp of the block when the event was recorded.
    data_type: DateTime

  - name: log_index
    description: Index of the log within the block, used to order events.
    data_type: UInt64

  - name: transaction_hash
    description: Hash of the transaction associated with the event.
    data_type: String

  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String

  - name: event_name
    description: Name of the Oracle event.
    data_type: String

  - name: event_data
    description: JSON object containing event-specific data.
    data_type: JSON

  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64

  - name: sender_address
    description: Address of the sender initiating the transaction.
    data_type: String

  - name: gas_price
    description: Gas price paid for the transaction, in wei.
    data_type: String

  - name: gas_used
    description: Gas used by the transaction.
    data_type: UInt64

  - name: value_transferred
    description: Amount transferred in the transaction, in wei.
    data_type: String

  - name: block_hash
    description: Hash of the block containing the event.
    data_type: String

  - name: log_data
    description: Raw log data payload.
    data_type: String
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2023-06-01"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.552273'
    _generated_fields:
    - description
    - config.tags
    - config.materialized

- name: contracts_backedfi_bIB01_Oracle_events
  description: The `contracts_backedfi_bIB01_Oracle_events` model captures and processes blockchain event logs related to the BackedFi protocol, enabling analysis of contract interactions and event occurrences over time.
  columns:

  - name: block_timestamp
    description: Timestamp of the block when the event was recorded
    data_type: DateTime

  - name: log_index
    description: Index of the log within the block, used to order events
    data_type: UInt64

  - name: transaction_hash
    description: Unique hash identifying the transaction
    data_type: String

  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String

  - name: event_name
    description: Name of the Oracle event
    data_type: String

  - name: oracle_id
    description: Identifier for the Oracle involved, if applicable
    data_type: String

  - name: request_id
    description: Unique request identifier for the Oracle request
    data_type: String

  - name: request_data
    description: Raw data payload of the Oracle request
    data_type: JSON

  - name: response_data
    description: Raw data payload of the Oracle response
    data_type: JSON

  - name: status
    description: Status of the Oracle request (e.g., 'pending', 'fulfilled', 'failed')
    data_type: String

  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64

  - name: transaction_index
    description: Index of the transaction within the block
    data_type: UInt64

  - name: event_data
    description: Additional event-specific data
    data_type: JSON
  meta:
    owner: analytics-team
    authoritative: false
    full_refresh:
      start_date: "2023-04-01"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.552319'
    _generated_fields:
    - description
    - config.tags
    - config.materialized

- name: contracts_backedfi_bIBTA_Oracle_events
  description: The `contracts_backedfi_bIBTA_Oracle_events` model captures and processes blockchain event logs related to the BackedFi protocol, enabling analysis of contract interactions and event occurrences over time.
  columns:

  - name: block_timestamp
    description: Timestamp of the block when the event was recorded
    data_type: DateTime

  - name: log_index
    description: Index of the log within the block
    data_type: UInt64

  - name: transaction_hash
    description: Hash of the transaction associated with the event
    data_type: String

  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String

  - name: event_name
    description: Name of the Oracle event emitted
    data_type: String

  - name: event_data
    description: JSON containing event-specific data payload
    data_type: JSON

  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64

  - name: transaction_index
    description: Index of the transaction within the block
    data_type: UInt64

  - name: sender_address
    description: Address of the sender initiating the transaction
    data_type: String

  - name: gas_used
    description: Amount of gas used for the transaction
    data_type: UInt64

  - name: status
    description: Status of the transaction (e.g., success or failure)
    data_type: String

  - name: block_hash
    description: Hash of the block containing the event
    data_type: String

  - name: created_at
    description: Timestamp when the record was created in the database
    data_type: DateTime
  meta:
    owner: analytics-team
    authoritative: false
    full_refresh:
      start_date: "2023-04-01"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.552364'
    _generated_fields:
    - description
    - config.tags
    - config.materialized

- name: contracts_backedfi_bMSTR_Oracle_events
  description: The `contracts_backedfi_bMSTR_Oracle_events` model captures and processes blockchain event logs related to BackedFi's bMSTR oracle contract, enabling analysis of oracle interactions and event occurrences over time.
  columns:

  - name: transaction_hash
    description: Unique identifier for the transaction in which the event was emitted.
    data_type: String

  - name: block_number
    description: The block height at which the event was included.
    data_type: UInt64

  - name: block_timestamp
    description: Timestamp when the block was mined, in UTC.
    data_type: DateTime

  - name: log_index
    description: Index of the log within the block, used to order events.
    data_type: UInt64

  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String

  - name: event_type
    description: Type of the Oracle event, indicating its purpose.
    data_type: String

  - name: event_data
    description: JSON object containing event-specific data payload.
    data_type: JSON

  - name: created_at
    description: Timestamp when the record was created in the database.
    data_type: DateTime

  - name: updated_at
    description: Timestamp when the record was last updated.
    data_type: DateTime
  meta:
    owner: analytics-team
    authoritative: false
    full_refresh:
      start_date: "2025-01-01"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.552401'
    _generated_fields:
    - description
    - config.tags
    - config.materialized

- name: contracts_backedfi_bNVDA_Oracle_events
  description: This model captures and processes Oracle event logs related to the BackedFi protocol, enabling analysis of contract interactions and event occurrences over time.
  columns:

  - name: block_timestamp
    description: Timestamp of the block when the event was recorded
    data_type: DateTime

  - name: log_index
    description: Index of the log within the block, used to order logs
    data_type: UInt64

  - name: transaction_hash
    description: Unique hash identifying the transaction
    data_type: String

  - name: event_name
    description: Name of the Oracle event emitted
    data_type: String

  - name: event_data
    description: JSON object containing event-specific data
    data_type: JSON

  - name: contract_address
    description: Address of the Oracle contract emitting the event
    data_type: String

  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64

  - name: sender_address
    description: Address initiating the transaction
    data_type: String

  - name: gas_price
    description: Gas price paid for the transaction in wei
    data_type: String

  - name: gas_used
    description: Amount of gas used for the transaction
    data_type: String

  - name: status
    description: Transaction status (e.g., success, failure)
    data_type: String

  - name: block_hash
    description: Hash of the block containing the event
    data_type: String

  - name: event_id
    description: Unique identifier for the event log
    data_type: String
  meta:
    owner: analytics_team
    authoritative: false
    full_refresh:
      start_date: "2025-01-01"
      batch_months: 6
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.552445'
    _generated_fields:
    - description
    - config.tags
    - config.materialized
