version: 2
models:

- name: contracts_backedfi_TSLAx_Oracle_events
  description: This model captures Oracle events related to TSLAx contracts, including timestamped logs and transaction details.
  columns:
  - name: block_timestamp
    description: The timestamp of the block containing the event, in UTC.
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block, used to order logs.
    data_type: UInt64
  - name: transaction_hash
    description: The hash of the transaction that generated the event.
    data_type: String
  - name: contract_address
    description: The address of the contract emitting the event.
    data_type: String
  - name: event_name
    description: The name of the Oracle event.
    data_type: String
  - name: event_data
    description: The JSON payload of the event data.
    data_type: JSON
  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64
  - name: transaction_index
    description: The index of the transaction within the block.
    data_type: UInt64
  - name: log_data
    description: Raw log data associated with the event.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bC3M_Oracle_events
  description: This model captures Oracle event logs related to BackedFi, including transaction details, block information, and event-specific data for analysis and reporting.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was logged, in UTC.
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block, used to order events.
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash of the transaction associated with the event.
    data_type: String
  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  - name: contract_address
    description: Address of the smart contract emitting the event.
    data_type: String
  - name: event_name
    description: Name of the event emitted, e.g., 'OracleUpdate'.
    data_type: String
  - name: data
    description: Event data payload in JSON format.
    data_type: JSON
  - name: block_hash
    description: Hash of the block containing the event.
    data_type: String
  - name: sender_address
    description: Address of the sender initiating the transaction.
    data_type: String
  - name: gas_used
    description: Amount of gas used for the transaction, in wei.
    data_type: UInt64
  - name: gas_price
    description: Gas price at the time of transaction, in wei.
    data_type: UInt64
  - name: status
    description: Transaction status indicator (e.g., success or failure).
    data_type: String
  - name: block_base_fee_per_gas
    description: Base fee per gas in the block, in wei.
    data_type: UInt64
  - name: block_difficulty
    description: Difficulty of the block.
    data_type: UInt64
  - name: block_gas_limit
    description: Gas limit of the block.
    data_type: UInt64
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bCOIN_Oracle_events
  description: This model captures Oracle event logs related to backedfi bCOIN, including transaction details, block information, and event-specific data.
  columns:
  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64
  - name: block_timestamp
    description: The timestamp when the block was mined, in UTC.
    data_type: DateTime64(0, 'UTC')
  - name: transaction_hash
    description: Unique hash identifying the transaction.
    data_type: String
  - name: log_index
    description: Index of the log within the block.
    data_type: UInt64
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: event_name
    description: Name of the Oracle event.
    data_type: String
  - name: event_data
    description: JSON object containing event-specific data.
    data_type: JSON
  - name: created_at
    description: Timestamp when the record was created in the database.
    data_type: DateTime64(0, 'UTC')
  - name: updated_at
    description: Timestamp when the record was last updated.
    data_type: DateTime64(0, 'UTC')
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bCSPX_Oracle_events
  description: This model captures Oracle event logs related to backedfi bCSPX, including transaction details, block information, and event-specific data.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was recorded
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block (sequence number)
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash identifying the transaction
    data_type: String
  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64
  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String
  - name: event_name
    description: Name of the event emitted
    data_type: String
  - name: event_data
    description: JSON object containing event-specific data
    data_type: JSON
  - name: sender_address
    description: Address of the sender initiating the transaction
    data_type: String
  - name: amount_wei
    description: Amount involved in the event in wei
    data_type: String
  - name: token_id
    description: Identifier for the token involved
    data_type: String
  - name: block_hash
    description: Hash of the block containing the event
    data_type: String
  - name: log_type
    description: Type of log (e.g., 'Transfer', 'Approval')
    data_type: String
  - name: gas_used
    description: Gas used for the transaction (optional, may be null)
    data_type: UInt64
  - name: gas_price_gwei
    description: Gas price in gwei at the time of transaction (optional, may be null)
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bHIGH_Oracle_events
  description: This model captures Oracle event logs related to the BackedFi high-value transactions, including timestamps, transaction details, and event-specific data for analysis.
  columns:
  - name: block_timestamp
    description: The timestamp when the block containing the event was mined (UTC).
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block, used for ordering.
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash identifying the transaction associated with the event.
    data_type: String
  - name: contract_address
    description: The address of the contract emitting the event.
    data_type: String
  - name: event_name
    description: The name of the Oracle event.
    data_type: String
  - name: event_data
    description: JSON object containing event-specific data fields.
    data_type: JSON
  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64
  - name: log_data
    description: Raw log data in hexadecimal format.
    data_type: String
  - name: sender_address
    description: Address of the sender initiating the transaction.
    data_type: String
  - name: receiver_address
    description: Address of the receiver, if applicable.
    data_type: String
  - name: amount_wei
    description: The amount involved in the event, in wei.
    data_type: String
  - name: event_timestamp
    description: The timestamp when the event was emitted (UTC).
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bIB01_Oracle_events
  description: This model captures Oracle events related to BackedFi, including transaction details, block information, and event-specific data for analysis and reporting.
  columns:
  - name: block_timestamp
    description: The timestamp of the block when the event was recorded (UTC).
    data_type: DateTime
  - name: log_index
    description: The index of the log within the block (sequence number).
    data_type: UInt64
  - name: transaction_hash
    description: The hash of the transaction associated with the event.
    data_type: String
  - name: contract_address
    description: The address of the contract emitting the event.
    data_type: String
  - name: event_name
    description: The name of the Oracle event.
    data_type: String
  - name: event_data
    description: JSON object containing event-specific data payload.
    data_type: JSON
  - name: block_number
    description: The number of the block containing the event.
    data_type: UInt64
  - name: sender_address
    description: Address of the sender initiating the event.
    data_type: String
  - name: receiver_address
    description: Address of the receiver involved in the event.
    data_type: String
  - name: amount_wei
    description: Amount involved in the event, denominated in wei.
    data_type: String
  - name: token_symbol
    description: Symbol of the token involved.
    data_type: String
  - name: status
    description: Status indicator of the event; e.g., 'success' or 'failure'.
    data_type: String
  - name: created_at
    description: Timestamp when the record was created in the database.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bIBTA_Oracle_events
  description: This model captures Oracle event logs related to BackedFi, including transaction details and event-specific data.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was emitted
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash of the transaction
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String
  - name: event_name
    description: Name of the Oracle event
    data_type: String
  - name: data
    description: Event-specific data payload in JSON format
    data_type: JSON
  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64
  - name: transaction_index
    description: Index of the transaction within the block
    data_type: UInt64
  - name: sender
    description: Address of the sender initiating the transaction
    data_type: String
  - name: recipient
    description: Address of the recipient, if applicable
    data_type: String
  - name: amount
    description: Amount involved in the event, in wei
    data_type: String
  - name: status
    description: Status of the transaction or event
    data_type: String
  - name: block_hash
    description: Hash of the block containing the event
    data_type: String
  - name: created_at
    description: Timestamp when the record was created in the database
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bMSTR_Oracle_events
  description: This model captures Oracle events related to BackedFi's bMSTR contracts, including transaction details, block information, and event-specific data.
  columns:
  - name: block_timestamp
    description: Timestamp of the block containing the event, in UTC.
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block, used to order events.
    data_type: UInt64
  - name: transaction_hash
    description: Hash of the transaction that emitted the event.
    data_type: String
  - name: block_number
    description: Number of the block containing the event.
    data_type: UInt64
  - name: contract_address
    description: Address of the contract emitting the event.
    data_type: String
  - name: event_name
    description: Name of the Oracle event.
    data_type: String
  - name: oracle_id
    description: Identifier for the Oracle involved in the event.
    data_type: String
  - name: data
    description: Event-specific data payload, in JSON format.
    data_type: JSON
  - name: amount
    description: Amount involved in the event, in wei.
    data_type: UInt64
  - name: token_address
    description: Address of the token related to the event.
    data_type: String
  - name: source_chain_id
    description: Identifier of the source blockchain network.
    data_type: UInt64
  - name: destination_chain_id
    description: Identifier of the destination blockchain network.
    data_type: UInt64
  - name: created_at
    description: Timestamp when the record was created in the database.
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: contracts_backedfi_bNVDA_Oracle_events
  description: This model captures Oracle events related to BackedFi's bNVDA contract, including transaction details, block information, and event-specific data.
  columns:
  - name: block_timestamp
    description: Timestamp of the block when the event was recorded
    data_type: DateTime
  - name: log_index
    description: Index of the log within the block
    data_type: UInt64
  - name: transaction_hash
    description: Unique hash identifying the transaction
    data_type: String
  - name: contract_address
    description: Address of the contract emitting the event
    data_type: String
  - name: event_name
    description: Name of the Oracle event
    data_type: String
  - name: event_data
    description: JSON object containing event-specific data
    data_type: JSON
  - name: block_number
    description: Number of the block containing the event
    data_type: UInt64
  - name: transaction_index
    description: Index of the transaction within the block
    data_type: UInt64
  - name: sender_address
    description: Address of the sender initiating the transaction
    data_type: String
  - name: receiver_address
    description: Address of the receiver, if applicable
    data_type: String
  - name: value
    description: Value transferred in wei; may be large, stored as String
    data_type: String
  - name: gas_price
    description: Gas price in wei; may be large, stored as String
    data_type: String
  - name: gas_used
    description: Amount of gas used for the transaction
    data_type: UInt64
  - name: status
    description: Transaction status code
    data_type: UInt64
  - name: block_hash
    description: Hash of the block containing the event
    data_type: String
  - name: created_at
    description: Timestamp when the record was created in the data warehouse
    data_type: DateTime
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - contracts
    - backedfi
    - events
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
