version: 2
models:
- name: esg_consensus_power
  description: This model aggregates consensus power data across different Ethereum clients.
  columns:
  - name: type
    description: Type of consensus power data.
    data_type: INT
  - name: client
    description: Ethereum client.
    data_type: STRING
  - name: mean
    description: Average consensus power.
    data_type: FLOAT
- name: esg_country_power_consumption
  description: Calculates the estimated power consumption for each country based on node configuration and distribution.  Combines daily country-level peer counts with a calculated average power consumption per client configuration.
  columns:
  - name: date
    description: Date of the measurement.
    data_type: DATE
  - name: country
    description: Country where the power consumption is measured.
    data_type: STRING
  - name: power
    description: Estimated power consumption in the country on the given date.
    data_type: FLOAT
- name: esg_execution_power
  description: This model calculates the mean execution power for different Ethereum clients.
  columns:
  - name: type
    description: Type of execution client.
    data_type: INT64
  - name: client
    description: Name of the execution client.
    data_type: STRING
  - name: mean
    description: Mean execution power.
    data_type: FLOAT64
- name: esg_hardware_config
  description: This model describes the hardware configuration of ESG systems.  It includes details such as CPU, RAM, storage, and GPU.
  columns:
  - name: type
    description: Type of hardware configuration.
    data_type: INT
  - name: cpu
    description: CPU model.
    data_type: STRING
  - name: cores_threads
    description: Number of cores and threads.
    data_type: STRING
  - name: architecture
    description: CPU architecture.
    data_type: STRING
  - name: ram
    description: RAM size.
    data_type: STRING
  - name: storage
    description: Storage size and type.
    data_type: STRING
  - name: gpu
    description: GPU model.
    data_type: STRING
  - name: psu
    description: Power supply unit (PSU) wattage.
    data_type: STRING
  - name: case
    description: Computer case type.
    data_type: STRING
  - name: os
    description: Operating system.
    data_type: STRING
- name: esg_idle_electric_power
  description: This model calculates the mean idle electric power consumption for different types of power sources.  The source data is synthetic.
  columns:
  - name: type
    description: Type of electric power source.
    data_type: INT
  - name: mean
    description: Mean idle electric power consumption.
    data_type: FLOAT
- name: esg_node_distribution
  description: Distribution of ESG node types.  Provides the type and its corresponding distribution.
  columns:
  - name: type
    description: Type of ESG node.
    data_type: INT64
  - name: distribution
    description: Distribution of the ESG node type.
    data_type: FLOAT64
