version: 2
models:
- name: esg_node_distribution
  description: 'TODO: Add description for esg_node_distribution'
  meta:
    sector: ESG
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - ESG
    - transformations
  columns:
  - name: distribution
    description: 'TODO: Add description for distribution'
    data_tests:
    - not_null
  - name: type
    description: 'TODO: Add description for type'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - distribution
      - type
- name: esg_consensus_power
  description: 'TODO: Add description for esg_consensus_power'
  meta:
    sector: ESG
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - ESG
    - transformations
  columns:
  - name: client
    description: 'TODO: Add description for client'
    data_tests:
    - not_null
  - name: mean
    description: 'TODO: Add description for mean'
    data_tests:
    - not_null
  - name: type
    description: 'TODO: Add description for type'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - client
      - mean
- name: esg_country_power_consumption
  description: 'TODO: Add description for esg_country_power_consumption'
  meta:
    sector: ESG
    refs:
    - esg_consensus_power
    - esg_execution_power
    - esg_idle_electric_power
    - esg_node_distribution
    - p2p_peers_geo_daily
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - ESG
    - transformations
  columns:
  - name: client
    description: 'TODO: Add description for client'
    data_tests:
    - not_null
  - name: mean
    description: 'TODO: Add description for mean'
    data_tests:
    - not_null
  - name: type
    description: 'TODO: Add description for type'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - client
      - mean
- name: esg_execution_power
  description: 'TODO: Add description for esg_execution_power'
  meta:
    sector: ESG
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - ESG
    - transformations
  columns:
  - name: client
    description: 'TODO: Add description for client'
    data_tests:
    - not_null
  - name: mean
    description: 'TODO: Add description for mean'
    data_tests:
    - not_null
  - name: type
    description: 'TODO: Add description for type'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - client
      - mean
- name: esg_idle_electric_power
  description: 'TODO: Add description for esg_idle_electric_power'
  meta:
    sector: ESG
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - ESG
    - transformations
  columns:
  - name: mean
    description: 'TODO: Add description for mean'
    data_tests:
    - not_null
  - name: type
    description: 'TODO: Add description for type'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - mean
      - type
- name: esg_hardware_config
  description: 'TODO: Add description for esg_hardware_config'
  meta:
    sector: ESG
    refs: []
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - ESG
    - transformations
  columns:
  - name: architecture
    description: 'TODO: Add description for architecture'
    data_tests:
    - not_null
  - name: case
    description: 'TODO: Add description for case'
    data_tests:
    - not_null
  - name: cores_threads
    description: 'TODO: Add description for cores_threads'
    data_tests:
    - not_null
  - name: cpu
    description: 'TODO: Add description for cpu'
    data_tests:
    - not_null
  - name: gpu
    description: 'TODO: Add description for gpu'
    data_tests:
    - not_null
  - name: os
    description: 'TODO: Add description for os'
    data_tests:
    - not_null
  - name: psu
    description: 'TODO: Add description for psu'
    data_tests:
    - not_null
  - name: ram
    description: 'TODO: Add description for ram'
    data_tests:
    - not_null
  - name: storage
    description: 'TODO: Add description for storage'
    data_tests:
    - not_null
  - name: type
    description: 'TODO: Add description for type'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - architecture
      - case
