version: 2
models:

- name: execution_blocks_clients_version_daily
  description: Business-facing table summarizing client versions per day, derived from raw execution data.
  columns:
  - name: date
    description: Date of the record in UTC (UTC date, no time component).
    data_type: Date
    tests:
    - not_null
  - name: client
    description: Client identifier, normalized to known categories or 'Unknown'.
    data_type: String
    tests:
    - not_null
  - name: version
    description: Client version string, may be empty if not specified.
    data_type: String
  - name: value
    description: Aggregated count of occurrences for the client-version on the date.
    data_type: UInt64
    tests:
    - not_null
  config:
    access: public
    materialized: table
    tags:
    - daily
    - client
    - version
- name: execution_blocks_production
  description: Data model representing execution blocks with associated metadata, transactions, logs, and related entities for Gnosis Chain analysis.
  columns:
  - name: block_timestamp
    description: UTC timestamp of the block (materialized from `timestamp` in source).
    data_type: DateTime
    tests:
    - not_null
  - name: extra_data
    description: Arbitrary extra-data bytes set by the block proposer (hex).
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - gnosis
    - execution
- name: int_execution_blocks_clients_version_daily
  description: '"Model representing daily counts of unique clients per version."'
  columns:
  - name: version
    description: Client version string.
    data_type: String
  - name: cnt
    description: Count of clients for the version on the date.
    data_type: Int64
  - name: date
    description: Date of the data aggregation.
    data_type: DateTime
  - name: client
    description: Client name or identifier.
    data_type: String
  config:
    materialized: view
    access: public
    tags:
    - production
    - execution
    - blocks
  meta:
    owner: analytics_engineer
    authoritative: false
    generated_by: schema-writer
- name: int_execution_blocks_gas_usage_daily
  description: Daily aggregation of gas usage statistics for execution blocks.
  columns:
  - name: date
    description: Date of the execution block.
    data_type: DateTime
    tests:
    - not_null
  - name: gas_used_sum
    description: Total gas consumed by transactions in the block.
    data_type: UInt64
    tests:
    - not_null
  - name: gas_limit_sum
    description: Maximum gas allowed in the block.
    data_type: UInt64
    tests:
    - not_null
  - name: gas_used_fraq
    description: Gas used fraction (gas_used_sum / gas_limit_sum).
    data_type: Float64
  config:
    materialized: incremental
    unique_key: date
    partition_by: toStartOfMonth(date)
    tags:
    - production
    - execution
    - blocks
    - gas
    access: public
  meta:
    owner: analytics_engineer
    authoritative: false
    generated_by: schema-writer
