version: 2
models:
- name: consensus_atts_inclusion_distance_d
  meta:
    blockchain: consensus
    sector: attestations
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - consensus
    - attestations
  description: 'TODO: Add description for consensus_atts_inclusion_distance_d'
  columns:
  - name: cnt
    description: 'TODO: Add description for cnt'
    data_tests:
    - not_null
    - unique
  - name: day
    description: 'TODO: Add description for day'
    data_tests:
    - not_null
    - unique
  - name: inc_dist_cohort
    description: 'TODO: Add description for inc_dist_cohort'
    data_tests:
    - not_null
    - unique
  - name: partition_month
    description: 'TODO: Add description for partition_month'
    data_tests:
    - not_null
    - unique
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - cnt
      - day
