version: 2
models:

- name: stg_execution__storage_diffs
  description: This table captures storage slot mutations produced by each transaction, enabling detailed analysis of contract state changes on the chain.
  columns:
  - name: transaction_hash
    description: Concatenated '0x' prefix with the transaction hash, serving as a unique identifier.
    data_type: String
  - name: transaction_index
    description: Zero-based index of the transaction within its block.
    data_type: UInt64
  - name: address
    description: Contract address (hex string) whose storage changed.
    data_type: String
  - name: slot
    description: 32-byte storage slot key in hex format.
    data_type: String
  - name: from_value
    description: Hex-encoded value before the change.
    data_type: String
  - name: to_value
    description: Hex-encoded value after the change.
    data_type: String
  - name: chain_id
    description: EVM chain identifier (e.g., 100 for Gnosis).
    data_type: UInt64
  - name: block_timestamp
    description: UTC timestamp of the block when the storage change occurred.
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonically increasing version number indicating ingestion order.
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - state
    - size
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
