version: 2
models:

- name: stg_execution__storage_diffs
  description: Business-facing staging model capturing storage slot mutations, account balance changes, contract deployments, and related execution data for analysis and auditing.
  columns:
  - name: slot
    description: Storage slot key (hexadecimal 32-byte string)
    data_type: String
    tests:
    - not_null
  - name: block_number
    description: Block height containing the storage change
    data_type: UInt32
    tests:
    - not_null
  - name: transaction_index
    description: Index of the transaction within the block
    data_type: UInt32
    tests:
    - not_null
  - name: transaction_hash
    description: Hash of the transaction causing the storage change
    data_type: String
    tests:
    - not_null
    - unique
  - name: address
    description: Contract address whose storage was modified
    data_type: String
    tests:
    - not_null
  - name: from_value
    description: Previous value of the storage slot (hexadecimal)
    data_type: String
  - name: to_value
    description: New value of the storage slot (hexadecimal)
    data_type: String
  - name: chain_id
    description: EVM chain identifier
    data_type: UInt64
    tests:
    - not_null
  - name: block_timestamp
    description: UTC timestamp of the block when the change occurred
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: insert_version
    description: Monotonic ingestion version in nanoseconds
    data_type: UInt64
  config:
    access: public
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
