version: 2
models:

- name: stg_execution__storage_diffs
  description: This table captures storage slot mutations produced by each transaction, enabling detailed analysis of contract state changes on the blockchain.
  columns:
  - name: slot
    description: 32-byte storage slot key (hexadecimal representation).
    data_type: String
  - name: block_number
    description: Block height at which the storage change occurred.
    data_type: UInt32
  - name: transaction_index
    description: Zero-based index of the transaction within the block.
    data_type: UInt32
  - name: transaction_hash
    description: Hash of the transaction that caused the storage change.
    data_type: String
  - name: address
    description: Contract address whose storage was modified.
    data_type: String
  - name: from_value
    description: Value before change (hexadecimal string).
    data_type: String
  - name: to_value
    description: Value after change (hexadecimal string).
    data_type: String
  - name: chain_id
    description: EVM chain identifier.
    data_type: UInt64
  - name: block_timestamp
    description: UTC timestamp of the block containing the change.
    data_type: DateTime64(0, 'UTC')
  - name: insert_version
    description: Monotonic ingestion version in nanoseconds.
    data_type: UInt64
  config:
    access: public
    materialized: view
    tags:
    - production
    - execution
    - state
    - size
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
