version: 2
models:

- name: stg_execution__storage_diffs
  description: Stage model for storage differences capturing transaction, storage, and account changes
  columns:
  - name: address
    description: Contract address involved in storage diff (hex string).
    data_type: String
  - name: block_number
    description: Block height at which the storage diff occurred.
    data_type: UInt32
  - name: slot
    description: Storage slot key (hex string, 32 bytes).
    data_type: String
  - name: from_value
    description: Value before change (hex string).
    data_type: String
  - name: to_value
    description: Value after change (hex string).
    data_type: String
  - name: chain_id
    description: EVM chain identifier.
    data_type: UInt64
  - name: block_timestamp
    description: UTC timestamp of the block when diff was recorded.
    data_type: DateTime64(0, 'UTC')
  - name: transaction_hash
    description: Hash of the transaction producing the diff.
    data_type: String
  - name: transaction_index
    description: Index of the transaction within the block.
    data_type: UInt32
  - name: insert_version
    description: Monotonic version for data ingestion.
    data_type: UInt64
  config:
    access: public
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
