version: 2
models:

- name: esg_carbon_emissions
  description: Carbon emissions data aggregated by date and country, including energy consumption and associated CO2 emissions in metric tons.
  columns:
  - name: date
    description: Date of measurement in UTC, format YYYY-MM-DD.
    data_type: DateTime
    tests:
    - not_null
  - name: energy
    description: Total energy consumption in MWh, calculated as sum of power over the day.
    data_type: Float64
  - name: co2_emissions
    description: Total CO2 emissions in metric tons (tCO2e), derived from energy consumption and CIF.
    data_type: Float64
  - name: mean_cif
    description: Average Carbon Intensity Factor (gCO2/kWh) for the country and date.
    data_type: Float64
  - name: power
    description: Power in watts (W) at the timestamp, used for calculations.
    data_type: Float64
  - name: country
    description: ISO 3-letter country code.
    data_type: String
    tests:
    - not_null
  config:
    materialized: table
    access: public
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: esg_power_consumption_top10
  description: Aggregated power consumption data for top 10 countries per date, with 'Other' category for remaining countries.
  columns:
  - name: date
    description: The date of power consumption measurement.
    data_type: DateTime
    tests:
    - not_null
  - name: country
    description: Country name or 'Other' for aggregated data.
    data_type: String
    tests:
    - not_null
  - name: power
    description: Total power consumption in wei for the given date and country.
    data_type: UInt64
    tests:
    - not_null
  - name: rank
    description: Rank of the country by power consumption for the date.
    data_type: UInt64
    tests:
    - not_null
  config:
    access: public
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_esg_carbon_emissions
  description: A fact table aggregating carbon emissions data based on power consumption and CIF values, with calculations for energy and emissions in metric tons.
  columns:
  - name: date
    description: The date of the measurement in UTC.
    data_type: DateTime
  - name: country
    description: ISO 3-letter country code.
    data_type: String
  - name: power
    description: Power consumption in kilowatts (kW).
    data_type: Float64
  - name: energy
    description: Total energy consumption in megawatt-hours (MWh).
    data_type: Float64
  - name: co2_emissions
    description: Total CO2 equivalent emissions in metric tons (tCO2e).
    data_type: Float64
  - name: mean_cif
    description: Average Carbon Intensity Factor in gCO2/kWh.
    data_type: Float64
  config:
    access: public
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_esg_power_consumption_top10
  description: Aggregated power consumption data for top 10 countries per date, with 'Other' category for remaining.
  columns:
  - name: date
    description: The date of power consumption measurement.
    data_type: DateTime
  - name: country
    description: Country name or 'Other' for aggregated entries.
    data_type: String
  - name: power
    description: Total power consumption in wei units.
    data_type: UInt64
  - name: rank
    description: Row number indicating the country's rank by power consumption for the date.
    data_type: UInt64
  config:
    access: public
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
