version: 2
models:

- name: esg_carbon_emissions
  description: Carbon emissions data aggregated by date and country, including energy consumption and associated CO2 emissions in metric tons.
  columns:
  - name: date
    description: Date of measurement in UTC, format YYYY-MM-DD.
    data_type: DateTime
    tests:
    - not_null
  - name: energy
    description: Total energy consumption in MWh, calculated as sum of power over the day.
    data_type: Float64
  - name: co2_emissions
    description: Total CO2 emissions in metric tons (tCO2e), derived from energy consumption and CIF.
    data_type: Float64
  - name: mean_cif
    description: Average Carbon Intensity Factor (gCO2/kWh) for the country and date.
    data_type: Float64
  - name: power
    description: Power in watts (W) at the timestamp, used for calculations.
    data_type: Float64
  - name: country
    description: ISO 3-letter country code.
    data_type: String
    tests:
    - not_null
  config:
    materialized: table
    access: public
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: esg_power_consumption_top10
  description: Aggregated power consumption data for top 10 countries per date, with 'Other' category for remaining countries.
  columns:
  - name: date
    description: The date of power consumption measurement.
    data_type: DateTime
    tests:
    - not_null
  - name: country
    description: Country name or 'Other' for aggregated data.
    data_type: String
    tests:
    - not_null
  - name: power
    description: Total power consumption in wei for the given date and country.
    data_type: UInt64
    tests:
    - not_null
  - name: rank
    description: Rank of the country by power consumption for the date.
    data_type: UInt64
    tests:
    - not_null
  config:
    access: public
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_esg_carbon_emissions
  description: A fact table aggregating carbon emissions data based on power consumption and CIF values, with calculations for energy and emissions in metric tons.
  columns:
  - name: date
    description: The date of the measurement in UTC.
    data_type: DateTime
  - name: country
    description: ISO 3-letter country code.
    data_type: String
  - name: power
    description: Power consumption in kilowatts (kW).
    data_type: Float64
  - name: energy
    description: Total energy consumption in megawatt-hours (MWh).
    data_type: Float64
  - name: co2_emissions
    description: Total CO2 equivalent emissions in metric tons (tCO2e).
    data_type: Float64
  - name: mean_cif
    description: Average Carbon Intensity Factor in gCO2/kWh.
    data_type: Float64
  config:
    access: public
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_esg_power_consumption_top10
  description: Aggregated power consumption data for top 10 countries per date, with 'Other' category for remaining.
  columns:
  - name: date
    description: The date of power consumption measurement.
    data_type: DateTime
  - name: country
    description: Country name or 'Other' for aggregated entries.
    data_type: String
  - name: power
    description: Total power consumption in wei units.
    data_type: UInt64
  - name: rank
    description: Row number indicating the country's rank by power consumption for the date.
    data_type: UInt64
  config:
    access: public
    materialized: table
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_esg_carbon_emissions_annualised_latest
  description: The latest annualized projected CO2 emissions in tonnes, filtered to include only data before the current month.
  columns:
  - name: annual_co2_tonnes_projected
    description: Projected annual CO2 emissions in tonnes for the latest available period.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - esg
    - carbon_emissions
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_esg_carbon_emissions_daily
  description: Daily carbon emissions data with 7-day moving averages, derived from ESG footprint sources. Includes date and smoothed metrics for lower and upper bounds at 90% and 95% confidence levels.
  columns:
  - name: date
    description: The date of the record, in UTC. Used as the primary temporal reference.
    data_type: DateTime
  - name: ma7_value
    description: 7-day moving average of daily CO2 emissions in kg, smoothed over the past week.
    data_type: Float64
  - name: ma7_lower_90
    description: Lower bound of the 90% confidence interval for the 7-day moving average.
    data_type: Float64
  - name: ma7_upper_90
    description: Upper bound of the 90% confidence interval for the 7-day moving average.
    data_type: Float64
  - name: ma7_lower_95
    description: Lower bound of the 95% confidence interval for the 7-day moving average.
    data_type: Float64
  - name: ma7_upper_95
    description: Upper bound of the 95% confidence interval for the 7-day moving average.
    data_type: Float64
  config:
    access: public
    materialized: view
    tags:
    - production
    - esg
    - carbon_emissions
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_esg_carbon_timeseries_bands
  description: A timeseries model providing daily ESG carbon footprint data with moving averages and month-to-date statistics.
  columns:
  - name: date
    description: The date of the record, in UTC.
    data_type: DateTime
  - name: value
    description: Daily mean of CO2 emissions in kg.
    data_type: Float64
  - name: lower_95
    description: Lower bound of the 95% confidence interval for daily CO2 emissions in kg.
    data_type: Float64
  - name: upper_95
    description: Upper bound of the 95% confidence interval for daily CO2 emissions in kg.
    data_type: Float64
  - name: lower_90
    description: Lower bound of the 90% confidence interval for daily CO2 emissions in kg.
    data_type: Float64
  - name: upper_90
    description: Upper bound of the 90% confidence interval for daily CO2 emissions in kg.
    data_type: Float64
  - name: ma7_value
    description: 7-day moving average of the daily CO2 mean in kg.
    data_type: Float64
  - name: ma7_lower_95
    description: 7-day moving average of the lower 95% confidence interval in kg.
    data_type: Float64
  - name: ma7_upper_95
    description: 7-day moving average of the upper 95% confidence interval in kg.
    data_type: Float64
  - name: mtd_avg
    description: Month-to-date average of the daily CO2 mean in kg.
    data_type: Float64
  - name: mtd_total
    description: Month-to-date total of the daily CO2 mean in kg.
    data_type: Float64
  config:
    access: public
    materialized: view
    tags:
    - production
    - esg
    - carbon_emissions
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_esg_cif_network_vs_countries_daily
  description: Daily carbon intensity values for network and selected countries, including comparison metrics and processed data.
  columns:
  - name: date
    description: Date of the measurement in UTC.
    data_type: DateTime
  - name: entity_code
    description: Identifier for the entity; 'GNOSIS' for network, country codes for countries.
    data_type: String
  - name: carbon_intensity
    description: Carbon intensity value in gCO2/kWh, rounded to one decimal place.
    data_type: Float64
  config:
    access: public
    tags:
    - production
    - esg
    - cif
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: api_esg_energy_consumption_annualised_latest
  description: The latest projected annual energy consumption in MWh for the project, derived from ESG data.
  columns:
  - name: annual_energy_Mwh_projected
    description: Projected annual energy consumption in megawatt-hours (MWh) for the latest period.
    data_type: Float64
  config:
    access: public
    materialized: view
    tags:
    - production
    - esg
    - energy_consumption
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: fct_esg_carbon_footprint_uncertainty
  description: Business-facing metrics for analyzing the uncertainty in ESG carbon footprint estimates, including energy, emissions, and population estimates, with comparisons to Chao-1 population metrics.
  columns:
  - name: date
    description: The date of the measurement or estimate, in UTC.
    data_type: DateTime
  - name: estimated_total_nodes
    description: Total estimated nodes in the network for the given date.
    data_type: UInt64
  - name: carbon_intensity_gco2_kwh
    description: Estimated carbon intensity in grams CO2 per kWh.
    data_type: Float64
  - name: node_category
    description: Category of nodes, e.g., 'home_staker', 'professional_operator', 'cloud_hosted', 'unknown'.
    data_type: String
  - name: country_code
    description: ISO country code representing the geographic distribution.
    data_type: String
  - name: total_estimated_nodes
    description: Sum of estimated nodes across categories for the date.
    data_type: UInt64
  - name: total_nodes_lower_95
    description: Lower bound of the 95% confidence interval for total nodes.
    data_type: UInt64
  - name: total_nodes_upper_95
    description: Upper bound of the 95% confidence interval for total nodes.
    data_type: UInt64
  - name: chao1_observed
    description: Number of nodes observed successfully in Chao-1 estimate.
    data_type: UInt64
  - name: chao1_estimated
    description: Total reachable nodes estimated by Chao-1 method.
    data_type: UInt64
  - name: chao1_success_rate
    description: Percentage of successful node discoveries in Chao-1 estimate.
    data_type: Float64
  - name: chao1_coverage
    description: Reachability coverage percentage in Chao-1 estimate.
    data_type: Float64
  - name: node_estimate_vs_chao1_pct
    description: Ratio of total estimated nodes to Chao-1 estimated total, as a percentage.
    data_type: Float64
  - name: applied_scaling_factor
    description: Scaling factor applied to align estimated nodes with Chao-1 estimates.
    data_type: Float64
  - name: network_weighted_cif
    description: Network effective carbon intensity in grams CO2 per kWh.
    data_type: Float64
  - name: total_energy_kwh
    description: Total energy consumption in kWh for the date.
    data_type: Float64
  - name: annual_energy_Mwh_projected
    description: Projected annual energy consumption in MWh.
    data_type: Float64
  - name: total_co2_kg_mean
    description: Mean total CO2 emissions in kilograms.
    data_type: Float64
  - name: total_co2_kg_std
    description: Standard deviation of total CO2 emissions in kilograms.
    data_type: Float64
  - name: daily_co2_kg_lower_95
    description: Lower bound of the 95% confidence interval for daily CO2 emissions.
    data_type: Float64
  - name: daily_co2_kg_upper_95
    description: Upper bound of the 95% confidence interval for daily CO2 emissions.
    data_type: Float64
  - name: daily_co2_kg_lower_90
    description: Lower bound of the 90% confidence interval for daily CO2 emissions.
    data_type: Float64
  - name: daily_co2_kg_upper_90
    description: Upper bound of the 90% confidence interval for daily CO2 emissions.
    data_type: Float64
  - name: annual_co2_tonnes_projected
    description: Projected annual CO2 emissions in tonnes.
    data_type: Float64
  - name: annual_co2_tonnes_std
    description: Standard deviation of annual CO2 emissions in tonnes.
    data_type: Float64
  - name: home_staker_co2_kg
    description: Total CO2 emissions in kg for home staker nodes.
    data_type: Float64
  - name: professional_co2_kg
    description: Total CO2 emissions in kg for professional operator nodes.
    data_type: Float64
  - name: cloud_co2_kg
    description: Total CO2 emissions in kg for cloud hosted nodes.
    data_type: Float64
  - name: unknown_co2_kg
    description: Total CO2 emissions in kg for unknown node category.
    data_type: Float64
  - name: home_staker_pct
    description: Percentage of total CO2 emissions attributable to home staker nodes.
    data_type: Float64
  - name: professional_pct
    description: Percentage of total CO2 emissions attributable to professional operator nodes.
    data_type: Float64
  - name: cloud_pct
    description: Percentage of total CO2 emissions attributable to cloud hosted nodes.
    data_type: Float64
  - name: home_staker_nodes
    description: Number of home staker nodes.
    data_type: UInt64
  - name: professional_nodes
    description: Number of professional operator nodes.
    data_type: UInt64
  - name: cloud_nodes
    description: Number of cloud hosted nodes.
    data_type: UInt64
  - name: unknown_nodes
    description: Number of nodes with unknown category.
    data_type: UInt64
  - name: relative_uncertainty_pct
    description: Relative uncertainty of total CO2 emissions expressed as a percentage.
    data_type: Float64
  - name: active_categories
    description: Count of categories with active nodes.
    data_type: UInt64
  - name: countries_with_nodes
    description: Number of countries with active nodes.
    data_type: UInt64
  - name: baseline_observed_nodes
    description: Number of nodes observed successfully in Chao-1 estimate.
    data_type: UInt64
  - name: chao1_total_estimated
    description: Total estimated nodes from Chao-1 method.
    data_type: UInt64
  - name: network_reachability_pct
    description: Percentage of nodes reachable in the network.
    data_type: Float64
  - name: discovery_completeness_pct
    description: Percentage of network discovery coverage.
    data_type: Float64
  - name: grams_co2_per_node_daily
    description: Grams of CO2 emitted per node per day.
    data_type: Float64
  - name: wh_per_node_daily
    description: Watt-hours consumed per node per day.
    data_type: Float64
  - name: calculated_at
    description: Timestamp when the metrics were calculated.
    data_type: DateTime
  - name: run_id
    description: Identifier for the run instance.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - esg
    - carbon_emissions
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
