version: 2
models:
- name: esg_carbon_emissions
  description: This model calculates daily carbon emissions based on power consumption and carbon intensity factor (CIF).  It joins data from gnosis_power_consumption and ember_electricity_data.
  columns:
  - name: date
    description: Date of the measurement.
    data_type: DATE
  - name: energy
    description: Daily energy consumption in MWh.
    data_type: FLOAT
  - name: co2_emissions
    description: Daily CO2 emissions in tonnes of CO2 equivalent (tCO2e).
    data_type: FLOAT
  - name: mean_cif
    description: Average carbon intensity factor (CIF) in gCO2/kWh for the given day and country.
    data_type: FLOAT
- name: esg_power_consumption_top10
  description: Top 10 countries by power consumption, aggregated daily.  Countries outside the top 10 are grouped into an "Other" category.
  columns:
  - name: date
    description: Date of the power consumption measurement.
    data_type: DATE
  - name: country
    description: Country name.  Values outside the top 10 are aggregated as 'Other'.
    data_type: STRING
  - name: power
    description: Total power consumption for the country on the given date.
    data_type: FLOAT
