version: 2
models:
- name: esg_carbon_emissions
  description: 'TODO: Add description for esg_carbon_emissions'
  meta:
    sector: ESG
    refs:
    - esg_country_power_consumption
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - ESG
    - metrics
  columns:
  - name: country
    description: 'TODO: Add description for country'
    data_tests:
    - not_null
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: power
    description: 'TODO: Add description for power'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - country
      - date
- name: esg_power_consumption_top10
  description: 'TODO: Add description for esg_power_consumption_top10'
  meta:
    sector: ESG
    refs:
    - esg_country_power_consumption
    contributors: 'TODO: Add contributors'
  config:
    tags:
    - ESG
    - metrics
  columns:
  - name: country
    description: 'TODO: Add description for country'
    data_tests:
    - not_null
  - name: date
    description: 'TODO: Add description for date'
    data_tests:
    - not_null
  - name: power
    description: 'TODO: Add description for power'
    data_tests:
    - not_null
  - name: rank
    description: 'TODO: Add description for rank'
    data_tests:
    - not_null
  data_tests:
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns:
      - country
      - date
