version: 2
models:

- name: stg_nebula_discv4__visits
  description: Staging model for visits data from nebula_discv4, including peer and protocol metadata.
  columns:
  - name: crawl_id
    description: Identifier for the crawl; nullable if not available.
    data_type: UUID
  - name: peer_id
    description: Unique identifier for the peer.
    data_type: String
  - name: agent_version
    description: Version string of the peer's agent software.
    data_type: String
  - name: protocols
    description: List of protocols supported by the peer.
    data_type: Array(LowCardinality(String))
  - name: dial_maddrs
    description: Array of multi-addresses used for dialing.
    data_type: Array(String)
  - name: filtered_maddrs
    description: Array of filtered multi-addresses.
    data_type: Array(String)
  - name: extra_maddrs
    description: Array of extra multi-addresses.
    data_type: Array(String)
  - name: dial_errors
    description: Array of dial error messages.
    data_type: Array(LowCardinality(String))
  - name: connect_maddr
    description: Multi-address used for connection; nullable if not connected.
    data_type: Nullable(String)
  - name: crawl_error
    description: Error message during crawl; nullable if no error.
    data_type: LowCardinality(Nullable(String))
  - name: visit_started_at
    description: Timestamp when the visit started.
    data_type: DateTime64(0, 'UTC')
  - name: visit_ended_at
    description: Timestamp when the visit ended.
    data_type: DateTime64(0, 'UTC')
  - name: peer_properties
    description: JSON object containing peer properties.
    data_type: JSON
  config:
    access: public
    tags:
    - production
    - nebula_discv4
    - visits
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_nebula_discv5__visits
  description: Staging model for visits data from nebula_discv5 source, including peer and protocol metadata.
  columns:
  - name: crawl_id
    description: Identifier for the crawl session; nullable if not available.
    data_type: String
  - name: peer_id
    description: Unique identifier for the peer; primary key component.
    data_type: String
  - name: agent_version
    description: Version string of the peer's agent software.
    data_type: String
  - name: protocols
    description: Array of protocols supported by the peer.
    data_type: Array
  - name: dial_maddrs
    description: List of multiaddresses used for dialing.
    data_type: Array
  - name: filtered_maddrs
    description: List of filtered multiaddresses.
    data_type: Array
  - name: extra_maddrs
    description: Additional multiaddresses associated with the peer.
    data_type: Array
  - name: dial_errors
    description: List of errors encountered during dialing attempts.
    data_type: Array
  - name: connect_maddr
    description: Multiaddress used for the connection; nullable if not connected.
    data_type: String
  - name: crawl_error
    description: Error message if crawl failed; nullable.
    data_type: String
  - name: visit_started_at
    description: Timestamp when the visit started.
    data_type: DateTime
  - name: visit_ended_at
    description: Timestamp when the visit ended.
    data_type: DateTime
  - name: peer_properties
    description: JSON object containing additional peer properties.
    data_type: JSON
  config:
    access: public
    tags:
    - production
    - nebula_discv5
    - visits
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_crawlers_data__ipinfo
  description: Staging model transforming raw IP info data into a structured format for analysis.
  columns:
  - name: loc
    description: Geographical location information, typically in "latitude,longitude" format.
    data_type: String
  - name: carrier
    description: Carrier or network provider name.
    data_type: String
  - name: company
    description: Company associated with the IP address.
    data_type: String
  - name: region
    description: Administrative region or state.
    data_type: String
  - name: asn
    description: Autonomous System Number associated with the IP.
    data_type: String
  - name: generic_provider
    description: Categorized provider type based on organization name.
    data_type: String
  - name: is_bogon
    description: Indicator if the IP is part of a bogon (invalid or reserved IP space).
    data_type: UInt64
  - name: timezone
    description: Time zone of the IP location.
    data_type: String
  - name: city
    description: City name corresponding to the IP.
    data_type: String
  - name: is_mobile
    description: Indicator if the IP is associated with mobile networks.
    data_type: UInt64
  - name: ip
    description: IP address.
    data_type: String
  - name: country
    description: Country name.
    data_type: String
  - name: org
    description: Organization name associated with the IP.
    data_type: String
  - name: postal
    description: Postal code.
    data_type: String
  - name: hostname
    description: Resolved hostname for the IP address.
    data_type: String
  config:
    access: public
    tags:
    - production
    - crawlers_data
    - ipinfo
    materialized: view
  meta:
    owner: analytics-team
    authoritative: false
    generated_by: schema-writer
- name: stg_nebula_discv4__discovery_id_prefixes_x_peer_ids
  description: Mapping from discovery ID prefix to peer_id, sourced from the nebula_discv4 database.
  columns:
  - name: discovery_id_prefix
    description: The prefix of the discovery ID used to identify peers, type UInt64.
    data_type: UInt64
  - name: peer_id
    description: The unique identifier of the peer, typically a string address.
    data_type: String
  config:
    access: public
    tags:
    - production
    - nebula_discv4
    - discovery_id_prefixes_x_peer_ids
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_nebula_discv4__neighbors
  description: Edges discovered between peers from neighbors responses in the nebula_discv4 network.
  columns:
  - name: crawl_id
    description: Unique identifier for the crawl session.
    data_type: UUID
  - name: crawl_created_at
    description: Timestamp when the crawl was initiated.
    data_type: DateTime64(0, 'UTC')
  - name: peer_discovery_id_prefix
    description: Prefix of the peer discovery ID, representing the peer.
    data_type: UInt64
  - name: neighbor_discovery_id_prefix
    description: Prefix of the neighbor discovery ID, representing the neighboring peer.
    data_type: UInt64
  - name: error_bits
    description: Bitfield indicating errors encountered during neighbor discovery.
    data_type: UInt16
  config:
    access: public
    materialized: view
    tags:
    - production
    - nebula_discv4
    - neighbors
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_nebula_discv5__discovery_id_prefixes_x_peer_ids
  description: Mapping from discovery ID prefix to peer_id, sourced from the nebula_discv5 database.
  columns:
  - name: discovery_id_prefix
    description: The prefix of the discovery ID used to identify peers, stored as an unsigned 64-bit integer.
    data_type: UInt64
  - name: peer_id
    description: Unique identifier for a peer, represented as a string.
    data_type: String
  config:
    access: public
    tags:
    - production
    - nebula_discv5
    - discovery_id_prefixes_x_peer_ids
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_nebula_discv5__neighbors
  description: Discovered neighbor relationships between peers in the Nebula Discv5 network crawl.
  columns:
  - name: crawl_id
    description: Identifier for the specific crawl session.
    data_type: String
  - name: crawl_created_at
    description: Timestamp when the crawl was initiated.
    data_type: DateTime64(0, 'UTC')
  - name: peer_discovery_id_prefix
    description: Unique prefix identifying the discovered peer.
    data_type: UInt64
  - name: neighbor_discovery_id_prefix
    description: Unique prefix identifying the neighbor peer.
    data_type: UInt64
  - name: error_bits
    description: Error bits indicating issues during neighbor discovery (bitmask).
    data_type: UInt16
  config:
    access: public
    tags:
    - production
    - nebula_discv5
    - neighbors
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
