version: 2
models:

- name: stg_nebula_discv4__visits
  description: Staging model for visits data from nebula_discv4, including peer and crawl metadata.
  columns:
  - name: visit_started_at
    description: Timestamp when the visit started.
    data_type: DateTime64(3)
    tests:
    - not_null
  - name: dial_errors
    description: Array of dial error messages encountered during visit.
    data_type: Array(LowCardinality(String))
  - name: agent_version
    description: Version string of the peer agent.
    data_type: String
  - name: crawl_id
    description: Identifier of the crawl during which the visit occurred.
    data_type: Nullable(UUID)
  - name: dial_maddrs
    description: List of dial multiaddresses used for connection.
    data_type: Array(String)
  - name: extra_maddrs
    description: Additional multiaddresses associated with the peer.
    data_type: Array(String)
  - name: visit_ended_at
    description: Timestamp when the visit ended.
    data_type: DateTime64(3)
  - name: filtered_maddrs
    description: List of filtered multiaddresses for the peer.
    data_type: Array(String)
  - name: connect_maddr
    description: Multiaddress used for the connection, nullable.
    data_type: Nullable(String)
  - name: protocols
    description: List of protocols supported by the peer.
    data_type: Array(LowCardinality(String))
  - name: crawl_error
    description: Crawl error message if any, nullable.
    data_type: LowCardinality(Nullable(String))
  - name: peer_properties
    description: JSON object containing peer properties.
    data_type: JSON
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
- name: stg_nebula_discv5__visits
  description: Staging model for visits data from nebula_discv5 source, including peer and crawl metadata.
  columns:
  - name: visit_started_at
    description: Timestamp when the visit started, in UTC.
    data_type: DateTime64(0, 'UTC')
    tests:
    - not_null
  - name: dial_errors
    description: List of dial errors encountered during the visit.
    data_type: String
  - name: agent_version
    description: Version string of the peer's agent.
    data_type: String
  - name: crawl_id
    description: Unique identifier for the crawl session.
    data_type: String
    tests:
    - not_null
  - name: dial_maddrs
    description: Array of dial multiaddresses used during the visit.
    data_type: Array(String)
  - name: extra_maddrs
    description: Array of extra multiaddresses associated with the peer.
    data_type: Array(String)
  - name: visit_ended_at
    description: Timestamp when the visit ended, in UTC.
    data_type: DateTime64(0, 'UTC')
  - name: filtered_maddrs
    description: Array of filtered multiaddresses.
    data_type: Array(String)
  - name: connect_maddr
    description: Multiaddress used for the connection, nullable.
    data_type: String
  - name: protocols
    description: List of protocols supported by the peer.
    data_type: Array(LowCardinality(String))
  - name: crawl_error
    description: Crawl error message, nullable.
    data_type: LowCardinality(Nullable(String))
  - name: peer_id
    description: Unique identifier of the peer.
    data_type: String
    tests:
    - not_null
  - name: peer_properties
    description: JSON object containing peer properties.
    data_type: JSON
  config:
    access: public
    materialized: view
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
