name: Build & Release DBT Cerebro

on:
  push:
    branches:
      - main

concurrency:
  group: gnosis-dbt-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Organization Name
        id: org_name
        run: |
          org_name=$(echo "${{ github.repository_owner }}")
          echo "org_name=$org_name" >> $GITHUB_OUTPUT

      - name: Extract commit
        id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ steps.org_name.outputs.org_name }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Latest
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ steps.org_name.outputs.org_name }}/gc-gnosis-dbt:latest \
            --push .

      - name: Push Versioned
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ steps.org_name.outputs.org_name }}/gc-gnosis-dbt:${{ steps.commit.outputs.short }} \
            --push .

  deploy-docs:
    # Wait for build to finish (so that `main` branch is fully up to date)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # Must fetch full history so we can push to gh-pages

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dbt (ClickHouse adapter)
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==1.9.4 dbt-clickhouse==1.9.1

      - name: Install dbt dependencies
        run: |
          dbt deps

      - name: Generate dbt docs
        run: |
          dbt docs generate

      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target      # dbt writes its static site into target/
          publish_branch: gh-pages   # push into gh-pages branch
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
