name: Build & Release DBT Cerebro

on:
  push:
    branches:
      - main

concurrency:
  group: gnosis-dbt-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Organization Name
        id: org_name
        run: |
          org_name=$(echo "${{ github.repository_owner }}")
          echo "org_name=$org_name" >> $GITHUB_OUTPUT

      - name: Extract commit
        id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ steps.org_name.outputs.org_name }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Latest
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ steps.org_name.outputs.org_name }}/gc-gnosis-dbt:latest \
            --push .

      - name: Push Versioned
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ steps.org_name.outputs.org_name }}/gc-gnosis-dbt:${{ steps.commit.outputs.short }} \
            --push .

  deploy-docs:
    name: Generate & Deploy dbt Docs
    needs: build
    runs-on: ubuntu-latest

    # Provide the ClickHouse connection details as environment variables
    env:
      CLICKHOUSE_URL: ${{ secrets.CLICKHOUSE_URL }}
      CLICKHOUSE_USER: ${{ secrets.CLICKHOUSE_USER }}
      CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
      CLICKHOUSE_DATABASE: ${{ secrets.CLICKHOUSE_DATABASE }}
      CLICKHOUSE_SCHEMA: ${{ secrets.CLICKHOUSE_SCHEMA }}

    steps:
      - name: Checkout (with full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0     # Required so that gh-pages can be updated correctly

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dbt (ClickHouse adapter)
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==1.9.4 dbt-clickhouse==1.9.1

      - name: Install dbt package dependencies
        run: |
          dbt deps

      - name: Generate dbt docs
        run: |
          dbt docs generate --empty-catalog

      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target        # Path where dbt puts generated docs
          publish_branch: gh-pages     # Branch to push the static site to
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
