version: 2
models:

- name: int_crawlers_data_labels
  description: This model processes crawler label data, categorizing projects into sectors such as DEX, Lending, Bridges, and others based on project names. It filters data by introduced_at date range and maintains incremental updates.
  columns:
  - name: introduced_at
    description: Timestamp when the label was introduced; in UTC.
    data_type: DateTime
  - name: address
    description: Lowercase blockchain address associated with the label.
    data_type: String
  - name: project
    description: Name of the project associated with the label.
    data_type: String
  - name: sector
    description: Sector category assigned based on project name, such as DEX, Lending, Bridges, etc.
    data_type: String
  config:
    access: public
    materialized: incremental
    tags:
    - production
    - crawlers_data
    - labels
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: schema-writer
