version: 2
models:

- name: int_crawlers_data_labels
  description: The int_crawlers_data_labels model consolidates and categorizes crawler data labels for various blockchain projects, enabling efficient analysis of project types and their associated attributes.
  columns:

  - name: address
    description: The unique blockchain address associated with the data label, stored in lowercase for consistency.
    data_type: String

  - name: project
    description: The name of the blockchain project or protocol, used to identify and categorize the data label.
    data_type: String

  - name: introduced_at
    description: The timestamp indicating when the label was introduced or recorded, used for temporal analysis.
    data_type: DateTime64
    tests:
    - not_null

  - name: sector
    description: Sector category assigned based on project name, such as DEX, Lending, Bridges, etc.
    data_type: String
  meta:
    owner: analytics_team
    authoritative: false
    generated_by: dbt-schema-gen
    _generated_at: '2025-12-12T23:06:58.588923'
    _generated_fields:
    - description
    - columns.address.description
    - columns.project.description
    - columns.introduced_at.description
    - config.tags
    - config.materialized
    - columns.introduced_at.data_type
    - columns.project.data_type
    - columns.address.data_type
